src/sqlfluff/cli/helpers.py

Thanks for putting `sqlfluff` together @alanmcruickshank -- I believe it has a ton of potential and eagerly await its future development!
While trying it out on Python 2 ran into [the dreaded `\u` escapes](https://matplotlib.org/2.1.1/devel/portable_code.html#the-dreaded-u-escapes). I understand Python 2 is not a priority (and it really should not be), but the fix was quite simple and so I though you may appreciate it.
Do let me know if there is anything else I can help you with in this regard.
Thanks!
-------------------------
* When running on Python 2, `sqlfluff` would produce strings as follows:
== [\u001b[30;1mtest/fixtures/linter/indentation_error_simple.sql\u001b[0m] \u001b[31mFAIL\u001b[0m
\u001b[36mL:   2 | P:   1 | L003 |\u001b[0m Single indentation uses a number of spaces not a …

color: Fix unicode literals in terminal coloring

---

.circleci/config.yml
CHANGELOG.md
LICENSE.md
README.md
src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/cli/helpers.py
src/sqlfluff/config.ini
src/sqlfluff/linter.py
src/sqlfluff/rules/std.py
test/cli_commands_test.py
test/cli_formatters_test.py
test/cli_helpers_test.py
test/linter_corrections_test.py
test/linter_test.py
test/rules_std_roundtrip_test.py
tox.ini

* Make sure the paths end up on separate lines in the output of linting
errors.
* This means that violations will be formatted as a self-sustainable
block (with a newline at the end).
Signed-off-by: mr.Shu <mr@shu.io>
----------------------------------------------
Hey @alanmcruickshank, I am not sure if the tests will pass on this one, but here is what I was trying to fix:
On `master` branch:
```
test/fixtures/linter $ sqlfluff lint -n *
== [indentation_error_simple.sql] FAIL
L:   2 | P:   1 | L003 | Single indentation uses a number of spaces not a multiple of 4== [indentation_errors.sql] FAIL
L:   2 | P:   1 | L003 | Single indentation uses a number of spaces not a multiple of 4
L:   3 | P:   1 | L002 | Single indentation uses mixture of tabs and spaces
L:   3 | P:   1 | L003 | Single …
```

fix: Paths on separate lines in linting output

---

.gitignore
DOCS.md
src/sqlfluff/cli/commands.py
src/sqlfluff/linter.py
src/sqlfluff/rules/crawler.py
src/sqlfluff/rules/std.py
test/cli_commands_test.py
test/linter_test.py

Mostly a request for feedback (I do not 100% understand the vision or even 10% understand the complexity of the codebase!). I'll work on tests, etc, if everyone likes the idea--
Basically the first thing i tried with sqlfluff was
```sh
echo 'select col from tbl' | sqlfluff lint
```
That didn't work so i tried using a `-` to specify stdin like:
```sh
echo 'select col from tbl' | sqlfluff lint -
```
And realized there is no sdtin functionality! I added a quick lint_string function and a cli handler. I don't know if stdin is in line with the sqlfluff vision, but thought it might be noted since it was literally the first thing i tried. I also attempted writing a fixer but was not sure how that would fit in with the rest of the cli (would it print the formatted string? What about the errors? …

Add stdin input for lint cli

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/linter.py
src/sqlfluff/parser/__init__.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/parser/lexer.py
src/sqlfluff/parser/match.py
src/sqlfluff/parser/segments_base.py
src/sqlfluff/parser/segments_common.py
test/dialects_test.py
test/fixtures/parser/ansi/functions_a.sql
test/fixtures/parser/ansi/functions_b.sql
test/fixtures/parser/ansi/select_simple_a.yml
test/parser_grammar_test.py
test/parser_segments_base_test.py
test/parser_segments_core_test.py

Big refactor of parse context to make things easier.
New generic forward matching routines including centralised bracket counting.
Removed old bracket counting routines.
Replace the bracket counting in Delimited & GreedyUntil.
Introduce the LambdaSegment option.
Update Changelog.
NB: This closes #23 and part of #22

Functions, Parse Context and Bracket Matching

---

setup.py

This fixes the installation issue (#41) with Python 2.7. I have not manually tested on Python 3, but did read the Python 3 docs to confirm that the `read()` function is available in both Python 2.7 and Python 3. Hopefully the Tox automated tests will confirm this.
* [Python 2.7](https://docs.python.org/2/library/configparser.html#ConfigParser.RawConfigParser.read)
* [Python 3](https://docs.python.org/3/library/configparser.html#configparser.ConfigParser.read)

Issue 41: Fix Python 2.7 installation issue

---

CHANGELOG.md
docs/source/index.rst
docs/source/realworld.rst
docs/source/rules.rst
src/sqlfluff/cli/commands.py
src/sqlfluff/rules/base.py

As raised in #13 by @barrywhart - the current docs are bit confusing about what role templating plays.
This hopefully addresses that a little by introducing a section on how sqlfluff fits into a modern data architecture and what role templating plays in that.
This PR also fleshes out the documentation around rules, adding autodoc for the base rule classes.

Better docs

---

CHANGELOG.md
README.md
src/sqlfluff/cli/commands.py
src/sqlfluff/linter.py
test/fixtures/templater/jinja_d_roundtrip/.sqlfluff
test/fixtures/templater/jinja_d_roundtrip/test.sql
test/rules_std_roundtrip_test.py

This closes #50 
Test case and code to manage safe merging of changes into a fixed script without wiping the templating tags.

Safe merging of changed elements while templating

---

src/sqlfluff/__init__.py
src/sqlfluff/config.py
src/sqlfluff/linter.py

Process dirs and files in alphabetical order

---

CHANGELOG.md
src/sqlfluff/cli/commands.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/parser/segments_base.py
test/cli_commands_test.py
test/fixtures/parser/ansi/select_e.sql
test/fixtures/parser/ansi/select_e.yml

Found a fixed a bug in recursive parsing where if a segment had no `parse_grammar` but one of it's children *did*, then it wouldn't be expanded because it would be seen as unexpandable and the `expand` function would never be called on it.
That was found as part implementing `UNION` expressions and so also fixes #61 .

Fixes to recursive parsing and Set expressions

---

.gitignore
src/sqlfluff/cli/commands.py
src/sqlfluff/linter.py
test/cli_commands_test.py

A fix for #86 
The docs say this is possible but it is not! My guess is that @alanmcruickshank forgot that stdin was not set up for fix when it was set up for lint :-)
Anyway here it is!
The flow i was thinking about was 
```sh
echo "  SELECT a  +  b FROM tbl;  "  | sqlfluff fix - --rules L001  
```
So that this can be piped again, the usual echos had to be done away with, otherwise doing something like this would not be as expected:
```sh
echo "  SELECT a  +  b FROM tbl;  "  | sqlfluff fix - --rules L001 > fixed.sql
```
For this to work I had to move the internals of `LintedFile.persist_tree` to a new function which produces a fixed string first.

Enable stdin input for fix cli

---

src/sqlfluff/rules/std.py
test/rules_std_test.py

This is a proposed change to address #8. The implementation was a little different than we thought it might be. In this case, `DISTINCT` is still being parsed as a keyword, not a function. My implementation may be pretty naive -- feedback is definitely welcome!

Issue 8: Warn if DISTINCT used with parentheses

---

docs/source/diff-quality.rst
docs/source/index.rst

Addresses #105.
I don't have a good way to view `.rst` files at this time, so I suggest checking the markup as well as the content before merging.

#105: Usage documentation for the diff-quality integration

---

docs/source/index.rst
docs/source/production.rst

@barrywhart - after approving your PR I was thinking that `diff-cover` is actually part of a larger theme. So rather that it coming at the end of the contents page as it's own topic, I've reworked it into a slightly larger piece on how to deploy sqlfluff in production. What do you think?
I think it fits nicer into the structure here.

Restructure production usage docs.

---

docs/requirements.txt

Now that we don't need to support py27 we can remove the deprecated outdated sphinx requirement.

Upgrade sphinx requirement - deprecating py2

---

README.md

@sanketsaurav I'm adding a badge for DeepSource.
If you're able to set yourselves up on https://shields.io/ that would be awesome. I saw that there's a build in badge in the UI - but not in the usual format. It also doesn't have a status returned for it. If you're able to make one then I'm happy to put it on the project.

Add badge for DeepCover

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/parser/ansi/select_i.sql
test/fixtures/parser/ansi/table_expression.sql

Rather than adding this to the bigquery dialect, it seemed common enough to add it to the main one for now. This closes #97 .

Better support for table expressions and nested select

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/ansi/select_j.sql
test/fixtures/parser/ansi/select_k.sql
test/fixtures/parser/ansi/select_l.sql
test/fixtures/parser/ansi/select_m.sql
test/fixtures/parser/ansi/select_n.sql
test/fixtures/parser/ansi/select_o.sql
test/fixtures/templater/jinja_b/jinja.yml

Fixes #149.
Fixes #147.
Fixes #146.
Fixes #145.
Fixes #144.
Adds:
- `FULL JOIN`
- `BETWEEN` / `NOT BETWEEN`
- Alias expressions without `AS`
- Better handling on bracketed join conditions 
- Interval Literals

Clear up and parsing improvements

---

README.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/linter.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/parser/segments_base.py
src/sqlfluff/rules/std.py
test/fixtures/cli/passing_b.sql
test/fixtures/linter/autofix/ansi/004_L003_indentation_3/after.sql
test/fixtures/linter/autofix/ansi/004_L003_indentation_3/before.sql
test/fixtures/templater/jinja_b/jinja.yml

fixes #151 .
@barrywhart @mrshu - can you review?
I've ironed out some bugs in the indentation code, but also been thinking about the *correct* indentation for the sample query, and I'd like to suggest a few changes. I think the correct indentation should look like this:
```
WITH
audience_counts AS (
SELECT
user_id,
list_id,
COUNT(email_id) AS audience
FROM
lists_emails AS list_emails
WHERE
list_emails.active != 'D'
GROUP BY
user_id,
list_id)
SELECT
user_id,
list_id,
audience,
CASE
WHEN audience > 0 AND audience <= 200 THEN '< 200'
WHEN audience > 200
AND audience <= 2000 THEN '200 - 2,000'
WHEN audience > 2000 AND audience <= 10000 THEN '2,000 - 10,000'
WHEN audience > 10000
AND audience <= 50000 THEN '10,000 - 50,000'
WHEN audience > 50000 AND audience <= 500000 THEN '50,000 - 500,000' …
```

Fixes to indentation work

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/rules/std.py
test/dialects_ansi_test.py
test/fixtures/linter/autofix/ansi/005_L017_function_spacing/after.sql
test/fixtures/linter/autofix/ansi/005_L017_function_spacing/before.sql
test/fixtures/parser/ansi/select_k.sql
test/fixtures/parser/ansi/select_s.sql
test/fixtures/parser/ansi/select_t.sql

Fixes #171 .
Also introduces rule L017 to catch functions with unwanted spaces.

Reorganise old tests and add support for functions with gaps

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/parser/segments_base.py
src/sqlfluff/parser/segments_common.py
test/dialects_ansi_test.py
test/fixtures/parser/ansi/select_s.sql
tox.ini

Implements Array notation as per #59. Also introduces some very lightweight pruning of match paths which have already been tried using the `ParseBlacklist` class.
@barrywhart This implements parsing for array notation - can you take a look at the example queries that it parses and see if they're what you had in mind?
Fixed #59

Array notation and match caching

---

CHANGELOG.md
src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/config.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/errors.py
src/sqlfluff/linter.py
src/sqlfluff/parser/lexer.py
src/sqlfluff/parser/segments_file.py
src/sqlfluff/rules/std.py
test/cli_commands_test.py
test/dialects_ansi_test.py
test/dialects_test.py
test/fixtures/linter/operator_errors.sql
test/fixtures/linter/parse_lex_error.sql
test/fixtures/parser/ansi/grant_all_on_table_mytable_to_role.sql
test/fixtures/parser/ansi/grant_all_privileges_on_mytable_to_role.sql
test/fixtures/parser/ansi/select_simple_e.yml
test/fixtures/parser/ansi/select_simple_j.sql
test/fixtures/parser/ansi/select_simple_j.yml
test/parser_lexer_test.py

Fixes #104 
Includes the boolean binary operators `AND`, `OR` etc... in the linting rule about consistent capitalisation.
Also fixes a couple of minor parsing bugs found during testing.

"ignore" parameter and a few parsing tweeks

---

.gitignore
src/sqlfluff/cli/commands.py
src/sqlfluff/errors.py
src/sqlfluff/linter.py
test/cli_commands_test.py

This is very much a discussion starter! Fixes #100 .
I set up an output format conditional in `lint_string()`, and propagated an `out_format` flag from there to the CLI.
When `out_format='json'`, the linter prints out each file's violations as a JSON payload on a single line. 
In the CLI:
```sh
$ echo 'SElect * from tbl' | sqlfluff lint - --out-format json --rules L010
{"filepath": "stdin", "violations": [{"code": "L010", "line_no": 1, "line_pos": 1, "description": "Inconsistent capitalisation of keywords."}]}
```
With multiple files, the full CLI output is not JSON interpretable. This is because the linter's CLI output is incremental, so there is not currently an easy way to construct a multi-file payload. 
```sh
$ sqlfluff lint test/fixtures/linter/indentation_errors.sql …
```

Add output format option for linter, json support.

---

src/sqlfluff/__main__.py
test/cli_commands_test.py

So that you can access the fluff CLI via `python -m sqlfluff`. This is very useful when you want to be specific about what python installation you're running!

Add __main__ interface to the cli

---

src/sqlfluff/cli/commands.py
src/sqlfluff/parser/segments_base.py
test/cli_commands_test.py

Fixes #197 
1.  Add a stdin handler for parse (this was missing!)
2. add yaml option for lint
3. add json option for parse
To support general serialization of the parse result to json or yaml, I needed to change how the printing was done.
For human output, printing is incremental and done via a generator. The logger prints out the file name separately from the parsed segments.
For JSON/YAML output, we need to collect everything together at one time and dump it. We also need to add the file path as that is not connected to the BaseSegment at all. 
As a result the parse command logic has gotten more complex, and serialization logic was moved from BaseSegment to the CLI handler. @alanmcruickshank please let me know if this fits with your vision of the project!

Consistent yaml and json output on parse and lint

---

MANIFEST.in
setup.py

This PR is designed to fix an issue raised in #211 whereby an install attempted without using a `virtualenv` on macOS Mojave and Catalina would fail. 
This PR is adapted from https://github.com/alanmcruickshank/sqlfluff/pull/216 where @alanmcruickshank has been working on a fix for this issue.
It turns out the `data_files` parameter in `setup.py` was attempting to place files in `/usr/local` by default, which gave a `Permission Denied` error.
[This StackOverflow post](https://stackoverflow.com/questions/43800753/pip-tries-to-install-package-in-the-wrong-location) suggested that using a `MANIFEST.in` file in tandem with setting `include_package_data=True` would ensure that any files listed in the manifest file were included in the distribution as expected. I tried that, and it worked. …

Fix install bug on MacOS

---

setup.py

Noticed these were present in `requirements.txt` but not in `setup.py`.  I'm pulling in a forked version of sqlfluff from git directly and it gets dependencies to install from here.

Add missing requirements to setup.py.

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/string_literals.sql

We had some instances of raw strings in a dbt project using bigquery that I'm working on adding sqlfluff to.
This change should parse everything listed under "Quoted string" and "Raw string" from the "String and Bytes Literals" section of BQ's SQL ref: (https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical#string_and_bytes_literals).
Adding a query to the fixtures seemed the easiest way to test a bunch of instances.  I had also thought about adding a `dialects_bigquery_test.py` to and duplicating the chunk that tests specific segment parsing - do you have a particular preference here?

Allow escaped quotes and raw/regex strings in BigQuery dialect.

---

src/sqlfluff/parser/lexer.py

This PR addresses #233. I commented out the debugging-related `print()` calls. I'd be happy to remove them instead, if you prefer.

Comment out debugging output

---

src/sqlfluff/parser/segments_base.py
src/sqlfluff/rules/std.py

Fixes a bug with `unparsable` `WITH` clauses and rule L018.
Another low hanging performance improvement fruit. `BaseSegment` now claims to be simple if it has a match grammar, and that grammar is also simple. This provides a meaningful -25% speed increase on very long queries (1000+ lines).
Fixes #189 (for now)

Bugfix + More performance improvements

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
test/dialects_ansi_test.py
test/fixtures/parser/bigquery/interval_function.sql

This is a change I made locally to support our dbt bq project where we have an interval specified with a cast and a call to timestamp_diff.  I believe this is bigquery-only but I'm not sure.
I'm slightly uncomfortable with putting something including a function call into `LiteralGrammar`.
@alanmcruickshank do you think this is something you're interested in?

Allow value of INTERVAL to be a function in BigQuery.

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/parser/snowflake/snowflake_string_literal.sql

You learn something new every day:
https://docs.snowflake.com/en/sql-reference/data-types-text.html#single-quoted-string-constants

Add snowflake string literal escape for single quote

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/parser/segments_base.py
test/fixtures/parser/postgres/postgres_within_group.sql

This fixes #293 .
NB: Relies on #265 being merged first to look less bloated.
Also includes some stability for BaseSegment to catch a few edge cases that occur with deep matching and parsing.

Add WITHIN GROUP syntax and stability to BaseSegment

---

src/sqlfluff/cli/commands.py
test/cli_commands_test.py

A small adjustment to the fix CLI handler for stdin, and remove the monkeypatch on the tests (which is why this was not caught initially).

Fixes #323: Fix from stdin writes more than the fixed sql to stdout

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/parser/ansi/select_trailing_comma_column_list.sql
test/fixtures/parser/ansi/select_where_in_unnest.sql

Allow trailing commas in the column list of a SELECT (BigQuery allows this)

---

src/sqlfluff/dialects/dialect_snowflake.py

Found while browsing Snowflake dialect.
https://docs.snowflake.com/en/sql-reference/constructs/sample.html

Fixes typo for Snowflake sampling method

---

src/sqlfluff/rules/std.py

Following this issue #327 
We add some documentation for the rules. I'm not really satisfied with how it looks when using • to explain white space rules. See the example below.
Any suggestion to improve this PR is warmly welcomed.

Improve rules documentation

---

src/sqlfluff/rules/std.py
test/fixtures/linter/column_references.sql

Fixes #396 -- I can make a separate issue for improving the config documentation
Fixes #400 
Your docs and code comments are the 💣 I wouldn't have stood a chance of contributing without them. Love the test suite as well (😍 `pytest`) which also helped me figure out how I was going to test my changes. Also, thanks for the guidance in #400 on how to tackle this 🙇‍♂️ 
A few notes:
- VSCode was complaining that several arguments in the various `_lint_references_and_aliases` methods went unused. I'm guessing this was intentional on your part, and so I kept that consistent. If you prefer elsewise, I'm happy to remove the additional parameter from the other methods
- I was getting some weird behavior when I put the alias extraction code in `L020._eval()` _before_ the using cols extraction. To be …

Check for column aliases in L027

---

src/sqlfluff/dialects/dialect_ansi.py
test/dialects_ansi_test.py
test/fixtures/linter/column_references_bare_function.sql
test/rules_std_test.py

L027 would fail on ANSI functions such as `current_timestamp` or `current_date` when called without brackets. This PR adds a `BareFunctionSegment` to allow rules to treat these special cases differently.
In this case, no update to L027 is required.
Closes https://github.com/alanmcruickshank/sqlfluff/issues/418

Add BareFunctionSegment

---

src/sqlfluff/linter.py
test/fixtures/linter/autofix/ansi/009_L010_keyword_capitalisation/.sqlfluff
test/fixtures/linter/autofix/ansi/009_L010_keyword_capitalisation/after.sql
test/fixtures/linter/autofix/ansi/009_L010_keyword_capitalisation/before.sql

The 'Unexpectedly depleted the fixes. Panic!' error was preventing the linter from fixing the file added in the test. The logic assumed that if there were no diff_fix_codes left, then we must be at the end of the raw file, and for this to be the case the length of the linted output buffer must be greater than or equal to the original file.
1. This isn't true as there could still be a delete templ_block to apply (correct in this test case)
2. The linting process could actually reduce the length of a file, meaning the lint could be completed with a smaller output buffer than the original file.

Remove 'Unexpectedly depleted the fixes. Panic!' broken logic from main linter loop

---

docs/source/dialects.rst
docs/source/index.rst
src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/dialects/__init__.py
src/sqlfluff/dialects/base.py
test/cli_commands_test.py

Fixes #435 .
I couldn't find a more elegant way of using `autodoc` to document the dialects (which would have been nice), so wrote them out longhand for the docs. The cli command is much more well integrated and tidier.

Add dialect readout command and docs

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/parser/segments_base.py
src/sqlfluff/rules/std.py
test/fixtures/parser/ansi/select_simple_b.yml
test/fixtures/parser/bigquery/select_replace_2.yml
test/fixtures/parser/snowflake/snowflake_pivot.yml
test/fixtures/templater/jinja_g_macros/jinja.yml
test/rules_std_test.py

Fixes #449 . This introduces a backward incompatible change to the handling of `*` segments but I think it's for the best.

Refactor wildcard expressions

---

CONTRIBUTING.md
README.md
tox.ini

This looks like a really great open source project. I'd like to contribute to its development so I started reading your docs. I noticed a couple of small issues there so here's a PR to fix them. 
With regards to instructions on `virtualenv`, I'm open to feedback on whether I should include more detail. Also, my improvement only recommends python's `venv` module rather than the independent [virtualenv](https://virtualenv.pypa.io/en/stable/) package. I believe in recommending a single tool and and python's `venv` module is best because it doesn't required additional installation. 
Let me know how I could improve this PR.

Fixed typo in README and added instructions on how to virtualenv

---

CODE_OF_CONDUCT.md
CONTRIBUTING.md

Closes #444 
For review by @sqlfluff/sqlfluff-maintainers .
Now that we've got a github org and the community is growing, I feel like we should probably should get in place some basic project governance. It's so much easier to get this stuff in place before we run into problems than trying to retro-fit it when something goes wrong.
This PR adds a code of conduct (as per https://opensource.guide/code-of-conduct/) and also adds a basic outline of how I think project process can work going forward.
What do people think?

Code of conduct + intial project governance

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/parser/__init__.py
src/sqlfluff/parser/grammar.py
src/sqlfluff/parser/segments_base.py
src/sqlfluff/parser/segments_common.py
test/fixtures/parser/bigquery/select_multi_except.sql
test/parser/grammar_test.py
test/parser/segments_core_test.py

This was triggered by #366 .
These fixes don't fix the issue but were necessary to get to properly debugging that issue.
This introduces:
- The `Checkpoint` Segment, which behaves a little like a grammar, but is really a segment so allows dialects to divide up queries during parsing without affecting the eventual structure.
- Adding an `exclude` keyword to the `OneOf` grammar to allow some patterns being matched to prevent the grammar from matching.
- A refactor or `look_ahead_match` to better handle multiple simple matches.

BigQuery Except clause refactor

---

.circleci/config.yml
README.md
setup.py
src/sqlfluff/__init__.py
tox.ini

Drop support for python 3.5 (related to #459)
Use 3.9 python 3.9 stable release in CI (Closes #461)

Modify supported python versions

---

src/sqlfluff/rules/std.py
test/fixtures/cli/passing_b.sql
test/rules_std_test.py

Addresses #467
Hi folks, I've been poking around with sqlfluff at work some (it's 👍 btw, awesome work!), figured I'd try and put a contribution in.  Please let me know any feedback!  Couple of things I'm unsure on that I could use a hand with:
- For adding a new rule, is there anything to do to default configs, or do you just accept the new rule as adding to the default behaviour?  Any numbering schemes to think about, other than just incrementing the latest rule by one?
- I couldn't get all the versions up and running through tox locally (too many competing environment setups 😬) but tests pass when calling `pytest` directly in 3.7.9 on my machine.  Is tox run in CI too to validate against other versions?
- For this rule if there's just two tables I _think_ it could be auto-fixed by …

New rule: keys instead of using for joins

---

src/sqlfluff/cli/commands.py
src/sqlfluff/linter.py
src/sqlfluff/parser/grammar.py
util.py

As brought up in #486 , we've had some stray print statements lying around.
This PR also makes Warnings or above red so that they're easier to find.

Make warnings red, and clear up old print statements

---

src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/cli/helpers.py
src/sqlfluff/core/parser/segments_base.py
test/cli/commands_test.py
test/cli/formatters_test.py
test/core/parser/segments_base_test.py

This fixes #503 , it also give some parts of the CLI a bit of love after some neglect.
Includes:
- Test case to catch #503 
- Actually using `colorama` for colour despite having it installed for ages 🤦 
- A makeover to use `type` rather than `__class__.__name__` for `.stringify()` and put the position first given the more reliable types being used now.

CLI output spruce

---

CHANGELOG.md
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/dialects/dialect_snowflake.py
src/sqlfluff/core/dialects/dialect_teradata.py
src/sqlfluff/core/parser/__init__.py
src/sqlfluff/core/parser/grammar.py
src/sqlfluff/core/parser/segments_base.py
src/sqlfluff/core/parser/segments_common.py
src/sqlfluff/core/parser/segments_file.py
test/core/parser/conftest.py
test/core/parser/grammar_test.py
test/core/parser/parse_test.py
test/core/parser/segments_base_test.py

With a few performance gains in mind I've gone through and removed several older sections of code which had been hanging around. I've also renamed and reorganized a few parts which had got convoluted.
- Extra test cases for the parser
- Removed `BaseSegment.grammar`, `BaseSegment._match_grammar()` and `BaseSegment._parse_grammar()` instead preferring references directly to `BaseSegment.match_grammar` and `BaseSegment.parse_grammar`.
- Removed `EmptySegmentGrammar` and replaced with better non-code handling in the `FileSegment` itself.
- Remove the `ContainsOnly` grammar as it remained only as an anti-pattern.
- Removed the `expected_string()` functionality from grammars and segments as it was poorly supported.
- Removed `BaseSegment.as_optional()` as now this functionality happens mostly …

Clearout to support refactoring

---

CHANGELOG.md
docs/source/api.rst
examples/basic_api_usage.py
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/dialects/dialect_snowflake.py
src/sqlfluff/core/dialects/dialect_teradata.py
src/sqlfluff/core/parser/__init__.py
src/sqlfluff/core/parser/grammar.py
src/sqlfluff/core/parser/segments_base.py
src/sqlfluff/core/parser/segments_common.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/std.py
test/api/simple_test.py
test/core/parser/segments_base_test.py
test/fixtures/parser/ansi/multi_statement_a_nc.yml
test/fixtures/parser/ansi/select_a.yml
test/fixtures/parser/ansi/select_e.yml
test/fixtures/parser/ansi/select_simple_b.yml
test/fixtures/parser/ansi/select_simple_e.yml
test/fixtures/parser/ansi/select_simple_e_nc.yml
test/fixtures/parser/ansi/select_simple_j.yml
test/fixtures/parser/ansi/select_with_a.yml
test/fixtures/parser/snowflake/snowflake_pivot.yml
test/fixtures/parser/snowflake/snowflake_semi_structured.yml
test/fixtures/templater/jinja_a/jinja.yml
test/fixtures/templater/jinja_b/jinja.yml
test/fixtures/templater/jinja_c_dbt/dbt_builtins.yml
test/fixtures/templater/jinja_f/jinja.yml
test/fixtures/templater/jinja_g_macros/jinja.yml

This builds on #501 and relates to #289  . That PR should be merged and reviewed first. Until then, this is to be considered *draft*.
- Added the `.istype()` method on segments to more intelligently deal with type matching in rules when inheritance is at play.
- Split `ObjectReference` into `ColumnReference` and `TableReference` for more useful API access to the underlying structure.
- `KeywordSegment` and the new `SymbolSegment` both now inherit from `_ProtoKeywordSegment` which allows symbols to match in a very similar way to keywords without later appearing with the `type` of `keyword`.
This is quite a backward incompatible change if anyone depends on the internal parse structure of queries (hence the updates to so many of the test cases). I'm glad this coincides with an upcoming major …

Split ObjectReference into ColumnReference and TableReference.

---

setup.py

This fixes #511 
After the new module structure, the `setup.py` structure hadn't been updated. This means that during docs builds, the autodoc step was failing and therefore nuking the rules page. This fixes that.

Update setup.py to fix imports

---

CHANGELOG.md
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/linter.py
src/sqlfluff/core/rules/__init__.py
src/sqlfluff/core/rules/base.py
test/core/rules/std_test.py

This half addresses #499 . 
This removes the custom code from the test suite and uses the `Linter()` fix routines instead. Adding a custom runaway rule is proving harder!

Remove fixing loop from test suite.

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

Fixes #522 
Skips safety when fixing stdin because files are not modified. Also skips printing out the no safety warning.

Silence safety warnings on fix from stdin

---

.circleci/config.yml
mypy.ini
requirements_dev.txt
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/errors.py
src/sqlfluff/core/parser/__init__.py
src/sqlfluff/core/parser/grammar/base.py
src/sqlfluff/core/parser/grammar/noncode.py
src/sqlfluff/core/parser/match_logging.py
src/sqlfluff/core/parser/match_wrapper.py
src/sqlfluff/core/parser/matchable.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/rules/std.py
src/sqlfluff/core/templaters.py
tox.ini

Based on the excellent work by @dnshio in #459 , this takes things the last mile and gets mypy into action.
It resolves the two outstanding issues, mostly by creating an abstract base class (`Matchable`) which `BaseGrammar` and a few other things inherit from. This base class does not depend on the rest of the library and so has no circular dependency issues.
This PR doesn't implement all of the checks I would like to introduce with mypy, but it does get it into CI so we can start building on it.

MyPy - round 2.

---

docs/source/conf.py

Just noticed that on https://docs.sqlfluff.com/en/latest/rules.html the page title specifies sqlfluff 0.1.5, this fixes that.
I also realised that the docs reflect the most recent push to master, not the most recent release on pypi. I'll make an issue to sort that out

Fix docs version to match current release

---

src/sqlfluff/core/dialects/dialect_snowflake.py
test/core/dialects/snowflake_test.py

This will close https://github.com/sqlfluff/sqlfluff/issues/533

Add USE statement to snowflake dialect with tests.

---

src/sqlfluff/core/dialects/dialect_ansi.py
test/fixtures/parser/ansi/shorthand_cast.sql

Previously resulted in a parse error:
```
---test.sql---
select '1' ::INT as id
```
```
(sqlfluff_venv) ➜  sqlfluff git:(master) sqlfluff lint test.sql
== [test.sql] FAIL
L:   1 | P:  11 |  PRS | Found unparsable section: ' ::INT as id'
WARNING: Parsing errors found and dialect is set to 'ansi'. Have you configured your dialect?
```

Allow whitespace before shorthand cast

---

docs/source/conf.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/std.py

Resolves #549 
- Removes the module path from the rule docs which is distracting
- Adds a decorator for showing if a rule returns LintFixes
- Minor copy fixes
Before:
After:

Tidy rules docs and add sqlfluff fix compatible

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/config.py
src/sqlfluff/core/linter.py
test/cli/commands_test.py
test/core/config_test.py
test/core/linter_test.py

Closes #483 
`--not-ignore-files` skips ignore file patterns, by default it is false and ignore file patterns are respected
When a path to a file to be linted is explicitly passed we look for ignore files in all directories that are parents of the file, up to the current directory.
If the current directory is not a parent of the file we only look for an ignore file in the direct parent of the file.

483 Ignore file passed explictly if matched in "ignore file config"

---

src/sqlfluff/core/rules/base.py
test/core/rules/std_test.py

I am currently trying to turn ON sqlfluff for our dbt project at Earnest
I have at least two rules that fail on edge cases and throw Exceptions that simply **halt sqlfluff's execution**. This is actually hard to debug as well because the SQL file in question is not present in the stack trace.
I would like to:
* Be defensive about potential Exceptions in applying rules, handling them as violations
* Give the users useful information when a rule throws an Exception, and a way for the user to silence that specific Exception (instead of having to ignore the file)
I have the following file, that generates a table with dates:
```sql
with
date_generator as (
select
dateadd(
day,
seq4(),
date '2010-01-01'
) as date
from table(
generator(
-- Number of days since start date
rowcount=>10000
)
)
), …
```

Handle exceptions applying rules as violations

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

For some reason two tests were failing on master for me. One is related to UNIX/Windows path handling. The other relates to an issue when trying to make a config object from the path `stdin` which would have no effect, except was causing a conflict error in trying to use both absolute and relative paths.
This PR fixes both.

Fix broken pathing issues

---

src/sqlfluff/core/linter.py
src/sqlfluff/core/parser/parser.py
test/core/dialects/dialects_test.py
test/core/linter_test.py

Reproduces the error from #587
```
sqlfluff lint /Users/niallwoodward/dev/pull_requests/sqlfluff/test/fixtures/parser/ansi/empty_file.sql
File "/Users/niallwoodward/dev/pull_requests/sqlfluff_venv/bin/sqlfluff", line 11, in <module>
load_entry_point('sqlfluff', 'console_scripts', 'sqlfluff')()
File "/Users/niallwoodward/dev/pull_requests/sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 829, in __call__
return self.main(*args, **kwargs)
File "/Users/niallwoodward/dev/pull_requests/sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 782, in main
rv = self.invoke(ctx)
File "/Users/niallwoodward/dev/pull_requests/sqlfluff_venv/lib/python3.7/site-packages/click/core.py", line 1259, in invoke
return …
```

Failing test with empty file

---

src/sqlfluff/core/dialects/dialect_snowflake.py
test/fixtures/parser/snowflake/snowflake_json_underscore_key.sql

Picked this one up from my work codebase. Had a parse error on the `_z` as the regex didn't match. Does anyone know why the regex was like that to start with? Don't want to have missed something.

Allow an underscore as the first char in a semi structured element key

---

.pre-commit-hooks.yaml
docs/source/conf.py
docs/source/configuration.rst
docs/source/production.rst
src/sqlfluff/config.ini

Test it out :)
```yaml
repos:
- repo: https://github.com/dmateusp/sqlfluff
rev: 9cb4a120ed877a3abdfbef054d00763997e73069
hooks:
- id: sqlfluff-lint
- id: sqlfluff-fix
args: [--rules, "L003,L014"]
```
Related: https://github.com/sqlfluff/sqlfluff/issues/523

Add pre commit hooks for `lint` and `fix`

---

test/core/linter_test.py

New L036 rule was causing this test to fail.
```
L:   1 | P:   1 | L036 | Select targets should be on a new line unless there is
| only one select target.
L:   1 | P:  13 | L010 | Inconsistent capitalisation of keywords.
L:   1 | P:  22 | L011 | Implicit aliasing of table not allowed. Use explicit
| `AS` clause.
L:   1 | P:  22 | L025 | Alias 'c' is never used in SELECT statement.
L:   1 | P:  22 | L031 | Avoid using aliases in join condition
L:   1 | P:  30 | L010 | Inconsistent capitalisation of keywords.
L:   1 | P:  33 | L009 | Files must end with a trailing newline.
```

Fix test on master branch now L036 added

---

CHANGELOG.md
src/sqlfluff/core/dialects/dialect_snowflake.py
test/core/rules/test_cases/L012.yml

Resolves #561 
Implements the window function grammar from https://docs.snowflake.com/en/sql-reference/functions/array_agg.html#syntax.
I think this is subtly different to the postgres grammar, which I believe still to be correct:
https://github.com/sqlfluff/sqlfluff/blob/master/src/sqlfluff/core/dialects/dialect_postgres.py#L49-L55
https://www.postgresql.org/docs/9.4/functions-aggregate.html#FUNCTIONS-ORDEREDSET-TABLE

L012 bug fix

---

setup.py

Introduced by #580 (AKA me 😢 )
Added `typing_extensions` but didn't add it to `setup.py` thinking it was std lib, when it's not 🤦‍♂️
To recreate the current issue:
```
$ python -m venv .venv
$ source .venv/Scripts/activate
$ pip install --pre sqlfluff
$ sqlfluff --version
...
ModuleNotFoundError: No module named 'typing_extensions'
```
FWIW I think we should do another alpha release after this PR

Include undeclared dependency "typing_extensions"

---

src/sqlfluff/cli/commands.py

If the user responds with "Enter" to the question "Are you sure you wish to attempt to fix these? [Y/n]", assume the default selection **Y**es.
Also makes the error when hitting a wrong key more explicit.
Fixes #638

Assume yes if prompted to attempt to fix

---

CHANGELOG.md
src/sqlfluff/core/linter.py
test/core/linter_test.py
test/fixtures/linter/passing.sql

At present, if an attempt to lint a file fails due to an unhandled internal error, the linting process quits and doesn't report which file is causing the issue. This makes it hard to identify what file has surfaced the internal error, which you need to do in order to .sqlfluffignore the file and work around it. This PR prints the exception as a warning with the file that has surfaced the issue.
Outcome:
```
WARNING    Unable to lint /Users/niallwoodward/dev/.../models/reporting/query.sql due to an internal error. Please report this as an issue with your query's contents and stacktrace below!
To hide this warning, add the failing file to .sqlfluffignore
File "/Users/niallwoodward/dev/pull_requests/sqlfluff/src/sqlfluff/core/linter.py", line 1254, in …
```

Handle internal errors elegantly and report the triggering sql file

---

src/sqlfluff/core/rules/std.py
test/core/rules/test_cases/L036.yml

Fix issue 646: Rule L036 misbehaves when there's trailing whitespace after "SELECT"

---

src/sqlfluff/core/linter.py
tox.ini

Two pieces of old code that I saw while reviewing some other PRs. These are remnants which can now be removed.

Remove cdifflib and file_mask references

---

requirements.txt
setup.py

We've previously restricted any versions of diffcover post 3.0. This PR relaxes that requirement to see whether this requirement is still necessary.
If tests pass, great. If tests fail, then we can assess the effort required for things to work.

Test upgrading diffcover dependency

---

test/fixtures/dbt_project/packages.yml

Resolves #674 
Newly released 0.6.4 is not compatible with dbt017

Freeze dbt_utils in dbt fixture to 0.6.3 🥶

---

setup.py

Fixing https://github.com/sqlfluff/sqlfluff/issues/241, https://github.com/sqlfluff/sqlfluff/pull/244
Hi I got same issue as https://github.com/sqlfluff/sqlfluff/issues/241, and I have noticed that you updated click version in requirments.txt file but in `setup.py` the click package version was not modified. Thus, I got the same issue continuously so I upgraded the click version
```
pip install sqlfluff==0.3.6
Requirement already satisfied: sqlfluff==0.3.6 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (0.3.6)
Requirement already satisfied: click>=2.0 in /opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages (from sqlfluff==0.3.6) (6.7)
...
File "/opt/hostedtoolcache/Python/3.7.9/x64/bin/sqlfluff", line 11, in <module> …
```

Bump Click Version

---

src/sqlfluff/core/rules/std.py
test/core/rules/test_cases/L019.yml

Rule L019 (leading/trailing commas) can fail when configured to "leading" commas when the beginning of a query contains one or more non-code lines.
The leading-comma version of the rule currently looks for code segments preceding the current segment. This change handles the case when there are none.

Fix leading comment/header issue in L019.

---

test/core/parser/grammar_test.py

Added two tests to show the OneOf behavior. Per https://github.com/sqlfluff/sqlfluff/pull/719#discussion_r567145572, I wasn't sure exactly how OneOf worked, and after reading the OneOf docs: https://github.com/sqlfluff/sqlfluff/blob/7f1880ba4449310200d0ee5e6c0a19cc883db63d/src/sqlfluff/core/parser/grammar/anyof.py#L214, I just wanted to make sure I understood correctly.
> If it matches multiple, it returns the longest, and if any are the same
length it returns the first (unless we explicitly just match first).

OneOf add tests to show that longest match is taken, but in case of same length, first is taken

---

src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/dialects/dialect_bigquery.py
src/sqlfluff/core/rules/std/L020.py
src/sqlfluff/core/rules/std/L025.py
src/sqlfluff/core/rules/std/L026.py
src/sqlfluff/core/rules/std/L027.py
src/sqlfluff/core/rules/std/L028.py
test/core/rules/test_cases/L020.yml
test/core/rules/test_cases/L025.yml
test/core/rules/test_cases/L027.yml
test/core/rules/test_cases/L028.yml

Addresses #356. This PR adds a new ANSI-level set called `value_table_functions`. It's empty at the ANSI level, but BigQuery updates it to add `UNNEST`. This set is not used in the grammars, but when there is a `table_expression` with an alias, affected rules use this set to determine the nature of that alias: Is it a table alias or a column alias? This is a weird concept, but that's essentially what BigQuery does.
Context: `UNNEST()` is usually, but not always, used to unpack an array of scalar values. In this case, it returns a "table" with only one column. BigQuery has the concept of ["value tables"](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#value_tables):
>In BigQuery, a value table is a table where the row type is a single value. In a regular table, …

Issue 356: Rules that fail when using BigQuery UNNEST() with alias

---

src/sqlfluff/core/dialects/dialect_ansi.py
test/fixtures/parser/ansi/select_named_window_no_parentheses.sql
test/fixtures/parser/ansi/select_named_window_no_parentheses.yml
test/fixtures/parser/ansi/select_named_window_with_parentheses.sql

Resolves #735 
Although the issue mentions linting errors, this was really a parsing issue. Once those were addressed, `sqlfluff lint` and `sqlfluff fix` are both happy with the test query "as is" (other than a benign, seemingly legit warning about indentation.

Issue 735: Fix some remaining issues with named windows

---

test/core/linter_test.py

This addresses a test which is not current cross-platform friendly. The fix makes the test not raise a false alarm with windows style paths.

Fix false alarm on test with windows-style paths.

---

.gitignore
src/sqlfluff/core/config.py
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/linter.py
test/core/linter_test.py
test/core/templaters/jinja_test.py
test/fixtures/templater/jinja_h_macros/.sqlfluff
test/fixtures/templater/jinja_h_macros/jinja.sql
test/fixtures/templater/jinja_h_macros/jinja.yml
test/fixtures/templater/jinja_h_macros/macros/bad_macro.sql

I think this addresses #713 and relates to the conversation we had with @sqlfluff/sqlfluff-maintainers earlier this week.
This enables masking of linting errors within templated sections using the new source mapping code.

Mask linting errors around templated sections.

---

examples/03_extracting_references.py
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/rules/std/L018.py
src/sqlfluff/core/rules/std/L022.py
src/sqlfluff/core/rules/std/L023.py
src/sqlfluff/core/rules/std/L024.py
test/api/util_test.py
test/fixtures/parser/ansi/multi_statement_b.yml
test/fixtures/parser/ansi/multi_statement_c.yml
test/fixtures/parser/ansi/select_r.yml
test/fixtures/parser/ansi/select_v.yml
test/fixtures/parser/ansi/select_with_a.yml
test/fixtures/parser/ansi/select_with_b.yml
test/fixtures/parser/bigquery/select_example.yml

This moves us closer to #289.
@NiallRees @kgpayne - this adds the details to do easy table reference extraction using sqlfluff.
@sqlfluff/sqlfluff-maintainers this adjusts the parse structure of WITH statements so that this kind of information is easier to extract. It does change quite a few of the test cases, but I think the simplicity in using the eventual structure is worth it.
Take a look at `examples/03_extracting_references.py` which hopefully should illustrate this use case well.

Use API to extract table references

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/core/rules/std/L016.py
test/core/rules/test_cases/L016.yml

This addresses #299 .
@barrywhart - was this what you had in mind?
It will still flag up lines that *end* with comments, but if it's a line with only comments on it, then it will be ignored if this config value is set. I've set the default so that it's not set, but it should show up in the docs as an option.

Allow ignoring comment lines

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/core/rules/std/L038.py
test/core/rules/test_cases/L038.yml

Add rule to lint trailing commas in select clauses

---

src/sqlfluff/api/simple.py
test/api/simple_test.py

Fixes #761.
Checks if there are any violations before accessing `result[0]`. Also adds a test for this tiny edge case. First bug of 0.4.0???

fix indexerror when lint API surfaces no errors

---

src/sqlfluff/core/rules/doc_decorators.py
src/sqlfluff/core/rules/std/L002.py
src/sqlfluff/core/rules/std/L014.py
src/sqlfluff/core/rules/std/L024.py
src/sqlfluff/core/rules/std/L030.py
test/core/rules/rule_test_cases_test.py
test/core/rules/std_test.py

Resolves #770.
I noticed that some of the rules provide fixes but do not specify `@document_fix_compatible`. This PR:

Issue 770: Detect undocumented fix-compatible rules

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/rules/std/L040.py
test/core/rules/test_cases/L010.yml
test/core/rules/test_cases/L040.yml
test/fixtures/linter/autofix/ansi/009_keyword_capitalisation/test-config.yml
test/fixtures/parser/ansi/select_g.yml
test/fixtures/parser/ansi/select_p.yml

I noticed that `null` was behaving differently to `true` and `false` and being classed as a keyword in some cases instead of a literal.
- This adds an additional `NullLiteralSegment` so that we can parse null differently in different situations.
- It also adds a new variant on the capitalisation rule (`L040`) which is a rule for capitalising literals like `true`, `false` and `null`.

Null Literal instead of "keyword"

---

CHANGELOG.md
docs/source/configuration.rst
src/sqlfluff/core/templaters/jinja.py
test/core/templaters/jinja_test.py
test/fixtures/templater/jinja_k_config_override_path_macros/.sqlfluff
test/fixtures/templater/jinja_k_config_override_path_macros/jinja.sql
test/fixtures/templater/jinja_k_config_override_path_macros/jinja.yml
test/fixtures/templater/jinja_k_config_override_path_macros/macros/foo.sql

If I define a path in my config where all my macros live,
and then define a few specific macros in the config file, the config
file macros will take precedent over the one defined in the path.
This allows the user to generally use most of their macros that
are being used in prod, and then just mock out the non compliant ones.

Macros Defined in Config take Precedence over Path Macros

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/dialects/dialect_exasol.py
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/core/rules/std/L042.py
test/core/rules/test_cases/L042.yml

This resolves #89 (and also the oldest open issue right now!)
This flags up any subqueries in join clauses, indicating that the user should use CTEs instead.
Small note, I also corrected the naming of `MainTableExpressionGrammar` to `MainTableExpressionSegment` because it was a `Segment` and not a `Grammar`. 😄

L042: #89 No Subqueries in Joins

---

src/sqlfluff/core/dialects/dialect_ansi.py
test/fixtures/parser/postgres/postgres_create_table.sql
test/fixtures/parser/postgres/postgres_create_table.yml
test/fixtures/parser/postgres/postgres_create_type.sql
test/fixtures/parser/postgres/postgres_create_type.yml

This resolves #341 and resolves #343.
I've added both to the ansi dialect, because they're additive and don't conflict with anything already there. Plus there may be other dialects beyond postgres with a similar syntax.

Postgres Syntax Gaps

---

src/sqlfluff/core/dialects/dialect_snowflake.py
test/core/rules/test_cases/L003.yml

This resolves #643 
The dedent segment which was moved in the `ansi` dialect wasn't moved in the `snowflake` dialect leading to odd indent behaviour.

#643: Fix snowflake indent

---

src/sqlfluff/core/dialects/dialect_snowflake.py
test/api/util_test.py

Issue [801](https://github.com/sqlfluff/sqlfluff/issues/801)
Using the new `.get_table_references()` util fails when specifying the "snowflake" dialect.
Test results:
```
============================================================================== test session starts ===============================================================================
platform darwin -- Python 3.8.3, pytest-6.2.2, py-1.10.0, pluggy-0.13.1
rootdir: /Users/kp/Projects/sqlfluff, configfile: pytest.ini
plugins: cov-2.11.1, hypothesis-6.3.0
collected 13 items
test/api/classes_test.py ....                                                                                                                                              [ 30%]
test/api/simple_test.py ....... …
```

#801: API .get_tables_references() Snowflake Dialect Bug

---

test/fixtures/parser/ansi/bracket_in_comment.sql

```
if bracket_is_definite:
raise SQLParseError(
f"Found unexpected end bracket!, was expecting one of: {matchers}, but got {matcher}",
segment=match.matched_segments[0],
)
sqlfluff.core.errors.SQLParseError: Found unexpected end bracket!, was expecting one of: [<Ref: SemicolonSegment>], but got <class 'sqlfluff.core.parser.segments.raw.end_bracket_SymbolSegment'>
src/sqlfluff/core/parser/grammar/base.py:589: SQLParseError
```
Any ideas on this one @alanmcruickshank? The logic around the error looks rather gnarly 😬

Bracket in comment bug

---

docs/source/rules.rst
plugins/sqlfluff-plugin-example/src/example/rules.py
src/sqlfluff/core/rules/__init__.py
src/sqlfluff/core/rules/std/L039.py
src/sqlfluff/core/rules/std/__init__.py

Right now the auto documentation for rules is broken! I actually introduced the bug on my pluggy PR.
@NiallRees brought it to my attention on Slack and I'm adding the bug fix
(see current issue: https://docs.sqlfluff.com/en/latest/rules.html#module-sqlfluff.core.rules.std)

Fix auto documentation for rules, broken by plugin PR

---

CHANGELOG.md
src/sqlfluff/core/dialects/dialect_ansi.py
test/fixtures/parser/ansi/expression_recursion.sql
test/fixtures/parser/ansi/expression_recursion.yml
test/fixtures/parser/ansi/expression_recursion_2.sql
test/fixtures/parser/ansi/expression_recursion_2.yml

This resolves #641 and resolves #669.
The way that the expression segment was parsing expressions with lots of operators was leading to recursion errors. This was because it was effectively parsing `a+b+c+d` as `a+(b+(c+d))`. This PR adjusts that parsing so that it parses as originally intended.

Fix infinite recursion issue with many operators

---

.readthedocs.yml

Docs have been failing fairly regularly for the pdf and latex builds. This updates the config to just not build those versions.

Don't build additional docs formats

---

plugins/sqlfluff-plugin-example/setup.py
src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/linter.py
src/sqlfluff/core/rules/base.py

Resolves #839 
I'm working on a real-world plugin for my employer. This PR addresses the noted issue. It also includes some othersmall changes I think will streamline plugin creation a bit.

Issue 839: Lint rules can see file path; other tweaks to the example plugin

---

.circleci/config.yml
src/sqlfluff/core/rules/std/__init__.py
tox.ini

For some reason `pydocstyle==6.0.0` released on 18th March is being installed in circle ci but not locally when installing from requirements and requirements dev. The [6.0.0 release adds](pydocstyle==6.0.0):
> Methods, Functions and Nested functions that have a docstring now throw D418 (#511).
I've ignored this rule in tox.ini

Fix linting

---

src/sqlfluff/core/dialects/dialect_ansi.py
src/sqlfluff/core/parser/grammar/anyof.py
test/fixtures/parser/ansi/arithmetic_a.yml
test/fixtures/parser/ansi/create_view_a.yml
test/fixtures/parser/ansi/modulo.yml
test/fixtures/parser/ansi/select_b.yml
test/fixtures/parser/ansi/select_j.yml
test/fixtures/parser/ansi/select_l.yml
test/fixtures/parser/ansi/select_m.yml
test/fixtures/parser/ansi/select_s.yml
test/fixtures/parser/bigquery/create_temp_function_with_select.yml
test/fixtures/parser/bigquery/select_1_gt_0.yml
test/fixtures/parser/bigquery/select_1_lt_0.yml
test/fixtures/parser/bigquery/select_gt_lt.yml
test/fixtures/parser/bigquery/select_lt_gt.yml
test/fixtures/parser/postgres/postgres_join_no_space.yml
test/fixtures/parser/snowflake/snowflake_lateral_flatten_after_join.yml
test/fixtures/templater/jinja_g_macros/jinja.yml

This is related to #870 .
In expression parsing, I noticed two parts not functioning correctly.
1. In `JoinOnConditionSegment` an additional `expression` layer was being added when it should just be _optionally bracketed_.
2. Nested expressions were being parsed as one big expression, because we we referring to an expression _grammar_ when brackets were present rather than an expression _segment_.
This addresses both.

Explicitly nest expressions when bracketed.

---

requirements.txt
setup.py

`dataclasses` is a library which became part of the standard library
from 3.7, so this package only needs to be added in environments with
Python 3.6 and lower
The reason how this cropped up was when I ran `sqlfluff` against our DBT repo running on Python 3.8.8.
And got the following traceback which is associated to having the `dataclasses` backport installed on Python 3.7 or above.
```
File "/venv/bin/sqlfluff", line 5, in <module>
from sqlfluff.cli.commands import cli
File "/venv/lib/python3.8/site-packages/sqlfluff/__init__.py", line 5, in <module>
from sqlfluff.api import lint, fix, parse, rules, dialects  # noqa: F401
File "/venv/lib/python3.8/site-packages/sqlfluff/api/__init__.py", line 6, in <module>
from sqlfluff.api.simple import lint, fix, …
```

only require dataclasses if installing on Python 3.6

---

src/sqlfluff/core/linter.py

This has been raised by several users now. As it isn't actionable by the end-user, it seems that it should be at the debug level.
https://sqlfluff.slack.com/archives/C01GX4L213J/p1614615362024600

Silence the Indent balance test failed warning

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/parser/ansi/like_operators.sql
test/fixtures/parser/ansi/like_operators.yml

This resolves #828 and #842.
I thought the issue was with regex strings, but it's actually just a lack of the `LIKE` style operators. This adds a relatively fully featured set based on on Postgres. I dithered a bit about whether this should go in the `ansi` dialect, or just in `postgres` but for now I don't think it's doing any harm here.
In mysql this might conflict with the bitwise negation operator `~`, but we don't seem to have many mysql users so far.

Like operators

---

src/sqlfluff/core/parser/grammar/base.py
src/sqlfluff/core/parser/helpers.py
src/sqlfluff/dialects/dialect_ansi.py
test/core/parser/helpers_test.py
test/dialects/ansi_test.py
test/fixtures/parser/ansi/set_order_by.sql
test/fixtures/parser/ansi/set_order_by.yml
test/fixtures/parser/ansi/set_order_by_complex.sql
test/fixtures/parser/ansi/set_order_by_complex.yml

This resolves #852 . This works by altering the `SelectableGrammar` and distinguishing between _ordered_ and _unordered_ select statements. For ease, they both have the same name, but only the former may contain `ORDER` or `LIMIT` clauses.
In solving this I've solved two other bugs:
1. In the `_look_ahead_match` heuristic, if there were multiple simple matches for a single matcher (e.g. multiple opened and closed brackets), then only one was being considered. This PR now iterates through all of them.
2. In `_bracket_sensitive_look_ahead_match` a critical error was thrown if we found an unmatched closed bracket. We could however get into this situation during terminator matching. In this case it's not a problem and is simply the signal that we should stop matching. Rather than raising an …

Set statement parsing

---

src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/std/L006.py
src/sqlfluff/core/rules/std/L010.py
src/sqlfluff/core/rules/std/L039.py
src/sqlfluff/core/rules/std/L048.py
test/core/linter_test.py
test/core/rules/std_test.py
test/fixtures/linter/operator_errors_ignore.sql
test/fixtures/rules/std_rule_cases/L006.yml
test/fixtures/rules/std_rule_cases/L048.yml

This resolves #360 .
It also refactors L006. Since the introduction of L039 (excessive whitespace), L006 no longer needs to lint for _too much_ whitespace. This PR applies that fix and also make the logic more reusable so that it can be used for L048 (missing whitespace around quoted literal). The refactor also improves the error message to be more explanatory (e.g. "Missing whitespace before *").
In implementing these I noted that L039 was only flagging on the first issue found and not all occurrences. This PR also extends that rule to fix that issue.
NB: L006 and L048 check for whitespace before *and* after (as before) but the anchor point for both is now the same. This means in comparing sets of check_tuples it appears as though the same error has appeared at the same position and …

Refactor L006 & L039, introduce L048

---

src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/core/rules/std/L044.py
src/sqlfluff/testing/rules.py
test/fixtures/rules/std_rule_cases/L044.yml

Resolves #930 
The coverage report is failing, but only because I added code to detect when linter tests cause unexpected exceptions -- I think the PR is ready for review and potential merge, unless we feel strongly about adding tests for the test framework.

Issue 930: L044 -- Max Recursion Depth

---

CHANGELOG.md
src/sqlfluff/cli/formatters.py
src/sqlfluff/core/config.py
src/sqlfluff/core/linter.py
src/sqlfluff/core/templaters/base.py
src/sqlfluff/core/templaters/dbt.py
src/sqlfluff/core/templaters/jinja.py
src/sqlfluff/core/templaters/python.py

This improves output UX, in particular for using the dbt templater. I think this resolves #645 too.
... now includes the templater and dbt version (if using the dbt templater)
```
==== sqlfluff ====
sqlfluff:           0.5.1 python:             3.8.5
dialect:        snowflake verbosity:              1
templater:            dbt dbt:              =0.19.1
rules:       L004, L010, L011, L014, L025
```
When running at the first verbose level (or above), there's now an output to show when model compilation is happening.
```
==== sqlfluff ====
sqlfluff:           0.5.1 python:             3.8.5
dialect:        snowflake verbosity:              1
templater:            dbt dbt:              =0.19.1
rules:       L004, L010, L011, L014, L025
==== readout ====
=== [ path: /root/data_warehouse ] === …
```

Logging and output improvements

---

CHANGELOG.md

I missed this during the initial release 😬

Fix missing version number in changelog

---

tox.ini

requires.io picked up that our version dependencies are out of date. This bumps dbt versions to the latest for each stream.

Update dbt versions for testing.

---

src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/core/rules/std/L045.py
test/fixtures/rules/std_rule_cases/L045.yml

Resolves #963.
Fixes another bug similar to the one addressed in #938 -- infinite recursion in one of the new CTE analysis rules.

Issue 963: Fix bug where L045 recurses forever if a CTE references itself

---

src/sqlfluff/core/dialects/__init__.py

Sort sqlfluff cli `dialects` output
before
```bash
(sqlfluff) ➜  sqlfluff git:(cli_sort_dialect) ✗ sqlfluff dialects
==== sqlfluff - dialects ====
ansi:                 ansi dialect [inherits from 'nothing']
bigquery:            bigquery dialect [inherits from 'ansi']
mysql:                  mysql dialect [inherits from 'ansi']
teradata:            teradata dialect [inherits from 'ansi']
postgres:            postgres dialect [inherits from 'ansi']
snowflake:      snowflake dialect [inherits from 'postgres']
exasol:                exasol dialect [inherits from 'ansi']
exasol_fs:        exasol_fs dialect [inherits from 'exasol']
```
after
```bash
(sqlfluff) ➜  sqlfluff git:(cli_sort_dialect) ✗ sqlfluff dialects
==== sqlfluff - dialects ====
ansi:                 ansi dialect [inherits from …
```

Sort cli dialects output

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/rules/std/L010.py

This PR speeds up L010 and L014 **a lot**. We can consider closing #962 as a result, or maybe we want to do more performance analysis and/or tuning?
Besides speeding up the two rules, this PR also makes a small change to the CLI to simplify the process for users profiling the performance of SQLFluff commands (e.g. lint, fix) on their own machines. In many cases, this means the maintainers can get performance insights without having to ask users to upload their confidential SQL code.
To generate a function-level performance report, the user would run:
```
python -m cProfile -s cumtime -m sqlfluff.cli.commands lint my_query.sql > output.txt
```

Speed up L010, allow invoking sqlfluff.cli.commands as a module to simplify profiling

---

src/sqlfluff/core/rules/std/L016.py

Resolves #967.
I didn't have a test case for this simple fix, but the person who reported the issue confirms that it fixed their problem. See comments on #967.

Issue 967: Add guard to avoid "tuple index out of range" error

---

src/sqlfluff/rules/L036.py
test/fixtures/rules/std_rule_cases/L036.yml

Resolves #1022 
This PR relates to the formatting discussion on PR #905, which led to us creating issue #946. This PR does not attempt to address the larger issues raised there. Rather, it addresses a particular case where L036 left behind poor formatting that, for some reason, was not addressed by other indentation rules such as L003.

Issue 1022: When L036 moves single select target to another line, remove whitespace

---

src/sqlfluff/core/parser/grammar/anyof.py
src/sqlfluff/core/parser/grammar/base.py
src/sqlfluff/core/parser/grammar/delimited.py
src/sqlfluff/core/parser/grammar/greedy.py
src/sqlfluff/core/parser/grammar/sequence.py
src/sqlfluff/core/parser/match_wrapper.py
src/sqlfluff/core/parser/segments/__init__.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/parser/segments/ephemeral.py
src/sqlfluff/core/parser/segments/raw.py
test/core/parser/grammar_test.py
test/core/parser/segments_common_test.py

This follows on from #1034, and should be reviewed after that is merged. It relates to #1019,
This addresses ephemeral segments so that they don't involve dynamic class generation. Specifically.
- `EphemeralSegment` now accepts a `parse_grammar` so that instances can act as the dynamic classes before.
- Creation of `EphemeralSegment` has been moved from the `@match()` decorator to a seperate decorator `@allow_ephemeral` which is then only attached to the `.match()` methods of grammars and not segments. This simplifies the code path and also avoids a circular reference.
- As we now only create the `EphemeralSegment` on `match()`, all the code which created the custom class can be removed from the `__init__` method of `BaseGrammar`.
- Extra test cases added to test the full lifecycle of an …

EphemeralSegment rework (#1019)

---

src/sqlfluff/core/errors.py
src/sqlfluff/core/linter.py
src/sqlfluff/core/templaters/dbt.py

We're currently having an issue where SQLFluff takes ages to fail, but results in the same failure on every file. Specifically it's where the dbt templater fails to compile and then keeps attempting (This clearly takes a LONG time).
This adds a `fatal` flag to some errors which enables them to terminate linting entirely, to return an error to the user faster.

Fail fast on fatal errors

---

src/sqlfluff/core/parser/markers.py
src/sqlfluff/core/parser/segments/base.py
test/core/parser/markers_test.py

Resolves #1047 .
Some of the code was written expecting line positions to be zero-indexed, and some expecting them to be 1-indexed. This resolves all to be 1-indexed, fixing the off-by-one error being caused during repositioning.
I'll do a bugfix release to 0.5.4 once this is merged

Off by one error fix in working locations

---

CHANGELOG.md
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/parser/segments/raw.py
src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/rules/L010.py
src/sqlfluff/rules/L013.py
src/sqlfluff/rules/L033.py
src/sqlfluff/rules/L034.py
src/sqlfluff/rules/L036.py
test/dialects/ansi_test.py
test/fixtures/rules/std_rule_cases/L036.yml

This solves some type checking issues introduced in 0.5.5 (resolves #1049) and also handles `distinct` clauses in L036 to resolve #1024.
The issue was that in editing new segments, the new `type` wasn't being passed through.

Type Fixes #1049 #1024

---

src/sqlfluff/cli/commands.py

This enables `sqlfluff lint -p 4` rather than just `sqlfluff lint --parallel 4`.

Add short option for parallel

---

CHANGELOG.md
src/sqlfluff/api/__init__.py
src/sqlfluff/api/simple.py
src/sqlfluff/core/linter/__init__.py
test/api/simple_test.py

This resolves #569 (an oldie), it's also a good one to fit into a major release if we've got 0.6.0 coming up, because it could break code which depends on the simple api.
Exactly as suggested by @dmateusp - this groups together any parsing exceptions and prints them nicely. Here's an example traceback if running in the console:
```
>>> import sqlfluff
>>> sqlfluff.parse("Select (1 + 2 +++) FROM mytable as blah blah")
File "<stdin>", line 1, in <module>
File "c:\...\sqlfluff\src\sqlfluff\api\simple.py", line 89, in parse
raise APIParsingError(parsed.violations)
sqlfluff.api.simple.APIParsingError: Found 2 issues while parsing string.
Line 1, Position 14: Found unparsable section: ' +++'
Line 1, Position 41: Found unparsable section: 'blah'
```

Better simple API parsing exceptions

---

tox.ini

These two settings are about the same thing: The length of long lines.
Setting `max-line-length = 196` avoids all flake8 E501 errors and allows us to:
1. Flag attempts to add of even longer lines
2. Wrap long lines and lower max-line-length toward the recommended 88 chars per line.

flake8 ignore=E501 and --max-line-length are mutually exclusive

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

Fixes #1043 
Echos some strings describing the way SQLFluff felt about the SQL it saw. This is mostly a proposal for the _copy_ of the strings. I'm fairly agnostic about it and realize the way it's written right now is very much of my vibe (which may not be shared by others!).
I'm also agnostic on how deeply this should be tested. Ought we be testing on the CLI output being an exact string match? if so, we can add cases to `test__cli__command_directed` and so on.
```
➜ sqlfluff lint test/fixtures/cli/passing_a.sql
All Finished 📜 🎉!
```
```
➜ sqlfluff lint test/fixtures/cli/fail_many.sql
== [test/fixtures/cli/fail_many.sql] FAIL
L:   3 | P:   8 |  TMP | Undefined jinja template variable: 'something'
L:   3 | P:  21 |  PRS | Line 3, Position 6: Found unparsable section: 'as
| …
```

Add a little fun on lint/fix CLI exit

---

mypy.ini
requirements.txt
setup.py
src/sqlfluff/cli/commands.py
src/sqlfluff/core/__init__.py
src/sqlfluff/core/linter/linted_file.py
src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/linter/linting_result.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/timing.py

The procedural nature of `BenchIt` was causing issues with the changes I'd like to make to the `Linter` class to support #1088 . I asked on the slack thread and nobody voted to keep the exiting `BenchIt` implementation, but I think there's still value in profiling and benchmarking tools.
This PR removes the `BenchIt` library and replaces the functionality with a `TimingSummary` object which displays more useful descriptive stats about where time was spent during the operation.

Rip out BenchIt and replace with TimingSummary

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/linter/runner.py
test/core/linter_test.py

As suggested in #1101 and to support #1088, this extracts runner selection logic into the `runner` module.

Extract runner selection logic

---

CHANGELOG.md
src/sqlfluff/cli/commands.py
src/sqlfluff/core/linter/common.py
src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/linter/linting_result.py
src/sqlfluff/core/linter/runner.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/templaters/base.py
src/sqlfluff/core/templaters/dbt.py
src/sqlfluff/core/templaters/jinja.py
src/sqlfluff/core/templaters/python.py
test/cli/commands_test.py
test/core/linter_test.py
test/core/templaters/base_test.py
test/core/templaters/jinja_test.py
test/core/templaters/python_test.py
test/fixtures/linter/autofix/bigquery/004_templating/after.sql

This PR has a couple of things to still shake out. Namely that one test is failing for a reason I don't understand, and it looks like the CLI output is treading on toes when running in parallel. Those issues aside, I think it's ready for a review, at least from an architecture standpoint.
This resolves #1088 .
I've tested it on our large dbt project with the dbt templater and it's FAST.
It also builds on #1103 so will be easier to review once that's merged.
In short:
- We render the sql files in the main thread and then pass them to the child threads for parsing and linting.
- The rest of the changes are making enough methods in the linter _static_ or _class_ methods to do that in a way that we don't have to create a new `Linter` object each time.

Draft: Resolve parallel dbt templating issue

---

.github/workflows/check-changelog-edited.yml
CHANGELOG.md

Closes #1094 
Adds a GH action to check that the changelog was edited in each PR. We can make this optional in the repo settings (um, at least Alan can): https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule
Testing this out on this branch. I will attempt to first fail the check and then pass it!

Add changelog check action

---

src/sqlfluff/rules/L017.py
test/fixtures/rules/std_rule_cases/L017.yml

- I have fixed:
Comparison in line 46 was wrong. Segment _start_bracket_ is nested a _bracketed_ segment, so it was never falling in the condition and was working accidentally for normal cases, but not working for window functions.

Fix L017 window function bug.

---

.circleci/config.yml
CHANGELOG.md
src/sqlfluff/rules/L034.py
src/sqlfluff/testing/rules.py
test/core/templaters/dbt_test.py
test/fixtures/dbt_project/models/my_new_project/L034_test.sql
test/fixtures/rules/std_rule_cases/L034.yml

Several users have now reported that L034 will apply broken fixes to select statements which contain macros (https://getdbt.slack.com/archives/CV2KM39KR/p1622420620013500), most commonly dbt's `{{ dbt_utils.surrogate_key() }}`. This change anchors L034 on the select statement segment so that statements using macros are completed ignored by the rule.
@barrywhart I realise this changes the behaviour that you added in https://github.com/sqlfluff/sqlfluff/pull/918, so I'm interested for your thoughts. For us to keep the behaviour you added and be able to ignore the statement if it contains a templated section we'll need to add additional functionality to the ignore_templated_areas logic.
I've had to remove the dbt017-py38 tests due to an incompability with dbt utils 0.6.3 which was throwing …

Ignore select statements with macros in L034

---

CHANGELOG.md
README.md
docs/source/teamrollout.rst

Quick docs update given a pending change to the sqlfluff-online deployment: https://github.com/sqlfluff/sqlfluff-online/pull/24
The app is currently live at https://online.sqlfluff.com/, and when that PR merges it will auto deploy to GCP which points to the right spot.

Update sqlfluff online links

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/parser/ansi/drop_schema_a.sql
test/fixtures/parser/ansi/drop_schema_a.yml
test/fixtures/parser/ansi/set_schema_a.sql
test/fixtures/parser/ansi/set_schema_a.yml

I have added SET SCHEMA and DROP SCHEMA support to ANSI dialect. The bug was originally opened for Postgres, but I noticed that it is supported by ANSI (and CREATE SCHEMA was already added there actually).
Closes #1080

Add SET SCHEMA and DROP SCHEMA support to ANSI dialect

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/parser/mysql/close.sql
test/fixtures/parser/mysql/close.yml
test/fixtures/parser/mysql/close_qualified.sql
test/fixtures/parser/mysql/close_qualified.yml
test/fixtures/parser/mysql/fetch.sql
test/fixtures/parser/mysql/fetch.yml
test/fixtures/parser/mysql/fetch_from.sql
test/fixtures/parser/mysql/fetch_from.yml
test/fixtures/parser/mysql/fetch_multiple.sql
test/fixtures/parser/mysql/fetch_multiple.yml
test/fixtures/parser/mysql/fetch_next_from.sql
test/fixtures/parser/mysql/fetch_next_from.yml
test/fixtures/parser/mysql/fetch_session.sql
test/fixtures/parser/mysql/fetch_session.yml
test/fixtures/parser/mysql/fetch_session_multiple.sql
test/fixtures/parser/mysql/fetch_session_multiple.yml
test/fixtures/parser/mysql/open.sql
test/fixtures/parser/mysql/open.yml
test/fixtures/parser/mysql/open_qualified.sql
test/fixtures/parser/mysql/open_qualified.yml

Added syntax for cursors and made a revision to the `IntoClauseSegment` that was discovered when working on the cursor statement syntax that also uses the `INTO` keyword.
Resolves #1145

Add cursor syntax to mysql dialect

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol.py
test/dialects/ansi_test.py
test/dialects/exasol_test.py
test/fixtures/parser/ansi/truncate_a.sql
test/fixtures/parser/ansi/truncate_a.yml
test/fixtures/parser/ansi/truncate_table_a.sql
test/fixtures/parser/ansi/truncate_table_a.yml

Adding support for the commonly implemented (but not strictly ANSI) `TRUNCATE TABLE` statement.

Add TRUNCATE to ANSI Dialect

---

CHANGELOG.md
docs/source/production.rst
src/sqlfluff/cli/commands.py
test/cli/commands_test.py

sqlfluff lint: Add "github-annotation" format

---

test/core/linter_test.py
test/core/templaters/dbt_test.py

Two of the dbt tests are failing on windows because of path normalisation. This addresses that and fixes both.

Normalise path tests for windows

---

src/sqlfluff/cli/commands.py

Currently, both `sqlfluff lint` and `sqlfluff fix` have the `--processes` flag but **only** `sqlfluff lint` has the shortened `-p` flag. 
I've added the `-p` flag to the `click.option()` for `sqlfluff fix` to add consistency across both calls. 
-----------
I've read through the CONTRIBUTING.md and noted this statement in the **Maintainers** section: 
> That means for smaller changes and improvements they may review changes as individuals and merge them into the project in a very lightweight way.
Because of that line, I have not cloned and ran the `tox` commands. If this change requires me to do that, please let me know and I will run through the test for this enhancement #1229

Add -p flag for fix command

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/create_js_function_deterministic.sql
test/fixtures/parser/bigquery/create_js_function_deterministic.yml

Fixes #1251 
Note technically this is only supported for `LANGUAGE js` but so is `OPTIONS` and it wasn't restricted when it was implemented, so I kept this simple and did the same for this.

Add DETERMINISTIC support for BigQuery

---

CHANGELOG.md
docs/source/configuration.rst
docs/source/indentation.rst
src/sqlfluff/core/default_config.cfg
src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/rules/std_rule_cases/L003.yml

Fixes #1250 
Note default is left as is to avoid a breaking change.

Allow optional indention of USING and ON clauses

---

CHANGELOG.md
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L047.py
test/fixtures/rules/std_rule_cases/L047.yml

Fixes #1260 
I've gone with the simpler option of two separate configs to avoid breaking backwards compatibility. So you can have:
```yml
prefer_count_1: True
```
or:
```yml
prefer_count_0: True
```
And if both are specified:
```yml
prefer_count_1: True
prefer_count_0: True
```
Then `prefer_count_1` takes precedence (no matter what order they are specified in).
As I say, ideally you'd not be able to have contradictory params like this, so let me know if you think we should introduce a breaking change here instead.
Barry
P.S. I swear I'm not trying to annoy you @barrywhart - I just seem to get each next PR finished just at the exact same time as you merge the last one! 😁

Support COUNT(0) preference over COUNT(*) or COUNT(1)

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/select_function_object_field_wildcard.sql
test/fixtures/parser/bigquery/select_function_object_field_wildcard.yml

A further enhancement to #1255 to allow wildcard support as well:
```sql
SELECT testFunction(a).*
FROM table1
```

Add wildcard support for function fields access in BigQuery

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/select_function_object_fields.sql
test/fixtures/parser/bigquery/select_function_object_fields.yml

Fixes #1171 
Adds explicit support of [OFFSET and ORDINAL clauses](https://cloud.google.com/bigquery/docs/reference/standard-sql/array_functions#offset_and_ordinal) of Array Functions, which can then be further referenced by fields:
```sql
SELECT
testFunction(a)[OFFSET(0)].* AS field_with_offset_wildcard
FROM table1
```

Support OFFSET and ORDINAL clauses of Array Functions in BigQuery

---

.github/workflows/check-yaml-files-generation.yml
CHANGELOG.md
CONTRIBUTING.md
test/fixtures/parser/bigquery/select_mixture_of_array_literals.yml
tox.ini

Fixes #1277 
This PR adds the following:
- Adds the generate command to `tox.ini` config so YAML files will be generated when contributors run `tox` locally
- Adds a new GitHub Action to check that contributors have included any necessary YAML changes by running the script and checking for diffs. The tests already pick up diffs, but ignores whitespace changes for manually edited files - which can then pollute future PRs when the next person runs the generate scripts.
YAML files can still be generated via the python script, via the new tox config above, or via manual editing - as long as they match what would auto generate.

Add fixture YAML generation checks

---

CHANGELOG.md
docs/source/inthewild.rst

Noticed in the last release that the links add #1267 don't work on this page: https://docs.sqlfluff.com/en/stable/inthewild.html
Looks like I missed an underscore :-(

Fix typo on the In the Wild page

---

CHANGELOG.md
src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/parser/ansi/select_named_window_with_parentheses.sql
test/fixtures/parser/ansi/select_named_window_with_parentheses.yml

Support empty OVER() clause in Window Specification

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/ansi/create_function_no_args.sql
test/fixtures/parser/ansi/create_function_no_args.yml
test/fixtures/parser/bigquery/create_function_no_args.sql
test/fixtures/parser/bigquery/create_function_no_args.yml
test/fixtures/parser/bigquery/create_js_function_underscore_name.sql
test/fixtures/parser/bigquery/create_js_function_underscore_name.yml
test/fixtures/parser/bigquery/select_udf_quote_everything.yml
test/fixtures/parser/bigquery/select_udf_quote_project_and_datasetfunctionname.yml

Fixes #1298
Basically same fix as #1254 but for Function Names - BigQuery doesn't define a more restrictive set of requirements for Function identifiers so we shouldn't either.
Also adds support for Parameterless functions in `CREATE FUNCTION` (e.g. `CREATE FUNCTION a() AS...`) which I discovered was [already available in ANSI SQL](https://github.com/sqlfluff/sqlfluff/blob/b6175995b1f92ebdb1fdd8ccf02d1d8465aa5770/src/sqlfluff/dialects/dialect_ansi.py#L2682) but not in the [override for BigQuery](https://github.com/sqlfluff/sqlfluff/blob/b6175995b1f92ebdb1fdd8ccf02d1d8465aa5770/src/sqlfluff/dialects/dialect_bigquery.py#L475). Also added a test case for this for both ANSI and BigQuery.

Add Parameterless Functions and more function names support to BigQuery

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/create_function_no_args.yml
test/fixtures/parser/bigquery/create_js_function_complex_types.yml
test/fixtures/parser/bigquery/create_js_function_deterministic.yml
test/fixtures/parser/bigquery/create_js_function_options_library_array.yml
test/fixtures/parser/bigquery/create_js_function_quoted_name.yml
test/fixtures/parser/bigquery/create_js_function_simple.yml
test/fixtures/parser/bigquery/create_js_function_underscore_name.yml
test/fixtures/rules/std_rule_cases/L048.yml

Rule L048 is the following:
> Quoted literals should be surrounded by a single whitespace.
> 
> _sqlfluff fix compatible._
> 
> **Anti-pattern**
> In this example, there is a space missing space between the string ‘foo’
> and the keyword AS.
> ```sql
> SELECT
>     'foo'AS bar
> FROM foo
> ```
> **Best practice**
> Keep a single space.
> ```sql
> SELECT
>     'foo' AS bar
> FROM foo
> ```
> 
That currently doesn't work with BigQuery User Defined Functions using the triple quote syntax:
```sql
CREATE TEMPORARY FUNCTION a()
LANGUAGE js
AS '''
CODE GOES HERE
''';
```
As it fails with ` Missing whitespace after []; } '''` because currently the UDF body is defined as a literal.
This PR moves it to it's own type (exactly the same as quoted literals except for the type) so rule L048 can be run …

Allow BigQuery UDF with triple quoted bodies to pass rule L048

---

src/sqlfluff/core/rules/analysis/select.py
test/fixtures/linter/autofix/bigquery/005_unnest_spacing/after.sql
test/fixtures/linter/autofix/bigquery/005_unnest_spacing/before.sql
test/fixtures/linter/autofix/bigquery/005_unnest_spacing/test-config.yml

Fixes #1302 so when SQL fails L003 (and adds indentation spacing) it doesn't break rule L025 (which has a special case for BigQuery that doesn't work when spacing is added).
Nope
- Other.
I don't know how to add a test case for this to be honest as it only …

Fix spacing issue for BigQuery UNNEST statement for rules L003 and L025

---

CHANGELOG.md
src/sqlfluff/config.ini

This is for a 0.6.4 release. This release was requested by @tunetheweb due to a high-priority BigQuery bug fix (issue #1302).

0.6.4 release

---

test/cli/commands_test.py

Fixes #1333. Changes the call to python in test___main___help() to sys.executable, which is the path of the current instance of Python that you are running. This ensures that sys.path is the same in the subshell. Also passes in os.environ into the subshell, in case the path is defined for any developers in the PYTHONPATH.
...
No
- Other.
- …

Bugfix PR, fixes issue #1333, wherein test___main___help() defaults to your default Python installation

---

plugins/sqlfluff-plugin-example/src/example/rules.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/rules/L001.py
src/sqlfluff/rules/L002.py
src/sqlfluff/rules/L003.py
src/sqlfluff/rules/L004.py
src/sqlfluff/rules/L005.py
src/sqlfluff/rules/L008.py
src/sqlfluff/rules/L009.py
src/sqlfluff/rules/L012.py
src/sqlfluff/rules/L014.py
src/sqlfluff/rules/L016.py
src/sqlfluff/rules/L018.py
src/sqlfluff/rules/L020.py
src/sqlfluff/rules/L023.py
src/sqlfluff/rules/L024.py
src/sqlfluff/rules/L037.py
src/sqlfluff/rules/L038.py
src/sqlfluff/rules/L039.py
src/sqlfluff/rules/L040.py
src/sqlfluff/rules/L044.py
src/sqlfluff/rules/L045.py
src/sqlfluff/rules/L046.py
test/core/rules/docstring_test.py

Add unittest for sqlfluff rules docstring for more readable doc and avoid regression.
before this patch, our rules ref have wrong syntax of code
Some of the rule without example
And this path should fix this.

Add unittest for rules docstring

---

docs/source/conf.py

We should using github star instead of github watch in our docs,
and I think we should remove repo code coverage in our docs too.
**Before**
**After**

Using github star instead of watch in docs

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/select_with_offset_3.sql
test/fixtures/parser/bigquery/select_with_offset_3.yml

Allow optional alias for BigQuery WITH OFFSET

---

src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_teradata.py
test/fixtures/parser/bigquery/select_with_union_and_qualify.sql
test/fixtures/parser/bigquery/select_with_union_and_qualify.yml
test/fixtures/parser/snowflake/snowflake_qualify_union.sql
test/fixtures/parser/snowflake/snowflake_qualify_union.yml
test/fixtures/parser/teradata/qualify_expression_union.sql
test/fixtures/parser/teradata/qualify_expression_union.yml

The `QUALIFY` clause was added by myself to BigQuery in #1281 but currently it is not set up to be used in UnorderedSelectStatements as used by the `UNION` statements:
```sql
SELECT a
FROM b
QUALIFY a > 122
UNION ALL
SELECT a
FROM b
QUALIFY a > 122
```
This PR adds that support.
I also added it to snowflake and teradata while at it as see they use this too
Shouldn't be
- Other.
- Added …

BigQuery: Allow Qualify Clause for UnorderedSelectStatements

---

src/sqlfluff/core/config.py
src/sqlfluff/core/dialects/base.py
src/sqlfluff/core/errors.py
src/sqlfluff/core/linter/linted_dir.py
src/sqlfluff/core/linter/linted_file.py
src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/linter/linting_result.py
src/sqlfluff/core/linter/runner.py
src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/doc_decorators.py
src/sqlfluff/core/timing.py

Progress on #1314 this adds coverage exceptions (using `# pragma: no cover`) for the `src/sql/core` files exception for:
- src/sql/core/parser (big one and this PR is big enough)
- src/sql/core/templaters (a lot of changes in #1264 waiting to be merged so best left alone)
**_It often seems to be `src/sqlfluff/core/linter/runner.py` which causes us noise in PR so hopefully the fact it is covered to 100% in this PR will reduce that noise until we can get to 100%._**
The remaining ones will be covered in a future PR.
The rest have been addressed and now show 100% coverage:
```
Name                                                 Stmts   Miss  Cover   Missing
----------------------------------------------------------------------------------
src/sqlfluff/__init__.py …
```

Pytest coverage exceptions for Core code - part 1

---

docs/source/gettingstarted.rst
docs/source/production.rst
examples/01_basic_api_usage.py
src/sqlfluff/rules/L010.py
src/sqlfluff/rules/L014.py
src/sqlfluff/rules/L030.py
src/sqlfluff/rules/L040.py
test/api/simple_test.py
test/cli/commands_test.py
test/fixtures/rules/std_rule_cases/L010.yml

closes https://github.com/sqlfluff/sqlfluff/issues/1128 and base on pr https://github.com/sqlfluff/sqlfluff/pull/1173.
Cause @scrambldchannel  seem not work on https://github.com/sqlfluff/sqlfluff/pull/1173 anymore, so I start PR base on it
and set @scrambldchannel as the co-author
Currently Rule L010 error message too generic, we should show configure what we set in the error message
- Other. …

Enhance error message L010 base on configure

---

src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/rules/L020.py
test/fixtures/rules/std_rule_cases/L020.yml
test/rules/std_L020_test.py

Rule_L020 only show first LintResult before,
after this patch merge Rule_L020 would show
all duplicate table aliases, without duplicate
position
I think this PR no need add `std_rule_cases` here, am I wrong?
- ~`.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.`~  Already exists and no need

Show all LintResult in Rule_L020

---

README.md

Branch name no longer correct, currently shows a "no builds" badge. Change missed in #1311
Nope
- [n/a] Please confirm you have completed any of the necessary steps below.
- Other.

Correct CircleCI badge reference

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/parser/bigquery/select_with_qualify.sql
test/fixtures/parser/bigquery/select_with_qualify.yml

A further enhancement to BigQuery `QUALIFY` support to allow optional `ORDER BY` and `LIMIT` clauses to be specified afterwards.
...
- Other.

Allow ORDER BY and LIMIT after QUALIFY in BigQuery

---

src/sqlfluff/rules/L001.py
test/fixtures/rules/std_rule_cases/L001.yml

Fixes #1371 
Currently we don't handle this:
```sql
printf ' \nSELECT 1' | sqlfluff fix -
```
As it throws this:
```
==== finding fixable violations ====
CRITICAL   [L001] Applying rule L001 threw an Exception: tuple index out of range 
File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/sqlfluff/core/rules/base.py", line 301, in crawl
res = self._eval(
File "/home/vladimir/work/extern/sqlfluff/venv/lib/python3.9/site-packages/sqlfluff/rules/L001.py", line 44, in _eval
while raw_stack[idx].is_type("whitespace"):
IndexError: tuple index out of range
```
This is because we don't do a length check in rule L001 before decrementing the index. We do do this check on similar lookback rules (L016, L018) so similar enough change to add …

Handle initial whitespace lines in rule L001

---

src/sqlfluff/rules/L034.py
test/fixtures/rules/std_rule_cases/L034.yml

Fixes #1268
Prevents L034 from making changes inside "INSERT" or "CREATE TABLE AS SELECT" statements, where the order of columns in a "SELECT" should be preserved.
- Other.

Issue 1268: L034 should not fix inside "INSERT" or "CREATE TABLE AS SELECT"

---

src/sqlfluff/rules/L003.py
test/fixtures/rules/std_rule_cases/L003.yml

Fixes #1310
Rule L003 was only allowing hanging indent for a single line. This results in inconsistent indentation. As an experiment, I disabled the single-line limitation. No tests broke, so I guess this is okay?
I added a new test based on the user-reported issue, so if future concerns arise about this rule, we'll have a test case to make sure we can converge towards a better solution and not "flap" back and forth.
...
As mentioned above, hanging indent is now allowed for any number of consecutive lines.  Is this ever a bad thing? Unsure.
- `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto …

Issue 1310: L003 fix mixes hanging and clean indents

---

benchmarks/bench_002/bench_002_pearson_fix.sql
src/sqlfluff/rules/L016.py
test/fixtures/linter/autofix/ansi/008_looping_rules_l003_l016_l019/after.sql
test/fixtures/linter/autofix/ansi/008_looping_rules_l003_l016_l019/before.sql
test/fixtures/linter/autofix/ansi/008_looping_rules_l003_l016_l019/test-config.yml
test/fixtures/rules/std_rule_cases/L016.yml

Fixes #1344 
L016 "Line is too long" has a bug that causes it to behave pathologically if it finds a line with an inline comment that is:
* Is on a line with other code
* Exceeds the maximum line length even after moving it to a line by itself
E.g.
```
,--  the "y variable" and uses_small_subject_line to be the "x variable" in terms of the regression line.
```
In this case, L016 keeps adding blank lines endlessly until it hits the `sqlfluff fix` iteration limit (typically 10).
- `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by …

Issue 1344: L016: "sqlfluff fix" adds too many newlines

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

Handles templater errors and otherwise unfixable errors better when fixing stdin.
fixes #1196 
Instead of excepting like:
```
➜ echo '--Airflow: ml_cxe_service_metrics -
CREATE TABLE IF NOT EXISTS {{ params.ml_schema }}.daily_service_metrics (
source_type varchar(10) NOT NULL,
visit_date date NOT NULL,
event_name text NOT NULL,
event_count bigint NOT NULL
)
diststyle even
compound sortkey(visit_date, source_type)
;' | sqlfluff fix - --dialect postgres
...
AttributeError: 'NoneType' object has no attribute 'templated_str
```
This PR allows fluff to exit like
```
➜ echo '--Airflow: ml_cxe_service_metrics -
CREATE TABLE IF NOT EXISTS {{ params.ml_schema }}.daily_service_metrics (
source_type varchar(10) NOT NULL,
visit_date date NOT NULL,
event_name text …
```

Handle template and unfixable errors when fixing stdin

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py
test/fixtures/rules/std_rule_cases/L016.yml
util.py

Fixes #1340 
It also adds a couple of test cases for recently merged changes (#1382 and #1385) that did not have coverage (we to figure out why Coverage checking has stopped! See #1388):
We now exit `fix` with a non-zero exit code if there are unfixable errors. This is a change in behaviour and may be unexpected by some, but we think it's better to raise these issues.
- Other.
- Added …

Change fix to use non-zero exit code if unfixable

---

docs/source/conf.py

Corrects the codecov badge on https://docs.sqlfluff.com/ to use the `main` branch (as we use) rather than the default `master` branch, which has a pitiful 96% code coverage 😁
Docs: https://alabaster.readthedocs.io/en/latest/customization.html#theme-options
Nope
- Other. …

Correct codecov badge for Docs website

---

src/sqlfluff/core/linter/runner.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/rules/L003.py
src/sqlfluff/rules/L019.py
test/fixtures/linter/autofix/ansi/008_looping_rules_l003_l016_l019/after.sql
test/fixtures/linter/autofix/bigquery/004_templating/after.sql
test/fixtures/linter/autofix/bigquery/004_templating/before.sql
test/fixtures/rules/std_rule_cases/L003.yml
test/fixtures/rules/std_rule_cases/L019.yml

Fixes #1387 
This PR fixes a couple of issues:
- Primary fix: Previously, when run in "trailing comma" mode, L019 was only moving commas one line at a time, even if there were multiple comment or blank lines between the initial location and the desired final location. This caused the linter to require additional loops (bad) and could result in hitting the linter loop limit while the comma was in mid-journey.
- Secondary fix: I found that when I fixed the above issue, it surfaced a bug in L003 that had previously been hidden in some cases. Amusingly, when a comma would move through a comment block, it would sometimes trigger useful indentation changes along the way. Now that the comma jumps immediately to the final destination, this was no longer occurring. So I updated L003 to explicitly …

Improve rules L003 and L019 by processing multi-line fixes in one pass.

---

src/sqlfluff/core/rules/doc_decorators.py

Noticed in our [Rules documentation](https://docs.sqlfluff.com/en/stable/rules.html) that when `sqlfluff fix compatible` is added, it causes the rest of the documentation to indent:
This means the `sqlfluff fix compatible` rules are out of alignment with the non-`sqlfluff fix compatible` rules.
Turns out to be because there it is straight inserted with no indents so looks like the start of a new section.
Don't think so. …

Fix "sqlfluff fix compatible" rules indenting to much in documentation

---

.github/codecov.yml

Currently when you open a PR you often get a false Coverage report when some, but not the main tests have finished. This PR ups the limit to prevent this from happening.
I picked 7 because we have:
- 4 main checks (3.6, 3.7, 3.8, 3.9)
- 3 dbt checks (018, 019, 020)
- 2 windows (py3.8 and dbt)
Or 9 coverage reports.
We want at least one main check and one dbt check to have completed so the minimum number of checks for that to have happened is 6. We'll add one for luck to get to lucky number 7.
Also changed default branch to `main`
- `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated …

Prevent CodeCov commenting on coverage differences too early

---

CONTRIBUTING.md
docs/README.md
docs/source/developingplugins.rst

Took a bit to figure this out so thought best to document it
Did some clean up of the CONTRIBUTION.md file while at it:
- Move the installing of the virtual env above testing.
- Renamed it from "Using your local version" to "Developing and Running SQLFluff Locally"
- Made titles in Title case consistently.
- Indented all the Nerdy Details under Nerdy Details.
Nope.
- Other. …

Add README on how to generate docs

---

src/sqlfluff/cli/commands.py

Follow on from #1385 
Following changes:
- The current error is not highlighted in red so is a bit lost.
- Also we only show the error when in `verbose` mode which I think in hindsight is not great.
- Should use stderr so anyone using output from stdout can continue to
- Explain how to override
Nope.
- Other. …

Better error messages on error

---

CONTRIBUTING.md
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L011.py
src/sqlfluff/rules/L012.py
test/cli/commands_test.py
test/fixtures/rules/std_rule_cases/L011.yml
test/fixtures/rules/std_rule_cases/L012.yml
test/rules/std_test.py

Fixes #1400 
Affects rules L011 and L012 which inherits from this. Default is left as explicit.
- Other.

Allow optional enforcing of implicit aliasing of tables (L011) and columns (L012)

---

src/sqlfluff/rules/L016.py
test/fixtures/linter/autofix/bigquery/002_templating/after.sql
test/fixtures/rules/std_rule_cases/L016.yml

Issue 845: L016 should compute line length prior to template expansion

---

src/sqlfluff/dialects/dialect_tsql.py

Remapping segments to Nothing() that have no TSQL equivalent.  This will keep the linter from pursing paths that include TSQL non-keywords and failing with the runtime error "Grammar refers to '<Keyword>KeywordSegment' which was not found in the tsql dialect".

TSQL: Remove match possibilities for segments with no TSQL equivalent

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/parser/postgres/postgres_psql_meta_command.sql
test/fixtures/parser/postgres/postgres_psql_meta_command.yml

This PR adds support for psql meta commands. Psql commands here start with \, followed by at least one alphabet character, and are then terminated by newline or \\. The File and Statement Segments had to be edited to accommodate for this new functionality.
Fixes #1327 
No, Postgres-specific, and all dialect tests are passing
Test cases added for psql meta commands, and sql commands in the same file (or same line for \\)
Documented regex in file

Added support for psql meta commands

---

src/sqlfluff/core/default_config.cfg
test/core/templaters/jinja_test.py
test/fixtures/templater/jinja_c_dbt/var_default.sql
test/fixtures/templater/jinja_c_dbt/var_default.yml

Add the default parameter for the stub for the dbt `var` macro.
https://docs.getdbt.com/reference/dbt-jinja-functions/var#variable-default-values
Not that I'm aware
- Other.

Add default parameter to dbt "var" macro stub

---

CHANGELOG.md
src/sqlfluff/rules/L036.py
test/fixtures/rules/std_rule_cases/L036.yml

Noticed I wasn't getting 100% pytest coverage, which looks to be due to #1427. Weird though as Coverage didn't flag this this.
Anyway, addressing that flagged another (admittedly obscure!) edge case - comments BEFORE columns (I mean - who does that!?!?). So added the test case and the support for that.
Note I also fixed some typos in the CHANGELOG.
Nope. Pretty obscure edge case, and added a test case for it. …

Further fix for L036

---

src/sqlfluff/core/templaters/base.py
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/after.sql
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/before.sql
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/test-config.yml
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if2/after.sql
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if2/before.sql
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if2/test-config.yml

Fix runtime error (IndexError ) when linting file with jinja "if"

---

src/sqlfluff/rules/L016.py
test/fixtures/rules/std_rule_cases/L016.yml

Fixes #1439 
We don't see to have access to `place_holder` content in rules so can't fix this. So for now it just fails the rule if too long without an auto fix.
Nope
- Other.

Stop exception in L016 for long Jinja comments

---

src/sqlfluff/dialects/dialect_teradata.py
test/fixtures/parser/teradata/select_stmt_normalize.sql
test/fixtures/parser/teradata/select_stmt_normalize.yml

Fixes #1185
Nope. Standard enough dialect enhancement.
- Other.

Add NORMALIZE to Teradata dialect

---

src/sqlfluff/core/parser/grammar/greedy.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/dialects/dialect_exasol.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_teradata.py
src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/rules/L036.py
src/sqlfluff/rules/L039.py
test/cli/formatters_test.py
test/core/parser/grammar_test.py
test/fixtures/linter/autofix/bigquery/004_templating/after.sql
test/fixtures/linter/autofix/bigquery/004_templating/before.sql

Trivial fix to spelling of "preceeding" to "preceding".

fix spelling of "preceding"

---

src/sqlfluff/dialects/exasol_keywords.py
test/fixtures/parser/exasol/AlterTableDistributePartition.yml
test/fixtures/parser/exasol/CreateTableStatement.yml
test/fixtures/parser/exasol/SelectStatement.sql
test/fixtures/parser/exasol/SelectStatement.yml

Fixes #1460
This moves `PARTITION` from being a unreserved keyword to a reserved one. Technically this is not correct as it should be unreserved, but without this the `PARTITION BY` is being seen as an identifier and changing that would be a good bit more complicated so think this is the easiest short term solution with little enough downsides. The whole reserved/unreserved thing is not strictly defined in SQLFluff in other dialects and probably could do with a bit of a review to be honest.
- `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python …

Fix Windows Clause for Exasol

---

README.md
docs/source/jointhecommunity.rst
setup.py

Correct `SQLFLuff` (with a capital `L`) to `SQLFluff` in a few places.
None
- Other.

Correct typo in SQLFluff name

---

src/sqlfluff/dialects/dialect_exasol_fs.py
test/fixtures/parser/exasol_fs/CreateAdapterScriptStatement.yml

This fixes the adapter script type for dialect `exasol_fs` and removes a TODO which was resolved in #690.
...
no
- Other.

EXASOL_FS: Fix adapter script type

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/parser/__init__.py
src/sqlfluff/core/parser/parser.py
src/sqlfluff/core/parser/segments/__init__.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol_fs.py
test/core/parser/segments_base_test.py

This adds a new property `file_path` to the BaseSegment which is filled in the RootSegment e.g. FileSegment. This solves the request in  #1472.
This PR is made to discuss the implementation, maybe someone with more knowledge about the architecture has a suggestion to improve this. Tests will be added.
...
...
- Other.
- Created GitHub issues for …

Adding a new BaseFileSegment class for FileSegments to inherit from

---

src/sqlfluff/rules/L033.py
test/fixtures/rules/std_rule_cases/L033.yml

Fixes #1481 
Gave tests proper name and added uppercase/lowercase support while at it (based on case of `UNION` keyword already set.)
- Other.

Disable rule L033 for dialects that do not support it (e.g. Exasol, Postgres)

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/tsql_keywords.py
test/fixtures/parser/tsql/alter_table_switch.sql
test/fixtures/parser/tsql/alter_table_switch.yml
test/fixtures/parser/tsql/create_table_as_select.sql
test/fixtures/parser/tsql/create_table_as_select.yml
test/fixtures/parser/tsql/create_table_with_distribution.sql
test/fixtures/parser/tsql/create_table_with_distribution.yml
test/fixtures/parser/tsql/minimal_function_no_alter.sql
test/fixtures/parser/tsql/minimal_function_no_alter.yml

This is an alternate PR to #1442.  
Adding support for Azure Synapse Analytics within the TSQL dialect.
TSQL dialect changes:
+Unreserved keywords list
+ALTER TABLE SWITCH segment
+CTAS segment
+CREATE TABLE segment replacing ANSI standard
+table distribution and index clause
+table distribution clause
+table index clause
New TSQL unreserved keywords:
"COLUMNSTORE",
"DISTRIBUTION",     # Azure Synapse Analytics specific
"HASH",             # Azure Synapse Analytics specific
"REPLICATE",        # Azure Synapse Analytics specific
"ROUND_ROBIN",      # Azure Synapse Analytics specific
"SWITCH",
"TRUNCATE_TARGET",  # Azure Synapse Analytics specific
New TSQL test cases:
ALTER TABLE SWITCH
CTAS
CREATE TABLE with a distribution and index clause
CREATE FUNCTION with no ALTER

TSQL dialect - provide alternate ASA PR incorporating ASA into TSQL

---

src/sqlfluff/dialects/dialect_postgres.py
test/dialects/postgres_test.py
test/fixtures/parser/postgres/postgres_select.sql
test/fixtures/parser/postgres/postgres_select.yml

Prior to this change, it was possible to parse `AT TIME ZONE` declarations with the postgres dialect, but only when used with datetime literals.
This PR builds on https://github.com/sqlfluff/sqlfluff/pull/1378 to allow `AT TIME ZONE` to be used with column references in PostgreSQL.
Examples of statements that this allows us to parse:
```
SELECT c_column AT TIME ZONE 'UTC' FROM t_table;
SELECT c_column FROM t_table WHERE (c_column AT TIME ZONE 'UTC')::time < '05:00';
```
- `.sql`/`.yml` parser test cases in `test/fixtures/parser` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running …

Allow Postgres column references to use `AT TIME ZONE`

---

test/fixtures/rules/std_rule_cases/L022.yml
test/fixtures/rules/std_rule_cases/L023.yml
test/fixtures/rules/std_rule_cases/L024.yml
test/fixtures/rules/std_rule_cases/L025.yml
test/fixtures/rules/std_rule_cases/L026.yml
test/fixtures/rules/std_rule_cases/L028.yml
test/fixtures/rules/std_rule_cases/L029.yml
test/fixtures/rules/std_rule_cases/L030.yml
test/fixtures/rules/std_rule_cases/L031.yml
test/fixtures/rules/std_rule_cases/L032.yml
test/fixtures/rules/std_rule_cases/L034.yml
test/fixtures/rules/std_rule_cases/L040.yml
test/fixtures/rules/std_rule_cases/L041.yml
test/fixtures/rules/std_rule_cases/L043.yml
test/fixtures/rules/std_rule_cases/L044.yml
test/fixtures/rules/std_rule_cases/L045.yml
test/fixtures/rules/std_rule_cases/L046.yml

This pull request improves remaining test cases' names from issue #574 . It changes names for all test cases with name following pattern: `test_\d+` so the issue can be closed. There are still some test cases that were named like "simple_pass" but since they were not auto-generated I left almost all of those as they were considering them out of scope for this change. 
I added description to a few of the cases using `desc:` yaml key as was recommended in the issue.
Please let me know if the names or descriptions I chose need further changes 🙂
closes #574
I changed test case alias_single_char_identifiers in L031.yml since it seemed to be using wrong keys and was passing only due to second pass_str overwriting first one. Please verify if this is correct.
- Included test cases to demonstrate …

Improved test cases names

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_postgres.py
test/dialects/ansi_test.py
test/dialects/postgres_test.py
test/fixtures/parser/postgres/postgres_null_filters.sql
test/fixtures/parser/postgres/postgres_null_filters.yml

Start treating `ISNULL` and `NOTNULL` as keywords in an expression rather than aliases
Prior to this change, if we were parsing an expression that contained the `ISNULL` or `NOTNULL`, we would treat them as
aliases. Since they are listed as keywords for Postgres and ANSI, this would cause some files to become unparsable (particularly if they were used in statements with actual aliases).
We fix this by introducing grammars for `ISNULL` and `NOTNULL`, and allowing them to be items in an expression. Since the `ISNULL` and `NOTNULL` keywords are non-standard (but are commonly supported), we remove them for the mysql, snowflake and exasol dialects which do not support them (based on the comment [here](https://github.com/sqlfluff/sqlfluff/issues/426#issuecomment-683465473)).
Technically we …

Fix handling of `ISNULL` and `NOTNULL` keywords

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/parser/snowflake/snowflake_pivot.sql
test/fixtures/parser/snowflake/snowflake_pivot.yml

Fix parsing of UNPIVOT by adding it to the list of reserved keywords.
Fixes #1474.
No.
- Other.

Snowflake - fix parsing of UNPIVOT

---

src/sqlfluff/core/linter/runner.py
src/sqlfluff/core/templaters/base.py
src/sqlfluff/core/templaters/dbt.py
test/core/templaters/dbt_test.py
test/fixtures/dbt/dbt_project/models/depends_on_ephemeral/b.sql
test/fixtures/dbt/dbt_project/models/depends_on_ephemeral/c.sql

Fixes #857
Adds a new public method to the templater interface to let the templater determine the order for linting files. With dbt, this is used to process dependent models (ephemeral models in particular!) before the models that use them.
* Extends the public interface for templaters (`RawTemplater` and its descendants)
* Changes two more properties of `DbtTemplater` to use `@cached_property` (`profiles_dir` and `project_dir`)
- Full autofix test cases …

Issue 857: Fix bug that can prevent linting ephemeral models

---

src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/parser/exasol/RecompressStatement.yml

This fixes just a very small typo in the `REORGANIZE` statement.
...
...
- Other.

Exasol: Fix typo in `REORGANIZE` statement

---

src/sqlfluff/core/templaters/dbt.py
test/core/templaters/dbt_test.py
test/fixtures/dbt/dbt_project/models/depends_on_ephemeral/a.sql
test/fixtures/dbt/dbt_project/models/depends_on_ephemeral/d.sql

Fixes #1510
Fixes a bug where the dbt templater was only fixing or linting the first file (and its dependents).
This PR also makes some changes to how `sequence_files()` processes directory names, to try and make file paths more canonical and avoid accidentally processing the same file twice.
- Other. …

SQLFluff can't find dbt models

---

src/sqlfluff/rules/L012.py

L012's description was missing the alias in the anti-pattern.  There's no implicit aliasing if there's no alias!

Fix L012 documentation

---

plugins/sqlfluff-templater-dbt/setup.py
tox.ini

sqlfluff-templater-dbt dependency on dbt ends up pulling
dbt-postgres, dbt-redshift, dbt-snowflake and dbt-bigquery
which are all pretty large. This commit changes the dependency
to dbt-core instead.
Fixes #1769
If a user installs sqlfluff in a different environment than dbt (for eg. using pipx or venv),
he/she would have to install additional dbt database dependencies (eg. dbt-bigquery)
... …

templater-dbt: Change dbt dependency to dbt-core

---

src/sqlfluff/cli/commands.py

Writing to file using `sqlfluff lint` caused an encoding error due to the completion message containing these Unicode characters ' 📜 🎉'. This PR disables those characters when sys.stdout isn't printed to terminal.
No
No test cases added - fix is trivial. Tested in my use case

Fixed encoding error when linting to file

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/create_table_with.sql
test/fixtures/dialects/hive/create_table_with.yml

_Firstly, thanks for adding this feature! Secondly, please check the key steps against the checklist below to make your contribution easy to merge._
_Please give the Pull Request a meaningful title (including the dialect this PR is for if it is dialect specific), as this will automatically be added to the release notes, and then the Change Log._
_If there is an open issue for this, then please include `fixes #XXXX` or `closes #XXXX` replacing `XXXX` with the issue number and it will automatically close the issue when the pull request is merged. Alternatively if not fully closed you can say `makes progress on #XXXX` to create a link on that issue without closing it._
Fixes #1772
Makes it possible to parse CREATE TABLE statements with WITH clauses.
...
...
No
- Included test cases to …

Hive: Fix bug in CREATE TABLE WITH syntax

---

src/sqlfluff/rules/L049.py
test/fixtures/rules/std_rule_cases/L049.yml

Fix L049 to allow `= NULL` in SET clauses

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L014.py
src/sqlfluff/rules/L029.py
test/fixtures/rules/std_rule_cases/L029.yml

Fixes #1747
This PR adjusts L029 to optionally check quoted identifiers in addition to naked identifiers.
In order to do this, we are adding a new configuration keyword, quoted_identifiers_policy, which represents the same thing as unquoted_identifiers_policy but for quoted identifiers.
The options for quoted_identifiers_policy are the same as unquoted_identifiers_policy with the addition of none, representing no checks for quoted identifiers.
We check quoted identifiers by stripping off the first and last character.  If we have a case where this shortcut would fail, we'll need to tweak the code before merging.
Changes:
+quoted_identifiers_policy default of none to default_config.cfg
+quoted_identifiers_policy description in config_info.py
L014.py: Rename unquoted_ids_policy_applicable …

L029: Check quoted identifiers in addition to naked identifiers

---

src/sqlfluff/rules/L016.py
test/fixtures/rules/std_rule_cases/L016.yml

Fix internal error in L016 when template/whitespace-only line too long

---

src/sqlfluff/rules/L027.py
src/sqlfluff/rules/L028.py
test/fixtures/rules/std_rule_cases/L028.yml

Fixes #1710
Sets Snowflake and Redshift as only two dialects that allow this
- Other.

L028 fix - Allow SELECT column alias in WHERE clauses for certain dialects

---

src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/dialects/exasol/ExecuteScript.yml
test/fixtures/dialects/exasol/OpenCloseSchema.yml
test/fixtures/dialects/exasol/PreloadStatement.yml
test/fixtures/dialects/exasol/RecompressStatement.yml
test/fixtures/dialects/exasol/SelectStatement.yml

This makes the reference in some statements more strict.
It turns some `ObjectReferenceSegment`s into `SchemaReferenceSegment`s, `ScriptReferenceSegment` or `TableReferenceSegment`s in some statements.
This could lead in some broken implementation if one uses the statement types already.
- Other. …

Exasol: Make references more strict

---

docs/requirements.txt
requirements.txt
setup.py

At v0.8.0, running `pip install sqlfluff` and then invoking `sqlfluff --help` (or any other command) results in the following error: `ModuleNotFoundError: No module named 'tqdm'`.
This PR adds `tqdm` to the installation requirements in  `setup.py` to fix the bug.

Fix: add tqdm to setup.py installation requirements

---

.github/workflows/ci-tests.yml

Fixes the recent issue with 0.8.0 whereby a new dependency was added but not added to setup.py so `pip install sqlfluff` failed.
This adds a test to our CI which does the following:
- `pip install git+https://github.com/@pull_request_author/sqlfluff@branch`
- `sqlfluff --version`
That is, it doesn't set up the full dev environment and instead mimics what users would see with a `pip install` to ensure that works, even if requirements.txt and requirements_dev.txt are not installed.
Proved this failed here when this branch was based on the broken v0.8.0: https://github.com/sqlfluff/sqlfluff/pull/1843/commits/5d3a11a2ce4fb60ae0a68b1c4c7504e923ca5c48
And that it passed when #1843 change was included: https://github.com/sqlfluff/sqlfluff/pull/1843/commits/0d9a2bc1165e26fa7619b5e4bab7d3b7c9ba15f2 …

Add test to ensure pip install works

---

src/sqlfluff/api/simple.py
src/sqlfluff/core/config.py
src/sqlfluff/core/linter/linter.py
test/api/simple_test.py

Adds the ability to have `exclude_rules` parameters for the simple API as discussed here: https://github.com/sqlfluff/sqlfluff/pull/1840#discussion_r744994114
Shouldn't be.
- Other.

Add `exclude_rules` option for the Simple API

---

tox.ini

Very simple PR. We are currently installing the sqlfluff package into our `linting`,`doclinting`, and `mypy` tox environments. These are all static analysis tools and hence don't need the package installed to run. 
We therefore add `skip_install=True` to these sections.
Approach is used in many other projects (e.g. flake8 https://github.com/PyCQA/flake8/blob/main/tox.ini)
No as mentioned above these tox environments aren't actually touching the package.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python test/generate_parse_fixture_yml.py` or by running `tox` …

Add `skip_install` to static analysis sections of tox.ini

---

src/sqlfluff/dialects/dialect_snowflake.py

Very simple PR. The Snowflake warehouse sizes in sqlfluff were wrong. I've updated them to the correct options (see https://docs.snowflake.com/en/sql-reference/sql/alter-warehouse.html).
No
- Other.

Correct Snowflake warehouse sizes

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/postgres/postgres_insert.sql
test/fixtures/dialects/postgres/postgres_insert.yml

Bugfix PR for bare functions not being accepted in a VALUES clause
Fixes #1875 
No
Test case added in Postgres - to match bug report

Added bare functions to values clause

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_create_table.sql
test/fixtures/dialects/snowflake/snowflake_create_table.yml

Naked `AUTOINCREMENT` (i.e. without modifiers) is allowed in Snowflake ([official documentation](https://docs.snowflake.com/en/sql-reference/sql/create-table.html#syntax)):
```
[ { DEFAULT <expr>
| { AUTOINCREMENT | IDENTITY } [ ( <start_num> , <step_num> ) | START <num> INCREMENT <num> ] } ]
```
To repro the issue, populate `test.sql`:
```sql
CREATE TABLE test (id INTEGER PRIMARY KEY AUTOINCREMENT);
```
Before:
```
$ sqlfluff lint test.sql --dialect snowflake
== [test.sql] FAIL
L:   1 | P:  18 |  PRS | Line 1, Position 18: Found unparsable section: ' (id
| INTEGER PRIMARY KEY AUTOINCREMENT)'
All Finished 📜 🎉!
```
After:
```
$ sqlfluff lint test.sql --dialect snowflake
All Finished 📜 🎉!
```
Workflows explicitly forbidding naked `AUTOINCREMENT`s will silently stop failing.
- Included test …

[Snowflake] Allow naked AUTOINCREMENT

---

src/sqlfluff/core/parser/grammar/delimited.py
src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/create_view.sql
test/fixtures/dialects/tsql/create_view.yml

This PR does two largely unrelated things. Firstly, it adds options to the tsql CREATE VIEW syntax.
Secondly, it fixes a bug in the Delimited(), which causes rogue behaviour when there is another Delimited within the same statement block.
Fixes #1892 
Fixes #1366
No. Though there are probably some code clean-ups wee can do where people have avoided using Delimited() because of errors they couldn't explain
Tests added for the TSQL stuff - which served as useful test cases for the Delimited() stuff. I haven't made any explicit unit tests for the delimited change

Fixed Delimited() logic, added TSQL grammar

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/ansi/insert_with_statement.sql
test/fixtures/dialects/ansi/insert_with_statement.yml
test/fixtures/dialects/ansi/with_insert_statement_a.sql
test/fixtures/dialects/ansi/with_insert_statement_a.yml
test/fixtures/dialects/ansi/with_insert_statement_b.sql
test/fixtures/dialects/ansi/with_insert_statement_b.yml
test/fixtures/dialects/ansi/with_insert_with_statement.sql
test/fixtures/dialects/ansi/with_insert_with_statement.yml
test/fixtures/dialects/ansi/with_update_statement.sql
test/fixtures/dialects/ansi/with_update_statement.yml

PR fixes #1888. This PR adds the ability to parse INSERT/UPDATE within a WITH clause as described in the linked issue.
I have this working for the cases described in the linked issue, however, I am struggling to get the following valid query to parse:
```SQL
WITH mycte AS (
SELECT
foo,
bar,
baz
FROM mytable1
)
INSERT INTO table2 (column1, column2, column3)
SELECT foo, bar, baz
FROM mycte;
```
I believe the dialect changes I made were sensible and should cover the above case, but still the parsing error, so any help/advice would be greatly appreciated! Thanks 😄 
No, but need help resolving one case of not parsing before we can merge. …

Parse UPDATE/INSERT within WITH clause

---

src/sqlfluff/rules/L041.py
test/fixtures/linter/autofix/ansi/023_l016_confuses_l041/after.sql
test/fixtures/linter/autofix/ansi/023_l016_confuses_l041/before.sql
test/fixtures/linter/autofix/ansi/023_l016_confuses_l041/test-config.yml

Fix bug where L041 was confused by L016's placement of newlines in the parse tree

---

docs/source/configuration.rst
src/sqlfluff/core/templaters/placeholder.py

A small improvement after #1871 
I used the python templater as an example, but in this case the "context" subsection is not needed. So I removed it from the templater and the relative docs to make it simpler.

Remove unnecessary context section, from code and the docs

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/select.sql
test/fixtures/dialects/tsql/select.yml

Updating TSQL to allow a PARTITION BY clause to include multiple columns.  Also updated a test case to include the scenario.

Tsql partition by multiple columns

---

plugins/sqlfluff-templater-dbt/setup.py
plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/snapshots/issue_1771.sql
plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/snapshots/issue_1771.sql.after
plugins/sqlfluff-templater-dbt/test/templater_test.py

Fixes #1771 
During templater processing, registers two Jinja extensions on the environment that we "intercept" from dbt, one for the `snapshot` tag and one for the `endsnapshot` tag
- Other.

Fix bug where "sqlfluff fix" deletes dbt "{% snapshot %}" line

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/ansi/drop_type.sql
test/fixtures/dialects/ansi/drop_type.yml

This PR adds the DROP TYPE statement to the ANSI dialect. Fixes #1911.
No
- Other.

Add DROP TYPE statement to ANSI dialect

---

docs/source/indentation.rst

Looks like "Fishtown Analytics" rebranded to "dbt labs" and the linked style guide has moved. The old URL was just a placeholder asking people to visit the new URL.
No
- Other.

Docs: fix broken link to external SQL style guide

---

.github/workflows/ci-tests.yml
setup.py

Fixes #1925. chardet was missing from setup.py. 
The reason we likely missed this in unit tests was because in tox.ini we install requirements.txt (which had chardet), followed by a developer install of sqlfluff, rather than installing the package and its requirements via just setup.py. This is something I've already resolved in #1860 so just need that merged in to prevent this in the future.
No, fixes missing requirement …

Add missing chardet install in setup.py

---

src/sqlfluff/rules/L055.py
test/fixtures/rules/std_rule_cases/L055.yml

This PR provides a new rule to raise a linting error when a RIGHT JOIN is detected and suggests that the user refactors to use a LEFT JOIN instead. Fixes #1749.
This is a very common style guide rule, for example in the popular fishtown analytics SQL guide:
Logic is very simple for this rule and I've included a bunch of unit tests.
No
- Other. …

New Rule L055: Use LEFT JOIN instead of RIGHT JOIN.

---

src/sqlfluff/rules/L053.py
test/fixtures/rules/std_rule_cases/L053.yml

Fixes #1899. This PR adds a rule to remove outer brackets on top-level SQL queries. Refer to corresponding issue for discussion.
No. Small tweak to L050 to fix issue but has no downstream impact.
- Other.

New Rule L053: Remove outer brackets from top-level statements.

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/join_types.sql
test/fixtures/dialects/spark3/join_types.yml

This PR aims to add `[LEFT] ANTI` and `[LEFT] SEMI` joins to the Spark3 dialect. Fixes #1933.
No
- Other.

Spark3 join types

---

src/sqlfluff/rules/L031.py

In the Rules Reference documentation section for L031 sphinx has been inserting the `TableAliasInfo` class:
This is clearly unintentional and seemed to be caused by the `TableAliasInfo` being defined as a sub-class of `Rule_L031`. I separated the classes in a manner consistent with other similar cases in L036 and L037 and this has resolved the issue in the documentation:
No, doc bugfix
- …

Documentation bug: Fix misplaced TableAliasInfo in L031 documentation

---

src/sqlfluff/cli/commands.py

This PR adds a short form `-h` option as an alternative to `--help` on the command line. I like to regularly check the help info on the command line and it's a big convenience to be able to just type `-h`.
Before and after below:
No, this has no impact on existing use of `--help`. Just provides a handy alternative for those that prefer `-h`.
- Other. …

Add short form help option (-h)

---

requirements.txt
requirements_dev.txt
setup.py

This addresses an issue discovered as part of developing the SQLFluff docker image. `typing_extensions` should be in `requirements.txt` not `requirements_dev.txt`. Makes sense to address this in its own PR rather than the docker image one.
Also added the comments on dependencies from `setup.py`
No
- Other. …

Move typing_extensions from requirements_dev.txt to requirements.txt

---

MANIFEST.in
requirements.txt
setup.cfg
setup.py

This PR is a straight swap from `setup.py` to declarative metadata  in `setup.cfg`. Simplifies the setup file and makes it easier for tools to extract the package metadata (e.g. extracting requirements for use in the docker build #1945).
No, exactly the same but uses declarative metadata.
- Other. …

Move package metadata to setup.cfg

---

CONTRIBUTING.md
docs/source/conf.py
mypy.ini
requirements.txt
setup.cfg
setup.py
src/sqlfluff/__init__.py
src/sqlfluff/config.ini
test/cli/commands_test.py

This is a follow up PR to #1960 in which I discuss moving the package version from the custom `config.ini` setup to a more standard approach in `setup.cfg`. 
I have updated all `config.ini` references to now refer to the version attribute in `setup.cfg`.
I have also included updates to CONTRIBUTING.md with updated release instructions.
The `stable_version` used in doc builds has been moved to a `[sqlfluff_docs]` section in `setup.cfg`.
I have tested building both packages, ran unit tests and test built the docs and all looks good.
No.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto …

Remove config.ini in favor of setup.cfg

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/postgres/postgres_position.sql
test/fixtures/dialects/postgres/postgres_position.yml

Fixes #1969 
Expand `IN` grammar to allow column references
Nope
- Other.

Allow column references in IN statement

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/select_column_object_with_keyword.sql
test/fixtures/dialects/bigquery/select_column_object_with_keyword.yml

Fixes #1981 
This is valid BigQuery even though `current` is a keyword:
```sql
-- current is a reserved word but keywords are allowed as part of a nested object name
SELECT
table1.current.column,
table1.object.current.column,
table1.object.nested.current.column,
FROM
table1
```
Docs: https://cloud.google.com/bigquery/docs/reference/standard-sql/lexical
> A reserved keyword must be a quoted identifier if it is a standalone keyword or the first component of a path expression. It may be unquoted as the second or later component of a path expression.
Only handles Column References. There would be more places where this should be implemented but think this is the main one.
- `.yml` rule test cases …

BigQuery: Allow keywords in column reference components

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/config.py
src/sqlfluff/core/linter/linter.py
test/cli/commands_test.py
test/fixtures/cli/extra_config_tsql.sql
test/fixtures/cli/extra_configs/.sqlfluff

Fixes #1244.
This PR adds a command line argument `--config` to the CLI `lint`, `fix`, and `parse` commands. 
The user can specify an additional config file such that the override logic is (later files override earlier ones):
- `default_config.cfg` (package default)
- `<user_appdir_configs>`
- `<user_homedir_configs>`
- `<user_homedir_configs>`
- `<configs_between_cwd_and_sql_path>`
- `<extra_config_file>` (this PR)
- Any command line arguments
This behaviour was voted on in the Slack channel: https://sqlfluff.slack.com/archives/C01GPHR8J0G/p1637859667129900
If no config files are included in the default config search paths then this argument can be used to specify a single off-path config file which will also be useful for several applications.
(Will investigate in a future PR adding …

Add config CLI argument to lint, fix, and parse

---

src/sqlfluff/rules/L054.py
test/fixtures/rules/std_rule_cases/L054.yml
test/rules/std_L054_test.py

Follow on from #1981 and #1987
Don't try to pop an empty column set in L054 to avoid weird error messages. Shouldn't really happen if there are no parsing errors and no `--noqa` (so took me a while to reproduce a test case!) but good check to have I think.
@jpy-git can you review too please since you added this rule?
Don't think so
- Other.
- …

Adds extra check to L054 to avoid weird error messages

---

src/sqlfluff/core/linter/linter.py
test/core/linter_test.py

Fixes #1977. Inline ignores weren't being processed on comment lines leading to issues like seen in the issue and the screenshot below. The fix is very simple.
No
- Other.

Fix issue with inline ignores not respecting comment lines

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_warehouse.yml

Makes the Snowflake dialect a bit more DRY, by replacing repetitive code for object tagging with the tag segments introduced in #1950. In doing so, a few bugs are fixed as well:
- Tags need to go last in a `create warehouse statement`.
- Tags cannot be combined with other options in an `alter warehouse unset` statement, [same as for schemas](https://github.com/sqlfluff/sqlfluff/pull/1950#discussion_r757818390).
- The tag sequence in `CreateExternalTableSegment` was missing `Bracketed`.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python …

Make Snowflake tags DRY

---

.github/workflows/ci-tests.yml
tox.ini

This should hopefully resolve the issues in #1957 with pytest_xdist causing unit test failures in dbt tests. moves `-n 2` option to standard unit tests only.
No
- Other.

Use posargs to enable pytest_xdist for standard unit tests only

---

src/sqlfluff/rules/L052.py
test/fixtures/rules/std_rule_cases/L052.yml

Fix #2014 . This PR addresses the linked issue as well as better defining the interaction of L052 with inline comments.
Unit tests show all the various permutations of L052 comment interactions.
No
- Other.

Fix inline comment interactions with L052

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_datetime_units.sql
test/fixtures/dialects/postgres/postgres_datetime_units.yml

This PR partially addresses #1886 (just the postgres datetime units). The postgres dialect was missing datetime units which was causing them to be interpreted as column references and triggering linting rules. I have implemented the complete list of additional units from https://www.postgresqltutorial.com/postgresql-extract/
Snowflake datetime units to follow in separate PR.
- Other.
- Added …

Grammar: Add complete datetime units to postgres dialect

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_drop_policy.sql
test/fixtures/dialects/postgres/postgres_drop_policy.yml

Fixes #2015. Adds DROP POLICY statement to the postgres dialect. (CREATE POLICY was added in #2021)
No
- Other.

Grammar: Add DROP POLICY statement to postgres dialect

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/delete_azure_synapse_analytics.sql
test/fixtures/dialects/tsql/delete_azure_synapse_analytics.yml

TSQL (Azure Synapse Analytics) allows for a table to be specified as part of a DELETE clause in order to support JOINs within a DELETE statement's WHERE clause.
+TableReferenceSegment ref at the right place in TSQL's DeleteStatementSegment
+Test case

TSQL (ASA): Allow for table identifier in DELETE clause

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_json_operators.sql
test/fixtures/dialects/postgres/postgres_json_operators.yml

Fixes #2033. The ansi dialect contains hash inline comments, however, these are not available in postgres. This was causing valid Postgres dialect (the #>> and #> JSON operators) to not parse. I have also added unit tests for the parsing of these JSON operators as there wasn't any previously. 
No
- Other. …

Grammar: Remove hash inline comment from Postgres

---

src/sqlfluff/rules/L043.py
test/fixtures/rules/std_rule_cases/L043.yml

Fixes #2047.  L043 was throwing an error when trying to incorrectly apply the fix for the IS NULL reduction case. This should only be applied when a column is compared to NULL in the condition expression, however, it was attempting to apply to functions. I have added the step to filter out the non-column null comparisons.
No, bugfix
- Other.
- …

Fix L043 issue when trying to autofix functions

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/insert_statement.sql
test/fixtures/dialects/tsql/insert_statement.yml

Fixes #2045
The ANSI InsertStatementSegment definition uses StartsWith(), which is generally incompatible with the way that we handle TSQL's optional delimitation.  This PR overrides with a TSQL-specific implementation of InsertStatementSegment not using StartsWith(). 
Added a test case proving that this fixes 2045.
Also fixed a trivial typo in ANSI documentation.

TSQL: INSERT INTO

---

src/sqlfluff/dialects/dialect_exasol.py
src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/exasol/SelectStatement.yml
test/fixtures/dialects/snowflake/snowflake_select_grouping_sets.yml
test/fixtures/dialects/snowflake/snowflake_within_group.yml
test/fixtures/rules/std_rule_cases/L054.yml

Fixes GROUP BY grammar type for snowflake and Exasol to be consistent with other dialects and to allow L054 to work on these grammars
The clause does change from type `group_by_clause` to `groupby_clause` so if anyone depends on that using API then they will need to update. But it's more consistent so we should make this change IMHO.
- Other. …

Bug fix of L054 for Snowflake and Exasol

---

src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/dialects/exasol/CreateUDFScriptDotSyntax.sql
test/fixtures/dialects/exasol/CreateUDFScriptDotSyntax.yml

This fixes the syntax for Exasol udf scripts and allows (...) parameter syntax.
- Other.

Exasol: Fix UDF script syntax

---

.gitignore
plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/packages.yml
plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/packages.yml.jinja2
plugins/sqlfluff-templater-dbt/test/generate_packages_yml.py
tox.ini

Makes progress on #2048:
* Converts `packages.yml` to a Jinja template which chooses the `dbt_utils` version based on the version of dbt installed. I considered whether this may be "overengineering", but the existence of this dbt_utils compatibility matrix convinced me this is a reasonable thing to do (a bit of futureproofing).
* Changes how we determine if a dbt model is disabled.
Without these changes, almost all the dbt templater tests are failing in the "parent" PR:
```
=================== 24 failed, 3 passed, 1 skipped in 14.45s ===================
```
With these changes, only two tests are failing:
```
============= 2 failed, 25 passed, 1 skipped, 2 warnings in 20.36s =============
``` …

Choose dbt_utils version based on the dbt version, change how we check if a model is disabled

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_alter_table.sql
test/fixtures/dialects/postgres/postgres_alter_table.yml

Follow up from #2096 
The [ALTER TABLE](https://github.com/sqlfluff/sqlfluff/blob/7aecf672872d05b608d614dc1f2b040e17a4f902/src/sqlfluff/dialects/dialect_postgres.py#L1275) parser did not account for all value types when setting a column's default value.
None
- Other. …

Allow for more value types in ALTER TABLE ALTER COLUMN SET DEFAULT statement

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/ansi/naked_identifiers.sql
test/fixtures/dialects/ansi/naked_identifiers.yml

The current numeric literal regex is matching the start of valid naked identifier segments and causing them to be split which results in parsing errors (Initially highlighted [here](https://github.com/sqlfluff/sqlfluff/pull/2111#discussion_r768046391)):
This PR adds a negative lookahead assertion to the numeric literal regex to check that we aren't at the start of naked identifier:
N.B. Since the negative lookahead comes after the exponential matching we don't need to worry about this impacting the parsing of those (evidenced by continued parsing of `select_numeric_literal_exponential_format.sql` unit test) 😄 
No
- …

Stop numeric literal from splitting valid naked identifiers.

---

.pre-commit-config.yaml
src/sqlfluff/rules/L003.py

With the new 0.920 release of mypy today it is flagging a new type issue in L003.
The issue is actually a valid one to raise: A tuple of BaseSegment is being appended to a tuple of RawSegment to create a complete raw stack similar to the complete stack I use in L050 or L009, however due to the naming convention I used those rules I could easily type the complete stack. In this case since it appends to the already defined raw stack you can't define the type at that assignment.
A full fix would require some variable renaming and slight rework of L003 so given that this issue is blocking all unrelated PRs I've just inline ignored it.
N.B. If using an earlier version of mypy this issue is not raised, but it will now raise for unused type ignore. Please update your mypy to avoid this: `tox -e …

Fix mypy type raise in L003

---

src/sqlfluff/core/parser/helpers.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
test/core/parser/parse_test.py
test/dialects/ansi_test.py
test/fixtures/dialects/ansi/semicolon_delimiters.sql
test/fixtures/dialects/ansi/semicolon_delimiters.yml
test/fixtures/dialects/tsql/go_delimiters.sql
test/fixtures/dialects/tsql/go_delimiters.yml

Fixes #2009. Consecutive GO segments separating batch segments were not parsing and likewise for consecutive semicolon segments separating statement segments. These are both valid syntactically, consecutive delimiters in this case are just separating empty statemtents:
This is fixed by setting the delimiter to one or more of itself. It gives the correct parse tree and works in the tests.
Removed an old test that was checking that consecutive semicolons raise a parse error, as they shouldn't raise a parse error.
No
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `python …

Add ability to parse multiple GO/semicolon delimiters

---

src/sqlfluff/core/linter/linter.py
test/core/linter_test.py

Fixes #797. After investigation (described in the issue) it seems most appropriate to not handle multiple newlines and instead add step to ensure all newline inputs to sqlfluff are normalised to unix-style line endings for consistency. Users wanting newline conversion should consider the easy to use [mixed-line-ending](https://github.com/pre-commit/pre-commit-hooks/blob/master/pre_commit_hooks/mixed_line_ending.py) pre-commit hook or the `dos2unix` command. 
Currently we load from files using universal newlines, but we don't do this for test input. Therefore I have added a conversion function to the linter to ensure consistency regardless of how the SQL is supplied.
No
- `.yml` rule test …

Normalise input newlines

---

src/sqlfluff/core/rules/base.py

Fixes #2137. Need to set `self.edit` attribute to None if no edit_segments supplied (i.e. for deletes).
Missed from original PR as this only comes up when two delete fixes are applied to the same segment.
No
- Other.

Hotfix for LintFix comparisons

---

.github/workflows/ci-tests.yml
docs/source/gettingstarted.rst
plugins/sqlfluff-templater-dbt/setup.cfg
requirements.txt
setup.cfg

Removes support for Python 3.6.
- Other.

Remove support for Python 3.6 (it's "end of life" December 23, 2021)

---

src/sqlfluff/__init__.py
src/sqlfluff/core/dialects/__init__.py
src/sqlfluff/core/linter/runner.py
tox.ini

Python3.6 support was recently removed in #2141, however, I can still see several references to python 3.6. Seeing if removing these is fine.
No
- Other.

Fully remove python3.6 references

---

src/sqlfluff/rules/L022.py
test/fixtures/rules/std_rule_cases/L022.yml

Fixes #2136. L022 currently uses closing bracket to find the end of a CTE. This is fine for most cases but unintentionally flags CTE column definitions as described in the linked issue. Fix is simple: Check that the preceding keyword to the bracketed segment is AS 👌
No
- Other. …

Fix L022 to not flag CTE column definitions

---

docs/source/configuration.rst
plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/.sqlfluffignore

The default name for the packages folder is `dbt_packages` since dbt v1.0.0 (see https://github.com/dbt-labs/dbt-core/issues/3523)
- Other.

docs: set `dbt_modules` to `dbt_packages`

---

.github/PULL_REQUEST_TEMPLATE.md

Very simple, spotted that the PR template doesn't tell people to use the generate-fixture-yml command via tox. Updating for consistency with the rest of the docs.
No
- Other.

Update PR template to reference tox generate-fixture-yml command

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/add_index.yml
test/fixtures/dialects/tsql/create_table_with_sequence_bracketed.yml
test/fixtures/dialects/tsql/declare_with_following_statements.yml
test/fixtures/dialects/tsql/if_else.yml
test/fixtures/dialects/tsql/if_else_begin_end.yml
test/fixtures/rules/std_rule_cases/L003.yml

L003 currently lints TSQL ELSE IF statements with successive indentation:
```
IF (1 > 1)
PRINT 'A';
ELSE IF (2 > 2)
PRINT 'B';
ELSE IF (3 > 3)
PRINT 'C';
ELSE IF (4 > 4)
PRINT 'D';
ELSE IF (5 > 5)
PRINT 'E';
ELSE
PRINT 'Z';
```
This fix will adjust the indentation:
```
IF (1 > 1)
PRINT 'A';
ELSE IF (2 > 2)
PRINT 'B';
ELSE IF (3 > 3)
PRINT 'C';
ELSE IF (4 > 4)
PRINT 'D';
ELSE IF (5 > 5)
PRINT 'E';
ELSE
PRINT 'Z';
```
Dialect Changes:
-Added an ELSE IF section to IfExpressionSegment
-Created an IfClauseSegment to reduce repetition in the definition
Test Case Changes:
-Added L003 test to confirm new indentation
-Parse test cases including IF have changed slightly to represent new IfClauseSegment

TSQL: Proper Indentation of ELSE IF

---

test/fixtures/rules/std_rule_cases/L003.yml
test/fixtures/rules/std_rule_cases/L014.yml
test/fixtures/rules/std_rule_cases/L043.yml

Two of the L003 linter tests have duplicate names.  I've adjusted one to properly match the test case.
Two of the L014 linter tests have duplicate names.  I've adjusted one to properly match the test case.
Two of the L043 linter tests are exactly the same.  I've removed one.

Linter Test Name Duplication

---

src/sqlfluff/rules/L026.py
src/sqlfluff/rules/L028.py
test/fixtures/rules/std_rule_cases/L026.yml
test/fixtures/rules/std_rule_cases/L028.yml

There is a `struct` complex datatype in `hive` and `redshift` dialects
You can easily access values using following syntax
```sql
select col.field1, col2
from db.tbl
```
There are `L026` violations raised while linting
This PR allows such syntax for hive+redshift same as for bigquery 
- Other.

Add struct support for `hive` and `redshift` (L026, L028)

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_alter_group.sql
test/fixtures/dialects/redshift/redshift_alter_group.yml

This is a fix for issue #2186. `NakedIdentifierStatement` will be changed to `ObjectReferenceSegment` to accommodate quoting.
No
- Other.

ALTER GROUP fix to accommodate quoted objects

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
test/core/parser/lexer_test.py
test/fixtures/dialects/ansi/non_breaking_space.sql
test/fixtures/dialects/ansi/non_breaking_space.yml

The lexer can't lex non-breaking spaces.  This PR will add non-breaking spaces to the whitespace lexer.

Lexer: add non-breaking spaces to whitespace

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/alter_table.sql
test/fixtures/dialects/tsql/alter_table.yml

This PR adds ALTER TABLE ... ALTER COLUMN functionality to the TSQL dialect.

TSQL: Add support for ALTER TABLE ALTER COLUMN

---

src/sqlfluff/rules/L058.py

Simple rewording of the lint message for new rule L058, as suggested [here](https://github.com/sqlfluff/sqlfluff/pull/2223#issuecomment-1004173471) by @jpy-git.
- Other.

Reword lint message for L058 per review

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/functions_a.sql
test/fixtures/dialects/tsql/functions_a.yml

Fixes #1909
This PR adds support for table-valued functions to the TSQL dialect.  TSQL defines TVFs by replacing the standard RETURNS [datatype] with RETURNS TABLE.  This PR adds TABLE as an option in the RETURNS clause.
No

TSQL: Table valued functions

---

src/sqlfluff/core/rules/base.py
src/sqlfluff/rules/L031.py
src/sqlfluff/rules/L043.py
src/sqlfluff/rules/L045.py
src/sqlfluff/rules/L058.py
src/sqlfluff/testing/rules.py
test/fixtures/rules/std_rule_cases/L031.yml
test/fixtures/rules/std_rule_cases/L043.yml
test/fixtures/rules/std_rule_cases/L058.yml

Fixes #2051 
This PR builds on yesterday's PR #2220:
* Yesterday's PR discards all fixes from a `LintResult` if any of the fixes **modify** templated code.
* This PR discards all fixes from a `LintResult` if any of the fixes **read from** templated code. This required a slight change to any rules which do this. (Fortunately, there are only a handful of such rules.)
- Other.
- Created …

Don't allow fixes to COPY code from templated regions

---

src/sqlfluff/rules/L044.py
test/fixtures/rules/std_rule_cases/L044.yml

This fixes an assertion failure that appeared in a user's failure log in a [Slack chat](https://sqlfluff.slack.com/archives/C01GX4L213J/p1641331471426900?thread_ts=1641329507.421800&cid=C01GX4L213J) yesterday.
- Other.

Fix L044 assertion failure: "SELECT *" with no "FROM" clause

---

src/sqlfluff/core/rules/__init__.py

Follows on from discussion with @barrywhart [here](https://github.com/sqlfluff/sqlfluff/pull/2234#issuecomment-1005298335)
Here's what the docs look like after updating the docstring:
No
- Other.

Docs: Make Specific Rules docstring more user friendly

---

.github/workflows/ci-tests.yml
plugins/sqlfluff-templater-dbt/test/templater_test.py

During the work on #2230  it was decided to disable the Windows dbt tests that require a Postgres connection in order to get that important fix through. This PR makes a Postgres database available on the Windows runner so that we can re-enable those tests 😄 
Simplified version of this article: https://www.cybertec-postgresql.com/en/postgresql-github-actions-continuous-integration/
No
- Other. …

Re-enable dbt tests that connect to Postgres on Windows runner.

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/truncate_table.sql
test/fixtures/dialects/spark3/truncate_table.yml

Addes class in spark3 dialect to match `TRUNCATE` statements and test cases to verify successful matching.
N/A. This is a straightforward one :) 
- Other.

Add coverage for `TRUNCATE` statement in Spark3 dialect

---

requirements.txt
src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/rules/L025.py
src/sqlfluff/rules/L026.py
src/sqlfluff/rules/L028.py
test/fixtures/rules/std_rule_cases/L025.yml

Fixes #1462
This is basically a rewrite of `L025`. Previously, it inherited from `L020`. Now, its implementation largely relies on `SelectCrawler`. A couple of other rules needlessly inherited from `L025` that could've simply inherited from `L020` -- I updated those, because after the rewrite, inheriting from `L025` no longer worked.
- Other. …

L025 should look at subqueries

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L057.py
test/fixtures/rules/std_rule_cases/L057.yml

Allow hyphens in L057 as quoted identifiers (same as we allow underscores), as a lot of these are flagging for a lot of my table names in BigQuery.
@jpers36 , any issues with this since you created L057? If you would prefer not to allow this, then happy to move to a BigQuery specific bit of L057 since that already exists.
None
- Other. …

Optionally allow additional configurable characters in L057

---

docs/source/inthewild.rst

Fix link to a page now that the base branch is `main`.
Nope. Did a quick grep and didn't find other pages with `master`
- Other.

Fix link for editing 'In The Wild' page with new base branch, `main`

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/refresh.sql
test/fixtures/dialects/spark3/refresh.yml
test/fixtures/dialects/spark3/refresh_function.sql
test/fixtures/dialects/spark3/refresh_function.yml
test/fixtures/dialects/spark3/refresh_table.sql
test/fixtures/dialects/spark3/refresh_table.yml

Add implementation to match on and test cases for `REFRESH` statements in spark3 dialect.
Fixes #1934 
N/A
- Other.

Spark3: Coverage for `REFRESH` auxiliary statements

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/rules/std_rule_cases/L025.yml

Fixes #2030 
BigQuery already had special code to deal with some ambiguity about which portion of an object reference was the table, schema, etc. To fix this issue (BigQuery functions that take a table as a parameter), we change it again, making it even more "accepting".
The tradeoff of doing it this way (which we were already doing in L026) is that rules using this function to interpret a reference are given things that _may or may not_ be table references. In this case, that works fine. Generally, any rule using this function must be designed so that it behaves reasonably in spite of the ambiguity. (Generally, rules should "fail safe", i.e. don't "fix" code unless they know for sure how to do it safely, and don't warn unless they're sure there's an issue.)
- Included test cases to …

L025 with 'bigquery' dialect: Correctly interpret calling functions with a table as a parameter

---

src/sqlfluff/core/rules/functional/__init__.py
src/sqlfluff/core/rules/functional/segment_predicates.py
src/sqlfluff/rules/L009.py
test/fixtures/rules/std_rule_cases/L009.yml

Fixes #2046 
Updates L009 to consider whether trailing newlines are in raw or templated space before reporting an issue.
- Other.

Update L009 to operate in raw, not templated space

---

src/sqlfluff/rules/L054.py

Decorates [`Rule_L054`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/rules/L054.py#L7) with [`document_configuration`](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/doc_decorators.py#L21), as the configuration keyword is already present in [config_info.py](https://github.com/sqlfluff/sqlfluff/blob/main/src/sqlfluff/core/rules/config_info.py#L120).
Closes #2287
Should be pretty harmless.
- …

docs: Document configuration keyword for rule L054

---

src/sqlfluff/rules/L020.py

There were missing `t` for "tables" in the SQLFluff doc on the "Rules Reference" page, rule L020. 
[https://docs.sqlfluff.com/en/latest/rules.html](https://docs.sqlfluff.com/en/latest/rules.html#:~:text=for%20two%20different-,ables,-%3A)
No.
- Other.

added missing "t" in doc for Rule_L020

---

src/sqlfluff/core/config.py
test/cli/commands_test.py
test/fixtures/cli/extra_configs/pyproject.toml

Unblocks #2300. Originally `extra_config_path` only allowed custom paths for `ini/cfg` files (added #1986), this PR allows custom paths for `pyproject.toml` files as well.
No
- Other.

Allow pyproject.toml as extra_config_path

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py
test/core/config_test.py
test/fixtures/config/toml/pyproject.toml

- Fix #1292
The cause of this bug is that some options in Click (`--nocolor` and `--verbose`) don't have default values when not specified as CLI options. In original code, only `None` must be default value. This change should define default values for each options other than `None`.
- Other.

Fix #1292: nocolor and verbose can work in config files

---

src/sqlfluff/dialects/dialect_hive.py
src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/hive/quoted_literal.sql
test/fixtures/dialects/hive/quoted_literal.yml
test/fixtures/dialects/spark3/create_table_datasource.yml
test/fixtures/dialects/spark3/create_table_hiveformat.yml
test/fixtures/dialects/spark3/quoted_literal.sql
test/fixtures/dialects/spark3/quoted_literal.yml

Closes #2309. Both Spark3 and Hive can use either single or double quotes for quoted literals (quoted identifiers use backticks).
Previous implementation had added a `SingleOrDoubleQuotedLiteralGrammar` and used it in place of `QuotedLiteralSegment`, however this means that all the grammar inherited from ANSI was still only using single quotes! I've fixed both of these grammars so they properly overwrite ANSI.
No
- Other.
- Added …

Fix spark and hive quoted literals

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_table_column.sql
test/fixtures/dialects/snowflake/snowflake_alter_table_column.yml

Snowflake: Add support for column rename
fixes #2206
* #2206 has 2 issues. The first issue (`SELECT TOP 1 *`) has been fixed in https://github.com/sqlfluff/sqlfluff/pull/2222, and this PR should fix the second issue.
* This is part 2 of the overall plan to get `tableColumnAction` implemented Snowflake, as defined in https://github.com/sqlfluff/sqlfluff/issues/2206#issuecomment-1004038513.
* None that I can think of.

Snowflake: Add support for column rename

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_create_table_as.sql
test/fixtures/dialects/redshift/redshift_create_table_as.yml

What the title says. `SelectableGrammar` can be bracketed in a `CREATE TABLE AS` statement.
Once again something that isn't made clear in the official AWS documentation :smile:  
Nope!
- Other.

Redshift: update CREATE TABLE AS match_grammar

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_table_column.sql
test/fixtures/dialects/snowflake/snowflake_alter_table_column.yml

Closes #2344. You can drop multiple columns at once in the Snowflake ALTER TABLE statement.
No
- Other.

Snowflake ALTER TABLE: Drop multiple columns

---

src/sqlfluff/rules/L041.py
test/fixtures/rules/std_rule_cases/L041.yml

Closes #2363. Fixes the linked issue, and more generally simplifies, the rule logic using the functional API.
No
- Other.

L041: Fix duplicate DISTINCT corruption

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py

PR #2382 (merged a few minutes ago) introduced some coverage issues by removing some code that I **thought** was unused. This PR undoes those changes to avoid breaking CI builds for other people.
- Other.

Rolls back some code cleanup that caused coverage report to show gaps

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/insert_overwrite_directory.sql
test/fixtures/dialects/spark3/insert_overwrite_directory.yml

Implementation of `InsertOverwriteDirectorySegment` and test cases for INSERT OVERWRITE DIRECTORY statements for spark3 dialect.
N/A
- Other.

Spark3: Support for `INSERT OVERWRITE DIRECTORY` statements

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/transaction.sql
test/fixtures/dialects/tsql/transaction.yml

In T-SQL, "TRANS" is also a synonym for "TRANSACTION". Since this is
different in each dialect, this just changes the TSQL parser.
fixes #2368
None that I expect 🙂
- Other.

Add "TRANS" keyword for TSQL

---

docs/source/configuration.rst
src/sqlfluff/core/config.py
src/sqlfluff/core/templaters/jinja.py
test/core/config_test.py
test/core/templaters/jinja_test.py
test/fixtures/templater/jinja_macro_path_does_not_exist/.sqlfluff
test/fixtures/templater/jinja_slice_template_macros/.sqlfluff
test/fixtures/templater/jinja_slice_template_macros/more_macros/echoecho.sql

Jinja templater: Allow "load_macros_from_path" to be a comma-separated list of paths

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_values_alias.sql
test/fixtures/dialects/postgres/postgres_values_alias.yml

Fixes parsing issue noted [here](https://github.com/sqlfluff/sqlfluff/pull/2400/files#r789723089).
In #2353 I tidied up the postgres alias expression to remove quoted literal alias which are invalid. At the time I also thought the bracketed segment was also not valid, but have since realised I was wrong there! :)
This adds the values alias back in to the dialect.
N.B. I also checked the syntax that I spotted this issue in and it's not valid MySQL so I think the MySQL changes in #2353 are still valid.
No …

Postgres: Fix Values alias regression

---

src/sqlfluff/rules/L060.py
test/fixtures/rules/std_rule_cases/L060.yml

Closes #2392. Adds a new rule to require the use of `COALESCE` over `IFNULL` or `NVL`. See linked issue for source + motivation. 
No
- Other.

L060: Use COALESCE instead of IFNULL or NVL.

---

src/sqlfluff/rules/L041.py
src/sqlfluff/rules/L043.py
src/sqlfluff/rules/L047.py
src/sqlfluff/rules/L056.py

Noticed a load of sty code formatting marks in rule docs due to bad markup.
Nope
- Other.

Fix code formatting in Rule docs

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/dialects/exasol/SelectStatement.sql
test/fixtures/dialects/exasol/SelectStatement.yml

Currently the `LOCAL.ALIAS` syntax is parsed by `sqlfluff`. But it parses `LOCAL` as an identifier rather than a keyword. Furthermore there are things like `SELECT local.local FROM x` possible. This isn't valid code.
I added a new `LocalAliasSegment` to the `ansi` dialect as a hookpoint because it's necessary to add it to the `ExpressionSegment`. Also added various test cases for the different possibilities.
none
- Other.
- Added …

Exasol: Fix `LOCAL.ALIAS` Syntax

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/ansi/create_index_simple.sql
test/fixtures/dialects/ansi/create_index_simple.yml

Fixes #2135 
This was added to ANSI as believe most (all?) dialects that support CREATE INDEX support CREATE UNQIUE INDEX
- Other.

Support CREATE UNIQUE INDEX

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_drop_procedure.sql
test/fixtures/dialects/postgres/postgres_drop_procedure.yml

Fixes #2091 : add support for `DROP PROCEDURE` statements in postgres
It is not as restrictive as it should be (for example with `argmode` in `FunctionParameterListGrammar`). The tradeoff is the segment stays short and clean.
I'm not sure it warrants leaving a TODO, but happy to include one if needs be.
- Other. …

Add Postgres DROP PROCEDURE support

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/insert_with_identity_insert.sql
test/fixtures/dialects/tsql/insert_with_identity_insert.yml

T-SQL's `IDENTITY_INSERT` needs a table name in addition to `ON`/`OFF`. So we add it.
Fixes: #2448
I don't think so 🙂
- Other.

Fix T-SQL's IDENTITY_INSERT syntax

---

test/fixtures/dialects/spark3/common_table_expressions.sql
test/fixtures/dialects/spark3/common_table_expressions.yml

From what I've found so far, CTEs work without any additional code for spark3 dialect but thought I would open PR for the test cases to help identify any regressions in the future.
N/A
- Other.

Spark3: test cases for Common Table Expressions

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L010.py
src/sqlfluff/rules/L014.py
src/sqlfluff/rules/L029.py
test/fixtures/rules/std_rule_cases/L010.yml
test/fixtures/rules/std_rule_cases/L014.yml
test/fixtures/rules/std_rule_cases/L028.yml
test/fixtures/rules/std_rule_cases/L029.yml
test/fixtures/rules/std_rule_cases/L030.yml
test/fixtures/rules/std_rule_cases/L040.yml

As raised on Slack 0.9.2 introduced a lot of keywords to Snowflake, including a lot of single word short alias's for dates (e.g. `d` for `day`).
This PR introduces the concept of `ignore_words` to allow the rules that check identifiers to be ignored for certain "allowed words". This is a good feature for feature to have anyway as allows users to handle bugs without waiting for the next release or turning off a rule entirely.
I've also excluded single letter chars from L026 and did some clean up in there for performance.
Adds an optional `ignore_words` parameter to the following rules:
- L010 - Inconsistent capitalisation of keywords.
- L014 - Inconsistent capitalisation of unquoted identifiers.
- L029 - Keywords should not be used as identifiers (rule inherits this from L010).
- L030 - …

Ignore words for various rules

---

src/sqlfluff/rules/L044.py
test/fixtures/rules/std_rule_cases/L044.yml

Fizes #2467
Originally part of #2464 but decided to pull out separately for easier review.
L044 expects a FROM statement to have a SELECT clause. This causes problems when using UPDATE with a FROM clause - especially when using a CTE that has a SELECT (otherwise L044 would be ignored).
Change `assert` into `if not` to fix.
Shouldn't be
- Other. …

Fix L044 exception when final statement has no SELECT

---

src/sqlfluff/rules/L039.py
test/fixtures/rules/std_rule_cases/L039.yml

Fixes final bug preventing #2473 from being merge
```
% echo "SELECT col1 FROM table1 WHERE 1 > = 1" | sqlfluff lint --dialect tsql -
CRITICAL   [L039] Applying rule L039 threw an Exception: local variable 'child_seg' referenced before assignment                                                                   
File "/Users/barry/sqlfluff/src/sqlfluff/core/rules/base.py", line 519, in crawl
res = self._eval(
File "/Users/barry/sqlfluff/src/sqlfluff/rules/L039.py", line 97, in _eval
anchor=child_seg,
UnboundLocalError: local variable 'child_seg' referenced before assignment
== [stdin] FAIL                                                                                                                                                                    
L: …
```

Fix L039 for T-SQL comparison operator using space

---

src/sqlfluff/rules/L031.py

Makes progress on #2484 by preventing exception being thrown on unparsable code.
I've not added a test case for this as 1) it's stupidly simple, and 2) it only happens for unparsable code which should in theory never happen. Let me know if you really think it needs it.
- Other.

Prevent L031 throwing exception on unparsable code

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/rules/L031.py

This fixes some runtime rule errors in #2245 detected by the new "Rules critical errors tests" CI check.
I recommend reviewing this PR with the "Hide whitespace" option checked.
- Other.

Add guards to prevent rule crashes

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/function_default_params.yml
test/fixtures/dialects/tsql/function_no_return.yml
test/fixtures/dialects/tsql/functions_a.sql
test/fixtures/dialects/tsql/functions_a.yml
test/fixtures/dialects/tsql/hints.yml
test/fixtures/dialects/tsql/stored_procedure_single_statement.yml

In T-SQL, function definitions must have parentheses, even if they have no parameters.
On the other hand, procedures can have parentheses around parameters, but they don't need to.
To correctly lint this difference, they now use different segments.
Fixes #2472
- Other.

Enforce parentheses for function definitions in T-SQL

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/raiserror.sql
test/fixtures/dialects/tsql/raiserror.yml

This probably doesn't support the complete raiseerror syntax, but it's a start 🙂
Fixes #2367
I don't thinks so.
- Other.

Add raiserror for T-SQL

---

src/sqlfluff/core/templaters/slicers/tracer.py
test/fixtures/rules/std_rule_cases/L009.yml

Bug fix: Defining and using Jinja macro in the same file causes runtime error

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/select_distribute_by.sql
test/fixtures/dialects/spark3/select_distribute_by.yml

This PR adds support for the DISTRIBUTE BY clause that is used in SELECT statements.
N/A
- Other.

Spark3: Support `DISTRIBUTE BY` clause in `SELECT` statement

---

plugins/sqlfluff-templater-dbt/docker/docker-compose.yml

Small change to the dbt Docker _development_ environment. It mounts the existing `profiles.yml` at `~/.dbt` so you can run dbt commands without having to manually set up this file. This change has no impact on normal SQLFluff users.
- Other.

dbt Docker environment: Mount the test profiles.yml at ~/.dbt

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_explain.sql
test/fixtures/dialects/postgres/postgres_explain.yml

Just noticed that Postgres `EXPLAIN ANALZYE` works perfectly fine with the British spelling of `ANALYSE`.
No
- Other.

Postgres: EXPLAIN ANALYSE allows British spelling

---

setup.cfg

Fixes #2519
Address the Megalinter issue discussed here: https://sqlfluff.slack.com/archives/C01GX4L213J/p1643566502596369. The issue was, the required version of `click` needed to be newer in order to ensure that the `click.shell_completion` module was present.
- Other.

Update click version requirement in setup.cfg to match that in requirements.txt

---

src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_postgres_keywords.py
test/fixtures/dialects/postgres/postgres_with.sql
test/fixtures/dialects/postgres/postgres_with.yml

Adds `NOT MATERIALIZED`, `SEARCH BREADTH/DEPTH FIRST`, and `CYCLE` clauses to Postgres CTEDefinitionSegment.
Closes #2523 
No
- Other.

Postgres specific CTEDefinitionSegment

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/rules/std_rule_cases/L039.yml

Fixes #2495 - prevent final comma being swallowed up
Fixes #2516 - move DollarQuotedLiteralSegment into QuotedLiteralSegment
A potential nicer fix to #2495 would be to have an alternative to `allow_trailing` option, which doesn't error when there is a trailing delimiter, but recognised this is not part of this Grammar. But had a quick look and can't figure out how to do that.
No
- Other. …

Fix Quoted Literals for Postgres and Redshift affecting rule L039

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Adding Indent/Dedent tags for TSQL's UPDATE statement.
None.

TSQL: Add indentation for UPDATE statement

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Adding Indent/Dedent tags for TSQL's SET statement.
No.

TSQL: Add indentation for SET statement

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
plugins/sqlfluff-templater-dbt/test/templater_test.py

Fixes #2253. Tests the behavior mentioned as broken in #1468.
- Other.

dbt templater: Fix bug where profile wasn't found if DBT_PROFILES_DIR contained uppercase letters

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L062.py
test/fixtures/rules/std_rule_cases/L062.yml
test/rules/std_L062_test.py

Fixes #362
Fixes #1800 
Follow on from #2507
This adds a very configurable new rule to allow blocking of certain terms. To quote from the rule docstring:
This generic rule can be useful to prevent certain keywords, functions, or objects
from being used. Only whole words can be blocked, not phrases.
This block list is case insensitive.
Example use cases:
* We prefer ``BOOL`` over ``BOOLEAN`` and there is no existing rule to enforce
this. We can add ``BOOLEAN`` to the deny list until such a rule is written to
cause a linting error.
* We have deprecated a schema/table/function and want to prevent it being used
in future. We can add that to the denylist and then add a ``-- noqa: L062`` for
the few exceptions that still need to be in the code base.
Can't think of any. Obviously people …

Adds new rule to allow blocking of certain words

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L059.py
test/fixtures/rules/std_rule_cases/L059.yml

fixes #2527 by providing a configuration option on the L059 rule.
No side effects expected as the default values for the newly added configuration are respecting the previous L059 behavior.
Even though I think I have fulfilled the requirements in terms of development, tests, documentation, please do not hesitate to help me ensuring this PR is OK, as I didn't wrote anything in python since a decade (literally), and I'm not 100% sure I respected the code of conduct (and if I failed, I'm sorry, I'll fix my mistakes).

Allow L059 to be configured to always prefer quoted identifiers

---

requirements.txt
setup.cfg
src/sqlfluff/cli/autocomplete.py
src/sqlfluff/cli/commands.py

Fixes #2543 
Not sure if this it the best way of doing this in Python, and don't think we can add test cases, so feel free to suggest improvements
Shouldn't be
- Other.

Remove requirement for Click>=8

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/select_replace.sql
test/fixtures/dialects/bigquery/select_replace.yml

Fixes https://github.com/sqlfluff/sqlfluff/issues/2549
BQ's `SELECT REPLACE` requires parentheses around replaced fields, but the BQ dialect implementation was permittig an invalid version without it.
This implemetation had the side effect of also failing to parse a `SELECT REPLACE()` with trailing comma and no additional fields, e.g the following would not parse correctly.
```sql
SELECT * REPLACE(foo AS bar),
FROM foo
```
Removing the unparenthesised version from the dialect makes the parsing more consistent with what BQ actually accepts, requiring the parentheses, and resolves the parse error on the trailing comma.
None that I'm aware of.
- ~`.yml` rule test cases in …

Correct parsing for BigQuery `SELECT REPLACE` clauses.

---

src/sqlfluff/core/templaters/slicers/tracer.py
test/core/templaters/jinja_test.py

Jinja and dbt templater: Fix "list index out of range" error

---

src/sqlfluff/core/templaters/slicers/tracer.py
test/core/templaters/jinja_test.py

Followon to PR #2555 that fixes a likely source of future issues. That PR avoided the crash mentioned in issue #2541, but there's a deeper issue: when whitespace control is used, `JinjaTracer` gets less output from the "alternate template". If a user's SQL file makes extensive use of whitespace control, we may get so little output from the "alternate template" that `JinjaTracer._slice_template()` may deduce an execution path that doesn't reflect what actually happened. This PR fixes that by reviving our old trick of disabling whitespace control (but only in the invisible "alternate" template).
- `.sql`/`.yml` parser test cases …

jinja and dbt templaters: More robust handling of whitespace control

---

src/sqlfluff/dialects/dialect_spark3.py
src/sqlfluff/rules/L003.py
src/sqlfluff/rules/L057.py
test/fixtures/dialects/spark3/select_from_file.sql
test/fixtures/dialects/spark3/select_from_file.yml
test/fixtures/rules/std_rule_cases/L057.yml

- Adds support to directly query files of supported types.
- Fixes #602 
- Reorganized some grammar for Files to isolate File keywords that support this clause.
- Removed "XML" File format. No test cases and requires additional work before it will parse correctly.
- Linting fails due to special characters in identifiers (L057). These special keywords are required so would be an exception to L057. I've not yet worked on rules so would appreciate any guidance on where to get started on fixing this particular bug.
```bash
> sqlfluff lint --dialect spark3 test/fixtures/dialects/spark3/select_from_file.sql
== [test/fixtures/dialects/spark3/select_from_file.sql] FAIL
L:   6 | P:  14 | L057 | Do not use special characters in identifiers.
L:  13 | P:  14 | L057 | Do not use special characters in …
```

Spark3: Add Direct File Query

---

src/sqlfluff/api/simple.py
src/sqlfluff/dialects/dialect_redshift.py
test/api/simple_test.py
test/fixtures/api/config_override/.sqlfluff

Simple API: Fix bug where omitted parameters still override .sqlfluff

---

src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/select.sql
test/fixtures/dialects/tsql/select.yml

The TSQL dialect inherits frame clause syntax from the ANSI dialect, but does not include the proper unreserved keywords in its keyword list.  This PR will add them.
https://docs.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql?view=sql-server-ver15#rows-or-range
None.

TSQL: Add Frame clause unreserved keywords

---

src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/rules/L003.py
src/sqlfluff/rules/L010.py
test/fixtures/rules/std_rule_cases/L010.yml
test/fixtures/rules/std_rule_cases/L030.yml

Capitalization rules (L010, L014, L030, L040) should ignore templated code

---

docs/source/indentation.rst
src/sqlfluff/core/default_config.cfg
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Fixes #2600
WINDOWS clauses will now indent (similar to other main clauses) which may cause some extra rules to flag for those that don't indent them.
- Other.

Support indenting WINDOWS clauses and (optionally) CTEs

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Adding indentation tags for the expression statements within an IF for the TSQL dialect.  Additionally, removed redundant options within the if clause.
None.

TSQL: Indent IF clause expression segments

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_semi_structured.sql
test/fixtures/dialects/snowflake/snowflake_semi_structured.yml

I found a bug in the snowflake dialect when accessing arrays of objects. This allows direct access of semi structured data within an array, a la: `my_array[1].some_attribute` which currently raises a parsing error.

Snowflake dialect: Adjust snowflake array access

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

This resolves #2244 and provides a clean solution to https://github.com/sqlfluff/sqlfluff-github-actions/issues/15.
This adds a `--write-output` to the `lint` and `parse` commands so that the commands can write directly to file. In the case that file output is enabled, the stdout logging is re-enabled so that the user can get e.g. yaml output to file and still get human output to stdout.

Allow file output directly from cli

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/rules/base.py
test/cli/commands_test.py
test/core/rules/config_test.py
test/fixtures/rules/std_rule_cases/L019.yml

Hitting the linter loop limit should be treated as an error

---

src/sqlfluff/core/rules/doc_decorators.py

This patch try to strict the order of rule's hand
writing docstring, fix_compatible, note, Configuration
and example pattern.
* Rule's hand writing docstring(expect example pattern
and note) is always in the fist place
* (Optional) Fix compatible in the second place
* (Optional) Note in the third place
* (Optional) Configuration in the fourth place
* Example pattern would always in the tail
It is compatible all orders of doc decorators …

Ensure ordering of fix compatible and config in rules docs

---

CONTRIBUTING.md

Changing the doc about local virtual environment to primarily suggest one that includes dbt dependencies.
The `py` environment doesn't include dbt dependencies, so developing the project with that venv can eventually hit a wall, like I did. After all, dbt templater tests are part of the PR checks and can fail as a result of changes in sqlfluff core. So to fully develop sqlfluff local dev setup should include the dbt deps. 
No.
- …

Doc a better choice for default env

---

src/sqlfluff/core/rules/analysis/select.py
test/fixtures/rules/std_rule_cases/L025.yml

Bug fix: L025 overlooking JOIN ON clause if join expression in parentheses

---

test/fixtures/rules/std_rule_cases/L002.yml
test/fixtures/rules/std_rule_cases/L003.yml
test/fixtures/rules/std_rule_cases/L016.yml
test/fixtures/rules/std_rule_cases/L017.yml
test/fixtures/rules/std_rule_cases/L025.yml
test/fixtures/rules/std_rule_cases/L031.yml
test/fixtures/rules/std_rule_cases/L037.yml
test/fixtures/rules/std_rule_cases/L043.yml
test/fixtures/rules/std_rule_cases/L048.yml
test/fixtures/rules/std_rule_cases/L058.yml
test/fixtures/rules/std_rule_cases/L059.yml
test/fixtures/rules/std_rule_cases/L060.yml

Fixes some common mistakes in rule yaml tests.
Covers these type of mistakes:
- Successful fix, but `fix_str` missing to assert the result -> add the missing `fix_str`
- `pass_str` used instead of `fix_str`, ie. fix result would not be asserted -> change `pass_str` to `fix_str`
- Unfixable failure, but `fix_str` is used with the same value as `fail_str`. Doesn't make sense to do that -> remove `fix_str`.
These mistakes were revealed by the pending additional assertions to testing/rules.py in https://github.com/sqlfluff/sqlfluff/pull/2624/files
No.
But note that a yaml rule test with only `fail_str` should always mean that there's an unfixable error and the query is not modified as a result. Or at least how I understood, but there's an open question about it: …

Fix mistakes in rule yaml tests

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/postgres/postgres_datatypes.sql
test/fixtures/dialects/postgres/postgres_datatypes.yml
test/fixtures/dialects/redshift/redshift_cast_conversion.yml
test/fixtures/dialects/redshift/redshift_create_external_table.yml
test/fixtures/dialects/redshift/redshift_create_external_table_as.yml
test/fixtures/dialects/redshift/redshift_create_table.yml
test/fixtures/dialects/redshift/redshift_datetime_cast.sql
test/fixtures/dialects/redshift/redshift_datetime_cast.yml

fixes #2649 .
- **Added support for `DATETIME` as a valid datatype in the `redshift` Dialect**. I did this by replacing the `DateTimeTypeIdentifier` segment in the `redshift` dialect (that was inherited from the `postgres` dialect), and adding `DATETIME` identifier as a possible `DateTimeTypeIdentifier`. The `DataTypeSegment` segment in the `redshift` dialect was then adjusted so that a `DateTimeTypeIdentifier` is a valid component of a `DataTypeSegment`. I added test cases to show support for `DateTimeTypeIdentifier`s (and `DATETIME` as a valid datatype) in the Redshift dialect with the `test/fixtures/dialects/redshift/redshift_datetime_cast.sql` file and the `test/fixtures/dialects/redshift/redshift_datetime_cast.yml` file.
- **Added test cases to show how `DATETIME` is parsed as a …

Redshift: Support DATETIME as a valid datatype

---

src/sqlfluff/testing/rules.py

Assert in yaml rule tests that if only `fail_str` is given, then the rule violation is detected but original query is not modified at all.
If this new check fails but some fixing is expected, then the test case can be passed by adding the missing `fix_str`.
So this just helps in keeping the test coverage better for fixing. 
This doesn't find any issues in the existing tests now, because those were just fixed in https://github.com/sqlfluff/sqlfluff/pull/2658.
No. …

Assert that fix_str is set

---

benchmarks/bench_002/bench_002_pearson_fix.sql
src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_merge_into.sql
test/fixtures/dialects/snowflake/snowflake_merge_into.yml

Fix for #2666 
Updated the snowflake dialect file to handle `AND` within the `WHEN NOT MATCHED` clause.
Updated snowflake merge dialect test to include an example.
- [x ] Please confirm you have completed any of the necessary steps below.
- Other.

Snowflake dialect update for `MERGE INTO` predicates

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/raiserror.sql
test/fixtures/dialects/tsql/raiserror.yml

TSQL's RAISERROR command has functionality not currently reflected in the SQLFluff TSQL dialect.
This PR will add:
-Unicode support
-Full argument support
-Option support

TSQL: Improve RAISERROR functionality

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Adding indentation so that multi-line CREATE STATISTICS and CREATE INDEX commands are indented on succeeding lines.
None.
- `[x] .yml` rule test cases in `test/fixtures/rules/std_rule_cases`.

TSQL: Add indentation for CREATE INDEX/STATISTICS

---

src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/dialects/exasol/CreateFunctionStatement.sql
test/fixtures/dialects/exasol/CreateFunctionStatement.yml
test/fixtures/rules/std_rule_cases/L003.yml

Currently the function body don't gets formattet correctly. Even worse that it breaks existing formatting.
Current:
```sql
CREATE FUNCTION schem.func (
p1 VARCHAR(6),
p2 VARCHAR(10)
) RETURN VARCHAR (20)
IS
res VARCHAR(20);
BEGIN
IF p1 IS NOT NULL AND p2 IS NOT NULL THEN
IF p1 = 1 THEN
res:= 'Hello World';
ELSE
IF p2 = 3 THEN
res:= 'ABC';
END IF;
res:= 'WOHOOOO';
END IF;
END IF;
RETURN res;
END schem.func;
/
```
This PR improves the formatting.
After:
```sql
CREATE FUNCTION schem.func (
p1 VARCHAR(6),
p2 VARCHAR(10)
) RETURN VARCHAR (20)
IS
res VARCHAR(20);
BEGIN
IF p1 IS NOT NULL AND p2 IS NOT NULL THEN
IF p1 = 1 THEN
res:= 'Hello World';
ELSE
IF p2 = 3 THEN
res:= 'ABC';
END IF;
res:= 'WOHOOOO';
END IF;
END IF;
RETURN res;
END schem.func;
/
```
Nope
- Included test cases to demonstrate …

Exasol: Improve function formatting

---

src/sqlfluff/dialects/dialect_exasol_keywords.py
test/fixtures/dialects/exasol/SelectStatement.sql
test/fixtures/dialects/exasol/SelectStatement.yml

Currently the `CROSS` keyword within a `JOIN` clause is handled as an alias of the previous table. This breaks code after formatting because `sqlfluff` fixes the `JOIN` condition to `INNER JOIN` and removes the `CROSS` because it wasn't used as an alias. To solve this I moved the `CROSS` keyword from unreserved to reserved to make it work.
```sql
-- before I executed fix
SELECT -1 * row_number() OVER() AS nummer
FROM sys.exa_sql_keywords
CROSS JOIN sys.exa_sql_keywords
UNION ALL
SELECT 0;
-- after I executed fix => broken sql
SELECT -1 * row_number() OVER() AS nummer
FROM sys.exa_sql_keywords INNER JOIN sys.exa_sql_keywords
UNION ALL
SELECT 0;
```
nope …

Exasol: Allow CROSS joins

---

CONTRIBUTING.md
tox.ini

~~Pin python version for pre-commit hooks.~~
~~Most notably this pins python version for the mypy pre-commit hook so that it's aligned.~~
~~So this is the same as https://github.com/sqlfluff/sqlfluff/pull/2629, but for pre-commit.~~
Document that tox must be installed with Python 3.8+ for mypy checks to work. That concerns both `tox -e mypy` and the mypy pre-commit hook.
Maybe it's worth mentioning that when user runs for example `tox -e pre-commit -- install`, a virtual environment is created at `.tox/pre-commit/lib/python3.10` (assuming that tox was installed with 3.10). Or if one runs `tox -e mypy` for the first time, another virtual environment is created at `.tox/mypy/lib/python3.8` (assuming that tox installation is with 3.8). And then, the version that was installed in the relevant …

Document python requirement for tox/mypy & remove basepython from conf

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/raiserror.sql
test/fixtures/dialects/tsql/raiserror.yml

Fixes #2695
TSQL supports variables as parameters for RAISERROR.  This PR adds this functionality to SQLFluff's TSQL dialect.
None.

TSQL: Add variables as options for RAISERROR parameters

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/window_functions.sql
test/fixtures/dialects/spark3/window_functions.yml

Changes to spark3 dialect so `WINDOW` functions would properly parse, specifically redefining `OverClauseSegment` and adding `NamedWindowSegment` as an optional segment to `FromExpressionElementSegment`
N/A
- Other.

Spark3: Support for `WINDOW` functions

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/alter_table.sql
test/fixtures/dialects/tsql/alter_table.yml

Adds the necessary syntax for `alter table X drop constraint Y` to T-SQL
fixes #2694
I don't think so.
- Other.

T-SQL: Add drop constraint syntax

---

src/sqlfluff/dialects/dialect_oracle.py
test/fixtures/dialects/oracle/at_signs.yml
test/fixtures/dialects/oracle/database_link.sql
test/fixtures/dialects/oracle/database_link.yml

Fixes #2705 
This required a rewrite of the executes added by @r0fls in #2608 as the `@` used for database links was getting swallowed by that as a comment. This in turn required some jiggy-pokery with the `StatementSegment` and `FileSegment` since the execute statements do not end in the usual semi-colons.
- Other.
- Created GitHub issues for any relevant followup/future enhancements …

Support database links in Oracle

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/ansi/ansi_cast_with_whitespaces.sql
test/fixtures/dialects/ansi/ansi_cast_with_whitespaces.yml
test/fixtures/dialects/postgres/postgres_cast_with_whitespaces.sql
test/fixtures/dialects/postgres/postgres_cast_with_whitespaces.yml
test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql
test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.yml

Fixes #2720 .
- **Allows whitespace around cast operators (`::`) in the `redshift` dialect.** I allowed this by adjusting the `DatatypeSegment` in the `redshift` dialect to match grammar using a `Sequence` parser instead of just a `OneOf` parser, and allowed that `Sequence` to have gaps (`allow_gaps=True`). This aligns the parsing logic of `DatatypeSegment`s in the `redshift` dialect to with its ancestor dialects (`postgres`, `ansi`); both of this ancestor dialects parse `DatatypeSegment`s using a `Sequence` parser. I demonstrated that `sqlfluff` now allows for whitespaces around cast operators in the `redshift` dialect with `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.sql` and `test/fixtures/dialects/redshift/redshift_cast_with_whitespaces.yml`.
This change will allow …

Redshift: Allow Whitespace Around Cast Operators

---

src/sqlfluff/rules/L018.py
test/fixtures/rules/std_rule_cases/L018.yml

L018: Move closing parenthesis to next line

---

src/sqlfluff/rules/L052.py

This PR is a straightforward but thorough reorganization of L052, splitting the long, complex `_eval()` function into several smaller, easier to understand functions. Benefits:
* Makes future work on L052 easier
* Future potential for reusing some of this code in other rules. Other rules sometimes need to move a segment to a different line. L018 is one example. (See issue #2713.) Currently, L018 is less sophisticated than L052 -- it basically just adds a newline, splitting one line into two. L052 is more sophisticated: If there is a trailing comment on the line, it leaves the comment on the same line, moving **only** the semicolon to the next line. This is tricky enough that we probably wouldn't want to write this code twice.
- Included test cases to demonstrate any code changes, which …

L052: Refactor _eval() into individual functions to improve readability

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/rules/L030.py
test/fixtures/rules/std_rule_cases/L030.yml

Fixes #2736
This is a breaking change as L030 goes from using `capitalisation_policy` to `extended_capitalisation_policy` so anyone using it will need to change their config. Should be a 0.11.0 release.
Unfortunately it's not possible to support both for backwards compatibility.
- Other.

Support Pascal case for L030

---

test/fixtures/rules/std_rule_cases/L049.yml

Fixes #2708. (Actually, it's already fixed, but this adds a `.yml` test for it.)
- Other.

Add L049 test for T-SQL alternate alias syntax (=)

---

src/sqlfluff/core/rules/analysis/select_crawler.py
test/fixtures/rules/std_rule_cases/L045.yml

Make L045 (Query defines a CTE but does not use it) case insensitive

---

docs/source/configuration.rst

Fixes #2740. (It wasn't actually a bug, but it did seem that the documentation could be better.)
- Other.

Improve docs for "load_macros_from_path"

---

src/sqlfluff/rules/L059.py
test/fixtures/rules/std_rule_cases/L059.yml

L059 removes the quotes around passwords within `CREATE USER` statements in Exasol dialect.
```sql
CREATE USER user_1 IDENTIFIED BY "h12_xhz";
--> after fix
CREATE USER user_1 IDENTIFIED BY h12_xhz;
```
```
L:   1 | P:  34 | L059 | Unnecessary quoted identifier "h12_xhz".
L:   1 | P:  43 | L009 | Files must end with a single trailing newline.
==== fixing violations ====
2 fixable linting violations found
Are you sure you wish to attempt to fix these? [Y/n] ...
Attempting fixes...
Persisting Changes...
```
This fixes this bug and ignores the `password_auth` segment type.
Nope …

L059: Exasol: Allow quotes around passwords in CREATE USER

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/select_transform_clause.sql
test/fixtures/dialects/spark3/select_transform_clause.yml

Add support for transform clause through redefining `SelectClauseSegmentGrammar` in Spark3 dialect and creating `TransformClauseSegment` 
N/A
- Other.

Spark3: Support for `TRANSFORM` clause

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/explain.sql
test/fixtures/dialects/spark3/explain.yml

Replace `ExplainStatementSegment` from ANSI to allow for additional parameters and an expanded list of explainable statements.
Removed `parse_grammar` from `ExplainStatementSegment` in ANSI and re-assigned `parse_grammar` to `match_grammar` in Postgres and Snowflake dialects.
- Other.

Spark3: Support for `EXPLAIN` statement

---

src/sqlfluff/core/linter/linter.py
test/core/linter_test.py
test/fixtures/linter/passing_cap_extension.SQL

Fixes issues raised in chat, whereby a file with a `.SQL` extension was completely ignored by SQLFluff and caused confusion as to why for user.
If you were previously expecting .SQL files to be ignored then you'll be surprised now. Can't see that being an issue though.
- Other.

Make extenstion case insensitive

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/create_table_complex_datatypes.sql
test/fixtures/dialects/spark3/create_table_complex_datatypes.yml

Makes progress on #2761. Rebuild Delimited for CREATE Statements (spark3 Dialect).
For a proper solution, I think the generation of the BracketedSegment needs to be recursive on its own result (and prioritized over everything else). However I am just scratching the surface of this and am not really capable / confident to properly fix it.
I'm not aware of any side effects.
Currently there are no tests at all for spark3 dialect hence I skipped this part. …

Spark3 bug: Create with complex data types (#2761)

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_delete.sql
test/fixtures/dialects/postgres/postgres_delete.yml

Quick patch to #2791. Same tweak as [this](https://github.com/sqlfluff/sqlfluff/pull/2792#pullrequestreview-901045237) comment.
AS is optional in aliases within DELETE statement
No
- Other.

Postgres: Make AS optional in Postgres DELETE

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_insert.sql
test/fixtures/dialects/postgres/postgres_insert.yml

A column in a Postgres table can be assigned a default value. This default value can then be specified when inserting into a table via a values clause.
This PR allows the DEFAULT keyword to be specified in a values clause
No
- Other.

Postgres: INSERT DEFAULT value

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/postgres/postgres_array.yml
test/fixtures/dialects/postgres/postgres_create_table_as.yml
test/fixtures/dialects/postgres/postgres_delete.yml
test/fixtures/dialects/postgres/postgres_insert.sql
test/fixtures/dialects/postgres/postgres_insert.yml
test/fixtures/dialects/postgres/postgres_values_alias.yml
test/fixtures/dialects/postgres/postgres_values_in_subquery.yml
test/fixtures/dialects/postgres/values.sql
test/fixtures/dialects/postgres/values.yml
test/fixtures/dialects/redshift/redshift_insert_into.yml
test/fixtures/dialects/spark3/explain.yml
test/fixtures/dialects/spark3/insert_table.yml
test/fixtures/dialects/spark3/pivot_clause.yml
test/fixtures/dialects/spark3/select_from_multiple_values_clauses.yml
test/fixtures/dialects/spark3/select_from_values.yml
test/fixtures/dialects/spark3/values.yml
test/fixtures/dialects/spark3/values_with_alias.yml

Couple things fixed here:
- Fixes regression in Postgres VALUES clause caused by copying of Spark3 grammar in #2590. Expression segments are all that are required in a values clause. Spark grammar didn't account for them and tried to define the individual literal/function/... types.
- Spark3 VALUES grammar is different from every other grammar. This is because I fixed these in #2404 and Spark3 later got overwritten unnecessarily.
No …

Fix Postgres VALUES, make Spark3 VALUES consistent

---

src/sqlfluff/dialects/dialect_exasol.py
test/fixtures/dialects/exasol/InsertStatement.sql
test/fixtures/dialects/exasol/InsertStatement.yml

Adds support for the `VALUES BETWEEN` clause (aka value range clause) for `INSERT` statements. This was introduced in 7.1.
nope
- Other.

Exasol: Support value range clause within INSERT statements (7.1+)

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/rules/L052.py
test/conftest.py

We recently modified SQLFluff to log a warning if a lint fix makes illegal changes to
the parse tree. This is the appropriate behavior. for _production_. However, in order
to catch new bugs in new or modified rules, we need to be more strict when running
automated tests. This PR changes the behavior during tests to raise an exception
rather than simply logging. This notifies rule authors of issues and forces them to
be addressed during PR review.
This PR also fixes some issues with L052 fixes. These had been fixed, but the fixes
were lost when we reverted a recent PR (to address other bugs). …

Automated tests should fail if a lint fix introduces a parse error

---

src/sqlfluff/dialects/dialect_spark3.py
test/fixtures/dialects/spark3/explain.yml
test/fixtures/dialects/spark3/refresh_function.yml
test/fixtures/dialects/spark3/refresh_table.yml

Refactor `RefreshFunctionStatementSegment`, `RefreshTableStatementSegment`, `RefreshStatementSegment` into a single class (`RefreshStatementSegment`) 
N/A
- Other.

Spark3: Refactor `REFRESH` statements into one class

---

.github/workflows/ci-tests.yml

* In job `python-version-tests`, we already told the version we
setup in step `Set up Python`, so we could simply run command
`tox -e py` to trigger the job, so we could remove the
`Set Tox Python Param` step
* In job `other-tests` we just set an unused variable by one step
and I think we should directly remove it.

Reduce unnecessary setting run ci

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
src/sqlfluff/core/templaters/base.py
src/sqlfluff/core/templaters/slicers/tracer.py
test/core/templaters/base_test.py
test/core/templaters/jinja_test.py

This PR began as a follow-on PR to #2846 to address a `JinjaTracer` bug that I previously didn't think was fixable 🎉 💯 , as well as adding assertions to catch potential future bugs where `JinjaTracer` returns incorrect results.
Fixes #2835
- Other.

Fix bug with Jinja and dbt "{% set %}" blocks

---

test/fixtures/dialects/README.md
test/generate_parse_fixture_yml.py

#2844
Adds some flags for faster/ more minimal rebuilding
- `--new-only`
- `--dialect bigquery`
- `--filter *with_*`
Nope

Add ability to regenerate subsets of fixture YAMLs (by dialect, or new only)

---

src/sqlfluff/core/linter/common.py
src/sqlfluff/core/linter/linted_file.py
src/sqlfluff/core/parser/lexer.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/core/templaters/slicers/tracer.py
src/sqlfluff/rules/L009.py
test/api/simple_test.py
test/core/templaters/jinja_test.py
test/fixtures/rules/std_rule_cases/L009.yml

Fixes #2822
OMG, this is the deepest bug I've seen in a long time. Fixing it has required changes to:
* Core lexer (placeholder generation)
* Core parser: How BaseSegment generates patches
* Core linter (patch application)
* Updating `JinjaTracer` with better handling of `{% endif %}` and `{% endfor %}`
* Updating `is_final_segment()` to optionally consider meta segments and updating L009 to use it
- Other. …

L009: Handle adding newline after `{% endif %}` at end of file

---

docs/source/inthewild.rst

_Reopening because I accidentally deleted the forked repo._
The maintainers have done an amazing job responding to issues that our team has noticed with SQLFluff so I figured I would pay it forward by adding some praise to the tool's docs. (I actually had to shorten this description a lot -- we love the tool and it gets better with every release!)
- Other.
- Created GitHub issues for …

Add Markerr to list of organizations using SQLFluff in the wild 

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/select_function_object_fields.sql
test/fixtures/dialects/bigquery/select_function_object_fields.yml
test/fixtures/dialects/bigquery/select_mixture_of_array_literals.sql
test/fixtures/dialects/bigquery/select_mixture_of_array_literals.yml

BigQuery: Better `STRUCT` Array Support

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/rules/L031.py
test/fixtures/rules/std_rule_cases/L031.yml

Disable L031 on BigQuery due to complex backtick / project name behavior

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/select_cast.sql
test/fixtures/dialects/hive/select_cast.yml

Extended version of ansi's `FunctionSegment` to add support of row typecasting
```
cast(row(val1, val2) as row(a integer, b integer))
```

Row typecasting in hive `cast` function

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/select_cast.yml
test/fixtures/rules/std_rule_cases/L027.yml

In `Hive` dialect there is a false positive violation detected in `rowtype` definition when query/subquery operates with join
```sql
select cast(row(t1.attr, t2.attr) as row(fld1 double, fld2 double)) as flds
from sch.tab1 as t1
join sch.tab2 as t2 on t2.id = t1.id
```
`fld1`, `fld2` interpret as table column alias rather than rowtype attribute name

Hive: fix to align with L027 rule (rowtype attribute name)

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/select_cast.sql
test/fixtures/dialects/hive/select_cast.yml

Extended primitive datatypes in `Hive` for `json`

Hive: added `json` type support

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/select_cast.sql
test/fixtures/dialects/hive/select_cast.yml

Adding support for complex datatypes in `cast` `rowtype` definition:
```
select
cast(row(col1, col2) as row(a bigint, b decimal(23, 2)))
from sch.tbl;
```

Hive: support for complex types in `cast` `rowtype` definition

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_view.sql
test/fixtures/dialects/snowflake/snowflake_alter_view.yml

Adds support in Snowflake for `ALTER VIEW` statements
Fixes #2910 
- Other.

Added Snowflake Alter View Support

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_inline_comment.sql
test/fixtures/dialects/snowflake/snowflake_inline_comment.yml

Snowflake supports inline comments starting with `//`. This PR adds support to SQLFluff for the same
Fixes #2918
- Other.

Added Support For Snowflake Inline Comments

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/select_unpivot.sql
test/fixtures/dialects/bigquery/select_unpivot.yml

BigQuery: support numeric aliases in `UNPIVOT` clauses

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_select.sql
test/fixtures/dialects/postgres/postgres_select.yml

Add support for column definitions in table aliases. This is commonly used when joining with functions that return result sets.
Fixes #2929 
No
- Other.

Adds support for column definitions in table alias expressions

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/base.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/rules/L010.py
src/sqlfluff/rules/L063.py
test/fixtures/linter/autofix/ansi/009_keyword_capitalisation/after.sql
test/fixtures/rules/std_rule_cases/L010.yml
test/fixtures/rules/std_rule_cases/L063.yml

Fixes #2556 by adding a new rule (L063) for datatypes, and removing datatypes from L010.
The new rule uses `extended_capitalisation_policy` to allow PascalCase (e.g. VarChar)
It also added a new, optional `parent` param for `matches_target_tuples` as they are often parsed like this:
```
[L:  4, P:  8]      |                    data_type:
[L:  4, P:  8]      |                        keyword:                              'time'
```
L010 can no longer be consistent between Datatypes and other Keywords. …

Add new rule L063 to allow separate capitalisation policy for Datatypes

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_spark3.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/inner_joins.sql
test/fixtures/dialects/tsql/inner_joins.yml
test/fixtures/rules/std_rule_cases/L026.yml

Fixes #2676 
This change means a `JOIN` clause can now have multiple tables, so multiple aliases. So we had to change `get_eventual_alias` to `get_eventual_aliases`.
- Other.

TSQL: Support nested joins

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/redshift/redshift_percentile_cont.sql
test/fixtures/dialects/redshift/redshift_percentile_cont.yml

Fixes #2951, an issue with parsing Redshift's [percentile_cont](https://docs.aws.amazon.com/redshift/latest/dg/r_WF_PERCENTILE_CONT.html#r_WF_PERCENTILE_CONT-synopsis) function.
- Other.

Allow multiple post function clauses in Postgres and Redshift

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/rules/L042.py

Makes progress on #2944.
It's a workaround, not a fix. The workaround is to let rules know if we're in "lint" or "fix" mode, so they can skip the "fix" logic when just linting. This is not a proper fix because L042 has a design flaw: It's modifying the parse tree directly, bypassing the use of `LintFix`. This will likely cause other issues in the future until it's fixed.
- Other.
- …

Bug: L042 modifies parse tree even during "lint"

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/bigquery/is_not_distinct.sql
test/fixtures/dialects/bigquery/is_not_distinct.yml

Makes progress on #2961 
Note we currently do not fully support this in the `SELECT` clause unless brackets are used.
- [z] Please confirm you have completed any of the necessary steps below.
- Other.

Add basic `IS (NOT) DISTINCT FROM` support in most dialects

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/insert_statement.sql
test/fixtures/dialects/tsql/insert_statement.yml

INTO keyword is optional in INSERT statements in T-SQL.
See: https://docs.microsoft.com/en-us/sql/t-sql/statements/insert-transact-sql?view=sql-server-ver15
N/A
- Other.
sqlfluff is already documented as supporting T-SQL dialect.

INTO is optional within T-SQL INSERT statement

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/waitfor.sql
test/fixtures/dialects/tsql/waitfor.yml

Add (partial) support for WAITFOR in T-SQL dialect.
https://docs.microsoft.com/en-us/sql/t-sql/language-elements/waitfor-transact-sql?view=sql-server-ver15
N/A
- Other.

TSQL: Add support for `WAITFOR` statement

---

.pre-commit-config.yaml

Simply bump black to 22.3.0. In some configuration, version 22.1.0 fails with this error:
https://stackoverflow.com/questions/71673404/importerror-cannot-import-name-unicodefun-from-click
- Other.

Bump black to 22.3.0 on pre-commit

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/create_function.yml
test/fixtures/dialects/tsql/declare_with_following_statements.yml
test/fixtures/dialects/tsql/function_with_variable.yml
test/fixtures/dialects/tsql/hints.yml
test/fixtures/dialects/tsql/merge.yml
test/fixtures/dialects/tsql/set_statements.sql
test/fixtures/dialects/tsql/set_statements.yml
test/fixtures/dialects/tsql/stored_procedure_begin_end.yml
test/fixtures/dialects/tsql/system-variables.yml
test/fixtures/dialects/tsql/triggers.yml
test/fixtures/dialects/tsql/update.sql
test/fixtures/dialects/tsql/update.yml

Fixes #2008 
Add support for assignments operators such as +=
The change restricts the accepted grammar as other SET expression do not allow = in T-SQL.
It does not cover all the cases of the SET @local_variable syntax.
- Other.

T-SQL: add support for assignment operators

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/go_delimiters.sql
test/fixtures/dialects/tsql/go_delimiters.yml

T-SQL files may start with a leading GO
- Other.

TSQL: allow leading GO

---

test/fixtures/dialects/sparksql/delta_write_table.sql
test/fixtures/dialects/sparksql/delta_write_table.yml

Additional test cases for SparkSQL
- Other.

SparkSQL: Test cases for Delta Variation of Writing a table

---

.github/workflows/ci-tests.yml
.github/workflows/critical-rules-test.yml

When GitHub Actions or Coverage experiences issues (as they are want to do!) we sometimes have to rerun the CI jobs. The Critical Rules Test is slow to run, but doesn't impact Coverage, so separate that out to it's own job so it doesn't need to be rerun if it passes.
Nope.
- Other.

Separate slow CI job to it's own workflow

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/create_table_column_options.sql
test/fixtures/dialects/bigquery/create_table_column_options.yml

Adds the possibility for SQLFluff to parse `STRUCT` definitions that utilises "column" `OPTIONS`.
```sql
CREATE TABLE t_table1
(
x STRUCT<
col1 STRING OPTIONS(description="An INTEGER field in a STRUCT")
>,
y ARRAY<STRUCT<
col1 STRING OPTIONS(description="An INTEGER field in a REPEATED STRUCT")
>>
);
``` 
No
- Other.
- Created GitHub issues for any relevant followup/future enhancements …

BigQuery: Add support for column `OPTIONS` in `STRUCT` definitions

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/create_table_trailing_comma.sql
test/fixtures/dialects/bigquery/create_table_trailing_comma.yml

BigQuery: Parse `CREATE TABLE` with trailing comma

---

src/sqlfluff/dialects/dialect_sparksql.py
test/fixtures/dialects/sparksql/create_table_complex_datatypes.sql
test/fixtures/dialects/sparksql/create_table_complex_datatypes.yml

Sparksql quoted identifier in STRUCT

---

src/sqlfluff/core/parser/segments/base.py
test/fixtures/rules/std_rule_cases/L030.yml

Fixes #3022 
I think I introduced this bug when fixing an earlier issue adding missing newlines to the end of a file (PR #2862). In that PR, I updated `BaseSegment.iter_patches()` to return an `EnrichedFixPatch`, which specifies the location of the change in both source and templated space. The bug was, if the modified segment is a mix of templated and literal code, the source slice was incorrect. which caused code **replacement** (delete + insert) to be misapplied as just an insertion, i.e. leaving the old, bad code in place, followed by the new, corrected code.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` …

Fix bug in patch generation for segments made of templated + literal fixes

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_alter_role.sql
test/fixtures/dialects/postgres/postgres_alter_role.yml
test/fixtures/dialects/redshift/redshift_alter_user.yml

Creates new class that provides support for both ALTER ROLE and ALTER USER statements following spec in postgres docs.
New functionality so shouldn't affect existing behavior.
New supporting test cases and fixtures added
fixes #3042

Postgres add `ALTER ROLE`/`ALTER USER` support

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_exasol.py
src/sqlfluff/dialects/dialect_redshift.py
src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/ansi/create_user.sql
test/fixtures/dialects/ansi/create_user.yml
test/fixtures/dialects/exasol/AlterRole.yml
test/fixtures/dialects/exasol/AlterUser.yml
test/fixtures/dialects/exasol/CreateRole.yml
test/fixtures/dialects/exasol/CreateUser.yml
test/fixtures/dialects/postgres/postgres_create_role.yml
test/fixtures/dialects/redshift/redshift_alter_user.yml
test/fixtures/dialects/redshift/redshift_create_user.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_abort_query.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_delegate_auth.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_delegate_auth_role.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_remove_delegate_auth.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_rename.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_reset_password.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_set_values.yml
test/fixtures/dialects/snowflake/snowflake_alter_user_unset_values.yml

Noticed while reviewing #3043 that these statements were inconsistent with other dialects.
Shouldn't be
- Other.

Exasol: `CREATE/DROP/ALTER USER/ROLE` clean up for consistency

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/rules/std_rule_cases/L025.yml

Postgres: Fix `UNNEST` for L025

---

docs/source/configuration.rst

There is an typo in `.sqlfluff` configuration example:
```ini
sql_file_exts = ".sql,.sql.j2...."
```
this leads to incorrectly interpret of extensions filter -> files are not picking at all

Fixed documentation for `sql_file_exts` example

---

src/sqlfluff/rules/L003.py

On each new line, L003 is rescanning the **entire** file from the beginning to the current line. This results in O(n^2) performance, i.e. really slow on large files. This small change caches the current line number and segment index (within `raw_stack`). I confirmed using `line_profiler` that this eliminates a lot of processing on a large file.
- Other. …

Rule L003 performance: Cache the line number and last newline position

---

src/sqlfluff/rules/L028.py
test/fixtures/rules/std_rule_cases/L028.yml

Fixes #3053 
This allows aliases throughout the query, including in places they maybe shouldn't be allowed like the `WHERE` clause. Some dilalects used to allow this only for those dialects, but forbid it from others. Now we're generalising this, that restriction is no longer in places for the others. I think that's fine though, and the intention of L028 is not to catch this type of syntax error. We can make another rule to check for that if we really want it. …

Allow aliases to pass L028

---

src/sqlfluff/core/templaters/slicers/tracer.py
test/core/templaters/jinja_test.py

Fixes #3049 
Updates JinjaAnalyzer to use Jinja's own parser to understand `{% set %}` commands
- Other.

Fix bug handling Jinja set with multiple vars, e.g.: {% set a, b = 1, 2 %}

---

src/sqlfluff/dialects/dialect_sparksql.py
test/fixtures/dialects/sparksql/delta_update_table.sql
test/fixtures/dialects/sparksql/delta_update_table.yml

- redefine `UpdateStatementSegment` from ANSI dialect
- added test cases for `UPDATE` syntax
N/A
- Other.

SparkSQL: Support for Delta `UPDATE` statement syntax

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_hive.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/postgres/postgres_create_extension.sql
test/fixtures/dialects/postgres/postgres_create_extension.yml

Fixes #3081
I moved the `CREATE EXTENSION` from ANSI to Postgres, as seems to be Postgres specific.
Also dropped it from TSQL as wasn't needed there.
- Other.

Postgres: Support `DROP EXTENSION`

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_mysql.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/ansi/create_function.sql
test/fixtures/dialects/ansi/create_function.yml
test/fixtures/dialects/bigquery/create_function_no_args.sql
test/fixtures/dialects/bigquery/create_function_no_args.yml
test/fixtures/dialects/mysql/drop_function.yml

Fixes #3078
I added this to ANSI (the `CREATE FUNCTION` was already in there), meaning could remove some off the inserts in other dialects (I left the class in those dialects as mostly different to ANSI).
Also fixed a typo in MySQL implementation.
- Other.

ANSI (and other dialects): Add `DROP FUNCTION` support

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_select.sql
test/fixtures/dialects/postgres/postgres_select.yml

Postgres: Support `COLLATE` in more clauses

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/rules/std_rule_cases/L003.yml

ANSI: Allow `indented_using_on` in `MERGE` statements `ON`

---

src/sqlfluff/core/rules/base.py
src/sqlfluff/core/templaters/base.py
src/sqlfluff/core/templaters/slicers/tracer.py
test/fixtures/rules/std_rule_cases/L052.yml

Fixes #3079
A `LintResult` whose fixes span multiple template blocks (where a "block" is where a Jinja `if` or `for` starts or ends) should be discarded. That's because one slice may be executed separately from the other at template rendering time, so a fix touching both may corrupt the code.
This new check is similar in spirit to an older one I removed a few months ago. The old one prevented a fix from touching 3 or more slices. It was more of a "rule of thumb", and there were no tests for it. This check, while similar, is more formal, and I've added a test for it.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` …

Don't allow fixes to span template blocks

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/ansi/select_f.yml
test/fixtures/dialects/ansi/select_numeric_literal_exponential_format.yml
test/fixtures/dialects/ansi/select_simple_i.yml
test/fixtures/dialects/bigquery/select_interval_expression.yml
test/fixtures/dialects/bigquery/select_safe_function.yml
test/fixtures/dialects/exasol/SelectStatement.yml
test/fixtures/dialects/mysql/interval.yml
test/fixtures/dialects/mysql/values_statement.yml
test/fixtures/dialects/postgres/postgres_array.yml
test/fixtures/dialects/postgres/postgres_select.yml
test/fixtures/dialects/snowflake/snowflake_changes_clause.yml
test/fixtures/dialects/snowflake/snowflake_create_stream.yml
test/fixtures/dialects/snowflake/snowflake_datetime_intervals.yml
test/fixtures/dialects/sparksql/numeric_literal.yml
test/fixtures/dialects/sparksql/select_cluster_by.yml
test/fixtures/dialects/sparksql/select_distribute_by.yml
test/fixtures/dialects/sparksql/select_sort_by.yml
test/fixtures/dialects/teradata/select_stmt.yml
test/fixtures/dialects/tsql/create_table_constraints.yml
test/fixtures/dialects/tsql/functions_a.yml
test/fixtures/dialects/tsql/raiserror.yml
test/fixtures/dialects/tsql/select_date_functions.yml

As identified while reviewing #3102 , the current definition of signed literals could be improved upon by using `PositiveSegment` and `NegativeSegment` instead of `PlusSegment` and `MinusSegment` (which are `binary_operators`).
This would prevent rules flagging incorrectly. Currently we get away with it as the rules check for three segments, but that might not always be the same.
I've also set up a `SignedSegmentGrammar` for ease of use elsewhere.
Nope. …

Improved signed literal parsing

---

src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/cli/outputstream.py
test/cli/commands_test.py
test/core/linter_test.py

Fixes #3080 
The `sqlfluff lint` command was not writing any output to the output file if `--write-output` was used with the default output format (human format). This PR refactors output formatting from output **destination** by creating a new base class for output, `OutputStream`.
It's a bigger PR than I expected, but I felt like there was some tech debt in this area that was worth addressing -- the combination of output formats, output locations, and the existence of the progress bar had created a "house of cards": broken, hard to understand because it coupled output format & location. It was going to be hard  to fix without addressing this.
This PR involves fairly low-level changes to how command-line output is written and interleaved with tqdm (progress bar) output. It's possible it …

Bug fix: Handle "lint" human-format file output correctly

---

src/sqlfluff/rules/L058.py
test/fixtures/rules/std_rule_cases/L058.yml

Fixes #3110
Changes L058 to verify there's no other code alongside the nested `CASE`.
- Other.

Bug: L058 (flatten nested `CASE`) triggers incorrectly (the `ELSE` contains additional code)

---

src/sqlfluff/core/linter/linted_file.py
test/cli/commands_test.py
test/core/linter_test.py

Previously, file permissions were being modified by `sqlfluff fix`. This was a side effect of using `NamedTemporaryFile`, which was setting the file to be readable only by the current user. This change grabs the permissions of the original input file and reapplies them to the output file.
- Other.

When fixing a file, preserve the input file's permissions

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/postgres/postgres_cte_in_materialized_view.sql
test/fixtures/dialects/postgres/postgres_cte_in_materialized_view.yml

Extra WITH statements could be associated with the compound statement.
Fixed by replacing match_grammar StartsWith and parse_grammar optional
Sequnce with a match_grammar Sequence.
Fixes #3092 
None
- Other.

Fix parsing of Compound Statements

---

src/sqlfluff/dialects/dialect_snowflake.py
test/core/rules/config_test.py

StartsWith() is not performant (to be addressed). For now, I've removed this from FromExpressionElementSegment(). This has parity with ANSI, and caused no errors or changes in our suite of Snowflake dialect tests
Fixes #3127
No
- Other.

Snowflake: `StartsWith()` in `FromExpressionElementSegment` caused performance issues for large queries

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/transaction.sql
test/fixtures/dialects/tsql/transaction.yml

This adds support for specifying a transaction for `save`, `rollback`, `commit` and `begin` (cf https://docs.microsoft.com/en-us/sql/t-sql/language-elements/begin-transaction-transact-sql?view=sql-server-ver15)
fixes #3122
- Other.

TSQL: Support names for transactions

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/alter_table.sql
test/fixtures/dialects/tsql/alter_table.yml

TSQL - ALTER TABLE statements - adds support for:
- WITH CHECK ADD CONSTRAINT
- CHECK CONSTRAINT
Added corresponding tests.
Fixes #3131 
No
- Other.

T-SQL - `ALTER TABLE` - add support for `WITH CHECK ADD CONSTRAINT` and `CHECK CONSTRAINT`

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/ansi/insert_a.sql
test/fixtures/dialects/ansi/insert_a.yml
test/fixtures/dialects/bigquery/insert.sql
test/fixtures/dialects/bigquery/insert.yml

As discussed on Slack
I haven't fixed ALL dialects as some have quite complex `INSERT INTO` grammar.
The original issue was raised for BigQuery.
- Other.

Allow column-less `INSERT INTO` with bracketed `SELECT` in ANSI and BigQuery

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/cast_variable.sql
test/fixtures/dialects/tsql/cast_variable.yml

Support `nvarchar(max)` and similar phrasings.
fixes #2710, #3116
- Other.

T-SQL: Support `NVARCHAR(MAX)`

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_col_position.yml
test/fixtures/dialects/snowflake/snowflake_select_values.sql
test/fixtures/dialects/snowflake/snowflake_select_values.yml
test/fixtures/dialects/snowflake/snowflake_within_group.yml

Snowflake: allow bracketless `VALUES` in `FROM` clauses

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/quoted_literal.sql
test/fixtures/dialects/hive/quoted_literal.yml

fixes #3138
Support back quoted identifier and literal in hive dialect 
None
- Other.

Hive: Support back quoted identifier and literal

---

CHANGELOG.md

Just realised I never hit save and so didn't commit this change in the last release. The [0.13.0 Release](https://github.com/sqlfluff/sqlfluff/releases/tag/0.13.0) has this change as took it from my local copy, but should update CHANGELOG to be aligned.
Nope
- Other.

Missed #3151 from CHANGELOG

---

src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/cursor.sql
test/fixtures/dialects/tsql/cursor.yml

Adds support for `OPEN`, `CLOSE`, `DEALLOCATE` and `FETCH` cursors
Fixes #2696
No
- Other.

TSQL: Support opening, closing, deallocating and fetching cursors

---

src/sqlfluff/cli/formatters.py
src/sqlfluff/core/errors.py
src/sqlfluff/core/templaters/jinja.py
src/sqlfluff/core/templaters/slicers/tracer.py

In large outputs PRS errors are almost impossible to see with the human eye. In addition they tend to be the only thing you care about if they exist. This PR just changes the color printed to be RED if the violation is a PRS error
No Side Effects

Highlight `PRS` errors in red

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

Fix bug where "encoding" setting in .sqlfluff file was not being respected

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_remove.sql
test/fixtures/dialects/snowflake/snowflake_remove.yml

Resolves https://github.com/sqlfluff/sqlfluff/issues/3183.
Added support for variables in remove statements [Snowflake].
Not that I'm aware of.
- Other.

Snowflake remove statement enhancement

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_materialized_view.sql
test/fixtures/dialects/snowflake/snowflake_alter_materialized_view.yml

Resolves https://github.com/sqlfluff/sqlfluff/issues/3201
Adds alter materialized view statement for Snowflake dialect.
None that I'm aware of.
- Other.

Snowflake: `ALTER MATERIALIZED VIEW` statement

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py
test/fixtures/cli/fix_even_unparsable.sql

Fix bug where the `fix_even_unparsable` setting was not being respected in `.sqlfluff`

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/xml.yml

This fixes wrong parsing of `for xml path ('something')` statements in T-SQL.
Fixes #3219
No
- Other.

TSQL: Fix `for xml path` identifier

---

src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/rules/L036.py
test/fixtures/linter/autofix/snowflake/003_previously_parse_tree_damaging/after.sql

About a month ago, I reworked the core linter to re-parse areas of the tree affected by fixes. This detects misbehaving rules so they can be fixed. One downside is that there's one kind of parse error that can be difficult to avoid: Generally, a segment's first and last children must be code or meta (for example, whitespace is not allowed).
This PR changes `BaseSegment.apply_fixes()` to automatically detect and fix these issues. It's a pretty simple and safe change, and I think it'll save future debugging and frustration for rule developers.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be …

Enhance `apply_fixes()` to automatically fix violations of `can_start_end_non_code`

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/rules/std_rule_cases/L003.yml

Procedure parameters are now indented, like function parameters.
Fixes #3200
- Other.

Indent procedure parameters

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/execute.sql
test/fixtures/dialects/tsql/execute.yml

Allow optional brackets around variables with EXECUTE statements.
- [x ] Please confirm you have completed any of the necessary steps below.
- `[x] .sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
- Other.

T-SQL: Allow optional brakets with EXECUTE

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_alter_domain.sql
test/fixtures/dialects/postgres/postgres_alter_domain.yml
test/fixtures/dialects/postgres/postgres_create_domain.sql
test/fixtures/dialects/postgres/postgres_create_domain.yml
test/fixtures/dialects/postgres/postgres_drop_domain.sql
test/fixtures/dialects/postgres/postgres_drop_domain.yml

Fixes #3256 
Only added test cases in docs in case I got any wrong, but these are not comprehensive.
Also cleaned a pointless `match_grammar` in the DropTrigger statement that I noticed at same time.
- Other.

Postgres: Add `DOMAIN` support

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_sparksql.py

A `match_grammar` which matches `Anything()` followed by a `parse_grammar` which does not, is pointless. Let's tidy them up.
Worse still it can lead to errors if only the `match_grammar` is overridden in another dialect and the `parse_grammar` is still inherited.
I don't think there's an easy test to add for this since sometimes there are legitimate uses cases for `Anything()` in `match_grammar` - just not these.
- Other.
- Added …

Remove redundant `Anything()` from `match_grammars`

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/bigquery/merge_into.sql
test/fixtures/dialects/bigquery/merge_into.yml

Allow optional `AS` in `MERGE` statements using `SELECT`

---

src/sqlfluff/rules/L046.py
test/fixtures/rules/std_rule_cases/L046.yml

L046 (spaces around Jinja tags) should check all slices in a segment

---

src/sqlfluff/rules/L028.py
test/fixtures/rules/std_rule_cases/L028.yml

L028: In tsql dialect, table variables cannot be used to qualify references

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_copy_into_table.yml
test/fixtures/dialects/snowflake/snowflake_create_stage.sql
test/fixtures/dialects/snowflake/snowflake_create_stage.yml

The following should parse:
```
CREATE OR REPLACE STAGE foo.bar
URL = 's3://foobar'
STORAGE_INTEGRATION = foo
FILE_FORMAT = foo.bar.baz
;
```
`FILE_FORMAT` can be object (e.g. `database.schema.object`) but at the moment can only handle naked identifiers (fails to parse the `.`s in the above).
---
Enhanced the `FileFormatSegment` class in Snowflake to handle objects.
None that I'm aware of.
- Other.
- Added appropriate documentation …

Snowflake: CREATE STAGE grammar enhancement for file formats

---

src/sqlfluff/core/rules/analysis/select.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/create_view_with_pivot.yml
test/fixtures/dialects/tsql/create_view_with_unpivot.yml
test/fixtures/dialects/tsql/select_pivot.sql
test/fixtures/dialects/tsql/select_pivot.yml

Fixes #2890 
TSQL allows for PIVOTs/UNPIVOTs to be interspersed with JOINs within a FROM clause, but the SQLFluff TSQL dialect only allows PIVOTs/UNPIVOTs as terminators to a FROM clause.  This code change will bring SQLFluff TSQL into harmony with TSQL.
As part of this change it is possible for from_pivot_expression segments to be grandchildren of a from_clause segment instead of direct children.  This PR updates the _get_pivot_table_columns function within select.py to handle this scenario.
This PR adds a no cover hint to select.py on a return call that flags as uncovered as a result of this change.  This mimics the return call immediately above it.

T-SQL: Fix `PIVOT` placement

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_external_table.sql
test/fixtures/dialects/snowflake/snowflake_alter_external_table.yml

Adds support for ALTER EXTERNAL TABLE in Snowflake.
https://docs.snowflake.com/en/sql-reference/sql/alter-external-table.html
None that I'm aware of!
- Other.

Snowflake: Support `ALTER EXTERNAL TABLE`

---

.github/workflows/check-yaml-files-generation.yml
.github/workflows/ci-tests.yml
.github/workflows/critical-rules-test.yml
.github/workflows/publish-dbt-templater-release-to-pypi.yaml
.github/workflows/publish-sqlfluff-release-to-pypi.yaml

Bumps GitHub Actions to their latest major versions. Main change is they're now using Node 16 instead of 12 internally, which was EOL at end of April.
- Changelog for `actions/checkout` can be [found here](https://github.com/actions/checkout/blob/main/CHANGELOG.md)
- Releases for `actions/setup-python` can be [found here](https://github.com/actions/setup-python/releases)
N/A
- Other. …

ci: bump github actions

---

src/sqlfluff/dialects/dialect_soql.py
test/dialects/soql_test.py

SOQL: Disallow non-`SELECT` statements

---

src/sqlfluff/core/parser/segments/base.py
test/fixtures/rules/std_rule_cases/L003.yml

Fixes #3303. These kinds of issues were supposed to be addressed by PR #3232 (aka the 🍺 🍻 review PR 😉 ), which was first included in 0.13.1. There was a slight bug in that logic which prevented it from always completing its job.
It should be pretty safe. This code is only activated when it detects an impending post-fix parse issue, and this is just a minor tweak to the existing code.
- Other. …

Fix critical parse error logged after L003 fix

---

src/sqlfluff/rules/L026.py
test/dialects/soql_test.py
test/fixtures/rules/std_rule_cases/L026.yml

Closes https://github.com/sqlfluff/sqlfluff/issues/3322
No
- Other.

SOQL: Disable L026 rule

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_create_function.sql
test/fixtures/dialects/postgres/postgres_create_function.yml

Postgres: correct `RETURNS TABLE` column type

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/postgres/postgres_create_index.sql
test/fixtures/dialects/postgres/postgres_create_index.yml

Closes https://github.com/sqlfluff/sqlfluff/issues/3368
Maybe it should be Postgres-only instead.
- Other.

Postgres: Parse index with column sort

---

src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_alter_table.sql
test/fixtures/dialects/redshift/redshift_alter_table.yml

Fixes #3391 
Also fixed some PrimaryKeyGrammar references
- Other.

Redshift: Correct `ALTER TABLE` syntax

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_create_function.sql
test/fixtures/dialects/postgres/postgres_create_function.yml

Fixes #3400 
Shouldn't be
- Other.

Postgres: Allow `CREATE FUNCTION` to use Expressions in default values

---

docs/source/configuration.rst
src/sqlfluff/core/templaters/placeholder.py
test/core/templaters/placeholder_test.py

* Per [the SQLFluff documentation](https://docs.sqlfluff.com/en/stable/configuration.html#placeholder-templating) the `dollar` templater may not include surrounding curly braces `{ }`, while the `numeric_dollar` templater may:
```sql
-- dollar
WHERE bla = $my_name
-- numeric_dollar
WHERE bla = $3 or WHERE bla = ${3}
```
However, the documentation is not accurate here, as it's actually the other way around: the `dollar` templater may include curly braces, while the `numeric_dollar` templater does not support them.
This PR does the following:
* updates the example of the `dollar` templater in the docs to show usage with curly braces
* updates the `numeric_dollar` templater to allow optional surrounding curly braces
- Included test cases to demonstrate any code changes, which may be one or …

Allow `numeric_dollar` templater to have curly braces, update `dollar` + `numeric_dollar` templater examples in docs

---

src/sqlfluff/rules/L027.py
test/fixtures/rules/std_rule_cases/L027.yml
test/rules/std_test.py

Fixes #3055, #3380, #3342
This PR reverts PR #2998, which introduced a lot of false positives in L027. This means #2992 could be reopened. We can revisit that enhancement if/when there's an implementation that avoids these issues. @dmohns 
It also adds test cases for the 3 user issues reported in relation to this new behavior.
- Other. …

L027: Fix false positives by reverting the PR for issue #2992: Check table aliases exist

---

src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_sparksql_keywords.py
test/core/rules/config_test.py
test/fixtures/dialects/sparksql/delta_vacuum.sql
test/fixtures/dialects/sparksql/delta_vacuum.yml

Implement `VacuumStatementSegment` and required keywordSegments to support Delta Lake's `VACUUM` statement and add test cases for the same.
N/A
- Other.

SparkSQL: Add support for Delta `VACUUM` statement

---

src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_sparksql_keywords.py
test/fixtures/dialects/sparksql/delta_describe_history.sql
test/fixtures/dialects/sparksql/delta_describe_history.yml

Adds `DescribeHistoryStatementSegment` and test cases in `DescribeHistoryStatementSegment`
- purposefully separated from `DescribeStatementSegment` since it's not a native spark command.
- Other.

SparkSQL: Add Delta Syntax for `DESCRIBE HISTORY` statement

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_insert.sql
test/fixtures/dialects/postgres/postgres_insert.yml
test/fixtures/dialects/postgres/postgres_select.sql
test/fixtures/dialects/postgres/postgres_select.yml

Fixes #3365 
I'm hoping not!
- Other.

Postgres: Optional select clause elements and better `ON CONFLICT` support

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_create_domain.sql
test/fixtures/dialects/postgres/postgres_create_domain.yml

Postgres: Support multiple `CONSTRAINTS` in `CREATE DOMAIN`

---

src/sqlfluff/core/rules/analysis/select.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/rules/std_rule_cases/L025.yml

Fixes #3462 
I uppercased value table values in common with other syntax
- Other.

Postgres: treat `GENERATE_SERIES` as a value table function

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py

While testing 1.0.0 I found this quality of life bug.
While using the dbt templater, if you're not careful with the path specification you could accidentally specify files explicitly in your dependencies which aren't actually rendered (as I found out in https://github.com/brooklyn-data/dbt_artifacts/issues/125). I don't think it's a _bug_ but it does currently result in a fatal `RuntimeError` if sqlfluff tries to lint a file which isn't found.
I think this is the wrong behaviour and while we should still warn the user, the linting of the rest of the project should continue. Hence changing the error to `SQLTemplaterSkipFile` instead of `RuntimeError`.

Swap to skip file if not found

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L062.py
test/fixtures/rules/std_rule_cases/L062.yml

Adds the ability to use `blocked_regex` as well as `blocked_words` for rule L062 to allow blocking certain bits of SQL (e.g. old schema's that should not be used).
Nope
- Other.

L062: add `blocked_regex` support

---

docs/source/indentation.rst
src/sqlfluff/core/default_config.cfg
src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/rules/std_rule_cases/L003.yml

fixes #3469
See [discussion in slack](https://sqlfluff.slack.com/archives/C01GX4L213J/p1654102498025949)
- Adds another config option for whether to indent the contents of an ON statement.
- Add tests for this rule
- Other.

Add config for optionally indenting contents of `ON` blocks

---

src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_sparksql_keywords.py
test/fixtures/dialects/sparksql/delta_generate_manifest.sql
test/fixtures/dialects/sparksql/delta_generate_manifest.yml

Created `GenerateManifestFilesStatementSegment`, updated `UNRESERVED_KEYWORDS` to include 'symlink_format_manifest' and added test cases
N/A
- Other.

SparkSQL: Support for Delta syntax to create manifest files through the `GENERATE` command

---

src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_sparksql_keywords.py
test/fixtures/dialects/sparksql/delta_convert_to.sql
test/fixtures/dialects/sparksql/delta_convert_to.yml

- update `PartitionSpecGrammar` to allow `ColumnDefinitionSegment` as a valid segment
- add `ICEBERG` non-reserved keyword
- add `ConvertToDeltaStatementSegment` class
- test cases 
N/A
- Other.

SparkSQL: Support for `CONVERT TO DELTA` command

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/rules/L022.py
test/fixtures/dialects/ansi/select_with_recursive.yml
test/fixtures/dialects/sparksql/common_table_expressions.yml
test/fixtures/dialects/tsql/create_view_with_cte.yml
test/fixtures/dialects/tsql/cte_s.yml
test/fixtures/dialects/tsql/hints.yml
test/fixtures/rules/std_rule_cases/L022.yml

Fixes #3474
Changes the parse structure for CTEs with column lists (unusual within the SQLFluff test cases).
- Other.

Fix L022 false positive when the CTE definition has a column list

---

src/sqlfluff/core/linter/linted_file.py
test/fixtures/rules/std_rule_cases/L001.yml

Allow linter to apply fixes spanning more than 2 slices

---

src/sqlfluff/core/templaters/jinja.py
test/core/templaters/jinja_test.py
test/fixtures/templater/jinja_q_multiple_path_macros/.sqlfluff
test/fixtures/templater/jinja_q_multiple_path_macros/even_more_macros/ultimate_foo.sql
test/fixtures/templater/jinja_q_multiple_path_macros/jinja.sql
test/fixtures/templater/jinja_q_multiple_path_macros/jinja.yml
test/fixtures/templater/jinja_q_multiple_path_macros/macros/foo.sql
test/fixtures/templater/jinja_q_multiple_path_macros/more_macros/other_foo.sql

The definition of `macro_ctx` inside the `for` loop basically kills the feature of "comma-separated list of `.sql` or folders" (see [docs](https://docs.sqlfluff.com/en/stable/configuration.html))
If a folder has multiple entries, only the last one will prevail because the `macro_ctx = {}` is being executed on each iteration.
Also, the `return` value of the function is a variable defined in an inner scope!
Since the _extraction_ of macros is accumulative (updating the same dictionary) I suggest updating the docs to explicitly say the last path takes precedence.
⚠️ Not sure how to test this. I couldn't find any test related to the code that I'm changing.
Should I create a bunch of directories with files defining dummy macros and prove it works?
- Included test cases to demonstrate any code …

Fix `load_macros_from_path` to actually support multiple paths

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_alter_table.sql
test/fixtures/dialects/redshift/redshift_alter_table.yml

Added support for default expression in Redshift alter table add column statements. 
Per [the AWS documentation](https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html) this is supported:
```
ALTER TABLE table_name 
{
ADD table_constraint 
| DROP CONSTRAINT constraint_name [ RESTRICT | CASCADE ] 
| OWNER TO new_owner 
| RENAME TO new_name 
| RENAME COLUMN column_name TO new_name            
| ALTER COLUMN column_name TYPE new_data_type
| ALTER COLUMN column_name ENCODE new_encode_type     
| ALTER COLUMN column_name ENCODE encode_type, 
| ALTER COLUMN column_name ENCODE encode_type, .....;      
| ALTER DISTKEY column_name 
| ALTER DISTSTYLE ALL       
| ALTER DISTSTYLE EVEN
| ALTER DISTSTYLE KEY DISTKEY column_name 
| ALTER DISTSTYLE AUTO             
| ALTER [COMPOUND] …
```

Allow `DEFAULT` expression in Redshift `ALTER TABLE ADD COLUMN` statements

---

src/sqlfluff/rules/L059.py
test/fixtures/rules/std_rule_cases/L059.yml

Disable L059 by default for Postgres

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_call.sql
test/fixtures/dialects/redshift/redshift_call.yml

Redshift: `CALL` statement

---

src/sqlfluff/rules/L025.py
test/fixtures/rules/std_rule_cases/L025.yml

Fixes #3522 
For context, see recent, related PR #3358.
- Other.

Fix L025 false positive for tsql VALUES clause

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/functions_a.yml
test/fixtures/dialects/tsql/insert_statement.yml
test/fixtures/dialects/tsql/select.yml
test/fixtures/dialects/tsql/stored_procedure_single_statement.yml
test/fixtures/rules/std_rule_cases/L010.yml

Fixes #3520 
Nope, this corrects behaviour to be more consistent
- Other.

T-SQL keyword functions should be treated as keywords

---

src/sqlfluff/rules/L025.py
test/fixtures/rules/std_rule_cases/L025.yml

L025 should not remove aliases from derived queries

---

src/sqlfluff/rules/L025.py
test/fixtures/rules/std_rule_cases/L025.yml

Fixes #3547 
This is a one-line change to yesterday's PR (#3546)
- Other.

L025: Derived query requires alias -- also handle UNION, etc.

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_comment_on.yml
test/fixtures/rules/std_rule_cases/L016.yml

L016: ignore_comment_clauses not working for postgres dialect

---

tox.ini

fixes #3563 
Because of the .coverage.py file, the linting raised this kind of error:
```
ValueError: source code string cannot contain null bytes
ERROR: InvocationError for command /home/zidder/pythonTricks/sqlfluff/.tox/linting/bin/flake8 (exited with code 1)
```
Now this error is gone, because the `.coverage.py` is not linted anymore.
- Other. …

Exclude .coverage.py from linting

---

src/sqlfluff/core/linter/linted_file.py
src/sqlfluff/core/parser/segments/base.py

This is in preparation for allowing source fixes. Lots of deletions 🚀 
Two main changes I'm making here:
1. We used to have `FixPatch` (which only had templated position) and `EnrichedFixPatch` (which had templated and source position). I've combined these into one class because I think we can always go straight to creating the latter. Perhaps confusingly, I've renamed the latter to the former, so now we just have `FixPatch`, but it also has templated position. This involved pushing a little logic upstream but not much.
2. In `.fix_string()` there were a few `if` statements for conditions that haven't been covered with tests and I've tried quite hard to trigger them. I'm relatively sure that the new template tracing logic means that our positioning is now good enough that we don't need …

Simplify lint fixing (prep for source fixes)

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_delete.yml
test/fixtures/dialects/postgres/postgres_values_in_subquery.yml
test/fixtures/dialects/postgres/postgres_with.yml
test/fixtures/rules/std_rule_cases/L022.yml

This fixes #3569 where rule L022 wants to put a new line after the closing parenthesis of the CTE argument list. It seems like the postgres dialect needed to be updated to match the ansi one as part of #3490 .
Not to my knowledge.
- Other.

Fix incorrect L022 with postgres dialect with CTE argument list

---

src/sqlfluff/rules/L013.py
test/fixtures/rules/std_rule_cases/L013.yml

In cases where the CTE has a column list, we don't need an alias for columns. This checks if the select has a `common_table_expression` parent and if that parent has a `cte_column_list` child. In that case, it doesn't complain about a missing alias.
Fixes #3558
I'm not 100% positive that this won't lead to false negatives in some weirdly nested situation. Open to feedback there.
Also, I'm not sure if this rule should be checking if the number of items in the `cte_column_list` matches the number of selects. It seems like that is out of scope for this rule (since it probably means that you have a syntax error), but I could be wrong. …

Allow no alias for selects in CTEs with a column list

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/select_top.sql
test/fixtures/dialects/redshift/select_top.yml

Adds grammar support for `SELECT TOP N` to redshift dialect. See the [redshift select syntax](https://docs.aws.amazon.com/redshift/latest/dg/r_SELECT_synopsis.html#r_SELECT_synopsis-synopsis) and [top-specific examples](https://docs.aws.amazon.com/redshift/latest/dg/r_Examples_with_TOP.html).
Fixes #3531
- Other. …

Redshift: Add `TOP X` to select clause modifiers

---

docs/source/teamrollout.rst

Was reading through [docs](https://docs.sqlfluff.com/en/stable/teamrollout.html) and came across a couple of changes to be made in the grammar.  This just looks at that one file.
Shouldn't be any code impacts since I'm just touching the docs
- [na] Please confirm you have completed any of the necessary steps below.
- Other. …

Small grammar cleanup in team rollout docs

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/create_js_function_complex_types.yml
test/fixtures/dialects/bigquery/create_js_function_options_library_array.yml
test/fixtures/dialects/bigquery/create_js_function_quoted_name.yml
test/fixtures/dialects/bigquery/create_js_function_underscore_name.yml
test/fixtures/dialects/bigquery/create_table_column_options.yml
test/fixtures/dialects/bigquery/declare_variable.yml
test/fixtures/dialects/bigquery/select_struct.yml

Was initially part of #3428 but to required as part of new fix #3590.
I think this still makes sense - the other Struct-like things (e.g. `TypelessStructSegment`) are segments and `StructTypeGrammar` was the odd one out. This swaps `StructTypeGrammar` to instead be `StructTypeSegment`.
This also removes the unnecessary and unreferenced definition of `StructKeywordSegment`.

Struct type should be a segment

---

src/sqlfluff/dialects/dialect_oracle.py
test/fixtures/dialects/oracle/alter_table.sql
test/fixtures/dialects/oracle/alter_table.yml

Oracle: extend support for `ALTER TABLE`

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py

This is a draft PR to assist with debugging #3587.
We *may* actually want to consider this a permanent fixture (or a variation of it), to allow dbt projects to a) better understand failing files and b) still lint the rest of the project.
In short, if a `dbt_compiler.compile_node()` raises any exception - we skip the file and output to the user a stringified version of the dbt error _and a reference to the file which caused it_ for later debugging.

Add a skip and better logging for fatal dbt issues

---

docs/source/developingplugins.rst

Previously the documentation did not mention how the _pluggy_ library works. People not familiar with the library will face issues when running custom implemented rules.  Added the documentation that supports how to include custom rules in linting. 
Fixes  #1429
No. 
- Other.

Improve documentation for custom implemented rules

---

src/sqlfluff/dialects/dialect_redshift.py
src/sqlfluff/rules/L057.py
test/fixtures/dialects/redshift/redshift_temporary_tables.sql
test/fixtures/dialects/redshift/redshift_temporary_tables.yml
test/fixtures/rules/std_rule_cases/L057.yml

See [redshift docs](https://docs.aws.amazon.com/redshift/latest/dg/r_CREATE_TABLE_NEW.html) about these temporary table names. This adds the ability to parse them and makes sure that rule L057 doesn't complain about them.
Fixes #3612
It's possible that this will no longer cause parse errors for `#` randomly at the beginning of some other identifier.
- Other.
- Created GitHub issues …

Handle redshift temporary tables with # at the beginning of name

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_bigquery.py
src/sqlfluff/dialects/dialect_mysql.py
src/sqlfluff/dialects/dialect_postgres.py
src/sqlfluff/dialects/dialect_snowflake.py
src/sqlfluff/dialects/dialect_teradata.py
src/sqlfluff/dialects/dialect_tsql.py

This is a clearup job.
On the `Delimited` grammar, specifying a comma as the delimiter is unnecessary, it's the default. Removing explicit references to commas results in smaller codebase and also less repetition.

Specifying comma delimited is unnecessary

---

src/sqlfluff/cli/__init__.py
src/sqlfluff/cli/commands.py
src/sqlfluff/cli/formatters.py
src/sqlfluff/core/linter/linting_result.py
test/cli/commands_test.py
test/rules/std_roundtrip_test.py

This resolves #3550 .
- Return codes are defined centrally in constants.
- All places setting return codes refer to the constants, and updated to the new logic.
- Test cases don't use the constants (intentionally so that we actually test they're right).

Consistent return codes

---

src/sqlfluff/core/dialects/base.py
src/sqlfluff/core/parser/grammar/base.py
src/sqlfluff/core/parser/grammar/delimited.py
src/sqlfluff/dialects/dialect_redshift.py
src/sqlfluff/dialects/dialect_sparksql.py

If we attempt to redefine a dialect element identically, this will now throw an error. It's another development safety net to catch some examples I've already removed.
I've added it with `no cover` because dialects are now clean, but tested it by adding some redundant definitions in and checking they throw errors.

Add errors for redundant definitions.

---

src/sqlfluff/dialects/dialect_sparksql.py
test/fixtures/dialects/sparksql/parse_integer_type.sql
test/fixtures/dialects/sparksql/parse_integer_type.yml

Fix issue [#3554]( https://github.com/sqlfluff/sqlfluff/issues/3554 ) as sparksql also accept the the type `INTEGER`
No.
- Other.

Add "INTEGER" to PrimitiveTypeSegment for Sparksql

---

src/sqlfluff/core/default_config.cfg
src/sqlfluff/rules/L057.py
test/fixtures/rules/std_rule_cases/L057.yml

L057: In BigQuery, allow hyphens by default

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_array_unnest.sql
test/fixtures/dialects/redshift/redshift_array_unnest.yml

Redshift: support array unnesting with index syntax
```sql
SELECT index, value
FROM mytable m, m.superarray AS value AT index
```
- Other.

Redshift: syntax for array unnesting with index

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_cast_conversion.yml
test/fixtures/rules/std_rule_cases/L027.yml

Fixes issue #3651.
Previously, the first argument to the `convert` redshift function was interpreted as a column reference rather than a data type. This could cause rule L027 to fail since the data type wasn't qualified with a table name even though that doesn't make sense. This adds explicit handling for `convert` to eliminate that issue.
Not that I'm aware of.
- Other.
- Created …

Add handling for redshift convert function data type argument

---

src/sqlfluff/core/rules/analysis/select_crawler.py
src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/rules/L026.py
test/fixtures/rules/std_rule_cases/L026.yml

L026: Add support for `merge_statement`

---

src/sqlfluff/rules/L042.py
test/fixtures/rules/std_rule_cases/L042.yml

L042: Fix internal error "Attempted to make a parent marker from multiple files"

---

src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/parser/segments/meta.py
src/sqlfluff/core/parser/segments/raw.py

This partly sets some of the groundwork for more immutable segments in future, but really I think this solves the test fails I'm getting on #3658.
Replace `id()` matching with explicit `uuid` so that we can control where to match and where not.

Use UUIDs for matching

---

.github/workflows/add-issue-labels.yaml

Closes https://github.com/sqlfluff/sqlfluff/issues/3665
See the auto-labeled issues in my fork: https://github.com/greg-finley/sqlfluff/issues
No. Maybe it should search issue body also, but searching only the title seems to have less false positives.
- Other.

Set issue dialect labels via Github Actions

---

.github/ISSUE_TEMPLATE/enhancement.yml

Noticed a typo in the github template. This is a little fix to address that.

Fix typo in github issue template

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/create_view_with_columns.sql
test/fixtures/dialects/tsql/create_view_with_columns.yml

T-SQL: Fix parsing of CREATE VIEW statements with column name syntax

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/collate.sql
test/fixtures/dialects/tsql/collate.yml

T-SQL: Allow `COLLATE` clause in `JOIN` conditions

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/create_function.yml
test/fixtures/dialects/tsql/datepart.sql
test/fixtures/dialects/tsql/datepart.yml
test/fixtures/dialects/tsql/select_date_functions.yml

T-SQL: Parse `DATEPART` date type as date type instead of column name

---

src/sqlfluff/dialects/dialect_ansi.py
test/fixtures/dialects/ansi/escaped_quotes.sql
test/fixtures/dialects/ansi/escaped_quotes.yml

Allows escaping single quotes inside single-quoted literals with `''`.
This used to fail, but now it works:
```
$ echo "SELECT 'This doesn''t parse!' AS mycolumn" | sqlfluff lint --dialect ansi -
All Finished 📜 🎉!
```
Fixes #3675
No
- Other.

Allow escaping single quotes in single-quoted literal with ''

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
src/sqlfluff/dialects/dialect_tsql_keywords.py
test/fixtures/dialects/tsql/collate.sql
test/fixtures/dialects/tsql/collate.yml

The main branch of SQLFluff currently parses collation names appearing in `COLLATE` expressions as column identifiers. For example, the following SQL ...
```
SELECT table1.col COLLATE Latin1_General_CI_AS
FROM table1;
```
... generates the following errors with dialect `tsql`:
```
L:   1 | P:  27 | L014 | Unquoted identifiers must be consistently lower case.                                                                      
L:   1 | P:  27 | L028 | Unqualified reference 'Latin1_General_CI_AS' found in
| single table select.
L:   1 | P:  27 | L028 | Unqualified reference 'Latin1_General_CI_AS' found in
| single table select which is inconsistent with previous
| references.
```
Instead, we want to parse the collation as dedicated identifier `"collation"`. This PR causes the above SQL …

T-SQL: Properly parse collation names

---

src/sqlfluff/rules/L042.py
test/fixtures/rules/std_rule_cases/L042.yml

L042: Address corner cases where fix corrupts the SQL

---

src/sqlfluff/rules/L028.py
src/sqlfluff/rules/L032.py
test/core/templaters/jinja_test.py
test/fixtures/rules/std_rule_cases/L028.yml
test/fixtures/rules/std_rule_cases/L032.yml

Fixes an issue raised on Slack where rules L028 and L032 autofix copy table names from one place in the code to another without setting the `source` field on `LintFix`. If those table names were templated, the fix would "untemplate" them at the fix destination.
With this PR, those lint issues will still be flagged, but no automatic fix will be applied.
- Other.
- Created GitHub issues …

L028, L032: Fix bug where fixes were copying templated table names

---

test/cli/commands_test.py

Resolves #3702.
I'm testing the effects of this on the draft name deprecation PR.

Attempt to handle logging issues at teardown

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_array_unnest.sql
test/fixtures/dialects/redshift/redshift_array_unnest.yml

Redshift currently uses the Postgres syntax for accessing array elements, but this appears to not be wholly correct.
* Postgres supports (but Redshift does not) range expressions like `myarray[1:3]`
* Redshift supports (I'm not certain whether Postgres does) expressions in the array index:
```sql
SELECT
value_a,
t.array_b[idx] AS value_b,
t.array_c[MOD(idx, 2)] AS value_c
FROM mytable t, t.array_a AS value_a AT idx
```
This adds a dedicated `ArrayAccessorSegment` for Redshift and a corresponding test. …

Redshift: support expressions in array accessors

---

src/sqlfluff/dialects/dialect_bigquery.py

Bigquery doesn't use primary or foreign keys, this PR resets the grammar.
fixes #3696 
- [ x ] Please confirm you have completed any of the necessary steps below.
- Other.

Bigquery reset primary and foreign keys

---

src/sqlfluff/cli/commands.py
test/cli/commands_test.py

This adds short options for many cli commands. I'm having to type too much during testing 😄 .
- `-d` for dialect
- `-t` for templater
- `-r` for rules
- `-e` for excluding rules
- `-i` for ignoring
- `-x` for fixed suffix
I've updated some of the pre existing tests to cover these cases.

Add short versions of several cli options

---

src/sqlfluff/dialects/dialect_sqlite.py
test/fixtures/dialects/sqlite/insert.sql
test/fixtures/dialects/sqlite/insert.yml

Implementing most of the SQLite [INSERT](https://www.sqlite.org/lang_insert.html) statement parsing. This change aims to cover most common use cases at first.
For reference these parts are known to be missing:
* upsert & return clauses at the end of the statement
* the AS table alias (which is relevant for upsert only)
* the leading WITH ... case 
All of which could be part of future work.
Fixes #3733 
Not that I can think of.
- …

SQLite: add parsing of INSERT statement

---

src/sqlfluff/dialects/dialect_bigquery.py
test/fixtures/dialects/bigquery/declare_variable.sql
test/fixtures/dialects/bigquery/declare_variable.yml

Support parameterized data types (https://cloud.google.com/bigquery/docs/reference/standard-sql/data-types?hl=en#parameterized_data_types)
Fixes #3663
- Other.

BigQuery: Fix parsing parameterized data types

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/select_datetime_functions.sql
test/fixtures/dialects/redshift/select_datetime_functions.yml

This PR is to allow current_timestamp without parenthesis in Redshift. 
Fixes #3573
None
- Other.

Add current_timestamp to Redshift as a bare function

---

src/sqlfluff/core/templaters/jinja.py
test/fixtures/linter/autofix/ansi/macro_file_jinja_include_undefined_variable/.sqlfluff
test/fixtures/linter/autofix/ansi/macro_file_jinja_include_undefined_variable/after.sql
test/fixtures/linter/autofix/ansi/macro_file_jinja_include_undefined_variable/before.sql
test/fixtures/linter/autofix/ansi/macro_file_jinja_include_undefined_variable/macros/utils.sql
test/fixtures/linter/autofix/ansi/macro_file_jinja_include_undefined_variable/test-config.yml

Fix bug where undefined Jinja variable in macro file crashes linter

---

src/sqlfluff/rules/L062.py
test/fixtures/rules/std_rule_cases/L062.yml

We shouldn't really block words in comments IMHO and since I wrote this rule, guess I should fix it 😉
Nope
- Other.

Enhance L062 to ignore blocked words in comments

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/config.py

Adds usage examples to the main -h output covering the use and placement
of the `--dialect`, `--rules`, and `--templater` options.
Also amends the error output when a required `--dialect` option is
absent to explain how to specify a dialect on the command line.
fixes #3764
- Other.

Provide usage examples for new users

---

requirements.txt
setup.cfg

Resolves #3763.
For users of py 3.7, it appears that `pluggly` has an unexpressed dependency on a relatively modern version of `importlib_metadata`. This ensures we have a modern enough version. Really we only need `0.9`, but that's a very old version, so this requires the first `1.0.0` version.

Require importlib_metadata >=1.0.0

---

src/sqlfluff/dialects/dialect_sparksql.py
src/sqlfluff/dialects/dialect_sparksql_keywords.py
test/fixtures/dialects/sparksql/select_qualify.sql
test/fixtures/dialects/sparksql/select_qualify.yml

fixes #3555 by adding the QUALIFY statement to the Spark SQL dialect.
No
- Other.

Add QUALIFY to SparkSQL dialect

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_alter_database.sql
test/fixtures/dialects/postgres/postgres_alter_database.yml

Postgres: Support setting user properties using intrinsic ON & OFF values

---

src/sqlfluff/dialects/dialect_sparksql.py
test/fixtures/dialects/sparksql/select_aggregate.sql
test/fixtures/dialects/sparksql/select_aggregate.yml
test/fixtures/dialects/sparksql/select_reduce.sql
test/fixtures/dialects/sparksql/select_reduce.yml

Implements https://github.com/sqlfluff/sqlfluff/issues/3373.
Credits to @cmotta for implementing the same for athena dialect in https://github.com/sqlfluff/sqlfluff/pull/3551 – it was easy to follow the approach taken there.
Nope
- Other.

sparksql dialect to support lambda expressions (->)

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/create_table_constraint_unique.yml
test/fixtures/dialects/mysql/create_table_index.sql
test/fixtures/dialects/mysql/create_table_index.yml
test/fixtures/dialects/mysql/create_table_primary_foreign_keys.yml

fixes #3817
- [ x] Please confirm you have completed any of the necessary steps below.
- Other.

MySQL: More support for index definition in CREATE TABLE

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/load_data.sql
test/fixtures/dialects/mysql/load_data.yml
test/fixtures/dialects/mysql/quoted_literal.sql
test/fixtures/dialects/mysql/quoted_literal.yml

fixes #3830 
The RegEx for the MySQL lexer is distinctly simpler now, I think. This removed the special case for `''` and just treats that as a "standard" single-quoted string.
Shouldn't be.
- Added: `.sql`/`.yml` parser test cases in `test/fixtures/dialects/mysql`

MYSQL: improve lexing for single-quoted strings

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/alter_table.sql
test/fixtures/dialects/mysql/alter_table.yml
test/fixtures/dialects/mysql/check_constraint.sql
test/fixtures/dialects/mysql/check_constraint.yml

Continuing from https://github.com/sqlfluff/sqlfluff/pull/3826, I implemented all the parts related to constraints in CREATE TABLE and ALTER TABLE, including CHECK constraint support.
https://dev.mysql.com/doc/refman/8.0/en/create-table.html
https://dev.mysql.com/doc/refman/8.0/en/alter-table.html
* It reuses TableConstraintSegment in ALTER TABLE ADD CONSTRAINT, the parse structure of ALTER changes.
* It reuses IndexOptionsSegment in ALTER TABLE, where (SECONDARY_)ENGINE_ATTRIBUTE is not allowed. I think it is not the linter's job to check for all syntax errors, and I did to avoid maintaining each for CREATE TABLE and ALTER TABLE. …

MySQL: support remaining constraint parts of CREATE/ALTER TABLE

---

src/sqlfluff/rules/L027.py
test/fixtures/rules/std_rule_cases/L027.yml

This is related to #356.
The previous fix of this issue (https://github.com/sqlfluff/sqlfluff/pull/722/files) ended up passing a parameter
to rule L027 for `value_table_function_aliases`, but not actually exempting these aliases from the rule.
It seems to me that the test case then passes because the result of the `unnest` function call is not counted as a table
reference, rather than passing because it is ok to use "unqualified" references for value tables (they are impossible
to qualify).
As such, I have added a new testcase `test_ignore_value_table_functions_when_counting_unqualified_aliases` which fails
on main, but passes with this fix.

Allow standalone aliases in L027

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_create_table.sql
test/fixtures/dialects/redshift/redshift_create_table.yml

Closes https://github.com/sqlfluff/sqlfluff/issues/3811
Don't think so
- Other.

Redshift: CREATE TABLE LIKE enhancements

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/quoted_literal.sql
test/fixtures/dialects/mysql/quoted_literal.yml

To support concatenation of double quoted string literals
fixes #3870 
no
- Other.

MySQL: Treat double quotes the same as single quotes

---

plugins/sqlfluff-plugin-example/src/example/rules.py
src/sqlfluff/core/config.py
src/sqlfluff/core/plugin/lib.py
test/core/config_test.py
test/fixtures/linter/autofix/snowflake/002_previously_parse_tree_damaging/.sqlfluff

This is a fairly separable part of #3847, and can be merged separately. It will also simplify the review of that PR to take these changes out of it.
This allows particular config values to be marked as deprecated, prompting the user to remove them if they are set in a config. Optionally it also allows a configurable message to be set, informing the user how to update their config accordingly.

Support Removed warning on configs

---

src/sqlfluff/core/parser/segments/base.py
src/sqlfluff/core/rules/base.py
src/sqlfluff/rules/L016.py
src/sqlfluff/rules/L026.py
src/sqlfluff/rules/L042.py
src/sqlfluff/rules/L052.py
src/sqlfluff/utils/analysis/select.py
test/core/parser/segments_base_test.py

This is another relatively separable part of #3847. It's a useful development alone and can be merged before the rest. That will also simplify the review of the other PR.
This changes the behaviour of `BaseSegment.path_to()`.
Previously it would return a `list` of segments. The first element of that list would be `self` and the last would be the segment passed as `other`. The others would be the segments between.
I noticed that many uses of `path_to` always cut the last element (i.e. slice `[:-1]`), and that there are use cases where we want to know more than just the lineage, but also where in the parent each child is.
This changes `path_to` to instead:
- ...return a `list` of `PathStep` (a `dataclass`), which combines the segment with a new `index` which states where in the parent the …

Refactor path_to

---

src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/create_function.yml
test/fixtures/dialects/tsql/declare_with_following_statements.yml
test/fixtures/dialects/tsql/function_with_variable.yml
test/fixtures/dialects/tsql/hints.yml
test/fixtures/dialects/tsql/if_else.yml
test/fixtures/dialects/tsql/merge.yml
test/fixtures/dialects/tsql/set_statements.yml
test/fixtures/dialects/tsql/stored_procedure_begin_end.yml
test/fixtures/dialects/tsql/system-variables.yml
test/fixtures/dialects/tsql/triggers.yml
test/fixtures/dialects/tsql/update.yml

This is part of #3824.
Given it might be a bit longer until that gets merged, it seems sensible to merge this part earlier because it's easily separable.
This makes more precise use of `RawEqualsSegment` in TSQL rather than the existing use of `EqualsSegment`.

Adjust TSQL Operators

---

src/sqlfluff/core/parser/segments/base.py
test/core/parser/segments_base_test.py

This is another relatively standalone part of #3824.
It's slightly more abstract than the others as nothing in the codebase _uses_ the method yet, but it is well tested, and takes a little more logic out of the parent PR to make that more manageable.
This has already been partly reviewed by @barrywhart as part of the original PR so should look familiar.

raw_segments_with_ancestors

---

README.md

Following discussion on #3882, this adds a docker badge to the readme so that we can trace the docker project. It also updates the styling on the github badge to match the others.

Update github badge and add docker badge

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/create_table_index.sql
test/fixtures/dialects/mysql/create_table_index.yml

It also adds support for index prefixes:
https://dev.mysql.com/doc/refman/8.0/en/column-indexes.html#column-indexes-prefix
fixes #3886 
- Other.

MySQL: Implement (key_part, ...) in index definitions

---

src/sqlfluff/dialects/dialect_redshift.py
test/fixtures/dialects/redshift/redshift_datetime_cast.yml
test/fixtures/dialects/redshift/redshift_super_data_type.yml
test/fixtures/dialects/redshift/select_keywords.sql
test/fixtures/dialects/redshift/select_keywords.yml

Fixes: #3512
A couple of `.yml` test fixtures where automatically re-created by `tox -e generate-fixture-yml -- --dialect redshift`. AFAIK this should be harmless.
- Other.

fix(redshift): Allow keywords in qualified references

---

src/sqlfluff/cli/click_deprecated_option.py
src/sqlfluff/cli/commands.py
test/cli/commands_test.py
test/cli/test_click_deprecated_option.py

Fixes #3644 
* introduces custom click's `DeprecatedOption` 
* This is used for handling `--disable_progress_bar`
* It's not covered with any tests yet, because not sure if this approach will defend itself.
Changing option to another is easy. But to avoid any issues I wanted to have nicely handled both versions of click option (bonus points for informing that one of them is deprecated). I was not able to find working solution, then found on click's GH [issue](https://github.com/pallets/click/issues/2263) with linked SO [example solution](https://stackoverflow.com/a/50402799/5172513). 
Seems to be working, but it's kind of hackish, and I'm not personally very happy of it. But it works now and as long the mentioned issue is opened, there is still a chance that such possibility will be …

provide custom DeprecatedOption

---

test/conftest.py
test/generate_parse_fixture_yml.py

Fixes: #3906 
This allows the usage of dot notation in `test/generate_parse_fixture_yml.py::_is_matching_criteria` when running `tox -e generate-fixture-yml -- --new-only`.
Type hints are now match runtime types.
- Other.
AFAIK no tests are needed, but happy to add some if deemed necessary.

fix(test): Return ParseExample namedtuple in get_parse_fixtures

---

src/sqlfluff/dialects/dialect_postgres.py
test/dialects/postgres_test.py

Adjust the ArrayAccessorSegment to parse empty sides of an array.
i.e. [:2] or [2:]
fixes #3842
+ref: https://github.com/sqlfluff/sqlfluff/issues/3842
- Other.

feat: Optional numerics for postgres arrays

---

src/sqlfluff/dialects/dialect_postgres.py
test/fixtures/dialects/postgres/postgres_create_type.sql
test/fixtures/dialects/postgres/postgres_create_type.yml

fix issue with empty enum for postgres

---

src/sqlfluff/cli/formatters.py
test/cli/formatters_test.py

- Output to stderr using click
- Use unused color var
- Pass color flag to click
fixes #3892
+ref: https://github.com/sqlfluff/sqlfluff/issues/3892
- Other.

fix: Click output to stderr on errors

---

src/sqlfluff/dialects/dialect_postgres_keywords.py
test/fixtures/dialects/postgres/postgres_create_table.sql
test/fixtures/dialects/postgres/postgres_create_table.yml

Fixed #3794 
To be on safe side, I've just changed `usage` word to `non-reserved` and it solved the issue.
Was checking with [postgres documentation](https://www.postgresql.org/docs/current/sql-keywords-appendix.html), and it seems to be alright with Postgres.
Probably not, at least tests didn't raise anything.
- Other. …

[issue_3794] allow to use 'usage' as identifier for postgres

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/config.py
test/core/config_test.py

So #3824 and #3847 changed existing configs for some rules. This makes it less backward compatible.
This PR maps the old configs to the new configs, and warns the user to update their config. This also makes the config changes not breaking changes. It makes it easier to deploy parts of #3673 incrementally.
In addition I've cleaned up some incorrect references. For python 3.2+ we also don't need to subclass `logging.Filter` anymore and can just provide a callable.
Slightly annoyingly, the config validation is done before the full logging setup is done so the warnings don't come out in red 🤷 . I had a quick look at resolving that but it seemed overkill.

Map old configs to new configs

---

src/sqlfluff/dialects/dialect_sqlite.py
test/fixtures/dialects/sqlite/create_table_check.sql
test/fixtures/dialects/sqlite/create_table_check.yml

Add support for table-level `CHECK` constraint by following the approach put forth in the PostgreSQL dialect.
See: https://www.sqlite.org/syntax/table-constraint.html
Fixes #3553 
Increases footprint of SQLite dialect due to inability to effectively override `ansi.TableConstraintSegment.match_grammar`.
- Other. …

SQLite: Add support for table-level CHECK constraint

---

src/sqlfluff/dialects/dialect_sparksql.py
test/fixtures/dialects/sparksql/select_qualify.sql
test/fixtures/dialects/sparksql/select_qualify.yml

fixes #3929 
No, AFAIK.
- Other.

SparkSQL: Fixed bug with `QUALIFY` usage without `WHERE` clause (applies also for Databricks dialect)

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/create_trigger.sql
test/fixtures/dialects/mysql/create_trigger.yml

fixes #3917
`CREATE TRIGGER` should be now better handled for mysql.
no
- Other.

MySQL: Fix create trigger

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_tsql.py
test/fixtures/dialects/tsql/outer_apply.sql
test/fixtures/dialects/tsql/outer_apply.yml
test/fixtures/rules/std_rule_cases/L003.yml

This PR resolves #3685.
n/a
- Other.

T-SQL: Fix indendentation of OUTER APPLY

---

src/sqlfluff/dialects/dialect_hive.py
test/fixtures/dialects/hive/select_lateral_view.sql
test/fixtures/dialects/hive/select_lateral_view.yml

Add support for `LATERAL VIEW` clause by following the approach put forth in the SparkQL dialect.
See: https://cwiki.apache.org/confluence/display/hive/languagemanual+lateralview
Fixes https://github.com/sqlfluff/sqlfluff/issues/3161
N/A
- Other.

Hive: Add support for LATERAL VIEW clause

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/create_trigger.sql
test/fixtures/dialects/mysql/create_trigger.yml

Add missing part of https://github.com/sqlfluff/sqlfluff/pull/3928
We can specify "IF NOT EXISTS" with CREATE TRIGGER statement
https://dev.mysql.com/doc/refman/8.0/en/create-trigger.html
Added example into test/fixtures/dialects/mysql/create_trigger.sql
which is valid as
```
mysql> CREATE TRIGGER IF NOT EXISTS some_trigger AFTER DELETE ON some_table
-> FOR EACH ROW DELETE FROM other_table;
Query OK, 0 rows affected (0.06 sec)
```
(tested with MySQL 8.0.29)
A parse error occurred before the change:
```
$ sqlfluff lint test/fixtures/dialects/mysql/create_trigger.sql --dialect=mysql
== [test/fixtures/dialects/mysql/create_trigger.sql] FAIL
L:   3 | P:   1 | L003 | Expected 1 indentation, found 0 [compared to line 02]
L:  10 | P:   5 | L003 | Expected 0 indentations, found 1 [compared to …
```

MySQL: Support optional "IF NOT EXISTS" with CREATE TRIGGER

---

docs/source/configuration.rst
src/sqlfluff/core/config.py
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/rules/config_info.py
src/sqlfluff/rules/L022.py
test/core/rules/rules_test.py
test/fixtures/rules/std_rule_cases/L022.yml
test/rules/std_test.py

Most of the references to `comma_style` were removed in #3847 . At that stage I didn't however clear up a few of the other references, in particular scattered across the config files.
`L022` was one still using the old config which raises risks for confusion. This PR migrates that rule off the old config and onto the new one. It _doesn't_ migrate the rule onto the reflow codebase itself because we don't yet have the capability to insert blank lines in that code (I'll make a note to cover that later).
While I was in there I simplified the nesting of the logic a little, but the intent is unchanged.

Consolidate comma style configs

---

src/sqlfluff/dialects/dialect_mysql.py
test/fixtures/dialects/mysql/load_data.sql
test/fixtures/dialects/mysql/load_data.yml
test/fixtures/dialects/mysql/replace.sql
test/fixtures/dialects/mysql/replace.yml

Also fixes usage of SelectPartitionClauseSegment in LoadDataSegment
fixes #3947 
No
- Other.

MySQL: Support REPLACE statement

---

src/sqlfluff/dialects/dialect_athena.py
test/fixtures/dialects/athena/select_underscore.sql
test/fixtures/dialects/athena/select_underscore.yml

Add support for using underscores for aliases (`AS`).
Fixes https://github.com/sqlfluff/sqlfluff/issues/3678
N/A
- Other.

Athena: Add support for using underscore aliases

---

plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
plugins/sqlfluff-templater-dbt/test/linter_test.py
plugins/sqlfluff-templater-dbt/test/templater_test.py
src/sqlfluff/utils/testing/cli.py
test/cli/commands_test.py

Co-authored-by: ssassi@sophilabs.com
Fixes https://github.com/sqlfluff/sqlfluff/issues/2895
`sqlfluff-templater-dbt` uses `dbt.parser.manifest` from `dbt-core`, which has [this bug](https://github.com/dbt-labs/dbt-core/issues/6055).
This is a workaround to avoid such issue.
This PR replaces #3957.
Test cases pending.
- Other. …

[BUGFIX] Changing cwd temporarily on manifest load as dbt is not using project_dir to read/write target folder

---

docs/source/configuration.rst

This resolves #585. Old issue!
I've been meaning to document in line configuration flags for ages. I've also been using them a lot in debugging for the reflow work so now seems a good time to do it.
Very open to feedback on exactly what we call them. Currently I've called them _"in-file configuration directives"_, but the original issue calls them _"in-code directives"_.

document inline configuration

---

src/sqlfluff/utils/analysis/select.py
test/fixtures/rules/std_rule_cases/L027.yml

Fixes https://github.com/sqlfluff/sqlfluff/issues/3961
This adds code to identify column references that are part of a lambda
expression, and mark them as "standalone aliases" that are exempt from rule
L027. (I.e. they are allowed to be unqualified, because there is no further
way to qualify them.)

Allow lambda argument columns to be unqualified

---

src/sqlfluff/dialects/dialect_ansi.py
src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_external_table.yml
test/fixtures/dialects/snowflake/snowflake_alter_materialized_view.yml
test/fixtures/dialects/snowflake/snowflake_alter_pipe.yml
test/fixtures/dialects/snowflake/snowflake_alter_schema.yml
test/fixtures/dialects/snowflake/snowflake_alter_share.yml
test/fixtures/dialects/snowflake/snowflake_alter_stream.yml
test/fixtures/dialects/snowflake/snowflake_alter_warehouse.yml
test/fixtures/dialects/snowflake/snowflake_create_schema.yml
test/fixtures/dialects/snowflake/snowflake_create_table.sql
test/fixtures/dialects/snowflake/snowflake_create_table.yml
test/fixtures/dialects/snowflake/snowflake_create_view.yml

This creates a TagReferenceSegment in Snowflake, and replaces all of its non-shared refs with this segment. Allows for db/schema scoped tags.
Fixes #3786
No, it only affects Snowflake. Added the TagReferenceSegment to ANSI for reusability.
- Other.

Snowflake tag reference segment

---

.github/workflows/ci-tests.yml
requirements_dev.txt

Looks like Windows CI check is failing on many branches. See if pinning helps. https://github.com/sqlfluff/sqlfluff/actions/runs/3331475162/jobs/5511256473
Eventually we'd get out of date if we pin? 🤷 
- Other.

Fix Windows CI check

---

src/sqlfluff/core/config.py

As noted by @tunetheweb - the recent release auto-migrates configs the wrong way around. this is a fix for that.

hotfix to config migration

---

src/sqlfluff/core/templaters/slicers/tracer.py
test/core/templaters/jinja_test.py
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if/after.sql
test/fixtures/linter/autofix/ansi/016_index_error_with_jinja_if2/after.sql
test/fixtures/linter/autofix/ansi/018_l003_indent_templated_code/after.sql

This resolves #3750.
Based on the existing logic to appropriately distinguish between the two kinds of `set` expression. This changes the `block_type` for the self contained type so that they are correctly indented.

Classify self contained set statements as templated

---

.github/codecov.yml

Since we added a Python 3.11 required CI test.
https://sqlfluff.slack.com/archives/G01G58WRJNR/p1667926639893419?thread_ts=1667922270.894929&cid=G01G58WRJNR

Bump after_n_builds to 10

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/linter/linter.py
test/cli/commands_test.py
test/core/linter_test.py

This resolves #4020 and resolves #3636.
Adds a basic `render` command which allows the user to render the given sql file for debugging. As per discussion in #4020, it only supports a single file, not full directories.

Make render command

---

src/sqlfluff/dialects/dialect_snowflake.py
test/fixtures/dialects/snowflake/snowflake_alter_table_column.sql
test/fixtures/dialects/snowflake/snowflake_alter_table_column.yml

Closes https://github.com/sqlfluff/sqlfluff/issues/4048
[Docs](https://docs.snowflake.com/en/sql-reference/sql/alter-table.html) say `COLUMN` keyword isn't required for `ADD` or `DROP`:
No
- Other.

Snowflake: ADD and DROP without COLUMN

---

src/sqlfluff/core/rules/base.py
src/sqlfluff/core/rules/crawlers.py
test/core/rules/rules_test.py

This partially addresses #3989. It fully addresses it in combination with #3942.
Rule crawlers (#3717) introduced more advanced crawling mechanisms and would filter out unparsable sections of code _before linting them_, however for rules which handle the own crawling this isn't sufficient - because they might still recurse down to sections of unparsable code. This PR filters violations after parsing to prune any which anchor on (or modify) unparsable code if that's set on the crawler.

Filter out issues in unparsable sections

---

src/sqlfluff/cli/commands.py
src/sqlfluff/core/linter/linter.py
test/cli/commands_test.py
test/core/linter_test.py

This resolves #1023 (an oldie).
It also actually allows us to simplify the code by emitting a `SQLFluffUserError` directly rather than an `OSError` and then needing to do guesswork around that.

Better file not found error #1023

---

docs/source/configuration.rst
src/sqlfluff/cli/formatters.py
src/sqlfluff/core/config.py
src/sqlfluff/core/default_config.cfg
src/sqlfluff/core/errors.py
src/sqlfluff/core/linter/linted_file.py
src/sqlfluff/core/linter/linter.py
src/sqlfluff/core/linter/linting_result.py
test/cli/commands_test.py
test/fixtures/cli/warning_a.sql

This resolves #201 (THE OLDEST OUTSTANDING ISSUE 🚀 ) - only took over 2 yrs.
This delivers almost exactly against the spec outlined in that original issue.
Rules can be configured as warnings, in which case they're displayed as such, but don't fail the file.

Allow warnings for specific rules

---

plugins/sqlfluff-templater-dbt/docker/shutdown
plugins/sqlfluff-templater-dbt/docker/startup

I'm setting up a new computer, and I noticed that the Docker dev scripts use `docker-compose`, which doesn't work anymore. `docker compose` is equivalent and still works.
- Other.

Use "docker compose", not "docker-compose"
