sqlfluff/sqlfluff

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_c.sql
> Correcting the DESC keyword

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/grammar.py
- src/sqlfluff/parser/lexer.py
- test/cli_commands_test.py
- test/cli_formatters_test.py
Closes #28.
Also fixes a bug introduced in the last release
> Improvements to Logging and Output

- CHANGELOG.md
- requirements.txt
- src/sqlfluff/cli/commands.py
- src/sqlfluff/errors.py
- src/sqlfluff/linter.py
- src/sqlfluff/templaters.py
- test/rules_std_test.py
- test/templaters_test.py
This doesn't yet solve the templating problem yet. We still need to solve the configuration side of things - but this seems like a good checkpoint, because the configuration feels like a slightly chunk of work.
> Basic Skeleton for templating

- README.md
- docs/source/architecture.rst
- docs/source/cli.rst
- docs/source/configuration.rst
- docs/source/index.rst
> Docs for configuration

- CHANGELOG.md
- README.md
- docs/source/configuration.rst
- src/sqlfluff/config.py
- src/sqlfluff/default_config.cfg
- src/sqlfluff/templaters.py
- test/config_test.py
- test/conftest.py
- test/dialects_test.py
- test/fixtures/config/inheritance_a/nested/tox.ini
- test/fixtures/templater/jinja_a/.sqlfluff
- test/fixtures/templater/jinja_a/jinja.yml
- test/fixtures/templater/jinja_b/.sqlfluff
- test/fixtures/templater/jinja_b/jinja.sql
- test/fixtures/templater/jinja_b/jinja.yml
- test/fixtures/templater/jinja_c_dbt/dbt_builtins.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins.yml
- test/templaters_test.py
- tox.ini
This also includes a couple of small fixes
> Macro templating and documentation

- CHANGELOG.md
- README.md
- docs/source/index.rst
- docs/source/rules.rst
- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/default_config.cfg
- src/sqlfluff/linter.py
- src/sqlfluff/rules/__init__.py
- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/cli_commands_test.py
- test/cli_formatters_test.py
- test/rules_std_test.py
Move to a new structure of defining rules, which is more compact and legible. This also implements autodocumentation too using the new structure.
Closes #43 
Closes #39
> Rework rules and rule sets

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/grammar.py
- test/fixtures/parser/ansi/select_simple_f.sql
- test/fixtures/parser/ansi/select_simple_g.sql
- test/parser_grammar_test.py
- Implemented `GROUP BY`and `LIMIT`.
- Added `ORDER BY` using indexes.
> More Select Clause mechanics

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/grammar.py
- test/fixtures/parser/ansi/select_simple_h.sql
Some of the functionality added here might not strictly be relevant for the ansi dialect. Maybe this is where we should start implementing other dialects. For now I've kept them all together, and I assume we'll use the first incompatibility changes as a trigger to split the dialects.
> More parsing capability on functions (Aggregates and window functions)

- src/sqlfluff/cli/commands.py
> Error more obviously on inaccessible path

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/segments_common.py
- src/sqlfluff/rules/std.py
- test/fixtures/parser/ansi/select_simple_e.yml
- test/fixtures/parser/ansi/select_simple_i.sql
- test/fixtures/templater/jinja_b/jinja.yml
- test/rules_std_roundtrip_test.py
This closes #11 and closes #12
> Linting for Aliasing

- src/sqlfluff/config.py
> Fix config fetching if values are missing.

- docs/source/configuration.rst
Related to #60.
@barrywhart - do you think this is clearer?
> Clarify the nested configuration

- CHANGELOG.md
- setup.py
- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/config.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/segments_base.py
- src/sqlfluff/templaters.py
- test/cli_commands_test.py
- test/fixtures/parser/ansi/select_simple_j.sql
- test/fixtures/parser/ansi/select_simple_j.yml
- Closes #79 (missing files from `install_requires`)
- Closes #77 (incorrect parsing of `CROSS JOIN`, including tests for this in future)
- Closes #65 (logging for config diffs)
- Closes #73 (parsing for the inequality operator)
> Clearup of a few smaller issues/fixes.

- src/sqlfluff/errors.py
- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/cli_formatters_test.py
> Allow rules to optionally override the description of the error.

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_d.sql
> is/is not null parsing + adding NOT IN

- test/cli_commands_test.py
- test/cli_helpers_test.py
A bit of housekeeping to deal with some slightly messy tests
> Parameterise some more tests

- CHANGELOG.md
- src/sqlfluff/rules/std.py
- test/rules_std_test.py
I think this fixes #87 
@nolanbconaway : Can you run this branch locally and see whether it does?
> Fix the "inconsistent" bug on L010

- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/rules_std_test.py
Fix for #99 
The issue was python2 rounding
> Fix for #99

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_f.sql
This closes #96 .
More sensible precedence in the expression parser.
> Fix for function parsing in complex expressions.

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_g.sql
This PR closes #101 .
Allow a limit clause to terminate a select clause, together with a from clause.
> Select clause with limit but no from

- src/sqlfluff/cli/formatters.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/__init__.py
- src/sqlfluff/parser/match.py
- src/sqlfluff/templaters.py
- test/dialects_ansi_test.py
- test/dialects_test.py
- test/parser_lexer_test.py
- test/templaters_test.py
This is primarily a pull request to do some spring cleaning.
- Remove some unused methods.
- Add some additional tests around some potential exceptions.
- Simplify some imports
- Generally improve test coverage.
> Spring Cleaning

- CHANGELOG.md
- docs/source/indentation.rst
- docs/source/index.rst
- src/sqlfluff/default_config.cfg
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/__init__.py
- src/sqlfluff/parser/grammar.py
- src/sqlfluff/parser/segments_base.py
- src/sqlfluff/parser/segments_common.py
- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/cli_commands_test.py
- test/config_test.py
- test/conftest.py
- test/fixtures/linter/indentation_error_hard.sql
- test/fixtures/linter/indentation_errors.sql
- test/fixtures/parser/ansi/select_a.yml
- test/fixtures/parser/ansi/select_e.yml
- test/fixtures/parser/ansi/select_simple_a.yml
- test/fixtures/parser/ansi/select_simple_b.yml
- test/fixtures/parser/ansi/select_simple_e.yml
- test/fixtures/parser/ansi/select_simple_j.yml
- test/fixtures/parser/ansi/select_with_a.yml
- test/fixtures/templater/jinja_a/jinja.yml
- test/fixtures/templater/jinja_b/jinja.yml
- test/fixtures/templater/jinja_c_dbt/dbt_builtins.yml
- test/parser_grammar_test.py
- test/rules_std_test.py
@barrywhart - can you take a look at this first pass at indentation rules? (relates to #76, #68, #66 )
1. What do you think of the initial principles?
2. What else needs adding that isn't currently covered here?
> First pass at indentation rules

- .deepsource.toml
- src/sqlfluff/cli/commands.py
- src/sqlfluff/parser/segments_base.py
- src/sqlfluff/rules/std.py
- src/sqlfluff/templaters.py
- test/linter_test.py
Changes:
- Use set comprehension instead of calling `set()` on an iterable in `src/sqlfluff/rules/std.py` and `test/linter_test.py`
- Use `.values()` to iterate over the values of a dictionary in `src/sqlfluff/templaters.py`
- Use identity test, `is`, for comparing types in `src/sqlfluff/parser/segments_base.py`
- Simplify `if` expression in `src/sqlfluff/cli/commands.py`
---
This PR also adds`.deepsource.toml` to run static analysis continuously on the repo with [DeepSource](https://deepsource.io). Upon enabling DeepSource, static analysis will be run on every PR to detect 500+ types of issues in the changes — including bug risks, anti-patterns, security vulnerabilities, etc.
DeepSource is **free to use for open-source projects**, and is used by teams at NASA, Uber, Slack among many …
> Fix some bug risks and code quality issues

- README.md
Added the new DeepSource repository badge for alanmcruickshank/sqlfluff.
> Update DeepSource badge

- CHANGELOG.md
- src/sqlfluff/dialects/__init__.py
- src/sqlfluff/dialects/base.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/rules/std.py
- test/fixtures/parser/bigquery/select_quoting.sql
Relates to #97 . Doesn't include all the dialect but does provide the basics.
> BigQuery dialect start and fix for infinite loop bug.

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_h.sql
Fixes #136 . Basic error on the case statement.
> Fix issue with case statement

- src/sqlfluff/rules/std.py
Breaking bug in the case of no up-breaks on a long line.
> Handle a no-unbreak scenario

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/create_table_auto_increment.sql
- test/fixtures/parser/ansi/create_table_column_comment.sql
- test/fixtures/parser/ansi/create_table_table_comment.sql
- test/fixtures/parser/ansi/create_table_varchar.sql
- test/fixtures/parser/ansi/create_view_a.sql
> #102: Add support for VARCHAR(100), AUTO_INCREMENT, col/tbl COMMENT

- src/sqlfluff/parser/segments_base.py
This is otherwise just kinda crufty
> Remove the from_raw method from the BaseSegment class.

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_p.sql
> Add support for CAST and EXTRACT-like functions

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_r.sql
> Allow union in With clause

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_s.sql
> Add Like and Not Like expressions

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_simple_k.sql
> Add support for the HAVING clause

- src/sqlfluff/rules/std.py
- test/fixtures/linter/autofix/ansi/006_L003_indentation_4/after.sql
- test/fixtures/linter/autofix/ansi/006_L003_indentation_4/before.sql
Sometimes indentation fixing still didn't work. This addresses a few of those issues and also adds a suitable test case for that.
> Correction of indentation fixes

- src/sqlfluff/dialects/__init__.py
- src/sqlfluff/dialects/base.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_mysql.py
> Introduce the mysql dialect and change comment lexing

- src/sqlfluff/dialects/dialect_ansi.py
- test/dialects_ansi_test.py
- test/fixtures/parser/bigquery/select_example.sql
Fixes an apparent error in expression parsing raised in #177. Also adds an additional test case submitted by @barrywhart.
> New test case and select clauses in functions

- src/sqlfluff/dialects/dialect_ansi.py
- test/dialects_ansi_test.py
> Support for a.b.*

- src/sqlfluff/dialects/dialect_ansi.py
- test/dialects_ansi_test.py
See discussion:
https://github.com/alanmcruickshank/sqlfluff/pull/188
> Support any number of nesting in wildcards

- CHANGELOG.md
- src/sqlfluff/cli/commands.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/grammar.py
- src/sqlfluff/parser/segments_base.py
Related to #189 .
This introduces the profiler and some low hanging performance gains.
> Performance improvements and profiling

- .circleci/config.yml
- CHANGELOG.md
- benchmarks/bench_001_package.sql
- benchmarks/benchmarks.yml
- requirements.txt
- src/sqlfluff/cli/commands.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/linter.py
- src/sqlfluff/parser/grammar.py
- src/sqlfluff/parser/lexer.py
- src/sqlfluff/parser/segments_base.py
- src/sqlfluff/parser/segments_common.py
- test/dialects_ansi_test.py
- tox.ini
- util.py
This PR addresses a few issues:
- Shortcuts some of the matching routines where possible with _simple_ rules. ( #189 )
- Benchmark logging to monitor performance over time. ( #189 )
- Handles potential nulls in the `parse_string` function.
- Enables lexing and parsing of the concatenate operator `||`.
> Initial performance increases

- src/sqlfluff/templaters.py
- test/templaters_test.py
> Disable HTML escaping for Jinja templates

- src/sqlfluff/cli/commands.py
- src/sqlfluff/config.py
@barrywhart - I believe this fixes #193 
Can you confirm?
> Fix issue with dialect not being read from config

- src/sqlfluff/errors.py
- src/sqlfluff/linter.py
- test/fixtures/linter/autofix/bigquery/001_L003L006L009_templating/.sqlfluff
- test/fixtures/linter/autofix/bigquery/001_L003L006L009_templating/after.sql
- test/fixtures/linter/autofix/bigquery/001_L003L006L009_templating/before.sql
- test/rules_std_fix_auto_test.py
> Insert opcode and tests

- src/sqlfluff/linter.py
> Deal with potentially empty directories

- src/sqlfluff/errors.py
- src/sqlfluff/rules/std.py
- test/cli_commands_test.py
> Fix line number bug with better hanging indent handling

- CHANGELOG.md
- src/sqlfluff/rules/std.py
- test/fixtures/linter/indentation_error_contained.sql
- test/rules_std_test.py
> Handle closing bracket properly

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/parser/grammar.py
- test/dialects_ansi_test.py
Fixes #206.
Also improves simple handling for Sequence grammars and enables the string style literal grammar.
> Several Fixes

- src/sqlfluff/dialects/dialect_ansi.py
- test/rules_std_test.py
> Classify NULL as a keyword

- CHANGELOG.md
- src/sqlfluff/templaters.py
- test/fixtures/templater/jinja_e/jinja.sql
- test/fixtures/templater/jinja_e/jinja.yml
- test/templaters_test.py
This fixes #196 .
@r-hempenstall, I needed to alter the test query you provided before I could make it work, can you confirm that this now successfully parses in your case?
> Enable to do directive in jinja templating

- docs/requirements.txt
- requirements.txt
> Bump Versions

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/fixtures/parser/ansi/create_table_as.sql
> Don't allow indentation checking on unparsables. More create syntax.

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/parser/lexer.py
- src/sqlfluff/rules/std.py
- test/fixtures/linter/block_comment_errors.sql
- test/parser_lexer_test.py
- test/rules_std_test.py
Fixes #236 
@pwildenhain would love your feedback on this functionality. 🙏
> Block comment refactor

- CHANGELOG.md
- docs/source/configuration.rst
- src/sqlfluff/config.py
- src/sqlfluff/parser/lexer.py
- src/sqlfluff/templaters.py
- test/fixtures/templater/jinja_f/.sqlfluff
- test/fixtures/templater/jinja_f/jinja.sql
- test/fixtures/templater/jinja_f/jinja.yml
- test/templaters_test.py
Fixes #249 .
NB: This means that *all* config reads will be type sensitive. That might need to be something that we deal with later, but not for now.
> Case sensitivity and type inference

- CHANGELOG.md
- src/sqlfluff/linter.py
Fixes #234.
Now, the fixer will avoid going back to any previous states that it has previously encountered.
> Catch potential infinite loops in fixing

- CHANGELOG.md
- docs/source/indentation.rst
- src/sqlfluff/config.py
- src/sqlfluff/default_config.cfg
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/parser/grammar.py
- src/sqlfluff/parser/segments_base.py
- src/sqlfluff/parser/segments_common.py
- test/rules_std_test.py
This fixes #232 an enables configurable indentation. @cnolanminich take a look at the docs I've written for this feature and see if they're sufficient for you to get this feature to work for your use case.
Consider this both a test of the docs and a test of the feature 😄 . I hope this addresses your use case well.
> Configurable indentation

- src/sqlfluff/linter.py
> Make sure config changes in folders are taken into account.

- src/sqlfluff/parser/lexer.py
- test/parser_lexer_test.py
> Fix issue with empty comment lines + tests

- src/sqlfluff/rules/std.py
- test.sql
> Fix issue with L003 and comments

- CHANGELOG.md
- src/sqlfluff/cli/commands.py
- src/sqlfluff/dialects/__init__.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/errors.py
- src/sqlfluff/linter.py
- src/sqlfluff/rules/__init__.py
- src/sqlfluff/rules/base.py
- src/sqlfluff/rules/std.py
- test/cli_commands_test.py
- test/rules_std_fix_auto_test.py
This also adds the new snowflake and postgres dialects, although without any new syntax attached to them yet.
> Fix command UX improvements, Rule Logging and Bugfixes

- .circleci/config.yml
- setup.py
- tox.ini
Also clean up the setup.py and update with a few new fields.
> Add testing pipeline for python 3.9

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/parser/grammar.py
> Change behaviour of Bracketed to be like Sequence

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_right.sql
> Fix and test for right joins

- CHANGELOG.md
- docs/source/configuration.rst
- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/config.py
- src/sqlfluff/default_config.cfg
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/errors.py
- src/sqlfluff/linter.py
- src/sqlfluff/rules/std.py
- src/sqlfluff/templaters.py
- test/conftest.py
- test/fixtures/templater/jinja_g_macros/.sqlfluff
- test/fixtures/templater/jinja_g_macros/jinja.sql
- test/fixtures/templater/jinja_g_macros/jinja.yml
- test/fixtures/templater/jinja_g_macros/macros/macro_1.sql
- test/rules_std_roundtrip_test.py
- test/templaters_test.py
Related to #156 (but probably doesn't completely solve it yet).
This also brings several jinja templater upgrades and a few postgres syntax upgrades.
> Templater upgrades

- src/sqlfluff/rules/std.py
- test/rules_std_test.py
> Linting function capitalisation

- src/sqlfluff/cli/commands.py
> Add readout for unfixable linting violations

- .gitignore
- CHANGELOG.md
- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/linter.py
- test/dialects_ansi_test.py
- test/fixtures/parser/mysql/alter_table.sql
- test/fixtures/parser/snowflake/snowflake_semi_structured.yml
This fixes #310 . Also includes warning for users with an unset dialect.
> ALTER TABLE statements, warning for unset dialects

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_trailing_comma_column_list.sql
- test/fixtures/parser/ansi/select_where_in_unnest.sql
> Add support for "WHERE c in UNNEST()"

- requirements.txt
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_case_a.sql
- test/fixtures/parser/ansi/select_case_b.sql
- test/fixtures/parser/ansi/select_simple_g.sql
- test/fixtures/parser/ansi/select_simple_k.sql
> Support CASE expr WHEN value ... case statements

- README.md
Re: #390, just a quick note in the readme with a link to the tool. I'll link to the source code on the sqlfluff online website so that people can sniff around that way if they want.
> Add readme note about sqlfluff online

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_function_in_group_by.sql
> Accept functions in group by clause

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_u.sql
> Fix #375 - Substring like functions

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/select_v.sql
> Allow nested WITH

- setup.py
- src/sqlfluff/__init__.py
> Add a useful error message for python2

- docs/source/index.rst
- docs/source/vision.rst
I've been meaning to put something like this together for a while. I think it starts to clarify some of the tricking bits we've found in the parser. @barrywhart - does this line up with what you expected? Any suprises.
btw: sorry for the long absence. Totally my bad.
> Adding a vision for sqlfluff

- docs/source/configuration.rst
- requirements.txt
- setup.py
- src/sqlfluff/config.py
See #405 for rationale and discussion
> Add config layer between 0&1 for user's os-specific config dir, fixes #405

- src/sqlfluff/dialects/dialect_ansi.py
> Numeric literals starting with a decimal

- src/sqlfluff/rules/std.py
- test/rules_std_test.py
> L013 Expects alias for star

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/parser/grammar.py
- test/fixtures/linter/autofix/snowflake/001_L014_semi_structured/.sqlfluff
- test/fixtures/linter/autofix/snowflake/001_L014_semi_structured/after.sql
- test/fixtures/linter/autofix/snowflake/001_L014_semi_structured/before.sql
- test/fixtures/parser/snowflake/snowflake_semi_structured_2.sql
- test/parser_grammar_test.py
> bugfix for semi structured queries with keywords

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/parser/bigquery/select_datetime.sql
> BigQuery date part units

- src/sqlfluff/dialects/dialect_ansi.py
- test/dialects_ansi_test.py
> Notnull and Isnull

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/parser/snowflake/snowflake_semi_structured_3.sql
> Fix snowflake array accessors

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/modulo.sql
> Add the modulo operator

- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/gettingstarted.rst
- docs/source/inthewild.rst
- setup.py
- src/sqlfluff/config.py
- src/sqlfluff/parser/grammar.py
- test/dialects_ansi_test.py
- test/fixtures/parser/ansi/select_j.sql
- test/fixtures/parser/ansi/select_l.sql
- test/fixtures/parser/ansi/select_m.sql
- test/fixtures/parser/ansi/select_n.sql
- test/fixtures/parser/ansi/select_o.sql
- test/fixtures/parser/ansi/select_p.sql
- test/fixtures/parser/ansi/select_q.sql
- test/fixtures/parser/ansi/select_r.sql
- test/fixtures/parser/ansi/select_s.sql
- util.py
Relates to #444. Updates references to the new url.
> Update references for new github org

- docs/source/configuration.rst
> Improve config documentation

- src/sqlfluff/default_config.cfg
- src/sqlfluff/rules/std.py
- test/rules_std_test.py
> Respect leading commas for rule L022

- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/parser/lexer.py
- test/fixtures/parser/snowflake/snowflake_col_position.sql
Resolves https://github.com/sqlfluff/sqlfluff/issues/451
> Add column index identifier in snowflake dialect

- src/sqlfluff/linter.py
- test/rules_std_test.py
Resolves https://github.com/sqlfluff/sqlfluff/issues/476
Does this look sensible @alanmcruickshank?
> If last 'equal' templ_block and last fixed_block, consume templ_block

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/linter/column_references.sql
This addresses #480 . Hopefully this results in another performance gain. I want to see what the benchmark test says before declaring success. ⏲️
> Wider use of the Checkpoint feature

- CHANGELOG.md
- src/sqlfluff/linter.py
- src/sqlfluff/rules/std.py
- test/fixtures/linter/autofix/ansi/008_L022L023L024_with_clause/after.sql
- test/fixtures/linter/autofix/ansi/010_L022_CTEs_and_newlines/after.sql
- test/fixtures/linter/autofix/ansi/010_L022_CTEs_and_newlines/before.sql
- test/rules/std_test.py
- test/rules_std_test.py
This fixes #366 .
It also limits the recursion within the fix routines to limit the extent to which a rule can _runaway_, i.e. end up in an infinite loop.
This involved a reasonable restructure of L022 to handle the kind of cases that were being thrown at it.
> Refactor L022 and add more test cases.

- CONTRIBUTING.md
- requirements_dev.txt
- tox.ini
> Add requirements_dev.txt

- src/sqlfluff/core/rules/std.py
- test/core/rules/std_test.py
I missed this when reviewing the L033 PR, so applying retroactively before I forget!
> Make L033 caseless

- docs/source/architecture.rst
- src/sqlfluff/core/dialects/dialect_ansi.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/match_logging.py
- src/sqlfluff/core/parser/segments/base.py
Mostly improves the documentation around the architecture (which was out of date).
This also includes some small performance tweeks which I found in the process.
> Docs update + Misc Performance Gains

- src/sqlfluff/core/rules/std.py
- test/cli/commands_test.py
- test/core/rules/std_test.py
- test/fixtures/cli/passing_a.sql
- test/fixtures/cli/passing_b.sql
> L031 include initialisms in from clauses

- README.md
- setup.py
Before we forget. Ended up doing some readme tidies while I was at it:
https://github.com/sqlfluff/sqlfluff/blob/d056fc179366fc4b0418c13828635431bea41b95/README.md
> README tidy + remove python 3.5 from setup.py

- src/sqlfluff/core/dialects/dialect_ansi.py
- test/core/parser/lexer_test.py
- test/fixtures/parser/ansi/escaped_quotes.sql
> Support escaped quotes in strings

- src/sqlfluff/core/dialects/dialect_ansi.py
- src/sqlfluff/core/dialects/dialect_postgres.py
- test/fixtures/parser/ansi/escape.sql
> Fix escape parsing in like clause

- MANIFEST.in
Resolves https://github.com/sqlfluff/sqlfluff/issues/572
(Can't believe I opened an issue for that haha)
> Fix include path default_config.cfg

- src/sqlfluff/core/rules/base.py
- src/sqlfluff/core/rules/std.py
- test/core/rules/test_cases/L031.yml
> Fix L031 bugs

- CHANGELOG.md
- benchmarks/benchmarks.yml
- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
Resolves #334 
As mentioned in #578 
By popular demand. 😄
> Remove --no-safety

- test/core/rules/std_test.py
- test/core/templaters/dbt_test.py
Running `black .` kept changing these files and upsetting flake8 which was annoying. This applies black and keeps flake8 happy
> Apply black

- src/sqlfluff/core/dialects/dialect_ansi.py
> Link to expression grammars in cockroachlabs for content

- src/sqlfluff/core/dialects/dialect_postgres.py
- test/core/dialects/postgres_test.py
- test/core/dialects/snowflake_test.py
Fixes #565 
FYI @gnilrets if you would like to test this out
> Add EPOCH datetime unit for postgres

- CHANGELOG.md
- CONTRIBUTING.md
> Add to changelog for 0.4

- src/sqlfluff/config.ini
Per slack chat, in prep for testing the github pypi action.
> Version bump 0.4.0a1 -> 0.4.0a2

- src/sqlfluff/config.ini
Next steps: Follow @nolanbconaway awesome documentation here: https://github.com/sqlfluff/sqlfluff/blob/master/CONTRIBUTING.md#building-package
> Release 0.4.0a3

- CHANGELOG.md
- src/sqlfluff/core/rules/std.py
> Improve L004 no auto fix available message

- src/sqlfluff/core/dialects/dialect_ansi.py
- test/core/rules/std_test.py
- test/core/rules/test_cases/L018.yml
- test/core/rules/test_cases/L031.yml
This has surfaced two unparsable test cases which need fixing
> Raise error on unparsable test cases

- CHANGELOG.md
- src/sqlfluff/core/dialects/dialect_snowflake.py
- test/core/dialects/snowflake_test.py
> Allow gaps between semi-structured colon accessors in snowflake

- .github/codecov.yml
Code cov seems to be broken in updating PRs at the moment, I think this config file is now required, so hopefully this should fix things.
For now this is a relatively basic config - my aim is to get something that _works_ and then we can iterate on configuration from there if we want to change it.
> Add CodeCov configuration

- src/sqlfluff/core/dialects/dialect_ansi.py
> Issue 430: Make the bare function segment dialect configurable

- .github/codecov.yml
The initial PR was not valid according the the codecov validator: https://docs.codecov.io/docs/codecov-yaml#validate-your-repository-yaml
This one is 😄
> Fix Codecov.yml

- src/sqlfluff/core/rules/std.py
- test/core/rules/test_cases/L031.yml
Resolves https://github.com/sqlfluff/sqlfluff/issues/635
> Handle non object_reference table references (e.g. lateral flatten function)

- setup.py
It seems this prevented installation
> Add sqlfluff.core.rules.std to setup.py

- src/sqlfluff/core/dialects/dialect_ansi.py
- test/fixtures/parser/ansi/create_table_a_pk_unique_fk_constraints.yml
> fix primary key is not a keyword #718

- src/sqlfluff/core/templaters/dbt.py
This addresses some of the errors I've been getting recently. I suspect they might be windows specific but I couldn't confirm that.
In general this adds some more specific error handling to the dbt templater to catch some edge cases better.
@dmateusp would you mind reviewing?
> Better error handling for dbt templater

- src/sqlfluff/core/dialects/dialect_ansi.py
- src/sqlfluff/core/rules/std/L015.py
- src/sqlfluff/core/rules/std/L020.py
- src/sqlfluff/core/rules/std/L025.py
- src/sqlfluff/core/rules/std/L026.py
- test/core/rules/test_cases/L025.yml
> Issue 404: Add fix routine for L025

- src/sqlfluff/core/rules/std/L017.py
- test/core/rules/test_cases/L017.yml
- test/fixtures/linter/autofix/ansi/005_function_spacing/after.sql
Fixes #598 .
@barrywhart - I've made this rule a bit safer. Do you think I've got the right balance of "auto-fixing what's easy" and "getting people to fix their own code"?
> Make L017 a bit safer

- .circleci/config.yml
> Run examples as part of test suite

- src/sqlfluff/core/rules/std/L039.py
- test/api/simple_test.py
- test/cli/commands_test.py
- test/core/rules/test_cases/L039.yml
> Add rule L039 for unnecessary whitespace

- .circleci/config.yml
- tox.ini
As mentioned in #742 
> should we have a windows-based circleci image to avoid those issues in the future?
This is that.
> Windows test environment

- src/sqlfluff/core/dialects/dialect_ansi.py
- test/core/parser/grammar_test.py
- test/fixtures/parser/postgres/postgres_join_no_space.sql
- test/fixtures/parser/postgres/postgres_join_no_space.yml
Fixes #607.
This isn't a very deep fix, and there might be other cases where something similar comes up like this, but this feels like the most pragmatic fix at the moment.
> Fix parsing error with no spaces #607

- CHANGELOG.md
- src/sqlfluff/config.ini
This resolves #470 🎉 🚀 
I'm going to wait to merge #603 before merging this, but otherwise this is almost ready to go.
> 0.4.0 Release PR

- src/sqlfluff/core/dialects/dialect_ansi.py
- test/core/dialects/snowflake_test.py
Just adding support for a missing case of permissions that can be granted to roles.
> Update the grant parser to also support managing permissions for roles.

- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/core/rules/std/L038.py
- src/sqlfluff/core/rules/std/L042.py
> Document config for rules

- .circleci/config.yml
- tox.ini
Kinda proves that https://github.com/sqlfluff/sqlfluff/issues/715 is maybe not as it seems?
> Add tests for dbt 0.19.0

- examples/04_getting_rules_and_dialects.py
- src/sqlfluff/__init__.py
- src/sqlfluff/api/__init__.py
- src/sqlfluff/api/info.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/dialects/__init__.py
- src/sqlfluff/core/linter.py
- test/api/info_test.py
This resolves #805 .
I've upgraded both the dialects and rules readouts to use NamedTuples for consistency. This also adds tests and examples.
> Dialect and Rules api

- src/sqlfluff/core/rules/std/L043.py
- test/core/rules/test_cases/L043.yml
Here's my attempt at #531. This is my first go at a SQLFluff PR, so hopefully I'm not too far off the mark 😅 
Thanks in advance for taking the time to review. Looking forward to get more involved in the project.
> #531: Use an explicit condition rather than case-when-bool

- CHANGELOG.md
- README.md
- setup.py
- src/sqlfluff/config.ini
There have been a significant number of bug fixes already so I thought it was worth pushing a version.
> Prepare for 0.4.1 release

- src/sqlfluff/core/dialects/dialect_snowflake.py
- test/fixtures/parser/snowflake/snowflake_secure_view.sql
- test/fixtures/parser/snowflake/snowflake_secure_view.yml
- test/fixtures/parser/snowflake/snowflake_secure_view_comment.sql
- test/fixtures/parser/snowflake/snowflake_secure_view_comment.yml
- test/fixtures/parser/snowflake/snowflake_view_comment.sql
- test/fixtures/parser/snowflake/snowflake_view_comment.yml
I took a try at #816. It's my first go at the parser and I've admittedly never used snowflake, so hopefully I'm not too far off the mark.
Thanks for taking a look!
EDIT:
Resolves #816
> Add secure, comment to snowflake create_statement

- src/sqlfluff/core/dialects/dialect_ansi.py
- src/sqlfluff/core/parser/lexer.py
- test/core/dialects/ansi_test.py
This resolves #847 .
Following on from #866, this addresses the rest of the outstanding bits and also adds a test case to make sure we catch all of them.
> Make sure all whitespace elements have is_whitespace

- src/sqlfluff/core/rules/std/L031.py
- test/fixtures/rules/std_rule_cases/L031.yml
> Issue 610: Rule L031 false positive when table appears twice in join

- src/sqlfluff/core/rules/std/L034.py
- src/sqlfluff/testing/rules.py
- test/fixtures/rules/std_rule_cases/L034.yml
> Issue 916: L034 should report the warning on the earlier, more complex select target

- src/sqlfluff/dialects/dialect_exasol.py
Last occurrence. Resolves #650
> Optional bracketing

- docs/source/inthewild.rst
Adding Drizly into SQLFluff in the wild! :)
> Add Drizly to sqlfluff in the wild

- docs/source/inthewild.rst
Saw a few ppl doing this, so I thought your friends at Petal ought to join in the fun 🎉
> Adding Petal to in the wild

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/parser/snowflake/snowflake_sample.sql
- test/fixtures/parser/snowflake/snowflake_sample.yml
Resolves #547.
Looks like I implemented this syntax ages ago but just did a really bad job. This fixes it so that it works again and adds a test case.
> Fix and test snowflake sample syntax

- src/sqlfluff/dialects/dialect_postgres.py
- test/dialects/postgres_test.py
Resolves #926 (which I opened).
This is my first SQLFluff PR; please LMK if I should do anything differently. 🙂
> change SPACE to have no special keyword status in Postgres dialect

- .github/PULL_REQUEST_TEMPLATE/bug_fix.md
- .github/PULL_REQUEST_TEMPLATE/new_feature.md
- .github/PULL_REQUEST_TEMPLATE/refactor.md
- .github/PULL_REQUEST_TEMPLATE/release.md
Following on from issue template, this is my stab at PR templates. In particular I'd like to prompt people to update the `CHANGELOG.md` more diligently to make the release cycle easier.
> Pull request templates

- CHANGELOG.md
- src/sqlfluff/core/rules/analysis/select_crawler.py
- src/sqlfluff/core/rules/std/L045.py
- test/fixtures/rules/std_rule_cases/L045.yml
> Issue 944: L045 false positive when CTE used in WHERE clause

- src/sqlfluff/core/rules/std/L019.py
- test/fixtures/rules/std_rule_cases/L019.yml
> Fix bug for fixing comma placements with inline comment

- docs/source/configuration.rst
- src/sqlfluff/__main__.py
> Correct typo sqfluff

- src/sqlfluff/core/rules/std/L043.py
- test/fixtures/rules/std_rule_cases/L043.yml
> Issue 972: sqlfluff fix returns broken coalesce statement

- src/sqlfluff/diff_quality_plugin.py
> Issue 975: Add rule code to diff_cover output

- src/sqlfluff/core/linter.py
- test/core/linter_test.py
> Issue 976: "noqa" directive uses incorrect line numbers when templating enabled

- docs/source/inthewild.rst
> Add Surfline to SQLFluff in the Wild

- docs/source/configuration.rst
- docs/source/index.rst
- docs/source/teamrollout.rst
Resolves #286.
I've been meaning to write this for a while. Would love people's input on the thrust of it. In particular @NiallRees, who I know has done some thinking about this.
> New team rollout ideas

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/parser/postgres/postgres_filter.sql
- test/fixtures/parser/postgres/postgres_filter.yml
> Add filter grammar

- src/sqlfluff/core/parser/grammar/sequence.py
- test/dialects/ansi_test.py
This resolves #1068.
Silly typo was the issue, most of this PR is a test case to make sure we (I) don't break it again. 🤦
> Fix Conditional indents + tests

- docs/source/architecture.rst
> Architecture docs rewrite

- CHANGELOG.md
- src/sqlfluff/rules/L034.py
- test/fixtures/rules/std_rule_cases/L034.yml
> L034 should ignore union statements

- CHANGELOG.md
- src/sqlfluff/core/config.py
- test/core/config_test.py
> #889 Use linux style xdg on mac

- CHANGELOG.md
I accidentally left out some details in the CHANGELOG for changes I made. I also corrected one of the previous entries to be in line with previous entries and reviewer comments concerning entry verbiage.
> Corrections to CHANGELOG

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/parser/snowflake/multiple_shorthand_casts.sql
- test/fixtures/parser/snowflake/multiple_shorthand_casts.yml
A parsing bug I came across the other day.
> Support sequential shorthand casts

- CHANGELOG.md
- tox.ini
dbt 0.20.0 adds some big changes (some which I suspect break the dbt templater). This adds it to the test suite, and if anything breaks then I'll also add the changes to fix it.
> Add dbt 0.20.0 to test suite

- .circleci/config.yml
- CHANGELOG.md
- src/sqlfluff/core/templaters/dbt.py
Resolves #1218 (and also enables the 0.20.* dbt test case in the automated testing - which I missed before).
@dmateusp - would you mind reviewing because this is a patch of code which you originally wrote?
> Enable the dbt 0.20.0 tests in production and fix templating.

- test/cli/commands_test.py
> Do not check the path in the GitHub annotation test so it'll work on Windows

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_teradata.py
- test/fixtures/parser/teradata/collect_stats.yml
- test/fixtures/parser/teradata/collect_stats_2.sql
- test/fixtures/parser/teradata/collect_stats_2.yml
- test/fixtures/parser/teradata/comment_on_column_stmt.sql
- test/fixtures/parser/teradata/comment_on_column_stmt.yml
- test/fixtures/parser/teradata/comment_on_table_stmt.sql
- test/fixtures/parser/teradata/comment_on_table_stmt.yml
- test/fixtures/parser/teradata/create_table.sql
- test/fixtures/parser/teradata/create_table.yml
- test/fixtures/parser/teradata/create_table_stmt_4.sql
- test/fixtures/parser/teradata/create_table_stmt_4.yml
Hello,
this pull request updates teradata dialect parser reported in #1231 (according to grammar rules in Teradata documentation)
Please review this PR, I'll make changes if there is something not right or missing.
Thank you
> Improved DDL script parsing for teradata dialect

- CHANGELOG.md
- src/sqlfluff/rules/L019.py
- test/fixtures/linter/autofix/ansi/019_trailing_comma_to_leading/.sqlfluff
- test/fixtures/linter/autofix/ansi/019_trailing_comma_to_leading/after.sql
- test/fixtures/linter/autofix/ansi/019_trailing_comma_to_leading/before.sql
- test/fixtures/linter/autofix/ansi/019_trailing_comma_to_leading/test-config.yml
- test/rules/std_test.py
> Issue 939: Comma is removed when fixing query with multiple CTEs

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/parser/bigquery/select_function_object_field.sql
- test/fixtures/parser/bigquery/select_function_object_field.yml
- tox.ini
> Support accessing function field names

- CHANGELOG.md
- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/rules/L007.py
- test/fixtures/rules/std_rule_cases/L007.yml
> Add optional end of line operators config for L007

- CHANGELOG.md
- docs/source/inthewild.rst
Also did some other clean up on the CHANGELOG.
> Add HTTP Archive entry to In the Wild page

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/parser/bigquery/select_mixture_of_array_literals.sql
- test/fixtures/parser/bigquery/select_mixture_of_array_literals.yml
> Add Array from Struct support for BigQuery

- CHANGELOG.md
- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/parser/bigquery/select_with_qualify.sql
- test/fixtures/parser/bigquery/select_with_qualify.yml
Fixes #1242 
Mostly based on #1193
> Add QUALIFY clause to BigQuery

- .github/PULL_REQUEST_TEMPLATE.md
- Other： just fix some typo in github PR template
> Fix typo in github PR template

- src/sqlfluff/__init__.py
Just some simple change for error python version hint
Just some simple change for error python version hint
> Show latest version number on unsupported Python error message

- src/sqlfluff/rules/L011.py
> Remove unused variable insert_str

- CONTRIBUTING.md
- README.md
- docs/source/api.rst
- docs/source/conf.py
- docs/source/configuration.rst
- docs/source/gettingstarted.rst
- docs/source/indentation.rst
- docs/source/inthewild.rst
Noticed a few occurrences to fix.
> Minor grammar corrections to documentation

- CONTRIBUTING.md
- README.md
Updated documentation with the following changes:
- Spelling and grammar fixes (primarily comma usage)
- Conciseness improvements (removal of filler phrases like "actually")
- Removal of contractions to provide a more formal tone, and improve ease of understanding for non-native English speakers
N/A
- Other. …
> Minor grammar, spelling, and readability fixes

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/parser/postgres/postgres_create_index.sql
- test/fixtures/parser/postgres/postgres_create_index.yml
More Postgres functionality! Added the dialect-specific CREATE INDEX block
Fixes #1322
No.
All examples in the Postgres docs are used, and passing, as tests.
> Postgres enhance create index

- src/sqlfluff/rules/L008.py
- tox.ini
ATT, remove unused deps in tox job
> Remove unused deps in tox test docbuild

- src/sqlfluff/core/parser/segments/base.py
- test/dialects/dialects_test.py
- test/fixtures/parser/ansi/comments.sql
- test/fixtures/parser/ansi/comments.yml
> Fix generate error on test file with just a comment

- CHANGELOG.md
- src/sqlfluff/config.ini
We've made a number of improvements to the fixing rules (amongst other changes!) so think we should do a release even though 0.6.5 was not that long ago.
Will aim to release afternoon/evening of Monday 20th September so comment here if you're working on a change you think will be finished before then and you'd like to include.
None
- Other.
- …
> Release v0.6.6

- CHANGELOG.md
- src/sqlfluff/config.ini
Break fix release to fix issue introduced in 0.6.7 for DBT
Also includes a small T-SQL fix merged since.
Hopefully not this time!
- Other.
> Prepare v0.6.8

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/documention.md
- .github/ISSUE_TEMPLATE/enhancement.md
- .github/PULL_REQUEST_TEMPLATE.md
Comments out the instructions so they will only be seen by the issue/PR raiser and not in the issue.PR
Nope
- Other.
> Comment out instructions in GitHub templates

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/create_table_temporary_external.sql
- test/fixtures/dialects/hive/create_table_temporary_external.yml
fixes #1824, just changed the grammar order such that "TEMPORARY" precedes "EXTERNAL".
No
- New test case added, and passing
> Hive: fixed hive create temporary external table

- CHANGELOG.md
- plugins/sqlfluff-templater-dbt/setup.py
- src/sqlfluff/config.ini
Release 0.8.1 to fix an issue with 0.8.0
Hopefully not this time!
- Other.
> Prepare 0.8.1

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/drop_procedure.sql
- test/fixtures/dialects/tsql/drop_procedure.yml
> Add DROP PROCEDURE statement to T-SQL

- src/sqlfluff/rules/L043.py
- test/fixtures/rules/std_rule_cases/L043.yml
This PR enhances L043 to fix #1797. I have also tidied up the docstring and added the corresponding unit tests.
L043 should now flag and fix more cases of unnecessary use of CASE. 
- Other.
> L043 refinement: Add autofix for common use of CASE to fill NULL values.

- src/sqlfluff/rules/L055.py
Super quick PR: Realised that I hadn't updated a comment when creating L055 so correcting.
No
- Other.
> Fix incorrect comment on L055

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/config.py
- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/rules/base.py
- test/fixtures/config/glob_exclude/test.sql
- test/fixtures/config/glob_include/test.sql
Following from discussion in #1972 we are renaming whitelist/blacklist to allowlist/denylist. This is a simple renaming and these names are only used internally so this PR has no impact on the any user facing code.
No
- Other.
> Rename whitelist/blacklist to allowlist/denylist

- .gitattributes
Fixes #2032
GitHub uses [Linguist](https://github.com/github/linguist) to determine language statistics in the repo.
Our language stats currently show 99.9% Python and 0.1 Dockerfile but no SQL.
On further investigation it appears Linguist has a list of vendored file paths that are excluded from the statistics and one of those is test/fixtures, which is where all of our SQL is stored.(https://github.com/github/linguist/blob/c8ca48856b1998681cdf1c1234145532006f95d8/lib/linguist/vendor.yml#L317)
Linguist provides the ability to override default behaviour via the .gitattributes file (https://github.com/github/linguist/blob/master/docs/overrides.md)
Given the projects focus on SQL we feel it would be nice to include the SQL files in our language statistics as it indicates to potential …
> Linguist: Include test/** in language statistics to better reflect use of SQL

- .github/ISSUE_TEMPLATE/bug_report.md
dbt 1.0.0 currently does not work with sqlfluff. This is being looked at in #2052. To help determine if dbt issues are existing bugs or a result of the new release it would be helpful to request the users dbt version in the bug_report template. 
No
- Other.
> Add request for users dbt version in bug_report issue template

- .pre-commit-config.yaml
- CONTRIBUTING.md
- tox.ini
This PR adds a basic pre-commit config to the project. This allows developers to run the linting/typing checks automatically at commit time. I know I'm not the only one who opens a PR only to realise the CI failed because I forgot to run black, so this is a nice convenience 😄
An important thing to note is that this isn't intended to provide extra checks compared to the CI, just as an easy way to automate these checks locally 👍 
I've also added a section to `CONTRIBUTING.md` to let people know how to get the pre-commit hooks setup.
N.B. for those not familiar with pre-commit, it only runs on staged files so is a quick check.
No, it's optional (but very convenient for devs to start using).
- …
> Add basic pre-commit config

- .pre-commit-config.yaml
Follow up PR to #2067. Adds a pre-commit hook to also run our doc linting at commit time.
No
- Other.
> Pre-commit: Add hook for doc8

- plugins/sqlfluff-templater-dbt/test/templater_test.py
I made a few tweaks to some dbt templater tests, following up the PR review for #2079.
- Other.
> Some tweaks suggested in the PR review

- examples/01_basic_api_usage.py
Adds example of Simple API parse JSON usage. Follows from discussion in #2082.
No
- Other.
> Add example for using JSON output of Simple API parse function

- CONTRIBUTING.md
I added some [A Git wiki](https://github.com/sqlfluff/sqlfluff/wiki) a while back, but never added it to our CONTRIBUTING.md file so not everyone will find it. This PR adds those links.
Nope
- Other.
> Add wiki links to CONTRIBUTING.md

- src/sqlfluff/__init__.py
This fixes mypy (which is also part of this project's pre-commit hooks) when developing locally with python 3.7.
Thanks @jpy-git for the help in https://github.com/sqlfluff/sqlfluff/pull/2144#issuecomment-998304477.
The error before this change:
```
$ mypy src/sqlfluff --ignore-missing-imports
src/sqlfluff/__init__.py:12: error: Module "importlib" has no attribute "metadata"
src/sqlfluff/__init__.py:12: error: Name "metadata" already defined (by an import)
Found 2 errors in 1 file (checked 154 source files)
```
With this fix:
```
$ mypy src/sqlfluff --ignore-missing-imports
Success: no issues found in 154 source files
```
Now I was able to run the pre-commits:
```
Fix End of Files.........................................................Passed
Trim Trailing …
```
> Fix mypy error on python 3.7

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_unpivot.sql
- test/fixtures/dialects/bigquery/select_unpivot.yml
Fixes #2153 
Nope. Simple bug fix
- Other.
> Fix bug with BigQuery UNPIVOT

- src/sqlfluff/rules/L041.py
- test/rules/std_fix_auto_test.py
Just fixing some comments that were a bit wrong.
No
- Other.
> Minor comment fixes

- .pre-commit-config.yaml
- mypy.ini
- requirements_dev.txt
I added the type stubs for the `regex` package into `typeshed` in this [PR](https://github.com/python/typeshed/pull/6713). Now we can have the regex sections of our code type checked 🎉 
No
- Other.
> Add types-regex package for type checking

- plugins/sqlfluff-templater-dbt/test/templater_test.py
- tox.ini
> jy_cleanup

- CONTRIBUTING.md
Add regexs and other improvements to release checklist
Nope just documentation
- Other.
> Improve release checklist to make releases easier

- src/sqlfluff/dialects/dialect_spark3.py
- test/fixtures/dialects/spark3/use_database.sql
- test/fixtures/dialects/spark3/use_database.yml
Class to match `USE DATABASE` syntax and appropriate test cases.
N/A
- Other.
> Spark3: Coverage for `USE DATABASE` statement.

- CONTRIBUTING.md
Add a paragraph to describe on how to run SQLFluff if changed locally.
Closes #2313 
No
- Other.
> docs: Document how to run SQLFluff with local changes to test them

- src/sqlfluff/rules/L044.py
- test/fixtures/rules/std_rule_cases/L025.yml
- test/fixtures/rules/std_rule_cases/L044.yml
- test/fixtures/rules/std_rule_cases/L045.yml
> Fix L044 assertion failure with delete stmt & cte

- docs/source/architecture.rst
- docs/source/configuration.rst
- docs/source/developingrules.rst
- docs/source/index.rst
- docs/source/rules.rst
- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/rules/base.py
Fixes #2286 and also cleans up a few other things to be more clear and consistent
Nope
- Other.
> Various documentation updates

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/use_dbt_utils.sql
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/templated_output/use_dbt_utils.sql
> Fix "connection already closed" issue with dbt 1.0 and dbt_utils

- docs/source/_static/custom.css
> Fix unnecessary white underline in doc site

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/redshift/redshift_update.sql
- test/fixtures/dialects/redshift/redshift_update.yml
> Allow UPDATE SET statements in RedShift

- src/sqlfluff/rules/L061.py
- test/fixtures/rules/std_rule_cases/L061.yml
> New rule L061 to use != over <>

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_function.yml
- test/fixtures/dialects/tsql/function_no_return.yml
- test/fixtures/dialects/tsql/function_with_variable.yml
- test/fixtures/dialects/tsql/functions_a.yml
- test/fixtures/dialects/tsql/hints.yml
- test/fixtures/dialects/tsql/merge.yml
- test/fixtures/dialects/tsql/minimal_function.yml
- test/fixtures/dialects/tsql/minimal_function_no_alter.yml
- test/fixtures/dialects/tsql/print.yml
- test/fixtures/rules/std_rule_cases/L028.yml
Fixes #1868 
Shouldn't be
- Other.
> Fix rule L028 for T-SQL for params

- src/sqlfluff/dialects/dialect_spark3.py
- test/fixtures/dialects/spark3/load_data.sql
- test/fixtures/dialects/spark3/load_data.yml
`LoadDataSegment` and test cases to for LOAD DATA statement in Spark3.
N/A
- Other.
> Spark3: Support for `LOAD DATA` statements

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/insert_statement.sql
- test/fixtures/dialects/tsql/insert_statement.yml
T-SQL allows inserting the result of a stored procedure, and this PR adds it to `sqlfluff`
Fixes: #2444
No
- Other.
> T-SQL: Support stored procedures in insert statements

- src/sqlfluff/rules/L026.py
- test/fixtures/rules/std_rule_cases/L026.yml
> Fix bug with L026 for simple deletes

- src/sqlfluff/rules/L054.py
- test/fixtures/rules/std_rule_cases/L054.yml
> Exclude WINDOW clauses from L054

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_table_primary_foreign_keys.sql
- test/fixtures/dialects/mysql/create_table_primary_foreign_keys.yml
> Support Foreign Key options for MySQL

- docs/source/developingrules.rst
Adds BaseRule docs to https://docs.sqlfluff.com/en/stable/developingrules.html
Nope.
- Other.
> Add base rule to developing rules page

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/system-variables.sql
- test/fixtures/dialects/tsql/system-variables.yml
> Support T-SQL system variables (e.g. @@rowcount)

- CHANGELOG.md
- plugins/sqlfluff-templater-dbt/setup.cfg
- setup.cfg
We released 0.9.2 a few days ago but have been made away of a few issues linting files, which have been fixed so keen to get a new version out.
However GitHub actions seems to be stalling on some of our CI tests so will wait for that to settle, and merge #2473 and #2479 (and whatever else is ready) before releasing.
- Other. …
> Prepare 0.9.3 release

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
Implements the change suggested in dbt Slack: https://getdbt.slack.com/archives/CV2KM39KR/p1643309430065900
- Other.
> dbt templater: For performance reasons, cache the database connection across models

- docs/source/inthewild.rst
Add a reference to the dbt_artifacts dbt package in the docs.
> Add dbt_artifacts package to in the wild docs

- requirements_dev.txt
- src/sqlfluff/core/linter/common.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/templaters/jinja.py
- test/core/linter_test.py
> "noqa": Add support for ignoring template (TMP) and parse (PRS) errors

- test/fixtures/dialects/spark3/select_having.sql
- test/fixtures/dialects/spark3/select_having.yml
Additional test cases for Spark3
N/a
- Other.
> Spark3: test cases for `HAVING` clause in `SELECT` statement

- CHANGELOG.md
- plugins/sqlfluff-templater-dbt/setup.cfg
- setup.cfg
Bumps version to 0.9.4 in preparation of a new release to fix a `click` dependency error.
Hope not.
- Other.
> Prepare 0.9.4

- docs/source/production.rst
Given the comments on [this issue](https://github.com/sqlfluff/sqlfluff/issues/2390) I've added additional documentation on how you can customize adapters
None
No tests to write, as just the documentation was updated
> Add additional documentation on dbt-adapter in pre-commit

- docs/source/configuration.rst
> Fix typo in sqlfluffignore docs

- src/sqlfluff/rules/L054.py
- test/fixtures/rules/std_rule_cases/L054.yml
> Snowflake: L054 should ignore "WITHIN GROUP" clauses

- docs/source/configuration.rst
- src/sqlfluff/core/default_config.cfg
**I accidentally deleted the branch containing the first version of this PR, which cause GitHub to irrevocably close the PR. Creating a new PR with the same contents.)**
Fixes #831
- Other.
> Add/Improve docs for config settings: "ignore", "ignore_templated_areas"

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_spark3.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/ansi/create_view_a.sql
- test/fixtures/dialects/ansi/create_view_a.yml
- test/fixtures/dialects/snowflake/snowflake_create_view.sql
- test/fixtures/dialects/snowflake/snowflake_create_view.yml
Fixes #2595
Corrected in quite a few dialects but only added test cases for two
- Other.
> Support CTEs in CREATE VIEW statements

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_mixture_of_array_literals.yml
- test/fixtures/dialects/bigquery/select_struct.sql
- test/fixtures/dialects/bigquery/select_struct.yml
> BigQuery support Array of Structs

- test/fixtures/dialects/spark3/select_order_by.sql
- test/fixtures/dialects/spark3/select_order_by.yml
Additional test cases for `ORDER BY` clause in a `SELECT` statement.
N/A
- Other.
> Spark3: Test Cases for `ORDER BY` in `SELECT`

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_pivot.sql
- test/fixtures/dialects/bigquery/select_pivot.yml
- test/fixtures/dialects/bigquery/select_unpivot.sql
- test/fixtures/dialects/bigquery/select_unpivot.yml
- test/fixtures/rules/std_rule_cases/L059.yml
Fixes #2616
Also fixes small issue with `PIVOT` statement not accepting multiple functions, that I noticed while looking if same fix needed to be applied there (it doesn't).
Nope
- Other.
> BigQuery UNPIVOT and PIVOT fixes

- src/sqlfluff/rules/L001.py
Fixes #2635
I wasn't able to reproduce the issue, so no test added, but the stack trace in the issue makes it pretty clear what's crashing, and it's easy to avoid.
- Other.
> Fix IndexError in L001

- src/sqlfluff/core/rules/analysis/select.py
- test/fixtures/rules/std_rule_cases/L025.yml
> Bug fix: L025 should consider BigQuery QUALIFY clause

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_delete.sql
- test/fixtures/dialects/postgres/postgres_delete.yml
Fixes #2638 
Note I've left some syntax as TODO as not well defined in Postgres docs with no Examples so will leave to someone with Postgres access to define later.
- Other.
> Postgres enhanced DELETE FROM syntax

- src/sqlfluff/rules/L033.py
- test/fixtures/rules/std_rule_cases/L033.yml
Fixes #2660 
Nope simple enough one this
- Other.
> Support L033 for RedShift

- test/fixtures/dialects/spark3/case_clause.sql
- test/fixtures/dialects/spark3/case_clause.yml
Additional test cases for spark3 dialect
N/A
- Other.
> Spark3: test cases for `CASE` clause

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_identifiers.sql
- test/fixtures/dialects/bigquery/select_identifiers.yml
> BigQuery: allow identifiers starting with dash

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_spark3.py
- test/fixtures/dialects/ansi/table_expression.sql
- test/fixtures/dialects/ansi/table_expression.yml
- test/fixtures/dialects/bigquery/create_temp_function_with_select.yml
- test/fixtures/dialects/bigquery/select_with_offset.yml
Fixes #2787 
Redefined and simplified the `FromExpressionElementSegment` to allow this to be parsed correctly.
- Other.
> BigQuery support UNEST aliases

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_insert.sql
- test/fixtures/dialects/snowflake/snowflake_insert.yml
Adds complete INSERT grammar (both single and multi table versions) to Snowflake dialect.
No
- Other.
> Snowflake: Complete `INSERT` grammar

- CHANGELOG.md
Release dragged on and forgot to update date.
Nope
- Other.
> Correct 0.11.0 release date in CHANGELOG

- src/sqlfluff/core/rules/functional/segments.py
- src/sqlfluff/rules/L042.py
- test/dialects/dialects_test.py
- test/fixtures/dialects/ansi/with_nested_in_with_statement.sql
- test/fixtures/rules/std_rule_cases/L042.yml
Reverts sqlfluff/sqlfluff#2795
> Revert "L042 Autofix - (CTE hoisting) Super Working PR"

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/redshift_datetime_cast.sql
- test/fixtures/dialects/redshift/redshift_datetime_cast.yml
> Redshift: Add support for AT TIME ZONE

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/redshift_transactions.sql
- test/fixtures/dialects/redshift/redshift_transactions.yml
Redshift transaction segment as specified in the documentation.
nope
- Other.
> Redshift: transaction statement

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/bigquery_parameters.sql
- test/fixtures/dialects/bigquery/bigquery_parameters.yml
> BigQuery: support Parameterized Numeric Literals

- src/sqlfluff/rules/L042.py
- test/fixtures/rules/std_rule_cases/L042.yml
> L042: Detect violations when column is templated

- docs/source/configuration.rst
Nowadays, we often get questions in Slack from SQLFluff users where they think it's a SQLFluff "bug" that their dbt models won't lint without a database, possibly failing in strange ways. I think they expect more of a "turnkey" experience than they are getting. This is an attempt to set some context so people are aware that setting up the `dbt` templater can be a fairly technical experience. I think this is helpful information, and I hope it will encourage more discussion and exchange of ideas and less of "SQLFluff has a bug". Ideally, this could lead to some user-contributed docs or examples, similar to that for SQLFluff GitHub Actions. …
> Documentation: Update dbt templater docs with more detail about pros and cons

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/.sqlfluffignore
- plugins/sqlfluff-templater-dbt/test/linter_test.py
- plugins/sqlfluff-templater-dbt/test/templater_test.py
> dbt templater should gracefully skip macro files

- src/sqlfluff/core/templaters/jinja.py
- test/core/templaters/jinja_test.py
> Jinja: Add support for Block Assignments

- pytest.ini
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/rules/L043.py
- test/fixtures/rules/std_rule_cases/L043.yml
> Fix bug where L043 corrupts SQL

- src/sqlfluff/rules/L010.py
- src/sqlfluff/rules/L030.py
- src/sqlfluff/rules/L040.py
- test/fixtures/rules/std_rule_cases/L010.yml
> Adjust L010 to ignore nulls and booleans covered by L040

- src/sqlfluff/dialects/dialect_spark3.py
- test/fixtures/dialects/spark3/join_types.sql
- test/fixtures/dialects/spark3/join_types.yml
> Spark3: Fix bug which did not allow multiple joins

- CHANGELOG.md
- plugins/sqlfluff-templater-dbt/setup.cfg
- setup.cfg
There's a bugfix in here which I'd love to get live (because it hit me today 🤷 - thanks @barrywhart  for #2887!).
Feels like a good time to get a small incremental release in. I didn't add a _notable changes_ section at the top because this feels like a very bugfixy release.
> 0.11.2 Release

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/tsql/merge.sql
- test/fixtures/dialects/tsql/merge.yml
> TSQL: Supported nested `MERGE` statements

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/explain.yml
- test/fixtures/dialects/mysql/update.sql
- test/fixtures/dialects/mysql/update.yml
in UpdateStatementSegment
followup to #2982 and #2832, add test case in update.sql as well
try to tackle with query like
```update a join b on a.id = b.id set a.type = b.type where a.type is null```
> MySQL: Allow `JOIN`s in `UPDATE` expressions

- .github/workflows/publish-sqlfluff-docker-image-to-dockerhub.yaml
Adds Dialect to Docker test to allow deploy to Docker
- Other.
> Add dialect to Docker test

- docs/source/inthewild.rst
Add Carepay to SQLFluff in the wild
- Other.
> Add CarePay to SQLFluff in the wild

- src/sqlfluff/core/rules/functional/segment_predicates.py
- src/sqlfluff/rules/L007.py
- test/fixtures/rules/std_rule_cases/L007.yml
> L007 should ignore templated newlines

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/ansi/create_function.yml
- test/fixtures/dialects/ansi/create_function_no_args.yml
- test/fixtures/dialects/ansi/create_zero_argument_function.yml
- test/fixtures/dialects/bigquery/create_function_no_args.yml
- test/fixtures/dialects/bigquery/create_js_function_complex_types.yml
- test/fixtures/dialects/bigquery/create_js_function_deterministic.yml
- test/fixtures/dialects/bigquery/create_js_function_options_library_array.yml
- test/fixtures/dialects/bigquery/create_js_function_quoted_name.yml
- test/fixtures/dialects/bigquery/create_js_function_simple.yml
- test/fixtures/dialects/bigquery/create_js_function_underscore_name.yml
- test/fixtures/dialects/postgres/postgres_create_dollar_quoted_function.yml
- test/fixtures/dialects/postgres/postgres_create_function.sql
- test/fixtures/dialects/postgres/postgres_create_function.yml
- test/fixtures/dialects/postgres/postgres_create_procedure.yml
- test/fixtures/dialects/postgres/postgres_create_zero_argument_function.yml
- test/fixtures/dialects/postgres/postgres_do.yml
- test/fixtures/dialects/redshift/redshift_create_procedure.yml
Fixes #3056
Nope
- [ x Please confirm you have completed any of the necessary steps below.
- Other.
> Postgres: Support quoted `LANGUAGE` params

- test/fixtures/dialects/sparksql/delta_delete_from.sql
- test/fixtures/dialects/sparksql/delta_delete_from.yml
Additional test cases
N/A
- Other.
> SparkSQL: Test cases for Delta `DELETE FROM` syntax

- docs/source/production.rst
- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/enums.py
- test/cli/commands_test.py
Makes progress on #3106
This is (for now) a PoC for adding native Github Actions annotation capabilities. The code is essentially copy/pasted from `yamllint` github action implementation and added to SQLFluff.
Here is a small demo how this would look like when using in Github Actions: https://github.com/dmohns/sqlfluff-test-github-action-annotation/pull/1/files
Before continuing to work on that I would like to understand if this feature has a place in SQLFluff.
If we continue to work on this, there is a few questions to be considered:
- Do we continue to maintain both "github-annotation" output formats?
- Option 1: Replace "old" `github-annotation` with github-annotation native. This will probably break existing pipelines
- Option 2: Add a new `github-annotation-native` format for now, …
> Add native Github-actions output

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/bigquery/select_extract.yml
- test/fixtures/dialects/postgres/postgres_select.yml
- test/fixtures/dialects/redshift/redshift_datetime_cast.sql
- test/fixtures/dialects/redshift/redshift_datetime_cast.yml
Fixes #3111 
Shouldn't be, but it is a change to our core expression grammar.
- Other.
> ANSI `AT TIME ZONE` parsing improvements

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/convert.sql
- test/fixtures/dialects/tsql/convert.yml
This adds support for T-SQL's `try_convert`
Fixes #3137
No
- Other.
> TSQL: Support `TRY_CONVERT`

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/delete_azure_synapse_analytics.sql
- test/fixtures/dialects/tsql/delete_azure_synapse_analytics.yml
- test/fixtures/dialects/tsql/insert_statement.sql
- test/fixtures/dialects/tsql/insert_statement.yml
Add missing table hints to `insert` and `delete`
Fixes #3136
- Other.
> TSQL: Add table hints to `INSERT` and `DELETE`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_composite_types.sql
- test/fixtures/dialects/postgres/postgres_composite_types.yml
Fixes #3050 by following the same methods as BigQuery and Snowflake
No
- Other.
> Postgres: Support Composite Types

- src/sqlfluff/core/templaters/jinja.py
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/rules/std_rule_cases/L020.yml
Fixes #3174 
I had to remove some type ignores added by @OTooleMichael in #3168 to get pre-commit to pass.
- Other.
> T-SQL: Fix exception when using variable names in `FROM` clause

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/postgres/postgres_create_materialized_view.sql
- test/fixtures/dialects/postgres/postgres_create_materialized_view.yml
> Postgres: Enhanced `CREATE MATERIALIZED VIEW`

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/delete.sql
- test/fixtures/dialects/bigquery/delete.yml
> BigQuery: Better `DELETE` table support

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_struct.sql
- test/fixtures/dialects/bigquery/select_struct.yml
Fixes #3211
Cleaned up some of the duplicated `ARRAY` code while at it so they are more aligned.
- Other.
> BigQuery: Better `STRUCT` support

- src/sqlfluff/rules/L003.py
- test/fixtures/rules/std_rule_cases/L003.yml
> L003 bug fix: Not ignoring templated newline

- docs/source/configuration.rst
fixes #3299 
Nope.
- NA: `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
- NA:`.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).
- NA: Full autofix test cases in `test/fixtures/linter/autofix`.
> Fix typo in Configuration documentation

- README.md
- docs/source/dialects.rst
- plugins/sqlfluff-templater-dbt/setup.cfg
- setup.cfg
- src/sqlfluff/core/dialects/__init__.py
- src/sqlfluff/core/dialects/base.py
- src/sqlfluff/dialects/dialect_soql.py
- test/cli/autocomplete_test.py
- test/fixtures/dialects/soql/.sqlfluff
- test/fixtures/dialects/soql/select_where_date_literals.sql
- test/fixtures/dialects/soql/select_where_date_literals.yml
Gets the SOQL dialect started. It adds just one feature. I think it should close https://github.com/sqlfluff/sqlfluff/issues/2465 and we can file issues for the other needed items.
It's worth assessing whether enough people want SOQL to justify having it / if this is enough of a start to justify merging this. Some issues I plan to file if this is merged (will add details within the individual issues):
- `:n` comparions like `SELECT Id FROM Opportunity WHERE CloseDate > NEXT_N_DAYS:15`
- Allow select from nested object like `SELECT Account.Name FROM Contact`
- Disallow `SELECT *` and `COUNT(*)`
- Disallow DDL/DML/DCL etc. (SOQL is read-only)
- Disallow ending statements with semicolons (seems like we can only do one statement per file)
- Disallow `JOIN`
- Disallow `SELECT DISTINCT` and …
> Start SOQL dialect

- docs/source/gettingstarted.rst
- docs/source/index.rst
The Getting Started samples did not work correctly for a brand new user. It was an effect of the recent change making dialect mandatory. (README.md was updated for this change, but index.rst and gettingstarted.rst had not been updated. Further, some of the output has changed (because of rule changes). I updated the output to reflect this.
Per Barry P's comment last time, I did not create an issue ahead of time.
None that I know of.
- …
> Update Docs: Getting Started and Index

- src/sqlfluff/dialects/dialect_soql.py
- test/fixtures/dialects/soql/select_where_date_n_literals.sql
- test/fixtures/dialects/soql/select_where_date_n_literals.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/3321
It's possible it goes somewhere besides `Expression_C_Grammar`.
- Other.
> SOQL: Support date_n_literal

- src/sqlfluff/rules/L025.py
- test/fixtures/rules/std_rule_cases/L025.yml
Fixes #3301 
Shouldn't be
- Other.
> L025: exclude `VALUES` clauses

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/redshift/window_functions.sql
- test/fixtures/dialects/redshift/window_functions.yml
> All dialects: Allow `RESPECT NULLS`/`IGNORE NULLS` in window functions

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/repeat_label.yml
- test/fixtures/dialects/mysql/repeat_multiple_statements.yml
- test/fixtures/dialects/mysql/repeat_no_label.yml
- test/fixtures/dialects/mysql/set_session_variable_expression.sql
- test/fixtures/dialects/mysql/set_session_variable_expression.yml
- test/fixtures/dialects/mysql/while_label.yml
- test/fixtures/dialects/mysql/while_no_label.yml
fixes #3392
Minor updates to parse structure of some MySQL tests.
- Included test cases to demonstrate any code changes:
- Added 2 tests to set_session_variable_expression.sql
> MySQL: Improve SET Syntax for Variable Assignment

- requirements_dev.txt
> Unpin coverage now issue 6.3 has been resolved

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_create_schema.sql
- test/fixtures/dialects/snowflake/snowflake_create_schema.yml
- test/fixtures/dialects/snowflake/snowflake_create_stream.yml
fixes #3413
No
- One new test added: `.sql`/`.yml` parser test cases in `test/fixtures/dialects` 
- One old parse structure update`.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
> SNOWFLAKE: Fully referenced object names in clone statements

- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/issue_1608.sql.after
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/use_var.sql
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/templated_output/use_var.sql
- src/sqlfluff/rules/L036.py
- test/fixtures/rules/std_rule_cases/L036.yml
- test/rules/std_L003_L036_L039_combo_test.py
- test/rules/std_L003_L065_combo_test.py
> L036: Treat wildcard as multiple select targets (i.e. separate line)

- README.md
Remove a reference to a non-implemented dialect.
n/a
- Other.
> Remove Delta Lake Reference in README.md

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/redshift_object_unpivot.sql
- test/fixtures/dialects/redshift/redshift_object_unpivot.yml
Fixes issue raised on slack
Nope
- Other.
> Redshift: Support Object unpivoting

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_select_stages_files.sql
- test/fixtures/dialects/snowflake/snowflake_select_stages_files.yml
> Snowflake: Support Stage data file parameters in `FROM` clauses

- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sparksql_keywords.py
- test/fixtures/dialects/sparksql/delta_describe_detail.sql
- test/fixtures/dialects/sparksql/delta_describe_detail.yml
created DescribeDetailStatementSegment and added appropriate test cases
- not included as part of DescribeDetailStatement since this isn't native spark sql and requires delta
- Other.
> SparkSQL: Support for the Delta `DESCRIBE DETAIL` command

- src/sqlfluff/rules/L045.py
- test/fixtures/rules/std_rule_cases/L045.yml
> L045: Add handling for nested queries and CTEs

- src/sqlfluff/rules/L026.py
- test/fixtures/rules/std_rule_cases/L026.yml
Fixes #3341 
Shouldn't be
- Other.
> L026: check standalone aliases as well as table aliases

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_group_by.sql
- test/fixtures/dialects/postgres/postgres_group_by.yml
Fixes #3476 coping much functionality from Exasol
Nope
- Other.
> Postgres: support grouping sets

- plugins/sqlfluff-templater-dbt/setup.cfg
- util.py
Closes https://github.com/sqlfluff/sqlfluff/issues/3579 . When we do a release, the `install_requires` block here will also be updated. I don't have the full context on the original issue, but I think this is what we wanted?
No
- Other.
> Pin sqlfluff-templater-dbt via release script

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/core/parser/grammar/noncode.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/matchable.py
- src/sqlfluff/core/parser/parsers.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/meta.py
This is a subset of the changes from #3620 - the dialect changes there are harder than expected to pick apart so I'd love to merge these separately. Then I'll handle the dialect changes in the original PR.
> Dialect Crumbs

- src/sqlfluff/rules/L016.py
- test/fixtures/rules/std_rule_cases/L016.yml
> L016: Ignore jinja comments if ignore_comment_clauses=True

- docs/source/gettingstarted.rst
update sqlfluff version to 1.2.1 from 0.3.1 in gettingstaretd.rst
> update sqlfluff version in gettingstareted.rst

- docs/source/gettingstarted.rst
- util.py
https://github.com/sqlfluff/sqlfluff/pull/3639#discussion_r925623669
> Bump version in gettingstarted.rst via the release script

- src/sqlfluff/core/templaters/slicers/tracer.py
- test/core/templaters/jinja_test.py
> Handle Jinja {% call ... %} blocks

- .github/workflows/add-issue-labels.yaml
Turns out we didn't have a label for it. Just added the label and added it to the automation.
No
- Other.
> Add Athena issue label

- src/sqlfluff/rules/L042.py
- test/core/templaters/jinja_test.py
- test/fixtures/rules/std_rule_cases/L042.yml
Fixes #3572
Makes progress on #3598
- Other.
> L042: Autofix sometimes results in "fix looping", hitting the linter "loop limit"

- .github/FUNDING.yml
This resolves #3715. I think this handles the link change on the flattr side.
> Update broken flattr link

- src/sqlfluff/core/parser/grammar/base.py
Draft PR to start resolving #3721.
I've removed some definitely unrequired code and removed the `no cover` tags from the other section. I want to see what coverage says before going further - when I initially tried just removing the other section I got some test fails so that implies that it _is_ being used.
> Revise no cover direction and remove unused code.

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/alter_materialized_view_set_options.sql
- test/fixtures/dialects/bigquery/alter_materialized_view_set_options.yml
- test/fixtures/dialects/bigquery/create_materialized_view.sql
- test/fixtures/dialects/bigquery/create_materialized_view.yml
- test/fixtures/dialects/bigquery/drop_materialized_view.sql
- test/fixtures/dialects/bigquery/drop_materialized_view.yml
> BigQuery: Support Materialized Views

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table.sql
- test/fixtures/dialects/tsql/alter_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/3748
No
- Other.
> T-SQL: ALTER TABLE DROP COLUMN

- src/sqlfluff/core/linter/linting_result.py
I broke the main branch through poor git hygiene 🤦 .
This PR is to fix it before I cause more damage.
> Fixed broken main branch

- test/fixtures/dialects/snowflake/snowflake_first_value_ignore_nulls.sql
- test/fixtures/dialects/snowflake/snowflake_first_value_ignore_nulls.yml
- test/fixtures/dialects/snowflake/snowflake_within_group.sql
- test/fixtures/dialects/snowflake/snowflake_within_group.yml
Fix a couple of minor syntax errors in Snowflake tests
No side effects
- [ x] Please confirm you have completed any of the necessary steps below.
I will update the yaml file in a second pass based on errors reported by unit tests. I'm not able to run the script locally (on macOS) to update the yaml files, so I'll do it by hand.
> Snowflake: Fix syntax errors in tests

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_create_function.sql
- test/fixtures/dialects/snowflake/snowflake_create_function.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/3844
No
- Other.
> Snowflake: CREATE FUNCTION IF NOT EXISTS

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/drop_trigger.sql
- test/fixtures/dialects/mysql/drop_trigger.yml
> MySQL: Add extended DROP TRIGGER functionality

- src/sqlfluff/rules/L008.py
- src/sqlfluff/utils/functional/context.py
This part of #3673.
It brings L008 into the reflow work, and uses logic which was all merged in #3824.
> Bring L008 into reflow work

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/postgres/postgres_revoke.sql
- test/fixtures/dialects/postgres/postgres_revoke.yml
Fix https://github.com/sqlfluff/sqlfluff/issues/3907
I think it's safe?
- Other.
> Postgres Revoke fix

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/join_hints.sql
- test/fixtures/dialects/tsql/join_hints.yml
This PR fixes #3916.
n/a
- Other.
> T-SQL: Allow specifying join hints

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_alter_procedure.sql
- test/fixtures/dialects/postgres/postgres_alter_procedure.yml
> Postgres: ALTER PROCEDURE

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_alter_table.sql
- test/fixtures/dialects/snowflake/snowflake_alter_table.yml
Added coverage for several alter table constraint actions (specifically add, drop, and rename).
Somewhat related to https://github.com/sqlfluff/sqlfluff/issues/3479
no
- Other.
> Snowflake: ALTER TABLE constraint actions

- src/sqlfluff/dialects/dialect_redshift.py
What the title says. It started with finding in our codebase that `current_user` couldn't be parsed and after a bit of digging in the official doc, that's all the bare functions I could find.
- Other.
> Update Redshift bare functions

- src/sqlfluff/core/config.py
- src/sqlfluff/core/linter/linted_dir.py
- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/core/linter/linting_result.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/parser.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/plugin/hookspecs.py
- src/sqlfluff/core/rules/base.py
- src/sqlfluff/core/templaters/base.py
- src/sqlfluff/rules/L027.py
- src/sqlfluff/rules/L057.py
- src/sqlfluff/rules/L059.py
New mypy version https://pypi.org/project/mypy/0.990/ introduced some extra checks which make CI fail. This addresses all of them.
> mypy edits for 0.990

- src/sqlfluff/dialects/dialect_soql.py
- test/fixtures/dialects/soql/date_literals.sql
- test/fixtures/dialects/soql/date_literals.yml
This resolves #3802 .
Does what it says on the tin :)
> Date and Datetime literals in SOQL

- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/rules/L003.py
> L003: Add missing "pragma: no cover"

- docs/source/layout.rst
Fix example in readme docs for indentation.
- Other.
> Fix syntax in indentation sample code docs

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_alter_type.sql
- test/fixtures/dialects/postgres/postgres_alter_type.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4075
There are other `renames` under `alter type` (see `test/fixtures/dialects/postgres/postgres_alter_type.sql`), but I think we are safe with this change.
- Other.
> Postgres: Alter type rename value

- .github/workflows/check-yaml-files-generation.yml
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/parser/lexer.py
- tox.ini
Recent builds failing. See https://github.com/tox-dev/tox/commit/3603a381d062d86b9b333f41feb67e5428ebfe1e
> Fix tox arguments

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_like_clause.sql
- test/fixtures/dialects/sparksql/select_like_clause.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4118
No
- Other.
> SparkSQL: ILIKE

- src/sqlfluff/rules/L071.py
- test/cli/commands_test.py
- test/fixtures/rules/std_rule_cases/L071.yml
fixes #3889
I didn't add test cases at " `.sql`/`.yml` parser test cases in `test/fixtures/dialects` " can anyone confirm if it is needed since I have only added a new rule?
- Other.
> Add rule for space around parenthesis

- src/sqlfluff/diff_quality_plugin.py
- test/diff_quality_plugin_test.py
> diff-quality: Handle the case where there are no files to check

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
CI is broken after https://github.com/dbt-labs/dbt-core/pull/6539
There could be some more graceful way to handle this by checking the dbt version, but I am not seeing that. This probably works?
- Other.
> Handle renamed dbt exceptions

- test/fixtures/dialects/snowflake/snowflake_insert.sql
- test/fixtures/dialects/snowflake/snowflake_insert.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/3169
Added test case here to confidently close the above issue.
No
- Other.
> Snowflake: INSERT INTO

- .pre-commit-config.yaml
- requirements_dev.txt
- src/sqlfluff/utils/testing/rules.py
- tox.ini
Closes https://github.com/sqlfluff/sqlfluff/issues/4334
This linter is gaining tons of traction with other open-source projects. It's also extremely fast: https://github.com/charliermarsh/ruff#ruff
No
- Other.
> Add ruff linter

- README.md
- Adds a section to the README.md about the available plugins and extensions 
- fixes #4099
- Other.
> Add extensions and plugin section to the README.md

- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/rules/std_rule_cases/AL01.yml
This resolves #4492 & resolves #4089 (with tests), I'm pretty sure it also fixes #4122 and fixes #4244 based on how those fail. Thanks to @praateekmahajan for pointing our that these issues were related.
> Handle missing aliases and align constraints better

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/lambda_function.sql
- test/fixtures/dialects/clickhouse/lambda_function.yml
Add parse lambda function Clickhouse
fixes #4254 
- Other.
> add parse lambda function Clickhouse

- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/bigquery/select_pivot.sql
- test/fixtures/dialects/bigquery/select_pivot.yml
- test/fixtures/dialects/sparksql/pivot_clause.sql
- test/fixtures/dialects/sparksql/pivot_clause.yml
Fixes #3779 
Fixes #3822 
No. I did look at merging these as suggested in https://github.com/sqlfluff/sqlfluff/issues/3779#issuecomment-1242016514, but there are some subtle differences between the two so don't think that is worth it
- Other.
> Fix PIVOT clauses for BigQuery and SparkSQL

- src/sqlfluff/utils/reflow/elements.py
I've got myself into a deep hole on indents and dedents, but in the process came to need this. It stops endless fixes on source elements. I've marked it as "no cover" because if rules are working properly, it shouldn't be required.
> Safety valve on source fixes

- README.md
Updates the Databricks note in the README to reflect the recent changes made in PR https://github.com/sqlfluff/sqlfluff/pull/4568
No
- Other.
> Update README with Databricks note

- test/generate_parse_fixture_yml.py
This is a small developer experience improvement.
- The parse test readout is hard to read.
- It talks about `yml` files and not `sql` files.
- It does things in an odd order.
This rationalises that method a little.
> Make parse test readout more helpful

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/delete.sql
- test/fixtures/dialects/bigquery/delete.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4646
No
- Other.
> BigQuery: Delete table reference

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_overlaps.sql
- test/fixtures/dialects/postgres/postgres_overlaps.yml
> Postgres - allow untyped OVERLAPS clauses

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/function_return.sql
- test/fixtures/dialects/mysql/function_return.yml
> MySQL: Add RETURN Statement

- docs/source/gettingstarted.rst
This updates the getting started docs now that we're post 2.0 release to make sure they're still accurate.
> Update getting started docs

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_sample.sql
- test/fixtures/dialects/snowflake/snowflake_sample.yml
> Snowflake: Add ReferencedVariableNameSegment to sample function

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/select.sql
- test/fixtures/dialects/sqlite/select.yml
Fixes #4600 
Fixes #4759 
No
- Other.
> SQLite: Remove refs to RESPECT and QUALIFY

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_execute_task.sql
- test/fixtures/dialects/snowflake/snowflake_execute_task.yml
In Snowflake, allow for the execution of task by specifying the schema name and task name
> Snowflake Execute Task with Schema

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_create_view.sql
- test/fixtures/dialects/snowflake/snowflake_create_view.yml
Allows Temporary Views in Snowflake. The docs don't mention them, but they are supported.
No
- Other.
> Snowflake: Support Temporary View

- CHANGELOG.md
- docs/source/gettingstarted.rst
- plugins/sqlfluff-templater-dbt/setup.cfg
- setup.cfg
> Bump to version 2.0.7

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/bare_functions.sql
- test/fixtures/dialects/oracle/bare_functions.yml
> Oracle: Update bare functions

- src/sqlfluff/rules/references/RF06.py
- test/fixtures/rules/std_rule_cases/RF06.yml
> Detect tsql square bracket quotes for RF06 #4724

- .gitignore
- src/sqlfluff/dialects/dialect_clickhouse.py
- src/sqlfluff/dialects/dialect_clickhouse_keywords.py
- test/fixtures/dialects/clickhouse/drop_statement.sql
- test/fixtures/dialects/clickhouse/drop_statement.yml
Features:
* Support `DROP` statements:
* `DROP DATABASE`
* `DROP TABLE`
* `DROP DICTIONARY`
* `DROP USER`
* `DROP ROLE`
* `DROP QUOTA`
* `DROP SETTINGS PROFILE`
* `DROP VIEW`
* `DROP FUNCTION`
- ~`.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.~
- Other.
- ~Added appropriate documentation for the change.~
> fix(dialect-clickhouse): Support DROP statements

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_index.sql
- test/fixtures/dialects/sqlite/create_index.yml
> SQLite: Support partial index

- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_hive_keywords.py
- test/fixtures/dialects/hive/select_regexp.sql
- test/fixtures/dialects/hive/select_regexp.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4831
No
- Other.
> Hive: Support REGEXP and IREGEXP

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_role.sql
- test/fixtures/dialects/tsql/create_role.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4517
No
- Other.
> TSQL: Create Role Authorization

- docs/source/gettingstarted.rst
Updates the link for pip installation instructions, which had changed slightly
No
- Other.
> Fixes pip installation link on Getting Started

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_example.yml
- test/fixtures/dialects/bigquery/select_struct.yml
- test/fixtures/dialects/bigquery/select_with_offset_2.yml
- test/fixtures/dialects/bigquery/typeless_array.yml
- test/fixtures/rules/std_rule_cases/LT01-excessive.yml
> Set type of ARRAY function for BigQuery

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
> profiles dir env var or default

- docs/source/configuration.rst
https://github.com/sqlfluff/sqlfluff/pull/4810 added support for Jinja Filters via a global variable `SQLFLUFF_JINJA_FILTERS`.
However, this feature was never added to the documentation.
No, documentation only.
- Other.
> docs(templater): Add documentation for `SQLFLUFF_JINJA_FILTERS`

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/alter_table.sql
- test/fixtures/dialects/mysql/alter_table.yml
Noticed an old bug when reviewing https://github.com/sqlfluff/sqlfluff/pull/4948
No
- Other.
> MySQL: Rename index

- src/sqlfluff/__main__.py
- src/sqlfluff/cli/commands.py
Ignore stuff for now to unblock other PRs. See https://github.com/pallets/click/issues/2558.
It's possible we can revert this PR if they release again.
The other alternatives are: wait for a new release, or pin to older `click` versions.
- Other.
> Ignore click mypy issues

- .github/labeler.yml
- .github/workflows/add-issue-labels.yaml
Closes https://github.com/sqlfluff/sqlfluff/issues/4951
https://github.com/github/issue-labeler
Potentially need to follow up if it doesn't work.
- Other.
> New GitHub issue labeler library

- .github/workflows/add-issue-labels.yaml
They released a feature that will allow ignoring issue body: https://github.com/github/issue-labeler/issues/77
No
- Other.
> Bump issue-labeler

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/postgres/array.sql
- test/fixtures/dialects/postgres/array.yml
Fixes https://github.com/sqlfluff/sqlfluff/issues/4945
Doesn't seem to break anything. There are probably lots of ways to solve this.
- Other.
> Postgres support underscore array data type syntax

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/group_by_all.sql
- test/fixtures/dialects/snowflake/group_by_all.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4940
No
- Other.
> Snowflake: Group by all

- src/sqlfluff/dialects/dialect_athena.py
- test/fixtures/dialects/athena/select_unnest.sql
- test/fixtures/dialects/athena/select_unnest.yml
fixes #4990 
via introducing a new athena specific PostFunctionGrammar
no
- Other.
> feat: support athena optional WITH ORDINALITY post UNNEST function

- src/sqlfluff/core/errors.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/conditional.py
- src/sqlfluff/core/parser/grammar/noncode.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/ephemeral.py
- src/sqlfluff/core/parser/segments/raw.py
Another one from exploring mypyc - these are a set of missing typehints that I added in the process.
No functionality. Just type hints 🎸
> Assorted typehints

- CONTRIBUTING.md
Resolves #2180 (an oldie), which describes how best for contributors to interact with the test suite. I've described my usual method. Very open to suggestions on how to make this clearer and easier to understand.
@juhoautio - I realise it's been a **loooong** time, but also open to your feedback on whether this is addresses what you were thinking as the OP.
> Documentation for the test suite (#2180)

- src/sqlfluff/cli/click_deprecated_option.py
- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/dialects/base.py
- src/sqlfluff/core/linter/linting_result.py
- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/core/parser/grammar/noncode.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/grammar/types.py
- src/sqlfluff/core/parser/lexer.py
- src/sqlfluff/core/parser/parsers.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/generator.py
- src/sqlfluff/core/parser/segments/meta.py
- src/sqlfluff/core/parser/segments/raw.py
- src/sqlfluff/core/rules/crawlers.py
- src/sqlfluff/core/rules/loader.py
- src/sqlfluff/core/templaters/base.py
- src/sqlfluff/core/templaters/python.py
- src/sqlfluff/core/timing.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres_keywords.py
- src/sqlfluff/rules/convention/CV09.py
- src/sqlfluff/rules/references/RF04.py
- src/sqlfluff/utils/reflow/reindent.py
This PR is a step towards mypy strict compatibility
Before
`Found 5463 errors in 155 files (checked 209 source files)`
After
`Found 1050 errors in 135 files (checked 210 source files)`
No
- Other.
> A step towards mypy strict

- src/sqlfluff/rules/structure/ST06.py
- test/core/linter/linter_test.py
Some new linting issues have started flagging up, this resolves them.
> Fix some new linting issues

- src/sqlfluff/core/config.py
There's a lot of `Dict[str, Any]` running around for the config. I know that it can't _really_ be any, since it's more like an arbitrarily nested dict of dicts. But `--strict` doesn't like having just `dict` as a type, so if anyone has other suggestions besides `Dict[str, Any]` I'm happy to implement it.
I'm not great with all the intricacies of typing, and this article was very helpful: https://realpython.com/python-type-checking/
> mypy strict in config

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/alter_table.sql
- test/fixtures/dialects/oracle/alter_table.yml
> Closes #4815

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/bind_variables.sql
- test/fixtures/dialects/oracle/bind_variables.yml
> Add SQL Plus bind variable support (Oracle)

- mypy.ini
- src/sqlfluff/core/rules/base.py
- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/core/rules/crawlers.py
- src/sqlfluff/core/rules/doc_decorators.py
- src/sqlfluff/core/rules/loader.py
FYI @alanmcruickshank I'll hold off on doing anymore work on this until you've got #5044 settled, since it seems like that's going to shake things up slightly
> Add mypy strict typing for sqlfluff.core.rules

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
In my testing of the latest release, there are two dbt errors which I got and which aren't handled particularly gracefully. In normal running we shouldn't see either - so I haven't added tests for these scenarios. They're more quality of life improvements for developing and debugging.
> Handle two kinds of dbt errors more gracefully

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_table_with_distribution.sql
- test/fixtures/dialects/tsql/create_table_with_distribution.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5050
No
- Other.
> TSQL: Fix Clustered Index asc/desc

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/snowflake/create_procedure.sql
- test/fixtures/dialects/snowflake/create_procedure.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4969
No
- Other.
> Allow double-quoted parameters in create procedure

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select_except.sql
- test/fixtures/dialects/snowflake/select_except.yml
> Snowflake support for bracketed query after `EXCEPT`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/update_table.sql
- test/fixtures/dialects/postgres/update_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5127
No
- Other.
> Postgres: Update returning with alias

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/cluster.sql
- test/fixtures/dialects/postgres/cluster.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5141
No
- Other.
> Postgres: CLUSTER

- src/sqlfluff/core/parser/grammar/delimited.py
This is entirely a simplification of the syntax of the `Delimited.match()` method. Code flow is exactly the same, just less nested.
For reviewing, the specific changes are:
- Don't set an `elements` variable. We already have `seeking_delimiter` to tell us whether we're looking for content or delimiters, so I've just used that boolean flag to do the logic instead of creating another variable. The only place where we really still need that logic is in the call to `_longest_trimmed_match`, so I've kept an inline `if` there.
- The only check of `if len(seg_buff) > 0:` had a really long positive `if` section, and then a tiny negative section at the end. I've swapped this around to fist check `if len(seg_buff) == 0:` (`break` if it is), and then continue un-nested.
- Likewise, after the …
> Un-nest the delimited match method

- test/generate_parse_fixture_yml.py
The parsing script fails quite noisily when it fails on a file and that can make it quite hard to pinpoint the issue. This makes it a bit neater and easier to find the issue.
> Quality of life improvements on parse fixture script

- .github/workflows/ci-pr-comments.yml
> Fix API issues in github comment action

- .github/workflows/ci-pr-comments.yml
- .github/workflows/ci-tests.yml
Resolves current issue in PR commenting workflow that it doesn't know which PR to comment on.
> Stash PR Number and hydrate later

- .github/workflows/ci-pr-comments.yml
> Update comment workflow again

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/rules/references/RF06.py
- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/dialects/exasol/alter_user.yml
- test/fixtures/dialects/exasol/create_user.yml
- test/fixtures/dialects/hive/set.yml
- test/fixtures/dialects/snowflake/match_recognize.yml
- test/fixtures/dialects/sparksql/set.yml
- test/fixtures/dialects/tsql/triggers.yml
- test/fixtures/rules/std_rule_cases/LT01-excessive.yml
- test/fixtures/rules/std_rule_cases/RF06.yml
This is a selection of issues found while putting together #5196. I'm separating them out because they're not really core functionality changes, more dialect improvements and rule test cases.
Most of these issues haven't been reported yet, although this does make some progress on #4922 (although that issue has other things that also need to be solved).
> Dialect spacing & quoting issues

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_table.sql
- test/fixtures/dialects/mysql/create_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5204
Is there a more concise way to express "this thing could be surrounded by brackets, but doesn't need to be"?
- Other.
> MySQL bracketed column constraint

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/insert.sql
- test/fixtures/dialects/postgres/insert.yml
> Fix insert on conflict with function in Postgres

- src/sqlfluff/dialects/dialect_tsql.py
CI is broken because of #5305 & #5282. This resolves the issues (I think).
> Fix for strange TSQL bugs

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/database_link.sql
- test/fixtures/dialects/oracle/database_link.yml
> Add support for functions and procedures calls via database link in Oracle

- docs/source/realworld.rst
The anchor in the dbt link is outdated, this PR updates it to the latest.
No
- Other.
> Fix the dbt anchor link in the realworld documentation

- src/sqlfluff/core/config.py
- src/sqlfluff/core/linter/linted_file.py
Two small typing improvements. I noticed both of them while working on some other things.
> One (very) small typing improvements

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/analyze.sql
- test/fixtures/dialects/trino/analyze.yml
Makes progress on #5151 
It doesn't support all examples in the docs as arrays in Trino aren't supported - but that's a separate concern
No
- Other.
> Trino: Support Analyze statements

- docs/source/api.rst
Closes #5354
Turns out, the documentation I had in mind have already been present in the example code, so I'm just adding the reference to it to the docs
No
- Other.
> API configuration documentation

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/set_names.sql
- test/fixtures/dialects/mysql/set_names.yml
> Add support for SET NAMES statement in MySQL

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_user.sql
- test/fixtures/dialects/tsql/create_user.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5424
No
- Other.
> TSQL: CREATE USER {FOR|FROM} LOGIN

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/create_table_constraints.sql
- test/fixtures/dialects/tsql/create_table_constraints.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5432
No. Just the new keyword should solve this issue, but I felt the grammar change was cleaner as well.
- Other.
> TSQL: ON DELETE NO ACTION

- src/sqlfluff/core/parser/grammar/conditional.py
- src/sqlfluff/core/rules/crawlers.py
- src/sqlfluff/utils/functional/segment_predicates.py
- src/sqlfluff/utils/functional/segments.py
- test/utils/reflow/respace_test.py
I think `black` has had some updates. This updates formatting accordingly.
> Update black linting

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/select.sql
- test/fixtures/dialects/tsql/select.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5484
No
- Other.
> TSQL: Top and Distinct in same query

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_view.sql
- test/fixtures/dialects/snowflake/create_view.yml
> Add Support for Snowflake Materialised View and Column Masking Policy

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/select.sql
- test/fixtures/dialects/postgres/select.yml
> Postgres: Allow nested block comments

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/bigquery/select_group_by.sql
- test/fixtures/dialects/bigquery/select_group_by.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5643
I put in ANSI instead of BigQuery. Snowflake just added this too, so I wouldn't be surprised if more dialects add it as well.
- Other.
> BigQuery: GROUP BY ALL

- src/sqlfluff/core/linter/linter.py
Small PR:
- Removes an uncovered patch of code which handled empty token lists (because that should now never happen).
- Renames variable from `tokens` to `segments` because that's what's actually in it.
- Removes the `config` return value and comment saying it was important - because it's not.
> Simplify one of the lexer methods

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table_switch.sql
- test/fixtures/dialects/tsql/alter_table_switch.yml
> TSQL: fix `ALTER TABLE ... SWITCH PARTITION`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_extension.sql
- test/fixtures/dialects/postgres/create_extension.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5819
No.
- Other.
> Postgres: Create extension cascade

- .github/workflows/ci-tests.yml
- constraints/dbt170.txt
- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- tox.ini
Fixes #5841 
Also adds dbt 1.7 to the test suite. Thanks @jtcohen6 for identifying the fix
No
- Other.
> Support dbt 1.7

- README.md
- docs/source/internals.rst
Minor documentation updates to clearly illustrate all available templaters supported by SQLFluff.
Also fixes one minor Markdown formatting issue.
No
- Other.
> Update documentation to include all templaters

- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sparksql_keywords.py
- test/fixtures/dialects/sparksql/databricks_dlt_apply_changes_into.sql
- test/fixtures/dialects/sparksql/databricks_dlt_apply_changes_into.yml
> Add support for Databricks TRACK HISTORY

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/grouping_sets.sql
- test/fixtures/dialects/trino/grouping_sets.yml
> fix(dialect-trino): Support Grouping Sets

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/pivot.sql
- test/fixtures/dialects/databricks/pivot.yml
> Allow anonymous PIVOTs in Databricks

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/common_on.sql
- test/fixtures/dialects/trino/common_on.yml
As discussed in Slack
Shouldn't be. Standard dialect addition and already supported in Postgres dialect.
- Other.
> Add COMMENT ON support to Trino dialect

- examples/06_full_parse_api.py
As discussed in slack, this adds an example python script using the SQLFluff python API to process SQL scripts.
> Parse API example

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_table_column.sql
- test/fixtures/dialects/snowflake/alter_table_column.yml
A simple fix for a variation of ADD COLUMN statement with multiple columns.
No
- [ x ] Please confirm you have completed any of the necessary steps below.
- Other.
> Snowflake:adds optional IF NOT EXISTS to ADD COLUMN

- src/sqlfluff/rules/references/RF03.py
While reviewing #6046 I realised that the docs for RF03 aren't particularly clear. This improves them to make them more specific about what the rule is actually for.
> Update the docs on RF03

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/rename.sql
- test/fixtures/dialects/clickhouse/rename.yml
fixes #6071 adding support for all the flavors of rename statement
Nope
> fix(clickhouse): add support for rename statement

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_view.sql
- test/fixtures/dialects/mysql/create_view.yml
fixes #6076 
Not that I know of, but this is my first pr so I have no idea how to judge that other than ensuring the dialect grammat tests pass
- [ x] Please confirm you have completed any of the necessary steps below.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated with `tox -e generate-fixture-yml`).   <- this one
- Other.
> Adding CTE to mysql views

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_trigger.sql
- test/fixtures/dialects/sqlite/create_trigger.yml
> SQLite: Create Trigger WHEN optionally bracketed

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/raise_function.sql
- test/fixtures/dialects/sqlite/raise_function.yml
> SQLite: Support Raise Function

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
Fixes uploading coverage files as part of CI. These were hidden files, so a new setting is now required.
None
- Other.
> CI: allow hidden file upload for coverage files

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/create_view.sql
- test/fixtures/dialects/duckdb/create_view.yml
> Duckdb: Fix Create View coverage

- util.py
Update the `util.py` script to handle the change of `sqlfluff-dbt-templater` migrating to pyproject.toml
None
- Other.
> CI: Update `util.py` for dbt templater `pyproject.toml`

- src/sqlfluff/dialects/dialect_databricks.py
- src/sqlfluff/dialects/dialect_databricks_keywords.py
- test/fixtures/dialects/databricks/create_database.sql
- test/fixtures/dialects/databricks/create_database.yml
> Add support for managed locations to databricks dialect schemas

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/create_macro.sql
- test/fixtures/dialects/duckdb/create_macro.yml
Supports `CREATE MACRO` and `CREATE FUNCTION` for DuckDB.
- fixes #6190
None
- Other.
> DuckDB: Support `CREATE MACRO`/`CREATE FUNCTION`

- README.md
- docs/source/jointhecommunity.rst
Closes https://github.com/sqlfluff/sqlfluff/issues/6161
> Update Slack link

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/command_terminator.sql
- test/fixtures/dialects/databricks/command_terminator.yml
> Added Support for Databricks SQL Notebook Cells

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/datatypes.sql
- test/fixtures/dialects/snowflake/datatypes.yml
This adds support for ARRAY types in Snowflake.
- fixes #6236
None
- Other.
> Snowflake: Support `ARRAY` types

- .github/labeler.yml
It's a new dialect and seems we forgot this one tiny thing for issue labeling.
No.
- Other.
> Add mariadb to issue labeler

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-tests.yml
- constraints/dbt190-winpy.txt
- constraints/dbt190.txt
- plugins/sqlfluff-templater-dbt/test/conftest.py
- tox.ini
- Added dbt 1.9.0 to the test matrix for the dbt templater
- Added the versions of dbt-core and dbt-postgres to the header of the Pytest output, so we can confirm the tests are running with the right versions.
- https://pypi.org/project/dbt-postgres/1.9.0b1/
- https://pypi.org/project/dbt-core/1.9.0b1/
- Other. …
> Test dbt Templater Plugin with dbt 1.9.0

- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
I think this resolves #6258.
@wyardley, does this solution work for you? I've taken a lot of inspiration from how yamllint have approached this problem.
> Add groups to the `github-annotation-native` format option.

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/databricks_dlt_create_view.sql
- test/fixtures/dialects/sparksql/databricks_dlt_create_view.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/6307
No
- Other.
> Databricks materialized view

- test/fixtures/dialects/README.md
Fix tox command in test/fixtures/dialects/README.md  
- fix #6341
Nope
- Other.
> Fix `tox` command in test/fixtures/dialects/README.md

- src/sqlfluff/rules/ambiguous/AM02.py
Add new dialects from https://github.com/sqlfluff/sqlfluff/pull/5979 into documentation. Companion to https://github.com/sqlfluff/sqlfluff/issues/5964
I don't think I need to test anything for documentation?
- Other.
> Update documentation with new dialects

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
Fixes #6378
Hopefully not.
- Other.
> Fix edge case in Jinja reindents

- README.md
Table Of Contents in main README to make navigating it easier.
N/A
- Other.
> Updated README with Table Of Contents

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/create_function.sql
- test/fixtures/dialects/databricks/create_function.yml
* added table valued function parsing
* Added support to databricks dialect to allow parsing table valued functions
* Added test cases
- Other.
> Databricks: Parse Table Valued Functions

- test/fixtures/dialects/databricks/create_function.sql
> Fix pre-commit on main branch

- .github/workflows/ci-tests.yml
- .gitignore
- .pre-commit-config.yaml
- requirements_dev.txt
- src/sqlfluff/api/simple.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/linter/patch.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/rules/base.py
- src/sqlfluff/core/rules/noqa.py
- src/sqlfluff/core/templaters/base.py
- src/sqlfluff/core/templaters/python.py
- src/sqlfluff/core/templaters/slicers/tracer.py
- src/sqlfluff/utils/reflow/elements.py
- src/sqlfluff/utils/reflow/reindent.py
- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/dialects/databricks/create_function.sql
- tox.ini
- tests if certain submodules can be compiled
- module list will eventually grow
- tests against compiled variant will eventually follow
- Other.
> Prework for introducing mypyc

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select.sql
- test/fixtures/dialects/snowflake/select.yml
> Snowflake: Support ORDER BY boolean

- src/sqlfluff/dialects/dialect_impala.py
- test/fixtures/dialects/impala/create_table_as_select.sql
- test/fixtures/dialects/impala/create_table_as_select.yml
Add segment to parse `CREATE TABLE ... AS SELECT ...` (CTAS) queries.
Fixes #6451 
None
- Other.
> Impala: support CREATE TABLE AS SELECT

- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_teradata.py
> Add Implicit Indents to Qualify

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/duckdb/create_table.sql
- test/fixtures/dialects/duckdb/create_table.yml
> DuckDB: Support MAP data type

- test/fixtures/dialects/snowflake/alter_table.sql
This fixes a minor linting error that somehow got merged.
> Fix minor linting error in CI

- src/sqlfluff/rules/ambiguous/AM08.py
- test/fixtures/rules/std_rule_cases/AM08.yml
Fixes #6491
Fixes #6507 
- Other.
> AM08: fix edge cases

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_row_access_policy.sql
- test/fixtures/dialects/snowflake/alter_row_access_policy.yml
> Fill in Gap in Snowflake `ALTER ROW ACCESS POLICY` Syntax Parsing

- src/sqlfluff/core/parser/grammar/base.py
This is a workaround for mypyc 1.14+ test failures.
This doesn't actually 'fix' the underlying limitations with mypyc, but allows for the package to be compiled.
- Other.
> mypyc: workaround for ABC inheritance

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_table.sql
- test/fixtures/dialects/snowflake/create_table.yml
> Fix Snowflake Dynamic Table Parsing

- src/sqlfluff/dialects/dialect_starrocks.py
- test/fixtures/dialects/starrocks/create_table_generated_column.sql
- test/fixtures/dialects/starrocks/create_table_generated_column.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/6580
- Other.
> [Starrocks] Support for generated columns

- CONTRIBUTING.md
- plugins/sqlfluff-templater-dbt/pyproject.toml
- pyproject.toml
As title. Displaying the metadata for `3.13`. Changing up the Contributing docs to conform to our preferred version.
No
- Other.
> Bump Python version in the docs and metadata

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_trigger.sql
- test/fixtures/dialects/mysql/create_trigger.yml
> Add support for `SET NEW.<column>` statements in MySQL.

- src/sqlfluff/rules/structure/ST11.py
Fixes the ST10 to ST11 note in the noqa suggestion. 
None
- Other.
> ST11: Fix rule name in documentation for `noqa`

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/ansi/obevo.sql
- test/fixtures/dialects/ansi/obevo.yml
> Add support for Obevo annotations.

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/select.sql
- test/fixtures/dialects/redshift/select.yml
> Redshift: Support GROUP BY ALL

- src/sqlfluff/rules/ambiguous/AM08.py
- test/fixtures/rules/std_rule_cases/AM08.yml
Handles non-uppercased `UNNEST` function names in AM08.
- makes progress on #6725
None
- Other.
> AM08: Handle any-cased `UNNEST`

- .github/workflows/add-to-release-notes.yml
The `ubuntu-20.04` runner is being retired. This replaces it with `ubuntu-latest` like other workflows
None
- Other.
> CI: Update add-to-release-notes to use ubuntu-latest

- CONTRIBUTING.md
- Makefile
- docker-compose.yml
- docker/development/Dockerfile
- plugins/sqlfluff-templater-dbt/docker/init
- plugins/sqlfluff-templater-dbt/docker/shell
- plugins/sqlfluff-templater-dbt/docker/shutdown
- plugins/sqlfluff-templater-dbt/docker/startup
- requirements_dev.txt
This creates a local development Docker environment:
- Make and docker-compose
- Compatible with Git inside the container
- shell and start options
- Removes unnecessary shell scripts in dbt templater
Nope, tested with dbt templater inside the container
- Other.
> Set up Docker development environment

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_network_policy.sql
- test/fixtures/dialects/snowflake/create_network_policy.yml
> Snowflake: Create Network Policy Network Rule List

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/security_label.sql
- test/fixtures/dialects/postgres/security_label.yml
Fixes #6694 
Add several tests - but there aren't that many examples in the docs, so coverage isn't complete.
No
- Other.
> Postgres: Support Security Label

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/select.yml
- test/fixtures/dialects/tsql/select_named_window.sql
- test/fixtures/dialects/tsql/select_named_window.yml
- test/fixtures/dialects/tsql/window_functions.yml
Fixes #6687
It's changed the parse tree of window functions in other places, but this is beneficial as it's more precise.
- Other.
> TSQL: Support named windows

- Dockerfile
This updates the Dockerfile to use Python 3.12
None
- Other.
> Update the Dockerfile to use Python 3.12

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/create_trigger.sql
- test/fixtures/dialects/oracle/create_trigger.yml
> Adds support for trigger predicates in `IF` statements and `:NEW.` variables in assignment statements in Oracle.

- src/sqlfluff/rules/structure/ST09.py
- test/cli/commands_test.py
- test/fixtures/rules/std_rule_cases/ST09.yml
Fix ST09 rule not detecting violations in Jinja templated SQL
Fixes #5506
Nope.
- Other.
> Fix ST09 rule not detecting violations in Jinja templated SQL

- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/rules/structure/ST03.py
- test/fixtures/rules/std_rule_cases/ST03.yml
- test/rules/std_ST03_test.py
> Resolve unused CTE bug
