sqlfluff/sqlfluff

- src/sqlfluff/core/errors.py
- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/core/linter/linter.py
- test/core/linter_test.py
This resolves #4040.
Duplicate violations (e.g. from multiple passes through a jinja loop) confuse the user and also end up just being deduplicated later. This filters them out early.
> Deduplicate violations in the source space

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_union.sql
- test/fixtures/dialects/sparksql/select_union.yml
> Fix bug in sparksql SELECT statement termination at UNION #4050

- plugins/sqlfluff-plugin-example/src/example/rules.py
The `get_rules` function in the plugin example template had a type error. The function returns all the rule classes that are defined in the plugin. The return type was incorrectly annotated as `List[BaseRule]` which means a list of *instances* of `BaseRule` and not classes derived from `BaseRule`. Making it `List[Type[BaseRule]]` instead fixes the error.
For reference, the type error shown by pyright was:
```
Expression of type "list[Type[Rule_Example_L001]]" cannot be assigned to return type "List[BaseRule]"
...
"Type[type]" is incompatible with "Type[BaseRule]"
```
None (AFAICT) …
> Fix type error in `get_rules` hook of plugin example

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_from_values.sql
- test/fixtures/dialects/sparksql/select_from_values.yml
Current code would always catch `=` and never `==`
- Other.
> Fix Spark comparison parsing

- tox.ini
Some of our test suites are really long and it's hard to work out which tests have failed. This adds _fails_ and _errors_ to the summary at the end of the pytest run which is otherwise just showing the _skipped_ tests as currently.
> Add errors and fails to pytest summary

- src/sqlfluff/core/linter/linter.py
- test/cli/commands_test.py
> Support parallel linting when many individual files specified

- src/sqlfluff/core/templaters/slicers/tracer.py
I saw a mypy error in the build for #3976. Can't reproduce it locally, but this was the error:
```
src/sqlfluff/core/templaters/slicers/tracer.py:79: error: No overload variant of "list" matches argument type "Scanner[str]"  [call-overload]
src/sqlfluff/core/templaters/slicers/tracer.py:79: note: Possible overload variants:
src/sqlfluff/core/templaters/slicers/tracer.py:79: note:     def [_T] __init__(self) -> List[_T]
src/sqlfluff/core/templaters/slicers/tracer.py:79: note:     def [_T] __init__(self, Iterable[_T], /) -> List[_T]
```
This PR adds a `type: ignore` comment to that line. …
> Fix mypy issue with regex

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_set_call_variable.sql
- test/fixtures/dialects/snowflake/snowflake_set_call_variable.yml
Fix parsing error when references to variables to have leading underscore. fixes #4086 
None
- Other.
> Enable variable reference names to have leading underscore for snowflake dialect

- src/sqlfluff/utils/functional/segment_predicates.py
Fixes this flake8 build error:
```
./src/sqlfluff/utils/functional/segment_predicates.py:196:5: F842 local variable 'slice_' is annotated but never used
```
- Other.
> Fix flake8 issue with segment_predicates.py

- plugins/sqlfluff-plugin-example/src/example/rules.py
- src/sqlfluff/core/templaters/slicers/tracer.py
I manually tested the example rule and noticed it didn't work. Looks like a bug introduced when adding new crawling behavior.
- Other.
> Fix bug in example rule plugin

- src/sqlfluff/core/templaters/slicers/tracer.py
- src/sqlfluff/rules/L034.py
- test/fixtures/rules/std_rule_cases/L034.yml
> Fix bug where L034 should ignore INSERT or "CREATE TABLE AS SELECT" with CTE

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/utf8/.sqlfluff
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/utf8/test.sql
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/utf8/test.sql.fixed
- plugins/sqlfluff-templater-dbt/test/rules_test.py
- plugins/sqlfluff-templater-dbt/test/templater_test.py
Fixes #3585, #3729 
Actually, it was ignoring the encoding on *every* platform, but for some reason, it seemed to work on other (non-Windows) platforms even with the bug.
- Other.
> Bug fix: dbt templater ignores .sqlfluff file encoding on Windows

- .github/codecov.yml
- .github/workflows/ci-tests.yml
- src/sqlfluff/__init__.py
- src/sqlfluff/core/cached_property.py
Fixes #4146 
Only require (and upload) coverage reports for:
* Python 3.11
* dbt 1.3.0
* Python Windows
Allegedly, uploading fewer coverage reports makes the coverage portion of the CI build less likely to hang.
- Other.
> Only upload 3 sets of test results to codecov (possible workaround for hanging builds)

- tox.ini
- util.py
tox4 changes passenv to a comma-separated list, rather than space-separated: https://github.com/tox-dev/tox/issues/2658
This is only really important for CI (which uses latest tox), so think it should be OK even for v3 users.
I also removed the last remaining references to CIRCLECI [that we replaced with GitHub Actions  a long time ago](https://github.com/sqlfluff/sqlfluff/pull/1361).
- Other.
- Added appropriate documentation for …
> Fix passenv to work with tox 4

- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
fixes #4140
When `--disable_progress_bar` was renamed to the more appropriate `--disable-progress-bar` there was a fallback to the old flag for `lint`, but not `fix`. This adds the same fallback for `fix`.
No.
- Other.
> Allow deprecated --disable_progress_bar flag for fix command

- src/sqlfluff/rules/L037.py
- test/fixtures/rules/std_rule_cases/L037.yml
Fixed unparseable query generated for NULLS FIRST, NULLS LAST
fixes #4136 
nothing
- Other.
> L037: insert ASC just after column_reference

- test/conftest.py
- test/test_testing.py
This is a little "quality of life" for those of us who just want to call `pytest` directly when running the test suite, instead of `tox`
This test failed when I just ran `pytest`, but succeeded when I ran `pytest -vv`. This is because "select" only appeared in the output when the verbosity level was at least two. Felt like the simplest change to just double check the verbosity level of the test run before deciding to check for this regex match
No …
> :bug: Check verbosity level of pytest run before running certain tests

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/rules/std_rule_cases/L006.yml
Fixes #4164 
Nope. Missed change from #4083 
- Other.
> Recognise || as an operator to avoid rule L006 flagging it

- src/sqlfluff/diff_quality_plugin.py
> diff-quality plugin: Print invalid JSON on parse failure

- .github/workflows/ci-tests.yml
- src/sqlfluff/core/default_config.cfg
This might fail but I hope it works.
The reason codecov isn't reporting is that the `Python 3.10 Windows tests` job isn't reporting. The error we're getting is `{'detail': ErrorDetail(string='Missing "owner" argument. Please upload with the Codecov repository upload token to resolve issue.', code='not_found')}`. We're currently using the v1 uploader and that has been officially sunset: https://github.com/codecov/codecov-action.
This updates to v3 (and hopefully solves our codecov issues).
See here for example: https://github.com/sqlfluff/sqlfluff/actions/runs/3749312506/jobs/6367654414
> Codecov migration

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_table_column_charset.sql
- test/fixtures/dialects/mysql/create_table_column_charset.yml
https://dev.mysql.com/doc/refman/8.0/en/charset-column.html
fixes #4191 
No
- Other.
> MySQL: Support column character set and collation

- src/sqlfluff/core/config.py
- src/sqlfluff/core/linter/__init__.py
- src/sqlfluff/core/linter/runner.py
In testing the 2.0.0a1 release, I repeatedly experienced pickling issues with the dbt templater.
The problem is in multi-threaded mode, that the `FluffConfig` object gets passed around, and the new dbt templater contains some non-pickle-happy objects. In child processes, the templater shouldn't be required (the same as the plugin manager), so this PR strips it out of the `FluffConfig` object before pickling.
> don't pickle the templater

- src/sqlfluff/core/linter/linted_file.py
> show fatal errors regardless

- src/sqlfluff/utils/reflow/elements.py
- src/sqlfluff/utils/reflow/reindent.py
- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/linter/autofix/ansi/024_remove_templated_errors/after.sql
- test/fixtures/rules/std_rule_cases/L003.yml
Found this bug while testing the new 2.0.0a1 release (#4203). I think this is the last one we need before releasing that, but will confirm on that thread once I've done a little more testing.
This PR fixes a bug where the reindentation logic would panic when being passed a templated indent. The code which finds indent segments wasn't robust to that chance and so wasn't checking whether indents were templated or not. This fixes that (includes test case).
I improved some of the reflow logging too while I was in there which was hard to debug with.
> don't consider templated whitespace

- requirements_dev.txt
- src/sqlfluff/core/rules/base.py
- src/sqlfluff/utils/reflow/sequence.py
Critical errors are great, but when debugging new releases it's really annoying that the filename isn't mentioned in the error directly. This adds the filename to the output (when there is one - it fails nicely when not).
> Include the filename in critical exceptions

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_pivot.sql
- test/fixtures/dialects/snowflake/snowflake_pivot.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4241
I wasn't sure if two unpivots was really possible, but [StackOverflow has it](https://stackoverflow.com/a/64331728/3869802).
- Other.
> Snowflake: Allow multiple unpivot

- src/sqlfluff/core/parser/segments/meta.py
- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/L003.yml
- test/fixtures/rules/std_rule_cases/L016.yml
This resolves #4230 .
It also brings in fixes to a few issues presented by the test query from the issue above:
1. Handing leading templated whitespace on the first line.
2. Allowing multiple source fixes in a single segment.
3. Allowing the `source_str` of a templated segment to be an empty string.
> Templated fix improvements and indentation

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_div.sql
- test/fixtures/dialects/sparksql/select_div.yml
SparkSQL, support DIV binary operator
Fixes #4117 
No
- Other.
> SparkSQL: Support DIV binary operator

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/rules/std_rule_cases/L003.yml
This resolves #4249 .
The redefinition of `block_comment` in the `tsql` dialect was missing the `type` argument required for the fix in #4240 to work.
> Fix #4249 (TSQL block comment indents)

- src/sqlfluff/core/default_config.cfg
- test/fixtures/rules/std_rule_cases/L006.yml
Placeholders shouldn't trigger spacing rules because they don't exist in the rendered SQL. This adds the `any` config for their spacing so we don't try to enforce anything.
There's probably something more subtle we could do here, but this will work for 99% of people. Ideally we would still complain if there was too much whitespace, but not if there wasn't enough. That isn't currently a configuration option however.
> Fix #4253 (incorrect trigger of L006 around placeholders)

- src/sqlfluff/utils/reflow/elements.py
- test/fixtures/rules/std_rule_cases/L019.yml
This resolves #4255 . The problem arises from trying to make a description for a mixed indent, which we don't actually need. This resolves that gracefully by providing a generic "mixed indent" return so that things can complete nicely.
> Fix #4255 (Fix exception on mixed indent description)

- src/sqlfluff/core/parser/lexer.py
I think this resolves #4251 - which is really two small bugs:
1. The error is using `.format()` and a f-string, and so doesn't render the remaining characters properly.
2. For some trailing characters, the lexing error doesn't work as intended. In particular the `r"[^\t\n\,\.\ \-\+\*\\\/\'\"\;\:\[\]\(\)\|]*"` regex for unlexable characters was added in #185 (yes back in 2020!), and the commentary on that PR isn't clear on why so many characters are excluded.
The tests might fail on this PR, but if not - I think it's a sensible simplification.
> Simplify lexing

- plugins/sqlfluff-plugin-example/test/rules/rule_test_cases_test.py
- Fix a broken import in the example plugin.
- Fixes #4024 
No.
I don't believe any item below applies here. But it'd be great of course if the example plugin unit tests would run in CI.
- Other.
> Fix #4024 example plugin unit tests import

- requirements.txt
- setup.cfg
- src/sqlfluff/core/config.py
Now that Python 3.11+ supports reading `.toml` files with [the builtin `tomllib` module](https://docs.python.org/3/library/tomllib.html), we can just use that instead of installing the 3rd party package `toml`. On Python 3.10 and lower, `toml` will still be installed.
No, I've just tested this on Python 3.8 and Python 3.11, so will see what the full `ci-tests` returns (might need to tweak the `# pragma: no cover` comment).
- Other.
- …
> toml: only install `toml` dependency if < Python 3.11 (otherwise use builtin `tomllib`)

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/alter_view_set_options.sql
- test/fixtures/dialects/bigquery/alter_view_set_options.yml
> BigQuery: Add ALTER VIEW

- src/sqlfluff/rules/L067.py
- test/fixtures/rules/std_rule_cases/L067.yml
This surrounds complex expressions with `()` before fixing a cast or convert to a shorthand cast using the `::` operator. Without this change, the cast would be applied to only part of the appropriate expression.
fixes #4301
No.
- Other.
> Bracket complex expressions before applying :: operator in Rule L067

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_alter_warehouse.sql
- test/fixtures/dialects/snowflake/snowflake_alter_warehouse.yml
Added optional parameter on the Snowflake Alter Warehouse SET command step.
While the documentation lists that field as required by first running `USE WAREHOUSE` or selecting a Warehouse prior to running the command it will target the active selected warehouse.
https://github.com/sqlfluff/sqlfluff/issues/4342
- [ X ] Please confirm you have completed any of the necessary steps below.
- Other. …
> Snowflake: Fix Alter Warehouse

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_struct.sql
- test/fixtures/dialects/bigquery/select_struct.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/4339
I believe sqlfluff's parser had an error in the order of:
- `[ { DISTINCT | ALL } ]`; and
- `[ AS { STRUCT | VALUE } ]`.
so that sqlfluff would parse e.g.
```sql
SELECT AS STRUCT DISTINCT id FROM table;
```
which BigQuery does not parse, BigQuery's grammar for `SELECT` looks
like this:
> ```
> SELECT
>     [ { ALL | DISTINCT } ]
>     [ AS { STRUCT | VALUE } ]
>    select_list
> ```
> — https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#select_list
This commit changes the order of
- `[ { DISTINCT | ALL } ]`; and
- `[ AS { STRUCT | VALUE } ]`
so that sqlfluff parses what BigQuery parses, i.e. e.g.:
```sql
SELECT DISTINCT AS STRUCT id FROM table;
```
- Included test cases to demonstrate any code changes, which …
> BigQuery: SELECT DISTINCT AS STRUCT

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_create_table_as.sql
- test/fixtures/dialects/postgres/postgres_create_table_as.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/4297
Allows non quoted strings as parameter values in the storage parameters.
No
- Other.
> Allowed Naked Identifiers

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/select_exclude.sql
- test/fixtures/dialects/duckdb/select_exclude.yml
A missing optional meant that regular wildcard statements didn't work this fixes it.
No
- Other.
> Bugfix: Duckdb SELECT *

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table.sql
- test/fixtures/dialects/tsql/alter_table.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/3913
Added support for adding multiple columns in a single alter table statement,
Another way this could of been done is by keeping "ADD" and "ALTER" in the same statement and then nest `ColumnDefinitionSegment` in a `Delimited` optional. This would have the side effect though of letting invalid syntax correctly parse. This is because ALTER COLUMN only allows a single column.
Happy with either solution.
No …
> TSQL: ALTER TABLE

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/ansi/functions_a.sql
- test/fixtures/dialects/ansi/functions_a.yml
fixes #4376
Added underscore as valid leading character for function names.
No
- Other.
> Allow function names to have a leading underscore

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/select.sql
- test/fixtures/dialects/tsql/select.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/4095
Added optional `VARYING` keyword to data type segment for TSQL only. This could of either been done here or on the `DatatypeIdentifierSegment`. Since changing `DatatypeIdentifierSegment` would mean significant impact to the regex parsing I felt that the change here was safer.
Added additional test cases to check and validate.
No
- Other. …
> Added Varying Keyword to allowed data type segments

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_alter_role.sql
- test/fixtures/dialects/snowflake/snowflake_alter_role.yml
- Added a Snowflake dialect segment for [ALTER ROLE](https://docs.snowflake.com/en/sql-reference/sql/alter-role)
- Makes progress on #3479
- Other.
> Add Snowflake dialect ALTER ROLE segment

- docs/source/production.rst
- docs/source/teamrollout.rst
This was linking to a github action, but should link instead to the docs on using pre-commit with sqlfluff.
fixes #4404
No
- Other.
> Fix incorrect link to pre-commit docs

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_alter_storage_integration.sql
- test/fixtures/dialects/snowflake/snowflake_alter_storage_integration.yml
- Adds support for the [Snowflake Alter Storage Integration statement](https://docs.snowflake.com/en/sql-reference/sql/alter-storage-integration)
- Makes progress on #3479 
- Other.
> Snowflake: ALTER STORAGE INTEGRATION segment

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_create_view.sql
- test/fixtures/dialects/postgres/postgres_create_view.yml
Support recursive views in Postgres
Fixes #3894
No
- Other.
> Postgres: Support Recursive View

- src/sqlfluff/dialects/dialect_postgres_keywords.py
> Postgres: Remove execution keyword inherited from ANSI

- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/linter/runner.py
- src/sqlfluff/core/rules/__init__.py
- src/sqlfluff/core/rules/base.py
- src/sqlfluff/utils/testing/rules.py
- test/core/linter_test.py
- test/rules/std_test.py
This is part of #4031 and builds on #4399 .
The original PR added the option to use aliases and groups in rule selection, this extends that functionality to the `--noqa` option.
To do that involved a bit more than expected, because we need to be able to pass around an accurate `reference_map` (so allow any references to be interpreted). Rule lists are generated in the main thread and then passed around, complicating the issue.
This PR introduces a `RulePack` class which replaces all the locations where previously we would use a list of instantiated rules (`List[BaseRule]`). This contains the same list of rules, but also the reference map used in creation. This means any time we have a list of rules, we have a map of references to use in any other selection locations.
> Enable noqa using aliases and groups

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/assert.sql
- test/fixtures/dialects/bigquery/assert.yml
> BigQuery: parse "AS description" part of assert expressions

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_with.sql
- test/fixtures/dialects/postgres/postgres_with.yml
Make the `NOT` optional in expressions like `WITH name AS NOT MATERIALIZED (...)`.
See https://www.postgresql.org/docs/15/queries-with.html#id-1.5.6.12.7
No
- Other.
> Postgres: AS MATERIALIZED support

- src/sqlfluff/utils/reflow/rebreak.py
- test/fixtures/rules/std_rule_cases/L007.yml
This resolves #4184.
That issue came from an edge case where the previous point might contain no segments. This adds logic to search backward to look past any empty points. In most cases, it won't need to search further than the first - so I don't expect any performance hits.
> Resolve #4184 (index error in L007)

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/L016.yml
This resolves #4386 . Slight tweak to the long line logic so that we do still process the final line of files where the final line has no trailing newline.
> Handle long lines without trailing newlines gracefully (#4386)

- tox.ini
This hopefully solves the install errors we saw when releasing 2.0.0a5. In that case the dbt templater was failing to install because we were trying to install it _before_ sqlfluff, and it couldn't find a matching version number on pypi.
This partially reverts some of the changes made in #4399. I now understand better why things were originally that way and I've added better comments to explain that.
> Revert some changes to tox

- src/sqlfluff/core/templaters/jinja.py
Jinja tests have been throwing three warnings:
- `<frozen importlib._bootstrap_external>:629: DeprecationWarning: find_module() is deprecated and slated for removal in Python 3.12; use find_spec() instead`
- `<frozen importlib._bootstrap_external>:1591: DeprecationWarning: FileFinder.find_loader() is deprecated and slated for removal in Python 3.12; use find_spec() instead`
- `<frozen importlib._bootstrap>:283: DeprecationWarning: the load_module() method is deprecated and slated for removal in Python 3.12; use exec_module() instead`
This follows the docs at https://docs.python.org/3/library/importlib.html#approximating-importlib-import-module (which weren't super helpful tbh - had to do some other fiddling), to get things to work without those methods.
Warnings are now gone 👍
> Remove importlib deprecated methods

- .github/workflows/ci-tests.yml
- constraints/dbt100.txt
- constraints/dbt110.txt
- constraints/dbt130-winpy.txt
- constraints/dbt130.txt
- constraints/dbt140-winpy.txt
- constraints/dbt140.txt
- tox.ini
DBT 1.0 no longer compiles, due to https://github.com/dbt-labs/dbt-core/issues/7075
Pulling CI forward to 1.1 and 1.4 respectively
No
- Other.
> Pull dbt CI tests forward to 1.1 and 1.4

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
This resolves #4467 .
The `indent_stats` object is always relative to the incoming indent (because it's just the _effect_ of a single `IndentPoint`). We weren't correcting for that when implicit indents were found in deeper indents.
Also making a small logging change which makes things more readable for this kind of debugging.
> Implicit indent fixes #4467

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/rules/aliasing/AL06.py
- src/sqlfluff/rules/aliasing/AL07.py
- src/sqlfluff/rules/aliasing/__init__.py
- test/cli/commands_test.py
- test/core/linter_test.py
- test/fixtures/linter/aliases_in_join_error.sql
- test/fixtures/linter/autofix/ansi/026_LT05_line_length_includes_earlier_fixes/.sqlfluff
- test/fixtures/rules/std_rule_cases/AL07.yml
- test/rules/std_test.py
This is the _final part of the rules reorg_ and so closes #4031 .
As per discussion on slack:
- L031 confuses lots of new users.
- Some people still use it.
- The fixing routines are occasionally useful.
This PR migrates it to AL07 (`aliasing.forbid`), and also updated the `force_enable` behaviour (already present for BigQuery) to now apply to all dialects. In effect, this rule is always disabled unless explicitly enabled. This means users that want it can enable it, but for new users, they don't need to know about it, which should speed adoption and lead to less confusion.
I've also updated the docs with words to that effect - pointing users to AL06 (`aliasing.length`) as a better substitute in most cases.
> Recode and disable L031 -> AL07

- src/sqlfluff/cli/commands.py
- src/sqlfluff/rules/capitalisation/CP05.py
- src/sqlfluff/rules/jinja/JJ01.py
- test/cli/commands_test.py
- test/fixtures/linter/.gitignore
Ok this is a long time coming. This resolves #2436 and adds the `sqlfluff format` CLI command.
It's basically a variant on `sqlfluff fix`, but with a hardcoded set of rules. This has a nice upside that if someone is using `exclude_rules`, they can still exclude rules - but they can't enable additional ones, so it remains fairly safe.
As a first pass I've added the following rules to the command:
- All of the capitalisation rules: `capitalisation`
- All of the layout rules: `layout`
- `ambiguous.union`
- `convention.not_equal`
- `convention.coalesce`
- `convention.select_trailing_comma`
- `convention.is_null`
- `jinja.padding`
- `structure.distinct`
I haven't added _extensive_ testing, because the majority of the machinery is the same as `sqlfluff fix`. There should be enough here to get …
> Add a sqlfluff format CLI command

- src/sqlfluff/core/default_config.cfg
- test/fixtures/rules/std_rule_cases/LT01-excessive.yml
2.0.0a6 LT01 doesn't handle snowflake semi structured spacing very well. This updates the default config accordingly.
People can also retrofit this to 2.0.0a6 by adding the following section to their config:
```cfg
[sqlfluff:layout:type:casting_operator]
spacing_after = touch:inline
[sqlfluff:layout:type:snowflake_semi_structured_expression]
spacing_within = touch:inline
spacing_before = touch:inline
```
> Snowflake semi-structured spacing

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_unpivot.sql
- test/fixtures/dialects/bigquery/select_unpivot.yml
Previous parsing of the BigQuery `UNPIVOT` clause misplaced the single value unpivot case's row value aliases, as it is according to the [documentation](https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax#unpivot_operator
).
Here the syntax parsing is correctly applied and an additional test case is added to cover this combination.
Fixes #4486
No.
- Other.
- …
> BigQuery: correct query syntax for single column `UNPIVOT` clauses

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT05.yml
Found a small bug in operator precedence while testing 2.0.0a6. This resolves that.
Lowercase `and` operators were picked up with a different precedence to uppercase `AND` because we were using `.raw` and not `.raw_upper`.
> Bug in operator precedence

- docs/source/layout.rst
I think this resolves #4429. The layout docs had not been updated since some of the indentation changes. I've updated them to include appropriate references to implicit indents, and also to reflect the current behaviour of the indentation algorithm.
> Update layout docs

- .github/workflows/ci-tests.yml
I tried to enable the "merge queue" again, and the tests never ran. I think this should resolve that. See https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#merge_group
> Trigger CI tests for merge groups

- README.md
- docs/source/configuration.rst
- docs/source/index.rst
- docs/source/releasenotes.rst
This is primarily about adding a migration guide for 2.0.0 (and therefore resolves #4030).
In doing this:
- I realised that the "notable versions" on the front of the docs is out of date (no versions since 1.0.0 have been added), so that section now just has "major" versions (i.e. 1.0.0 and 2.0.0).
- The content that used to be in that section has been moved to a "release notes" section of the docs (name inspired by what the [airflow docs](https://airflow.apache.org/docs/apache-airflow/stable/release_notes.html) use).
- Release notes only reference releases which bring breaking changes (although I've kept the initial writing on releases pre 1.0 from the front page of the docs). Those release notes are mostly reformatted sections from the changelog for the major and minor releases.
Other …
> 2.0.0 Migration Guide

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/linter/autofix/bigquery/006_fix_ignore_templating/after.sql
- test/fixtures/rules/std_rule_cases/LT01-excessive.yml
This resolves a few issues in bigquery specific spacing raised during testing by @tunetheweb .
Specifically:
- spacing after `EXCEPT` and `REPLACE`.
- spacing around angle brackets.
- spacing around array type specifiers
- spacing within qualified function names.
In doing this I've also revised the parsing of array types more generally so that the "type" part of it is a distinct segment. This is partly necessary for the spacing rules to apply properly, but also I think it's more representative of how array literals are structured.
> Bigquery spacing

- src/sqlfluff/utils/reflow/respace.py
As part of revising layout config, I removed the `inline` option. @tunetheweb was still using it 😄 .
This adds a more helpful deprecation message and also auto-translates the value in the short term.
I've tested locally, but not adding to test suite because this should eventually be removed.
> Add a deprecation warning for removed config option.

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_create_user.sql
- test/fixtures/dialects/snowflake/snowflake_create_user.yml
In Snowflake, some of the properties of `create user` statement can have single quotes, but they are not accepted by SQLFluff right now. This PR aims to allow them.
No.
- Other.
> Snowflake: Optional quotes for `create user` statement

- plugins/sqlfluff-templater-dbt/test/templater_test.py
- src/sqlfluff/utils/testing/logging.py
- test/core/config_test.py
- test/core/linter_test.py
- test/core/rules/rules_test.py
This resolves #1146.
Based on pytest's own github issues, it seems wise to just implement a single workaround which simplifies existing tests. This moves all of the log handling into a context manager so that all the complexity is in one place, in a way that works well for users.
> Resolve #1146 (log propagation)

- docs/source/configuration.rst
- src/sqlfluff/core/config.py
- test/core/config_test.py
- test/fixtures/config/toml/pyproject.toml
This resolves #4519.
The new rules config (containing `.` characters in the rule name), conflicts with the `toml` format where we use `.` for the section separators rather than `:` (as per `.sqlfluff`).
This adds a special case in the toml parsing so that they can be interpreted in exactly the same way.
> Support new rules config in toml files.

- src/sqlfluff/core/default_config.cfg
- test/fixtures/rules/std_rule_cases/LT01-excessive.yml
This resolves #4521 . The more specific data types have already had a similar treatment.
There's a small chance that this could create issues with some more exotic datatypes - but nothing in the current test suite, and if there are - then we should adjust those specific cases similar to what was done in #4511 .
> Postgres datatype spacing issues

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
This removes codecov from our CI pipeline. It's no longer necessary.
#4532 means we've got coverage checks in GithubActions now.
Coveralls is a good enough interface to dig into any coverage misses (and there's an uploaded html report anyway).
> Remove Codecov from CI

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
- .github/workflows/create-release-pull-request.yaml
- .github/workflows/publish-dbt-templater-release-to-pypi.yaml
- .github/workflows/publish-sqlfluff-release-to-pypi.yaml
We're getting warnings in the Github Actions flows because of deprecated releases. This updates:
- `actions/upload-artifact` from `v2` to `v3`
- `actions/setup-python` from `v3` to `v4`
That should silence the warnings. The methods we use on each appear to be unchanged in both cases.
> Github Action Deprecations

- src/sqlfluff/dialects/dialect_ansi.py
- test/dialects/ansi_test.py
- test/fixtures/dialects/mysql/explain.yml
- test/fixtures/dialects/mysql/quoted_literal.yml
- test/fixtures/dialects/mysql/update.yml
- test/fixtures/dialects/mysql/variable_assignment.yml
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
This resolves #4484. We don't have good test coverage of `indented_joins`, this adds a test case and also fixes the indents - they were _far_ too complicated (and wrong).
> Resolve #4484 (issues with indented_joins indents)

- .pre-commit-hooks.yaml
This PR updates the pre-commit hook configuration and adds the following flags to the pre-commit hooks that SQLFluff provides:
- `--processes 0` for both `lint` and `fix`: Parallelizing the operations is likely always desired to speed up the pre-commit hooks.
- `--show-lint-violations` for `fix`: If not specified, issues that cannot be fixed automatically will need to be identified by manually running `sqlfluff lint`.
n/a
- Other.
- …
> Add additional flags to `sqlfluff` invocations in pre-commit hooks

- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
- pytest.ini
- src/sqlfluff/core/parser/segments/base.py
- test/dialects/dialects_test.py
- test/rules/yaml_test_cases_test.py
- tox.ini
This stems from a discussion on slack about the duration of the test suite. Previously, the longest duration was around 16 minutes. The longest parts are below, taken from this example: https://github.com/sqlfluff/sqlfluff/actions/runs/4441331387
- The python matrix tests (without coverage): 7-11mins
- Python 3.11 tests (with coverage): 13mins
- Python 3.10 windows test (with coverage): 16mins
- _"Critical errors test"_: 8mins
This PR does a few things:
- It expands the use of [pytest marks](https://docs.pytest.org/en/7.1.x/how-to/mark.html), from just the existing `integration_test` mark to:
- A `fix_suite` mark which maps roughly to the original `integration_test` mark.
- A `parse_suite` mark which covers the similar parsing suite for parsing structure tests and parsing/lexing success …
> Rethink test segregation in CI

- .github/workflows/ci-test-python.yml
I think in #4547 , while CI is much better, coveralls is now slightly broken (i.e. reporting low coverage ~60%): https://coveralls.io/github/sqlfluff/sqlfluff?branch=main
I think it's because several uploads are coming with the same flag name. This uses the same method as the github actions coverage to distinguish between them.
The test is whether coveralls reports the right coverage _for this PR_.
> Repair Coveralls

- src/sqlfluff/rules/convention/CV11.py
- test/fixtures/rules/std_rule_cases/CV11.yml
This resolves #4453. The algorithm in `CV11` didn't account for the parse structure of semi-structured accessing. This extends the handling to deal more robustly with that.
> Fix #4453: Snowflake semi-stuctured casts in CV11

- src/sqlfluff/utils/reflow/reindent.py
I found this bug in the process of working through #4033. The locations of previous untaken indents we're being corrupted by _negative_ untaken dedents. They should _not_ be included in the positive untaken indent tracking.
No test cases changed at this stage. I think that's ok - and a test case to stretch them will come as part of #4033 (and now actually as part of #4564).
> Fix untaken indent bug

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/dialects/dialect_ansi.py
On heavily nested expressions, being able to shortcut when a "long enough" match is found helps significantly. On combination with #4576, this has a very significant effect on heavily nested files.
It's a slightly dialled back version of what I think could be achieved, but it's a step in the right direction and does have some impact already.
> Use terminators in BaseExpression

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
This resolves #4559. TSQL reimplements `WhereClauseSegment` (and is the only dialect to do so) and didn't use the implicit indent segment. This fixes that (and adds a test case)
> Fix #4559: TSQL implicit indents on WHERE

- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/meta.py
I found this while looking into #4559. Debugging implicit indents is hard because they're not obvious in the parse tree. This addresses that by making them more visible.
This change should really only affect logging - so I haven't included extensive tests.
> Make implicit indents visible in the parse tree

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/column_alias.sql
- test/fixtures/dialects/mysql/column_alias.yml
> MySQL: allow quoted literal in alias name

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_table_functions.sql
- test/fixtures/dialects/postgres/postgres_table_functions.yml
Fxied #3843 
Don't think so
- Other.
> Support `WITH ORDINALITY` clauses in Postgres

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
This is a very small PR, related to #3744.
It makes dbt errors slightly nicer formatted in the CL so we don't get a full tracelog. Example.
Before this PR, a profiles file error would look like this:
```
=== [dbt templater] Sorting Nodes...
ERROR      dbt_profiles_dir: C:\Users\alanc\.dbt could not be accessed. Check it exists.
File "C:\Python39\lib\runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "C:\Python39\lib\runpy.py", line 87, in _run_code
exec(code, run_globals)
File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\Scripts\sqlfluff.EXE\__main__.py", line 7, in <module>
sys.exit(cli())
File "C:\Users\alanc\.virtualenvs\data_warehouse-quLENCc_\lib\site-packages\click\core.py", line 1130, in __call__ …
```
> Nicer formatted dbt errors

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/create_materialized_view.sql
- test/fixtures/dialects/clickhouse/create_materialized_view.yml
- test/fixtures/dialects/clickhouse/create_table.yml
Improve the Clickhouse dialect:
- Parse `MATERIALIZED VIEW` with dedicated Statement
Also fix bugs:
- `On Cluster` statement (with `ClusterReferenceSegment` function) that blocked some tests cases
- Statement Segment management (with `StatementSegment` function) that blocked any addition o *Something*Class (as issued with `CreateMaterializedViewStatementSegment` evolution)
No side effect.
- ~`.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.~
- Other.
- ~Added appropriate documentation for the change.~
> fix(dialect-clickhouse): Add materialized view statement

- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/linter/linting_result.py
- src/sqlfluff/core/timing.py
- test/cli/commands_test.py
- test/core/linter_test.py
This adds more granularity to the `--bench` output so that rule timings are visible (from performance session with @WittierDinosaur). Also adds rule timings to the timing csv output for performance tuning.
> --bench output with rule timings

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/core/parser/grammar/noncode.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/matchable.py
- src/sqlfluff/core/parser/parsers.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/meta.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
This relates to #3390, although probably not obviously.
`RegexMatcher` is bad, because it doesn't prune nicely using the `.simple()` route. Much of the way to get around that is through a greater use of the `TypedMatcher`, which means we can push the regex operations up into the lexer. **However**, up till now the `TypedMatcher` didn't support `simple` matching _either_. This implements that feature.
As a side effect, some of the handing for _non-simple_ matching can be removed from the base grammar - resulting in a simpler codebase. While it's still _possible_ to end up with some non-simple options (because we haven't get removed all of the `RegexMatcher` options), they now aren't actually used in any of the relevant cases. Because the aim is to remove them in the long run, instead of …
> .simple() matching for TypedMatcher

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/bigquery/select_with_window.sql
- test/fixtures/dialects/bigquery/select_with_window.yml
Fixes #4496 
I also added support for named windows so all the BigQuery WINDOW examples parse
- Other.
> Correct BigQuery WINDOW parsing

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/temporal_tables.sql
- test/fixtures/dialects/tsql/temporal_tables.yml
Support for `PERIOD FOR SYSTEM_TIME` (temporal tables)
Follow-up for #3542
Fixes https://github.com/sqlfluff/sqlfluff/issues/3542#issuecomment-1482836223
- Other.
> TSQL: `PERIOD FOR SYSTEM_TIME` (temporal tables)

- src/sqlfluff/dialects/dialect_snowflake.py
Adding the corresponding Dedent. Omitting this makes SQLFluff to keep increasing indent for every subsequent command by 1 every time it encounters a CREATE USER clause:
```sql
CREATE USER IF NOT EXISTS my_user
MUST_CHANGE_PASSWORD = true;
GRANT ROLE sysadmin TO USER my_user;
CREATE USER IF NOT EXISTS another_user
MUST_CHANGE_PASSWORD = true;
GRANT ROLE sysadmin TO USER another_user;
```
None
- Other.
- Added appropriate documentation …
> Snowflake: Stop ever-increasing indent in CREATE USER

- src/sqlfluff/dialects/dialect_athena.py
- test/fixtures/dialects/athena/select_underscore.sql
- test/fixtures/dialects/athena/select_underscore.yml
Fixes parsing error for Athena dialect when alias starts with underscore.
N/A
- Other.
> Athena: Fix parsing error with aliases starting with underscore

- src/sqlfluff/rules/convention/CV05.py
- test/fixtures/dialects/bigquery/alter_table_set_options.sql
- test/fixtures/dialects/bigquery/alter_table_set_options.yml
- test/fixtures/rules/std_rule_cases/CV05.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4644
No
- Other.
> BigQuery: Fix null assignment in options segment

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/exasol/MergeStatement.yml
- test/fixtures/dialects/snowflake/snowflake_merge_into.yml
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
Makes progress on #4232 
This is a first attempt to clean up and unionize the different `MergeInsertClauseSegment` of dialects.
- Other.
> Consistent indentation in `MERGE` `INSERT` clause

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/rules/references/RF06.py
- test/fixtures/rules/std_rule_cases/RF06.yml
Fixes #4310 which is about L029 and L059 being in conflict with each other where one wants unreserved keywords quoted and one doesn't, so it's impossible to make both happy without adding specific keywords to the ignore list.
Default behavior should remain the same, new behavior is behind a flag that defaults to off
- Other. …
> fix(RF06/L059): allows configuring prefer_quoted_keywords to deconflict with L029

- src/sqlfluff/rules/layout/LT07.py
- test/core/parser/markers_test.py
- test/fixtures/rules/std_rule_cases/LT07.yml
Did some linting of our wider project and found this bug. Took the opportunity to rationalise how LT07 works more generally. I think it was much more convoluted than it needed to be.
Includes a test case to demonstrate the issue which was originally unexpectedly making this rule flag up errors.
> Fix bug in templated with clauses LT07

- src/sqlfluff/rules/aliasing/AL05.py
Fixes this:
Don't think so but would like @alanmcruickshank to review to confirm if this was intentional.
- Other.
> Mark `is_alias_required` as a private class so it doesn't appear in docs

- src/sqlfluff/core/templaters/slicers/tracer.py
- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/join.sql
- test/fixtures/dialects/clickhouse/join.yml
Clickhouse: Add support for [LEFT] ARRAY JOIN
- Other.
> Clickhouse: Add support for [LEFT] ARRAY JOIN

- src/sqlfluff/rules/layout/LT03.py
- src/sqlfluff/rules/layout/LT04.py
This is triggered by the early performance investigations from @WittierDinosaur . We've noticed LT04 is a culprit of slowness in some larger queries. This adds a shortcut for places where the full reflow routine isn't required. It doesn't cover all cases, but in cases that are _clearly passing_ it bypasses the need to run the full reflow routine to generate the fix.
If that has a meaningful impact, it would be fairly easy to port similar changes to the operator routines, and also add some additional clauses here to account for some other scenarios.
> Add performance shortcuts to LT03 & LT04

- .github/workflows/create-release-pull-request.yaml
- CONTRIBUTING.md
- util.py
For the release script I always have to use `--help` to remember the command and the option name. The script doesn't really work _without using the option_ however - so it seems more sensible to make it an argument so that it's always required. I think the command is also too long. This shortens things:
```bash
python util.py prepare-release --new_version_num=1.1.1
python util.py release 1.1.1
```
I've also updated the CI script, but I'm hoping this is easier for me to remember when kicking this off manually in future.
> Make version number an argument not an option in release script.

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_execute_task.sql
- test/fixtures/dialects/snowflake/snowflake_execute_task.yml
All the use of `EXECUTE TASK <name>` when using Snowflake.
https://docs.snowflake.com/en/sql-reference/sql/execute-task#syntax
> fix{dialect-snowflake}:Execute Task

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/snowflake_alter_table_column.sql
- test/fixtures/dialects/snowflake/snowflake_alter_table_column.yml
Allows Snowflake `ALTER TABLE ALTER COLUMN` statements to set and unset tags.
Syntax: https://docs.snowflake.com/en/sql-reference/sql/alter-table-column
> fix{dialect-snowflake}:Alter Table Column Set/Unset Tag

- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
In the current release `--persist-timing` only works on `lint`. This adds it to `fix` too (and also `format` in the process).
> Allow persist timing on `fix` too.

- src/sqlfluff/rules/convention/CV03.py
- test/fixtures/rules/std_rule_cases/CV03.yml
This resolves #4681 . When a comma is in a loop - it's not safe to remove. This prevents that.
> Safety valve for fixes in CV03

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/create_view.sql
- test/fixtures/dialects/sparksql/create_view.yml
This change adds support for `USING` and `OPTIONS` clauses within `CREATE VIEW` statements. This is done to reflect spark sql documentation: 
https://spark.apache.org/docs/latest/sql-data-sources-jdbc.html
As evident on the bottom of this page, these are officially supported in `CREATE VIEW` statements. 
A test case has been added to `test/fixtures/dialects/sparksql/create_view.sql` to test this new support.
- [X ] Please confirm you have completed any of the necessary steps below.
- Full …
> SparkSQL: Add using and options clause to create view statement

- src/sqlfluff/core/rules/base.py
I've noticed a very noisy error for a while during testing. This resolves the `No config_keywords defined for {code}` error by setting a default empty list on the base rule class.
> Add a default for config_keywords and remove noisy error.

- src/sqlfluff/rules/capitalisation/CP01.py
- src/sqlfluff/rules/capitalisation/CP05.py
- test/fixtures/rules/std_rule_cases/CP01.yml
- test/fixtures/rules/std_rule_cases/CP03.yml
The pull request at https://github.com/sqlfluff/sqlfluff/pull/2566 made sense for users who set ignore_templated_areas to true because those macros are not under their control.  However, if a user is writing their own macros and would like to lint those, that commit made the capitalization rules completely unusable.
For example, the following code in a single file would not trigger any violations, even if ignore_templated_areas is set to false:
{% macro abc() %}
sElEcT a, B fRoM abc;
{% endmacro %}
{{ abc() }}
That is... a surprising result...
This commit will now only skip templated areas if we are actually configured to do that.  Hopefully this will allow their use in templated areas if desired, while still avoiding false positives when we ignore template areas as the previous commit …
> Capitalization rules ignore templated code only if configured to

- src/sqlfluff/core/templaters/slicers/tracer.py
- test/core/templaters/jinja_test.py
The "import" and "from" Jinja directives are currently treated as of type "block_start".  This (unsurprisingly) leads to this error:
Indent balance test failed for 'demo.sql'. Template indents will not be linted for this file.
And then template indentation rules don't work correctly any more.  So we see errors like:
```
L:   5 | P:   1 | LT02 | Line should not be indented.
| [layout.indent]
```
on code like:
```
{% import 'echo.sql' as echo %}
{% if True %}
SELECT 1;
{% endif %}
```
even though template_blocks_indent is still on.
This commit fixes the problem by treating those directives as simple "templated" types, similar to how the "include" type already is. …
> Jinja templater: treat "import" and "from" as templated

- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/enums.py
- test/cli/commands_test.py
While testing the parser it's sometimes useful to supress output (long output can take as long to write to stdout as the thing I'm testing!). This adds an additional `none` output which then outputs... nothing.
> Add a no-output option

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/add_jar.sql
- test/fixtures/dialects/sparksql/add_jar.yml
- test/fixtures/dialects/sparksql/select_order_by.sql
- test/fixtures/dialects/sparksql/select_order_by.yml
This change fixes a bug with the `file_literal` regex. Previously literals such as `/word` would be considered a file. This is an issue because literals such as `/sum` were being lexed as a file literal rather than part of an expression. 
Now the `file_literal` regex requires that the file end with either a file extension or url parameters. 
- Other.
- Added …
> SparkSQL: Fix file literal lexing

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/window_functions.sql
- test/fixtures/dialects/sparksql/window_functions.yml
This change adds support for interval expressions within the window frame bounds in spark sql. While it isn't clear that this is supported on the official documentation. The ANTLR grammar file on the OSS displays this https://github.com/apache/spark/blob/007a42b8511b005aabdf45955e504d1f71eb1d25/sql/catalyst/src/main/antlr4/org/apache/spark/sql/catalyst/parser/SqlBaseParser.g4#L1120
A test was added to `test/fixtures/dialects/sparksql/window_functions.sql` …
> SparkSQL: Improve window frame bounds

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_reset.sql
- test/fixtures/dialects/postgres/postgres_reset.yml
- test/fixtures/dialects/postgres/postgres_set.sql
- test/fixtures/dialects/postgres/postgres_set.yml
Not much to say beyond what's in the title.
From https://www.postgresql.org/docs/15/sql-set-role.html
- Other.
> Add support for PG SET ROLE / RESET ROLE

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/ansi/create_cast.sql
- test/fixtures/dialects/ansi/create_cast.yml
- test/fixtures/dialects/ansi/drop_cast.sql
- test/fixtures/dialects/ansi/drop_cast.yml
- test/fixtures/dialects/postgres/postgres_create_cast.sql
- test/fixtures/dialects/postgres/postgres_create_cast.yml
- test/fixtures/dialects/postgres/postgres_drop_cast.sql
- test/fixtures/dialects/postgres/postgres_drop_cast.yml
Add CREATE CAST and DROP CAST statements to the ANSI dialect, following the SQL 2016 grammar at:
https://jakewheat.github.io/sql-overview/sql-2016-foundation-grammar.html
Then, add the same statements to the postgres dialect, changing the grammar to follow the grammar defined at:
https://github.com/postgres/postgres/blob/4380c2509d51febad34e1fac0cfaeb98aaa716c5/src/backend/parser/gram.y
The test fixtures were validated as follows:
* ANSI statements were run through https://developer.mimer.com/sql-2016-validator/
* PG statements were parsed using my local PG 15 instance. …
> Add the CREATE/DROP CAST statements to ANSI and PG

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_with.sql
- test/fixtures/dialects/postgres/postgres_with.yml
PostgreSQL supports the non-standard RETURNING clause on a DML query, and therefore those queries can also be used in a CTE.
- Other.
> Allow DML queries to be selectable in CTEs on PG

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_create_table.sql
- test/fixtures/dialects/postgres/postgres_create_table.yml
The online documentation omits CHAR VARYING as a possible type. However, the grammar lets you do it.
- Other.
> Add CHAR VARYING data type for PG

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_drop_view.sql
- test/fixtures/dialects/postgres/postgres_drop_view.yml
DROP statement in ANSI SQL does not support dropping multiple views at a time, but PostgreSQL does.
- Other.
> Add support for dropping multiple views with PostgreSQL

- src/sqlfluff/core/dialects/base.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_materialize.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
Keep out the zero length keyword.  Their inclusion is due to the fact
that some keywords are specified in multiline strings, and the trailing
newline results in an empty string.
I think their inclusion is almost certainly accidental, so this code
strips the input string before we split it in order to avoid that
problem.
- Other. …
> Keep out zero length keywords

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_array.sql
- test/fixtures/dialects/postgres/postgres_array.yml
PG array access with a slice is quite simple:
https://github.com/postgres/postgres/blob/4380c2509d51febad34e1fac0cfaeb98aaa716c5/src/backend/parser/gram.y#L16392-L16409
| '[' a_expr ']'
| '[' opt_slice_bound ':' opt_slice_bound ']'
opt_slice_bound:
a_expr
| /*EMPTY*/
The existing code has a few problems:
1.  It does not allow for an access like "[:]".
2.  It does not support expressions.
3.  It has too many layers of matchers.  There is already an Accessor_Grammar that has AnyNumberOf these accessors, so we don't need another outer AnyNumberOf here.  We also don't need a Sequence containing a single OneOf.
These are all easy enough to fix.
Fixes #4336  …
> Simplify and fix PG array accessor segment & support expressions

- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/rules/std_rule_cases/LT01-trailing.yml
Found an issue in testing where some macros would trigger LT01 unnecessarily. This was because of incorrect handling of templated newlines. This fixes that.
> Fix issue with macros triggering LT01

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_clickhouse.py
- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_teradata.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/exasol/AlterTableDistributePartition.yml
- test/fixtures/templater/jinja_l_metas/001.yml
- test/fixtures/templater/jinja_l_metas/009.yml
Greedy matchers are less performant than their non-greedy equivalent. they're also more prone to over-matching. This PR removes most uses of StartsWith() - with a view to deprecate in the medium term. Of all of these changes, only one change has happened to the parse fixtures - and it's an improvement! There are a few StartsWith instances left, these have proven tricker to excise, so I figured I'd spin them off into a separate PR.
This also speeds up parsing of some of my large files by 5-10%
It changes the parse tree position of some trailing whitespace. But this is due to an inconsistency between GreedyMatch and Sequence. GreedyMatch discards trailing whitespace, Sequence does not. Either are fine, but we should be consistent - and hopefully, we should be able to remove GreedyMatch soon …
> Remove the majority of greedy matchers

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/linter/autofix/bigquery/001_templating/after.sql
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
Another one found during testing against our project. IMHO I think the comment indentation rules are _too strict_ right now. While I agree that the default _fix_ anchor should be the _following_ line - if a comment currently matches the indentation of the line before, then I don't think that should trigger a linting error. This opens up that.
> Allow comment match with preceding line

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/set.sql
- test/fixtures/dialects/hive/set.yml
This resolves #3560 and resolves #1768. Two quite old issues. My parsing structure for the `set -v` command is perhaps a little non-standard, but I think the implications of that are small and we can always clean it up later if anyone builds on this work.
> Support hive set syntax

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/arithmetric_a.sql
- test/fixtures/dialects/sqlite/arithmetric_a.yml
This commit copies over the changes from #4717 into the SQLite grammar, since it had been copy/pasted.
The change was made by diffing the original Expression_A_Grammar from before #4717 was merged, against the current SQLite implementation. I only found the one difference being removal of "PRIOR" keyword, so I only override Expression_A_Unary_Operator_Grammar so that can be removed.
Also the tests were copied verbatim from the ANSI dialect tests. …
> SQLite: Fix multiple parse issues in Expression_A_Grammar

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_greenplum.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/mysql/alter_database.yml
- test/fixtures/dialects/mysql/create_database.yml
- test/fixtures/dialects/mysql/create_table_column_charset.yml
- test/fixtures/dialects/postgres/postgres_create_table.yml
- test/fixtures/dialects/snowflake/snowflake_create_table.yml
- test/fixtures/dialects/tsql/collate.yml
- test/fixtures/dialects/tsql/create_external_table.yml
- test/fixtures/dialects/tsql/create_table_constraints.yml
This is the result of searching for sequences of "COLLATE" followed by some other segment type.  During this exercise, I realized that some dialects also accept string literals instead.
This commit makes the CollationReferenceSegment in the ANSI dialect a little extra permissive and accepts either an object reference or a string literal.
- Other. …
> Use the new CollationReferenceSegment everywhere

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
I think the part of code which I've covered here is now getting pretty mature, so this bug was a little hard to pinpoint - but I think the crux is that we should evaluate untaken indents _outward in_ (i.e. backwards) rather than forwards. This means that the right priority is given in locating potential indents to force. This resolves #4540 .
> Fix #4540: Untaken indents evaluation order.

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_trigger.sql
- test/fixtures/dialects/sqlite/create_trigger.yml
This PR gives SQLite support for CreateTrigger. In doing so, StatementSegment could no longer use the Greedy matcher, as Delimited statements can exist inside the statement. Several of the SelectStatement grammar pieces have also been displaced for the same reason. I've gathered several examples of CreateTrigger from the sqlite docs and other sources to test.
Fixes #1846 
No
- Other. …
> SQLite: Support CreateTrigger

- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/templaters/slicers/tracer.py
- test/core/templaters/jinja_test.py
> Fix #4603 indent after Jinja 'do' directive

- src/sqlfluff/core/templaters/base.py
- test/core/templaters/base_test.py
This resolves #2855. There was an unnecessary flag to cover some misshapen test cases which I've fixed here. It's a low risk PR because only really covers the test suite and not the core codebase.
> Fix #2855: (Tech debt: check consistency in TemplatedFile init)

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_safe_function.yml
- test/fixtures/rules/std_rule_cases/LT01-operators.yml
Makes progress in: https://github.com/sqlfluff/sqlfluff/issues/4645
The idea here is to introduce a BigQuery specific `SafePrefixSegment` to better control the whitespacing within the function call. This
- **does** resolve the whitespace issue between `dot` and `function_name`
- **does not** resolve the whitespace issue between `SAFE` and `dot`
**Open Question:**
It's not clear to me why this still happens
```
"Expected single whitespace between 'SAFE' keyword and dot '.'."
```
Shouldn't
```
Sequence("SAFE", Ref("DotSegment"), allow_gaps=False)
```
prevent exactly that?
No …
> Inroduce `SAFE` prefix segment

- docs/source/configuration.rst
Use linux style xdg on mac (#955) had introduced a change where macOS config files no longer use the `~/Library/.. ` config directory and instead prefers the linux variant. The documentation was not updated, however.
This PR seeks to amend that.
No. This is only a documentation fix.
> fix: correct macos/osx config file location

- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
There's a clause in `_crawl_indent_points()` which handles potential bracketed expressions around implicit indents. In testing 2.0.6 I found a bug in it - this solves that bug and adds a test case.
> Fix bug with brackets and implicit indents

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/redshift_create_view.sql
- test/fixtures/dialects/redshift/redshift_create_view.yml
Fixes #4806 - adds back funcitonality removed in Postgres
No
- Other.
> Redshift: Support with no schema binding

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
There is a small typo in a error message, 2 words appear without space in the middle. This is just adding that space. See attached image:
No
- Other.
> Fix: Small typo in error message

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/insert_into_table.sql
- test/fixtures/dialects/hive/insert_into_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4816
No
- Other.
> Hive: INSERT INTO without TABLE keyword

- .github/workflows/ci-tests.yml
- constraints/dbt140-winpy.txt
- constraints/dbt140.txt
- constraints/dbt150-winpy.txt
- constraints/dbt150.txt
- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- tox.ini
Fixes an issue wherein dbt.flags cannot find PROFILES_DIR.
The issue that this call used to fix seems to have been fixed in a backported change https://github.com/dbt-labs/dbt-core/commit/c952d44ec5c2506995fbad75320acbae49125d3d#diff-b99c74c2d09fa1ea054aa843fa3738bd7c9d39acb9c5b90ca920f0e1fcf38010
No
- Other. …
> Make SQLFluff compatible with DBT 1.5

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_sqlite_keywords.py
- test/fixtures/dialects/sqlite/create_table.sql
- test/fixtures/dialects/sqlite/create_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/4829
Maybe could sneak into sqlite dialect directly instead of ANSI, but I felt `ColumnConstraintSegment` still has a ton of overlap so didn't want to redefine in sqlite.
- Other.
> Sqlite: COLLATE column constraint

- src/sqlfluff/rules/layout/LT12.py
- src/sqlfluff/utils/reflow/sequence.py
- test/cli/commands_test.py
This fixes #4807.
Two rules didn't play nice with empty files. I've added explicit handling for that scenario in LT12, and in the reflow constructor for LT02 (and other rules using reflow).
> Fix #4807: LT02 & LT12 issues with empty files.

- src/sqlfluff/dialects/dialect_athena_keywords.py
Athena v2 uses Presto, Athena v3 uses Trino as backend.
So i've added link to reserved keywords for Trino
> Add link to Trino keywords (Athena v3)

- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_mysql_keywords.py
- test/fixtures/dialects/mysql/create_index.sql
- test/fixtures/dialects/mysql/create_index.yml
Adding support for NOCOPY and INSTANT algorithm on CREATE INDEX on the MySQL dialect
Both algorithms are supported by MariaDB as defined in the MariaDB documentation:
https://mariadb.com/kb/en/create-index/
fixes #4864 
No side effects are expected but these algorithms are only currently supported by MariaDB.
- Other. …
> Adding support for NOCOPY and INSTANT algorithm on CREATE INDEX on MySQL dialect

- src/sqlfluff/dialects/dialect_athena.py
- test/fixtures/dialects/athena/show_tables.sql
- test/fixtures/dialects/athena/show_tables.yml
- test/fixtures/dialects/athena/show_views.sql
- test/fixtures/dialects/athena/show_views.yml
This PR makes progress on #4811 by  addressing the Athena side of the bug report. It adds a new Show segment and the associated tests to drive it.
I narrowed the scope to just one DB since this is my first PR over here, I have a couple style questions that I thought would be easier to ask in this context.
Nope, just grammar
- Other. …
> Add show tables/views to athena

- test/fixtures/dialects/athena/select_group_by.sql
- test/fixtures/dialects/athena/select_group_by.yml
Athena dialect tests:
* add "weird" cases for `group by` when grouping columns and `grouping sets` are combined
> Athena: add "weird" test cases for `group by`

- docs/source/configuration.rst
- docs/source/internals.rst
This PR tries to improve the documentation about configuration of the various templaters.
Currently, the documentation can be a little hard to read and understand. For example
- Placeholder templater docs is a subsection to Jinja. In the middle of other Jinja documentation, which can be distracting.
- Alone from the configuration documentation It's not immediately clear which templaters exists. Users have to find the  Internals documentation to learn about available templaters.
- All available configuration options for the Jinja templater are not available at one glance.
See the current structure:
To address these point, this PR groups all templating into a section of the configuration docs, like so
Then, all the specifics are handled in the corresponding sections.
**Note:** I tried to …
> docs(templater): Refactor templater configuration docs

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/create_table.sql
- test/fixtures/dialects/oracle/create_table.yml
Oracle: Add support for `$` and `#`  in identifier
- Other.
fix for https://github.com/open-metadata/OpenMetadata/issues/7216
> Oracle: Add support for `$` and `#`  in identifier

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/drop_external_table.sql
- test/fixtures/dialects/tsql/drop_external_table.yml
`fixes #4918`, introduces support for `DROP EXTERNAL TABLE` in TSQL
no
- Other.
> TSQL: support for `DROP EXTERNAL TABLE`

- docs/source/releasenotes.rst
Noticed this on [the release notes page](https://docs.sqlfluff.com/en/latest/releasenotes.html#upgrading-to-1-4):
Nope, simple doc update
- Other.
> Remove extra code escapes from release notes docs

- docs/source/configuration.rst
- docs/source/production.rst
- examples/04_config_overrides.py
- src/sqlfluff/cli/click_deprecated_option.py
- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/templaters/jinja.py
- test/cli/commands_test.py
- test/fixtures/templater/jinja_m_libraries_module/.sqlfluff
This resolves a potential security risk, and also adds a bunch of documentation to cover it.
It enables a CLI option to override the `library_path` option in the templater to prevent unsecured code being called.
> Security option for library path

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
This resolves the compatibility issues with dbt 1.5.2 onwards due to https://github.com/dbt-labs/dbt-core/pull/7949. For those versions onward we need to manually inject the `project_root` into the context before calling any of the methods that require it.
Also removes an old path handling clause which was resolved in 2022.
> Fix compatibility with dbt 1.5.2+

- .github/workflows/ci-tests.yml
- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
This re-enables support and tests for dbt 1.1 and 1.2. It effectively selectively reverts the fixes made in #4886, which fixed support for 1.5, but broke support for 1.1 & 1.2.
Combined with #4941 and #4939, this means we should have full compatibility with dbt 1.1.0 up to the latest 1.5.2. Anything pre 1.1 doesn't compile anymore so I'm very comfortable not supporting that 😄 .
Note that I'm added `dbt110` back into the coverage group so that the clauses for 1.1 and 1.2 are covered.
> Re-enable dbt 1.1 & 1.2

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/alter_table.sql
- test/fixtures/dialects/mysql/alter_table.yml
Addin support to RENAME COLUMN whe using ALTER TABLE, which is supported by MySQL which the doc can be checked here: https://dev.mysql.com/doc/refman/8.0/en/alter-table.html
fixes #4947 
No side effect expected, syntax is fully supported by MySQL and MariaDB.
- Other.
> Adding support to ALTER TABLE with RENAME COLUMN on MySQL dialect

- src/sqlfluff/rules/references/RF05.py
Fixes the following (redacted) error report, seen in VSCode:
```
CRITICAL   [RF05] Applying rule RF05 to 'XXXXX.sql' threw an Exception: string index out of range 
File "/XXXXX/sqlfluff/lib/python3.11/site-packages/sqlfluff/core/rules/base.py", line 796, in crawl
res = self._eval(context=context)
^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/XXXXX/sqlfluff/lib/python3.11/site-packages/sqlfluff/rules/references/RF05.py", line 132, in _eval
if identifier[-1] == "*":
~~~~~~~~~~^^^^
IndexError: string index out of range
```
No
- [Y] Please confirm you have completed any of the necessary steps below.
- …
> RF05 BigQuery empty identifier bug

- src/sqlfluff/cli/commands.py
Some of the fixes [here](https://github.com/sqlfluff/sqlfluff/pull/4954) (but not all) needed to be removed because of the new [click release](https://github.com/pallets/click/releases/tag/8.1.5).
> Remove mypy ignores

- .github/FUNDING.yml
Flattr seems to be retiring their platform for funding, and github sponsorship is much more fully featured. Adding link here - ditto to the org page in separate PR.
> Update funding yaml to use github sponsors

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_from_lateral_view.sql
- test/fixtures/dialects/sparksql/select_from_lateral_view.yml
- test/fixtures/dialects/sparksql/select_lateral_view_supported_tvf.yml
- Closes https://github.com/sqlfluff/sqlfluff/issues/4978
- Add 4 more valid sparksql lateral view test cases listed below. They not not necessarily allowed by documentation but definitely parsable and runnable. Not sure if it's a feature or bug of Spark. Let me know if you don't want explicitly test for them:
```sql
-- table alias + optional AS + column alias
LATERAL VIEW OUTER EXPLODE(ARRAY()) tbl_name c_age
-- optional table alias + optional AS + column alias
LATERAL VIEW OUTER EXPLODE(ARRAY()) c_age
-- table alias + optional AS + column aliases
LATERAL VIEW INLINE(array_of_structs) exploded_people name, age, state
-- optional table alias + AS + column aliases
LATERAL VIEW INLINE(array_of_structs) AS name, age, state
```
- Included test cases to demonstrate any code changes, which may …
> fix: sparksql lateral view parse tree for multiple column alias

- docs/source/conf.py
Closes https://github.com/sqlfluff/sqlfluff/issues/4987
Hits a dead link: https://github.com/sphinx-doc/alabaster/blob/7a9df17b6366c96baba6bf5e14f9b6ff6bf7defa/alabaster/layout.html#L104
I'm too lazy to find a replacement. It's probably just fine to drop off this banner.
- Other.
> Remove broken 'fork me' banner from docs

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select.sql
- test/fixtures/dialects/snowflake/select.yml
Better fix for #4968 
The [snowflake keyword snytax](https://docs.snowflake.com/en/sql-reference/reserved-keywords) says this about `CROSS`:
```
Cannot be used as table name or alias in a FROM clause.
```
So looks like it can be used as a column name as requested by #4968 and implemented in #4975.
This PR excludes it from table aliases only.
No more than original fix :-)
- Other.
- …
> Correct Snowflake `CROSS JOIN` syntax

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/dollar_quoted_literal.sql
- test/fixtures/dialects/clickhouse/dollar_quoted_literal.yml
Prior to this change, dollar quoted literals failed to parse when using the Clickhouse Dialect. 
Example (Output generated using tests in this repo):
```
Query: SELECT * FROM foo WHERE col1 = $$bar$$;
FAILED test/dialects/dialects_test.py::test__dialect__base_file_parse[clickhouse-dollar_quoted_literal.sql] - assert not [SQLParseError("Line 1, Position 29: Found unparsable section: ' = $$bar$$'"), SQLParseError("Line 3, Position 29: Found unparsable section: ' = $baz$bar$baz$'")]
FAILED test/dialects/dialects_test.py::test__dialect__base_broad_fix[clickhouse-dollar_quoted_literal.sql] - assert not [SQLParseError("Line 1, Position 29: Found unparsable section: ' = $$bar$$'"), SQLParseError("Line 3, Position 29: Found unparsable section: ' = $baz$bar$baz$'")]
FAILED …
```
> Clickhouse Dialect - Support Dollar Quoted Literals

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/postgres/create_function.yml
- test/fixtures/dialects/snowflake/grant_revoke.yml
Fixes a bug whereby function names in grants were treated as object references, making reflow improperly space the brackets.
No
- Other.
> Bugfix: Treat Function name properly in grants

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/rules/ambiguous/AM06.py
- test/fixtures/dialects/bigquery/select_function_parameter_order_by_multiple_columns.yml
- test/fixtures/rules/std_rule_cases/AM06.yml
Fixes #3649 
Shouldn't be
- Other.
> AM06 to ignore aggregate ORDER BY clauses

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/within_group.sql
- test/fixtures/dialects/oracle/within_group.yml
Closes #4145
Also add support to "on overflow" clause.
Tests taken from the  examples in [Oracle documentation](https://docs.oracle.com/en/database/oracle/oracle-database/21/sqlrf/LISTAGG.html#GUID-B6E50D8E-F467-425B-9436-F7F8BF38D466)
- Other.
> Add support to oracle's listagg function

- examples/05_simple_api_config.py
- src/sqlfluff/api/simple.py
This PR enables passing a `FluffConfig` to the simple API and not just a `config_path`. I've added an example file to demonstrate the functionality.
> Simple API config and examples

- src/sqlfluff/core/rules/base.py
While building docs, the warning for rule configuration occasionally flags and that's because of the import path for the `BaseRule` (which shouldn't apply any configuration _anyway_). This provides an exception for that and explicitly _doesn't_ check for any of this when we're instantiating the `BaseRule`.
> Fix: Add exception to the warning & config for the BaseRule.

- docs/source/gettingstarted.rst
The example `.sqlfluff` config file in the Getting Started section:
```
[sqlfluff]
dialect = ansi
[sqlfluff:indentation]
tab_space_size = 2
[sqlfluff:rules:CP01]
capitalisation_policy = lower
```
gives me these warnings when run with version 2.1.4 of sqlfluff:
```
WARNING    Rule configuration contain a section for unexpected rule 'CP01'. These values will be ignored. 
WARNING    The reference was however found as a match for rule CP01 with name 'capitalisation.keywords'. SQLFluff assumes configuration for this rule will be specified in 'sqlfluff:rules:capitalisation.keywords'
```
and the rule then appears to be ignored (the capitalisation of the keywords does not change to lowercase).
The changes fixes the example config file according to the suggestion.
Documentation-only change.
> DOC: Fix .sqlfluff example in Getting Started

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/named_argument.sql
- test/fixtures/dialects/oracle/named_argument.yml
> Fix for parsing of Oracle functions with named arguments

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/errors.py
- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/linter/noqa.py
- src/sqlfluff/core/linter/runner.py
- test/cli/commands_test.py
- test/core/linter/noqa_test.py
- test/fixtures/cli/disable_noqa_test.sql
This resolves #2337 (an oldie). I've tried to mirror the `mypy` syntax as closely as possible.
My algorithm for what counts as "used" has a few loopholes in it, but I think they're manageable for now (e.g. We count an `enable` as _used_ when it successfully re-enables something disabled by a `disable` - but this only evaluation happens if we get close enough to it in the file (usually because there was an error within the span, or after it. If we never get there, we never evaluate it and _both_ the enable and disable will be deemed unnecessary).
The new test case in `commands_test.py` is probably the best place to see what the effect of this is.
@tunetheweb I know you had views on the original PR here so would be curious for your review on this one.
> Warn on unused `noqa` directives

- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/match_logging.py
- src/sqlfluff/core/parser/match_wrapper.py
- src/sqlfluff/core/parser/segments/meta.py
Strict mypy for `match_wrapper.py` and `match_logging.py`. This is a relatively minimal PR. There's a larger version of this which would include `ephemeral.py` too, but that's a much bigger change.
> strict mypy: match_wrapper & match_logging

- src/sqlfluff/core/parser/match_result.py
This is a performance improvement which stems from the `mypy --strict` work. We were doing some type munging on every instantiation of a `MatchResult` - this is a very simple change but it saves one of the top items on the `cProfile` output. Saves about 10% on big files.
> Mypy gain: Remove unnecessary tuple construction in MatchResult

- src/sqlfluff/core/linter/runner.py
- src/sqlfluff/core/plugin/host.py
- src/sqlfluff/core/rules/base.py
This resolves another issue created by #5020 .
When running in a multiprocessing configuration, the error about import order was flagging unnecessarily. This further restricts that validation so that it only happens in the main process.
> Fix for multiprocessing warnings.

- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/matchable.py
- src/sqlfluff/core/parser/parser.py
- src/sqlfluff/core/parser/segments/base.py
- test/core/parser/grammar_test.py
- test/core/parser/parse_test.py
- test/core/parser/parser_test.py
- test/core/parser/segments_base_test.py
- test/core/parser/segments_common_test.py
- test/dialects/conftest.py
Another possible performance improvement from the mypy work. Saves ~10% on large files.
In the ParseContext object, we made copies as we move up and down the parsing structure. This does some more "smart" management of the context (and uses `contextlib` instead) to avoid all the copying, and just use context managers properly instead. I've also consolidated the way that people interact with the context too.
At this point, the distinction between `ParseContext` and `RootParseContext` makes no sense - so I've merged the two together and simplified the whole module as a result. There is now only `ParseContext`.
I didn't manage _total_ isolation, so I still do some tuple manipulation to add some safety, because getting lists to play nice was too hard.
> Less copying in the ParseContext

- src/sqlfluff/core/errors.py
Squashing a small one here 😁 
I needed to use `Tuple[Any, ...]` for typing `__reduce__` since everything is a subclass of  `SQLBaseError` and `mypy` didn't like us having different return values for inherited methods
I also this that `mypy` helped us find a bug -- the `__reduce__` for `SQLBaseError` was referencing `self.pos` which doesn't exist. I replaced it here with `None` which seems appropriate
> :white_check_mark: Add strict typing for errors module

- .pre-commit-config.yaml
Right now it errors for me on the older version of `mypy`, when I bring it up to the current version it passes just fine
> :arrow_up: Bump mypy version in pre-commit

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/match_wrapper.py
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/clickhouse/system_statement.yml
Hopefully a nice small and tidy PR.
This moves the `_prune_options` method (and `_first_non_whitespace` along with it) from the `AnyOf` grammar up into `BaseGrammar`. I've also moved it _inside_ `_longest_trimmed_match()` which means it's automatically used in `Delimited` as well as `AnyOf` or `AnyNumberOf`. Performance impact should be positive, but small.
Part of this is for simplification, but I also hope to take another pass at the parse statistics to support better optimisation there, and having the pruning operation within that step should help significantly with doing that.
This led to finding an issue in the `ansi` dialect (related to some `clickhouse` statements) - so that's why I've touched one of the dialect and yaml.
> Move `_prune_options` within `_longest_trimmed_match`.

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/.sqlfluff
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/operator_errors.sql
- plugins/sqlfluff-templater-dbt/test/templater_test.py
Hopefully nice an easy one.
This resolves #5054 (at least until dbt changes their internal APIs).
This attempts to clear the internal logger handlers (using an existing method which exists within the dbt project).
> Try to silence dbt logging #5054

- src/sqlfluff/core/linter/linter.py
- test/core/linter/linter_test.py
I thought I'd fixed this a while ago!
When there's only one file being processed we shouldn't invoke any of the multithreaded runners. This clause detects running on a single file and forces us to use the simple runner in that case.
No tests in this case because both options work, this is more of a performance hack.
> Never run in multiprocessing mode with only 1 file.

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/limit_clause.sql
- test/fixtures/dialects/postgres/limit_clause.yml
Adding logic to fix issue [#4938 ](https://github.com/sqlfluff/sqlfluff/issues/4938).
Handles cases for postgres well.
File now parses:
example.sql
```
SELECT col_a
FROM test_table
LIMIT 2 * 5 * 10 OFFSET (5 + 10);
SELECT col_a
FROM test_table
LIMIT ALL OFFSET 10 - 5;
```
```
% sqlfluff lint --dialect postgres example.sql
All Finished 📜 🎉!                    
```
- Other.
- Created …
> fixing limit handling for bracketed arithmathic operations

- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/segments/base.py
Following on from #5046 , this consolidates the `.matching_segment()` method into `.deeper_match()`. In doing this, I've made the `name` option on these context managers a required argument and changed up how the `ParseContext` keeps track of location in parse tree. Specifically, we now keep track of a _stack_ of names, rather than just the top name, which would allow a better indication of _where_ we are in the parsing operation - particularly given everything else is very recursive.
It's worth noting that this location is _only_ for logging purposes, and I don't even use that output yet anywhere in this PR. The intent is that it will be more usable for diagnosing inefficient portions of dialects.
This _does_ introduce back a little more overhead into changing context, but I've attempted …
> Better context based tracking

- src/sqlfluff/utils/analysis/select.py
Debugging performance of AL05, I found this optimisation. It cuts the runtime of AL05 on my test file (a big mess query) by 10x!! 🎉 🚀 
In essence we were recursively exploring far too much of the parse tree and then going back to work out which elements to remove at the end of that recursion. The more efficient way to solve that is just to limit recursion in the first place. Double saving of 1) faster tree traversal and 2) not needing to prune them back off again later.
Across a blended project it has the following impacts on time spent:
- AL04 -75%
- AL05 -68%
- AM04 -60%
- RF01 -35%
- ST05 -47%
Especially exciting that these are some of the longest running rules. Overall reduction in linting time of ~30% (with the caveat that results may vary depending on project makeup and the rules …
> Optimisation on select analysis

- src/sqlfluff/core/templaters/base.py
- src/sqlfluff/core/templaters/slicers/tracer.py
Relatively trivial PR to add strict typing to the templating tracer, and some of templating base. Small change, but yielding the work as I'm unlikely to progress more in the next week
No
- Other.
> Add strict typing to the templating tracer

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/fetch_first_row_only.sql
- test/fixtures/dialects/oracle/fetch_first_row_only.yml
Closes #5058 
Add support for fetch first row(s) only, without specifying how many rows.
In this clause oracle fetches only 1 row.
- Other.
> Add support for fetch first row(s) only in Oracle

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/rules/aliasing/AL08.py
- src/sqlfluff/rules/aliasing/__init__.py
- test/fixtures/rules/std_rule_cases/AL08.yml
I've been meaning to add this for ages, strangely never been requested.
This is a new rule to catch duplicate columns. A sibling to https://docs.sqlfluff.com/en/stable/rules.html#rule-aliasing.unique.table
Optional case sensitivity which defaults to case insensitive, also quote stripping included.
> New Rule: AL08 - column aliases must be unique

- .github/workflows/ci-test-dbt.yml
- tox.ini
Tox released a new version, which blocked the way we defined the dbt environments: https://github.com/tox-dev/tox/issues/2858
This reacts to that to unblock CI.
> fix new more restrictive tox

- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/rules/references/RF01.py
- src/sqlfluff/rules/structure/ST05.py
This is a fairly small PR, aimed at improving performance of RF01.
Includes one syntax simplification in RF01 (which is trivial), but more importantly updating the `.recursive_crawl()` method to filter based on the same type sets we now use in rule crawling.
Early testing suggests this more than halves the time spent in RF01 in long queries. Across a blended project the impact is more like 10%. Similar gains on ST05.
> RF01 & recursive_crawl improvements

- requirements_dev.txt
In #4225 we pinned `pydocstyle` to pre `6.2.0` because of https://github.com/PyCQA/pydocstyle/issues/618. Now that's resolved we can allow later versions again.
> Free up pydocstyle again

- src/sqlfluff/rules/ambiguous/AM07.py
This is part of cleaning up the select crawlers.
As part of that I've had a bunch of issues with AM07. The original code was quite convoluted and hard to follow, in particular there was a `list` being passed around and mutated in several methods.
This clears up that rule to make it easier to work with in future. I haven't changed any of the tests and you'll note that this PR only touches one file. Specifically:
- I've removed all mutation within methods. Everything is now handled with return values.
- All returns are now fully typed, and rather than returning a `list` they return just an `int` and `bool`.
- I've removed the need to pass around as many values. In particular we were passing around a `context` and a `crawler` which weren't' necessary.
- There's more logging, and better …
> Refactor AM07

- src/sqlfluff/rules/jinja/JJ01.py
As noted in #5115, `JJ01` is also a fairly slow rule at the moment. On inspection this is because there's a lot of duplication going on as it crawls through the file.
This PR switches from crawling every `raw` segment in the file to only triggering _once_ on the root segment of the file, and then iterating through the templated slices from there. There might be a case in the future for a more generic mechanism, but for now this model is much more efficient.
The only complexity in here is that source fixes _must_ be attached to a `raw` segment rather than a `BaseSegment` (for reasons which I think are fairly sensible), but that means when we identify a source fix in this rule we _then_ try and identify an appropriate "host" segment for it. Feels potentially a little backward, but …
> Optimise crawl behaviour of JJ01

- src/sqlfluff/core/rules/base.py
After some very high level performance investigations into `LT02`, I found that almost 20% of the time was being spent in copying stuff. The use of `deepcopy` was the culprit. Since this original code was written, I think the `BaseSegment.copy()` method has been cleaned up enough that it's safe to use instead.
No additional tests because the code is already well covered.
> Reduce copying in LintFix instantiation

- src/sqlfluff/core/parser/segments/base.py
This fixes an issue which was an oversight from some of the previous `mypy` work. If we try to apply fixes to an unparsable segment, then this fails (because we try to set position). No coverage because it's a very niche area.
> Ensure Unparsable can be given position.

- src/sqlfluff/core/plugin/host.py
- src/sqlfluff/core/timing.py
This resolves the current issues with coverage tests failing intermittently, and with mypy recently complaining about context vars
> Fix coverage & mypy

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/ansi/create_table_column_constraint.yml
- test/fixtures/dialects/ansi/create_view_a.yml
- test/fixtures/dialects/ansi/select_d.yml
- test/fixtures/dialects/athena/select_filter.yml
- test/fixtures/dialects/athena/select_map_function.yml
- test/fixtures/dialects/athena/select_reduce.yml
- test/fixtures/dialects/bigquery/literals_with_data_type_and_quoted.yml
- test/fixtures/dialects/bigquery/select_if.yml
- test/fixtures/dialects/bigquery/select_quoting.yml
- test/fixtures/dialects/mysql/json.yml
- test/fixtures/dialects/mysql/update.yml
- test/fixtures/dialects/postgres/create_view.yml
- test/fixtures/dialects/postgres/null_filters.yml
- test/fixtures/dialects/redshift/super_data_type.yml
- test/fixtures/dialects/snowflake/create_view.yml
- test/fixtures/dialects/sparksql/databricks_dlt_constraint.yml
- test/fixtures/dialects/sparksql/select_from_where_clause.yml
This resolves #5099 .
Treatment of null literals was inconsistent, specifically in `IS`/`IS NOT` expressions where null literals were being parsed as keywords. This resolves that.
> Treatment of null literals. #5099

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/comparison_operators_with_space.sql
- test/fixtures/dialects/oracle/comparison_operators_with_space.yml
Add support for comparison operators with space in Oracle
Closes #5059 
- Other.
> Add support for comparison operators with space in Oracle

- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/dialects/dialect_hive.py
While we can do need an arbitrary `**kwargs` argument to the grammar `.copy()` method, we never validate that for any given grammar, that we only pass appropriate values. This method is only called on import of grammars and so I think some validation is necessary.
In particular, I found an example where in the `hive` dialect we were passing an unused kwarg which was being silently ignored.
This adds an `assert` into the base `.copy()` method, and then fixes the one place where that assert was being violated.
NOTE: Most of the lines of code changed here are actually just `isort` running on the hive dialect. The rest of the changes are pretty minimal.
> Grammar .copy() assert no unexpected kwargs

- test/dialects/unparsable_test.py
This is part of #5124 . Before I start changing the unparsable logic - I thought I should put some tests around the existing logic.
Not loads of tests, but this does give us enough to act as a comparison point. Ideally I'd like it to be a little more specific in future, but at the very least I don't want it to get more generic (i.e. just getting a totally unparsable statement).
> Tests for unparsable sections

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_athena.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_oracle.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_tsql.py
When we introduced deeper support for terminators in the context, it highlighted a few of the older grammars which already had _some_ support for terminators but with a slightly different syntax. This updates `Delimited` to use `terminators` and not `terminator` (note the plural - it's also a list rather than a single grammar). No functionality change for now, this almost entirely just syntax. It does use the parent `terminators` attribute from `AnyOf` in the background though.
The other grammar which needs this treatment is `StartsWith`, but I'll handle that as a separate PR (because it's a more tricky beast).
> `terminator` > `terminators` on Delimited grammar

- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/dialects/dialect_ansi.py
Merging #5152 fixed the bug which left a loophole in #5150. This closes that loophole.
No user facing changes. This is prep for stricter unparsable controls as part of #5124.
> Tighten terminators on `Delimited`

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/alter_table.sql
- test/fixtures/dialects/sparksql/alter_table.yml
fixes #5166 
making PartitionSpecGrammar optional in ALTER TABLE SET LOCATION based on https://spark.apache.org/docs/latest/sql-ref-syntax-ddl-alter-table.html
No
- Other.
> SparkSQL: Support ALTER TABLE SET LOCATION without partition spec

- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_teradata.py
- src/sqlfluff/dialects/dialect_trino.py
- test/core/parser/grammar/grammar_other_test.py
- test/fixtures/dialects/postgres/update_table.yml
The justification for this isn't totally obvious.
- We're extending the use of terminators across dialects.
- Some terminators make sense to require whitespace before them, some don't.
- Currently this is configured on the _grammar_ (i.e. it's applied in the same way for all terminators).
- This doesn't make sense as we have more and more diverse things used as terminators.
- That means that we need a better way of controlling whether whitespace is required. That would either involve _per terminator configuration_ (which adds a lot of overhead), _OR_ we have some way of inferring whether whitespace is required based on the terminator itself.
- This PR implements the latter, inferring that if it's a _keyword_ (i.e. contains only letters), then it likely _does_ require whitespace before it …
> Remove configurable `enforce_whitespace_preceding_terminator`

- src/sqlfluff/core/parser/grammar/sequence.py
Simple code flow refactor of the `match()` method of `Sequence`. All I've done is flipped some `if` statements to deal with the negative cases first and then reduce nesting afterward.
> Flip the if in sequence and un-nest

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_oracle.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
This resolves some currently duplicated code in a few places across the grammars. With this PR, all grammars delegate terminator management to the base grammar. This reduces duplication and redundancy across the grammars.
> Pull terminator setting up into the base grammar

- docs/source/configuration.rst
- docs/source/partials/starter_config.cfg
**Following up on this [Slack thread](https://sqlfluff.slack.com/archives/C01GX4L213J/p1694012643958789), here is a consistency fix for documentation, i.e. keeping boolean values capitalised.**
**None.**
- Other.
> Capitalise boolean values in example configs, for consistency

- src/sqlfluff/core/parser/match_algorithms.py
This ports some optimisations from https://github.com/sqlfluff/sqlfluff/pull/5143 over to the old MatchResult format, because I'd like to build on them for https://github.com/sqlfluff/sqlfluff/pull/5167.
The forward search part of this code is no longer required (since we now have stricter whitespace procedures). The backward search can also be better optimised.
> Simplify Greedy Match

- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/helpers.py
- src/sqlfluff/core/parser/segments/base.py
- test/dialects/unparsable_test.py
This ports some optimisations from #5143 over to the old `MatchResult` format, because I'd like to build on them for #5167.
Same functionality ⚒️ 
Fewer lines of code ✂️ 
Better comments 📜 
Less duplication, less nesting and simpler code flow 😸 
I'm hoping this should be fairly uncontroversial.
> Refactor of Sequence match

- test/conftest.py
- test/generate_parse_fixture_yml.py
Quality of life improvements to the `generate_parse_fixtures.yml` script. Functionality unchanged, but the user feedback is now much better. In particular, it doesn't just stop on the first file. We now get feedback like this (taken from my testing of the new parse modes - which is a good way to show what's failing and what's not):
```
py .\test\generate_parse_fixture_yml.py
Match Pattern Received:
filter=* dialect=all new-only=False
Found 1292 file(s) to generate
'ansi' complete.                All Success ✅
'athena' complete.              All Success ✅
'bigquery' complete.            All Success ✅
'databricks' complete.          All Success ✅
'db2' complete.         All Success ✅
'duckdb' complete.              All Success ✅
'clickhouse' complete.          All Success ✅
'greenplum' …
```
> Upgrades to the parse fixture generation script

- .github/workflows/ci-tests.yml
Coveralls is being buggy again.
This posts the coverage report from out internal coverage report directly onto the PR using a comment. Tested on #5177.
> Output coverage report direct to PR

- .github/workflows/ci-tests.yml
This is a bugfix for #5180. It wasn't updating the comment on coverage fails.
> Update coverage job to run in the right conditions

- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/dialects/dialect_bigquery.py
- test/core/parser/grammar/grammar_anyof_test.py
Another step on #5124 .
Combined with #5186 , this removes the last parts of `parse_grammar` (apart from the `FileSegment` which is the final puzzle piece and will come last). We do this by adding greedy support to `AnyNumberOf` (and therefore to `OneOf` and all the other similar grammars).
Interestingly, most of the effects of this are in the `bigquery` dialect.
> Parse modes for `AnyNumberOf`

- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_athena.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_clickhouse.py
- src/sqlfluff/dialects/dialect_databricks.py
- src/sqlfluff/dialects/dialect_db2.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_hive.py
- src/sqlfluff/dialects/dialect_materialize.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_oracle.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_soql.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sqlite.py
- src/sqlfluff/dialects/dialect_teradata.py
- src/sqlfluff/dialects/dialect_trino.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/conftest.py
- test/core/linter/linter_test.py
- test/core/parser/grammar/grammar_other_test.py
- test/dialects/ansi_test.py
This is another step on #5124.
It only adds a little more functionality (making the `Anything()` grammar terminator aware), but mostly cleans out a bunch of grammars using `parse_grammar` following #5167.
In particular it removes `parse_grammar` from `StatementSegment` (and all the dialect versions of that). That one didn't need any special features to remove now that we're part way through the work.
After this I believe that the only remaining parse grammars are in the bigquery dialect, which will need a little more work.
> Terminators on `Anything()` + Strip _most_ of the other `parse_grammar`

- .github/workflows/ci-pr-comments.yml
- .github/workflows/ci-tests.yml
As discussed by myself and @greg-finley - we think this should fix the issue people see when staging external PRs and the new coverage commenter failing.
Relates to #5188 .
This follows advice from https://securitylab.github.com/research/github-actions-preventing-pwn-requests/
Unfortunately (or perhaps fortunately?), I don't think this will trigger until _after_ the PR is merged. So I think we'll have to test in prod 🤷 . I'll keep an eye on it post merge and we can always revisit if it fails at that point.
> PR Comment action

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
Does what it says on the tin. Hopefully should improve CI runtimes somewhat.
> Cache python dependencies in GHA

- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/parser.py
- src/sqlfluff/core/parser/segments/base.py
Some of our internal consistency checks only work if there's a `parse_grammar`. This obviously presents some issues because these won't _fail_ anymore, but that means they also don't actually work.
This is the first of a few of these changes (all relating to #5124). Starting with an easy one to make sure we haven't dropped anything when we get to the _end_ of the parsing process. This replaces a check that otherwise happened deeper in the parsing process.
> Consistency check in root parse

- src/sqlfluff/core/linter/linted_dir.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/parser/parsers.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/rules/aliasing/AL07.py
- src/sqlfluff/rules/convention/CV04.py
- src/sqlfluff/rules/convention/CV11.py
- src/sqlfluff/rules/structure/ST02.py
- test/core/rules/rules_test.py
- test/dialects/dialects_test.py
- test/utils/reflow/reindent_test.py
This is the third of a few of these changes (all relating to #5124). This updates the parsing checks after fixes to use `.match()` instead of `.parse()`.
Some of our internal consistency checks only work if there's a parse_grammar. This obviously presents some issues because these won't fail anymore, but that means they also don't actually work.
The effect of this PR is that we're much more extensively and effectively testing the impact on fixes to make sure we don't break parsing of the file in question (or at least don't make it worse).
This is going to look like a strange combination of things. Here's why:
1. The core of this PR is the changes to `linter.py` and `segments/base.py`. It takes the `_validate_segment_after_fixes` and uses `.match()` rather than `.parse()`. This is a …
> Validate fix parsing based on match_grammar

- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_postgres_keywords.py
- test/fixtures/dialects/postgres/datatypes.sql
- test/fixtures/dialects/postgres/datatypes.yml
> Add support for bpchar datatype in postgres

- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/segments/base.py
- test/core/parser/segments/segments_base_test.py
- test/fixtures/templater/jinja_l_metas/001.yml
- test/fixtures/templater/jinja_l_metas/009.yml
- test/rules/std_fix_auto_test.py
- test/utils/analysis/test_query.py
Within segments, there is a convention that they do not start or end with whitespace. If that was going to occur, the same whitespace segments should be delegated up to a parent segment such that they aren't at the ends (except for the outer `FileSegment`, or more specifically, any segment which sets `can_start_end_non_code`).
There was a consistency check whenever fixes were applied which made sure that was the case. _However_ it was only applied if there was a `parse_grammar`. This is bad a) because nothing has a parse grammar anymore and b) because it was mostly not applied anyway c) because it _also_ wasn't being applied on new segments.
This PR resolves that by making the test not dependent on `parse_grammar`, and also applying it more liberally. It's not got a lot of computational …
> Revise segment whitespace validation

- src/sqlfluff/core/parser/grammar/base.py
- test/core/parser/conftest.py
- test/core/parser/grammar/grammar_anyof_test.py
- test/core/parser/grammar/grammar_base_test.py
- test/core/parser/grammar/grammar_other_test.py
- test/core/parser/grammar/grammar_ref_test.py
- test/core/parser/grammar/grammar_sequence_test.py
- test/core/parser/helpers_test.py
- test/core/parser/match_algorithms_test.py
- test/core/parser/parse_test.py
- test/core/parser/parser_test.py
- test/core/parser/segments/conftest.py
- test/core/parser/segments/segments_base_test.py
- test/core/parser/segments/segments_common_test.py
- test/core/parser/segments/segments_file_test.py
- test/core/parser/segments/segments_raw_test.py
- test/dialects/conftest.py
This is almost entirely a _find-and-replace_ job (with a couple of other nits).
In particular, lots of tests refer to `seg_list` or `raw_seg_list`, and both are **always tuples**. This renames them so they're not labelled as lists.
Other than that, this fixes some typos, adds a few more test cases to `.simple()`. Hopefully non-controversial, and would otherwise complicate a separate PR.
> Parser test nits

- test/generate_parse_fixture_yml.py
This is a tiny change to the yaml generation script which adds a timer. Useful to assess the impact of improvements to the parsing algorithms.
> Test Script Timing

- src/sqlfluff/dialects/dialect_ansi.py
- test/conftest.py
For reasons lost to the mists of time, the lexers and parsers for brackets have different labels. We also don't _type_ the bracket segments on parsing. This PR resolves that, and is also helpful for the future parsing of brackets.
> Unify lexer names and types for brackets

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_athena.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/sparksql/databricks_operator_colon_sign.yml
- test/generate_parse_fixture_yml.py
This came up while working on the next phase of #5124.
The way that JSON accessing is done in the SparkSQL dialect was very fragile. I've instead copied some of the same methodology from the Snowflake dialect which I think is more robust and ported it across to SparkSQL.
In the process, the `Accessor_Grammar` was (I think) the only grammar with an underscore, so I've also renamed it in all dialects to `AccessorGrammar` in line with the convention.
> Spark Accessor Grammars

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select_replace.sql
- test/fixtures/dialects/snowflake/select_replace.yml
Resolves #5225. 
Previously, `SELECT * REPLACE (...)` resulted in an unparsable error. Also added corresponding test cases.
- Other.
> Resolve #5225: Snowflake unparsable select replace

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_pipe.sql
- test/fixtures/dialects/snowflake/create_pipe.yml
Fix for issue: #5240 
- Even though Snowflake's documentation shows notification integration as a quoted string, Snowflake accepts this value as unquoted. https://docs.snowflake.com/en/sql-reference/sql/create-pipe
- Updating the integration value to be either one of a quoted literal or an object reference segment.
- Adding two tests. Both to test integration being quote vs unquoted, and also to test a slightly more complex pipe statement with the '$' notation.
- Should be no impact anywhere else …
> Allow Snowflake pipe integration to be a quoted or unquoted

- docs/source/configuration.rst
- In the configuration documentation, the [Library Templating](https://docs.sqlfluff.com/en/2.3.2/configuration.html#library-templating) section contains a sample snippet for adding the Airflow filter `ds` with a comment linking to the  `ds_filter` function at `airflow/template.py#L50`.  
- The previous link is outdated as of  https://github.com/apache/airflow/commit/b82ce61285f3f4f0c7eccb2c3effaef53c9fb84e/airflow/templates.py.
**This change updates the sample snippet to correctly link the `ds_filter` function**
-------
None
> - Included test cases to demonstrate any code changes, which may be one or more of the following:
>   - `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`.
>   - `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto …
> minor: update docs with correct link to airflow ds_filter

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_table.sql
- test/fixtures/dialects/snowflake/alter_table.yml
Resolves #5174. Previously, quoted constraint names were unparsable. Also changed primary key and foreign key references to allow for composite keys (i.e. multiple columns). 
Added corresponding tests.
- Other.
> Resolves #5174: Snowflake alter table constraint

- src/sqlfluff/core/parser/segments/base.py
Found this while working on #5230.
The `.apply_fixes()` method was very deeply nested, in a way that made the code hard to follow. This flips some `if` statments so that we can un-nest that code, make it easier to follow and cleaner.
In the process I've also slightly changed the conditions for validating things. The the segment _type_ is the same and we're just editing the content (e.g. capitalisation changes) then we don't do a full re-parse validation (and we trust that the rule is being sensible). For anything else more significant we do still trigger a validation though.
> Unnest fixing and re-address validation triggers

- src/sqlfluff/core/dialects/base.py
- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/grammar/anyof.py
- src/sqlfluff/core/parser/grammar/base.py
- src/sqlfluff/core/parser/grammar/delimited.py
- src/sqlfluff/core/parser/grammar/greedy.py
- src/sqlfluff/core/parser/grammar/sequence.py
- src/sqlfluff/core/parser/match_algorithms.py
- src/sqlfluff/core/parser/matchable.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/types.py
I've wanted to do this for *AAAAAAGES*.
For a long while the dependency path for the common matching interface has been quite complex. We define the interface fairly clearly with `Matchable`, but a similar interface needs to be defined on the _uninstantiated_ `BaseSegment` class.
This led to the slightly strange `MatchableType`, which was `Union[Type[BaseSegment], Matchable]`, but this PR adds `Matchable` to the inherited classes for `SegmentMetaclass`, which means we can get rid of `MatchableType` and use the a _single_ interface definition.
I've also removed `type` as a defined attribute on `Matchable` because it was poorly and inconsistently implemented (grammar classes didn't support it). There were a few places where we were using it, notably in bracket matching and in dialect …
> Revise MatchableType -> Matchable

- src/sqlfluff/core/parser/lexer.py
- src/sqlfluff/core/parser/parsers.py
- src/sqlfluff/core/parser/segments/keyword.py
- src/sqlfluff/core/parser/segments/raw.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/rules/convention/CV02.py
- src/sqlfluff/rules/convention/CV10.py
- src/sqlfluff/rules/convention/CV11.py
- src/sqlfluff/rules/structure/ST02.py
- test/conftest.py
- test/core/parser/parser_test.py
Now that `type` isn't a required attribute of `Matchable` (see #5252), this frees up the ability to adjust the interface on `RawSegment` to be a bit more helpful.
There are two sources of types for a `RawSegment`, those which come from the class (already called `_class_types`), and those linked to the instance ... currently called ... `type` 🤦 . This changes that _singluar_ type argument to a tuple called `instance_types`.
Apart from being more intuitive, it's not obvious _why_ we need to do this change. The reason for that is that it's a dependency of #5230 - especially making sure that the re-parse check can still succeed in that world . (I'm hoping it's also the _last_ required dependency to get that one merged too 🤞 )
> Change RawSegment `type` to `instance_types`

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/interval_operations.sql
- test/fixtures/dialects/oracle/interval_operations.yml
Closes #5259 
Oracle interval syntax is `interval '1' hour`, diffrent than other dialects.
- Other.
> Add support for date operations with intervals in Oracle

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/execute_immediate.sql
- test/fixtures/dialects/snowflake/execute_immediate.yml
Fixes #5216
Parses Snowflake's `EXECUTE IMMEDIATE` statement.
Original SQL snippet:
```sql
EXECUTE IMMEDIATE
$$
BEGIN
CALL META.PROCEDURE_DROP
('FOO','REFERENCE');
END;
$$;
```
now successfully parses to:
```yaml
file:
statement:
execute_immediate_clause:
keyword:    'EXECUTE'
whitespace: ' '
keyword:    'IMMEDIATE'
newline:    '\n'
whitespace: '  '
quoted_literal: "$$\n  BEGIN\n    CALL META.PROCEDURE_DROP\n      ('FOO','REFERENCE');\n  END;\n$$"
statement_terminator: ';'
newline:              '\n'
[META] end_of_file:
```
Followed the examples and added a class `ExecuteImmediateClauseSegment` to parse the statement.
One issue: Snowflake has a variable syntax like `:var` for [binding a variable](https://docs.snowflake.com/en/developer-guide/snowflake-scripting/variables#using-a-variable-in …
> Snowflake: Parse EXECUTE IMMEDIATE clause

- src/sqlfluff/cli/autocomplete.py
I think this is an alternative solution to #5195 (rather than #5197). We've previously tried not to force CLI related libraries on users who don't need them. See #2543.
This ensures older `click` versions don't error with an import error due to the type checking.
Resolves #5195 .
@jdahlbom - could you check whether this also solves the problem you highlighted in your PR?
> Resolve click import options on autocomplete

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/drop_function.sql
- test/fixtures/dialects/postgres/drop_function.yml
> Change drop function to allow DropBehaviourGrammar with space after function name

- src/sqlfluff/core/parser/segments/base.py
Very very small change, but has a sizable performance impact on segment comparisons, which is important for LT02 performance. This *halved* the bottleneck speed of the linting step in my large test file. There is almost certainly more work to be done here, but thought I should get this merged first.
> Performance improvement on segment comparison

- src/sqlfluff/core/rules/base.py
This is pure refactoring, no functionality changes.
This method was a little convoluted. It's the main performance bottleneck for reflow linting, for reasons which I'm only just getting into - but before I do much restructuring I thought I should merge the simplified version.
> Simplify `_process_lint_result`

- src/sqlfluff/rules/layout/LT03.py
- src/sqlfluff/rules/layout/LT04.py
This resolves #5257 . For some reason, these docs didn't get updated when we did the layout rules changes around `2.0.0`.
> Update rule docs with correct config

- src/sqlfluff/core/templaters/jinja.py
- test/cli/commands_test.py
- test/core/templaters/jinja_test.py
This resolves #5276 .
It doesn't raise the original posted issue as a templating error, because it's not a templating error on a file - it's a configuration issue, but this PR wraps it in a better output and makes it clearer what the error was to help users resolve it themselves.
> Better error reporting for invalid macros

- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/utils/reflow/depthmap.py
This is a very small PR, it's a performance improvement for reflow by streamlining the creating of the hash function of segments. Small change - but it's one of the bottlenecks of LT02 so should have a performance uplift.
> Cache the `BaseSegment` hash in reflow

- docs/source/configuration.rst
- src/sqlfluff/rules/jinja/JJ01.py
- test/fixtures/rules/std_rule_cases/JJ01.yml
This resolves #5219 by disabling `JJ01` unless the templater is a subclass of `JinjaTemplater` (which would also include the `dbt` templater too). I've also updated a couple of the relevant docs at the same time.
> Disable JJ01 unless jinja active

- src/sqlfluff/utils/reflow/rebreak.py
- test/fixtures/rules/std_rule_cases/LT05.yml
This *should* resolve #5096.
Ignores any potential rebreak locations inside templated tags so that we don't mistakenly try and break on them. There might be other places we need to do this, but I think this solves the immediate one.
> Don't apply LT05 on templated rebreak locations #5096

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_table.sql
- test/fixtures/dialects/mysql/create_table.yml
> Fix parsing error with table name '_' in MySQL

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/quoted_slash.sql
- test/fixtures/dialects/oracle/quoted_slash.yml
> Fix parsing error when using quoted slash in Oracle

- src/sqlfluff/core/parser/match_algorithms.py
- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/core/parser/segments/raw.py
- src/sqlfluff/utils/reflow/depthmap.py
This was triggered by the overhead of converting a `set` to `frozenset` in `depthmap.py`, but really the `class_types` attribute of a segment should already be a `frozenset`. The reasons we hadn't done that already were that I couldn't work out an elegant way of doing it. This makes the change so that we're always dealing with `frozenset` objects right from the start. This should have a double whammy performance improvement, first on segment creation, and then later on `DepthMap` construction.
> `Set` to `FrozenSet` in segment class_types

- src/sqlfluff/utils/reflow/depthmap.py
Two very small performance improvements in `DepthMap`:
1. Rather than using `min()` and `max()` on the `code_idxs` we can rely on the tuple always being sorted so just taking the first and last values instead.
2. We're calculating the `hash()` of a segment twice in this code - let's just calculate it once and then reuse it.
> Two depth map performance improvements

- src/sqlfluff/rules/layout/LT09.py
- test/fixtures/rules/std_rule_cases/LT09.yml
This resolves #5329 .
As the original issue describes, leading commas were throwing off the behaviour is LT09. I've excluded commas from the logic, and added an appropriate test case. 👍
> Commas fix in LT09

- examples/05_simple_api_config.py
- src/sqlfluff/core/config.py
- test/core/config_test.py
This PR resolves #5207. This mostly uses existing machinery to create nested configs, but exposes it in an easier way and includes an example in the API examples folder. Eventually we might want to deprecate `from_string` and only allow `from_strings`, but that turns this into a more breaking release than it needs to be.
> Add a public API for nesting config strings.

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- test/cli/commands_test.py
There was one of the `echo()` calls in the `stdin` fix codepath which would occasionally log to `stdout` rather than `stderr`. This adds a test case and forces it to always go to `stdout` when fixing directly from the command line.
This resolves #5327 .
> Resolve #5327 (logging to stdout)

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/utils/reflow/config.py
- src/sqlfluff/utils/reflow/reindent.py
- src/sqlfluff/utils/reflow/sequence.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
This resolves #3311 (and oldie).
I've kept the same config variable name as used before and used in the long line rule config, but this time in the `indentation` config. If set, any comment-only lines will be totally ignored from reindentation.
> Allow ignoring of comments from indentation entirely #3311

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/within_group.sql
- test/fixtures/dialects/trino/within_group.yml
adds support for the options to the listagg function.
https://trino.io/docs/current/functions/aggregate.html#array_agg
fixes #5367 
no
- `.sql`/`.yml` parser test cases in 
> add listagg extras support in trino dialect

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/mysql/grant.sql
- test/fixtures/dialects/mysql/grant.yml
Fix #5261 and add support for `*.*` grant statament like this: `GRANT ALL PRIVILEGES ON *.* TO ...`
- Other.
> Fix GRANT ALL PRIVILEGES statement in MySQL

- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_postgres_keywords.py
- test/fixtures/dialects/postgres/create_function.sql
- test/fixtures/dialects/postgres/create_function.yml
Postgres's `create function` grammar doesn't only allow to define functions as a string literal, but also as a plain body of SQL, should the function be `language sql`: https://www.postgresql.org/docs/current/sql-createfunction.html
Limited support for this was introduced in: https://github.com/sqlfluff/sqlfluff/issues/5310
#5310 does have some rather serious issues though:
- Matching a semicolon after `END`  [here](https://github.com/sqlfluff/sqlfluff/pull/5316/files#diff-84df248c7619e658dbf10bea3cad532f9c0d17e06230f791f4cdd419721d2573R1318) means that the lexer doesn't close the function, as it's looking for a semicolon that has already been matched. The generated YAML testcase actually showcases this issue and only accidentally works because the added statement also happens to be the …
> postgres: add support for bodies of "language sql" functions

- pyproject.toml
This is a follow on from #5373. Our mypy config includes exceptions for `pathspec`, `dbt` and `pluggy` because in the past they didn't have type stubs. I believe they now do and so we can remove those exceptions.
> Remove exceptions for typing stubs that now exist.

- .github/workflows/publish-dbt-templater-release-to-pypi.yaml
- .github/workflows/publish-sqlfluff-docker-image-to-dockerhub.yaml
- .github/workflows/publish-sqlfluff-release-to-pypi.yaml
- Dockerfile
- pyproject.toml
On publishing 3.0.0a1, several of the publish actions complained.
Mostly due to old version numbers (which I've updated here), but also because the update to `pyproject.toml` broke the docker image. This fixes that too.
> Update publish actions and Dockerfile.

- .github/workflows/publish-dbt-templater-release-to-pypi.yaml
- .github/workflows/publish-sqlfluff-release-to-pypi.yaml
This is a tiny PR to resolve some deprecation warnings in the publish action. `skip_existing` is deprecated - we should use `skip-existing` instead.
> Update publish github action to use kebab case

- src/sqlfluff/dialects/dialect_sqlite.py
- src/sqlfluff/rules/structure/ST05.py
- test/fixtures/dialects/sqlite/block_comment_end_of_input.sql
- test/fixtures/dialects/sqlite/block_comment_end_of_input.yml
> SQLite: Allow block comments to be terminated by end of input

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/delete_multitable.sql
- test/fixtures/dialects/mysql/delete_multitable.yml
https://dev.mysql.com/doc/refman/8.0/en/delete.html
fixes #5347 
No
- Other.
> Permit .* after each tbl_name in multi-table delete syntax

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_stage.sql
- test/fixtures/dialects/snowflake/create_stage.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5418
The [link](https://docs.aws.amazon.com/AmazonS3/latest/userguide/bucketnamingrules.html) in the comment above the regex says:
```
Note
Before March 1, 2018, buckets created in the US East (N. Virginia) Region could have names that were up to 255 characters long and included uppercase letters and underscores. Beginning March 1, 2018, new buckets in US East (N. Virginia) must conform to the same rules applied in all other Regions.
```
But like, why bother maintaining these regexes? We just need to find that they start with the right thing to know which one it is.
- …
> Simplify Snowflake regexes

- src/sqlfluff/dialects/dialect_sparksql.py
Following sql was causing parse errors:
```
CREATE TABLE alembic_version (
version_num STRING NOT NULL,
CONSTRAINT alembic_version_pkc PRIMARY KEY (version_num)
) USING DELTA;
```
This was fixed by setting sparksql to use the unused createtable implementation. There was a slight error there, that I also fixed. Now it works great.
Another parse error was with an update statement without where clause:
```
UPDATE table1
SET col1= 0
```
This was fixed by making the where clause optional.
Let me know what you think of it.
> adds few fixes for databricks/sparksql

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/databricks_dlt_create_table.sql
- test/fixtures/dialects/sparksql/databricks_dlt_create_table.yml
- test/fixtures/dialects/sparksql/databricks_dlt_create_view.sql
- test/fixtures/dialects/sparksql/databricks_dlt_create_view.yml
[The Delta Live Table in Databricks](https://docs.databricks.com/en/delta-live-tables/sql-ref.html) allows one to add constrains on columns while creating a table or view. This syntax is not supportted by sqlfluff at the moment (yielding parsing errors), even though a `ConstraintStatementSegment` already exists for the sparksql and databricks dialects.
This PR uses the existing `ConstraintStatementSegment` in `CreateViewStatementSegment` and `TableDefinitionSegment` so the syntax is supported.
Examples:
```sql
CREATE OR REFRESH LIVE TABLE taxi_raw(
a STRING COMMENT 'a',
b INT COMMENT 'b',
CONSTRAINT valid_a EXPECT (a IS NOT NULL),  <-- This is supported now by this PR
CONSTRAINT valid_b EXPECT (b > 0)  <-- This is supported now by this PR
)
AS SELECT
a,
b
FROM …
```
> Support parsing CONSTRAINT definitions when creating Delta Live Tables in SparkSQL/Databricks

- test/api/simple_test.py
The modification in simple_test.py involves adding an assert statement in the test `test__api__lint_string_specific_exclude_single`. This change ensures that the test accurately checks the specific set of rule codes, particularly confirming the presence of rule `AM04` and others in the result. This adjustment improves the precision of the test in verifying the functionality of rule exclusions.
- Other. …
> fix assertion in `test__api__lint_string_specific_exclude_single`

- src/sqlfluff/utils/testing/cli.py
- test/cli/commands_test.py
While refining #5364 I found these inconsistencies with the CLI test fixtures. This PR does two things:
1. Does platform normalisation on the `output_contains` argument to `invoke_assert_code` method, renames the argument to `assert_output_contains` and then makes much wider use of this in the test cases (I think it was originally only used once but a lot of tests were just doing in manually).
2. Changes exception handling routines to _always_ raise exceptions (not just when `ret_code` was 0), but only when they're not `SystemExit` exceptions. This is much closer to the intent of how this method should work (and solves some headaches with debugging failing tests here).
> Refine CLI testing fixture

- docs/source/production.rst
This resolves #3857 (or at least documents that we can't properly resolve it and recommends a workaround).
I've also added some slightly better formatting too.
> Add warning about github actions annotations limit

- src/sqlfluff/core/enums.py
To allow a better experience for dark-background users, adding a background of WHITE seems to be a good experience.
Tested on about 10 themes in MacOS' Terminal.app and alacritty for both dark and light backgrounds.
Related to #1170 
Explored replacing the output formatter with `rich`, but that seems like too much work when I think this simple fix will do.
No known side effects
- Other. …
> Change Color.lightgrey to have a white background - dark theme friendly

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/back_quoted_identifier.sql
- test/fixtures/dialects/clickhouse/back_quoted_identifier.yml
Fixes https://github.com/sqlfluff/sqlfluff/issues/5356
Fixes https://github.com/sqlfluff/sqlfluff/issues/4637
Prior to this change, backquoted identifiers failed to parse when using the Clickhouse Dialect. 
Examples as identified in tests. 
This became a bigger issue as of the release of [dbt-clickhouse v1.6.1](https://github.com/ClickHouse/dbt-clickhouse/compare/v1.6.0...v1.6.1#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR3-R7) yesterday (2023/12/4), which expands dbt references with backticks.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto …
> Clickhouse Dialect - Support BackQuoted Identifiers

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/create_table_datetime.yml
- test/fixtures/dialects/mysql/create_table_null_position.sql
- test/fixtures/dialects/mysql/create_table_null_position.yml
Fixes #5443
Prior to this change `null/not null` statements in between `default` and `on update` caused `Found unparsable section` error even though mysql executes such statements without errors.
I hope not
- Other.
> MySql: create table: allow null/not null in any position

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/extract_temporal.sql
- test/fixtures/dialects/duckdb/extract_temporal.yml
- test/fixtures/dialects/duckdb/from_first.sql
- test/fixtures/dialects/duckdb/from_first.yml
- test/fixtures/dialects/duckdb/qualify.sql
- test/fixtures/dialects/duckdb/qualify.yml
makes progress on #5051
Supports the `qualify` statement for DuckDB.
Supports the `from-first` syntax for DuckDB.
The `SelectStatementSegment` now inherits from ansi rather than postgres as the majority of postgres's grammar does not apply to duckdb.
- Other.
> DuckDB: Qualify and From-First

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_database_role.yml
- test/fixtures/dialects/snowflake/grant_revoke.sql
- test/fixtures/dialects/snowflake/grant_revoke.yml
fixes #5489, and related issues with REVOKE and GRANT <permission> TO DATABASE ROLE which weren't discovered at the time I reported the issue. 
Modified existing test fixtures for Snowflake (`grant_revoke.sql`, `grant_revoke.yml` and `create_database_role.yml`).
- Other.
> Snowflake dialect: Add support for DATABASE ROLE in GRANT/REVOKE

- .pre-commit-config.yaml
- pyproject.toml
- requirements_dev.txt
- src/sqlfluff/core/dialects/__init__.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/parser/context.py
- src/sqlfluff/core/parser/segments/raw.py
- src/sqlfluff/core/rules/noqa.py
- src/sqlfluff/core/templaters/jinja.py
- src/sqlfluff/utils/reflow/reindent.py
- test/core/linter/linted_file_test.py
This is my first contribution here. I hope to contribute to adding more features in the future. For now I'm reading the contributing guide and looking at the code structure and the linting/test stages. Which leads to this small MR.  
Antoine
This MR proposes to add theses `mypy` checks:
- [`warn_redundant_casts`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-warn_redundant_casts)
- [`strict_equality`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-strict_equality)
- [`extra_checks`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-strict_concatenate) (previously named `strict_concatenate`)
- [`no_implicit_reexport`](https://mypy.readthedocs.io/en/stable/config_file.html#confval-implicit_reexport)
I chose theses checks by taking the first ones …
> [CI] Add a few more mypy ckecks

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_cluster_by.sql
- test/fixtures/dialects/sparksql/select_cluster_by.yml
- test/fixtures/dialects/sparksql/select_distribute_by.sql
- test/fixtures/dialects/sparksql/select_distribute_by.yml
> SparkSQL: allow distribute/sort/cluster by at end of set operation

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/set.sql
- test/fixtures/dialects/sparksql/set.yml
fixes #5503
This is a simple fix to make SQL statement parsable
```sql
SET spark.sql.cache.serializer=org.apache.spark.sql.execution.columnar.DefaultCachedBatchSerializer;
```
Parsed Tree:
```
[L:  1, P:  1]      |file:
[L:  1, P:  1]      |    statement:
[L:  1, P:  1]      |        set_statement:
[L:  1, P:  1]      |            keyword:                                          'SET'
[L:  1, P:  4]      |            whitespace:                                       ' '
[L:  1, P:  5]      |            property_name_identifier:
[L:  1, P:  5]      |                properties_naked_identifier:                  'spark'
[L:  1, P: 10]      |                dot:                                          '.'
[L:  1, P: 11]      |                properties_naked_identifier: …
```
> SparkSQL: allow value in set_statement to be Java class name

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/exclamation_mark.sql
- test/fixtures/dialects/sparksql/exclamation_mark.yml
> SparkSQL: exclamation mark as logical not

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/databricks_dlt_apply_changes_into.sql
- test/fixtures/dialects/sparksql/databricks_dlt_apply_changes_into.yml
For Spark / Databricks SQL, according to [the offical SQL language reference](https://docs.databricks.com/en/delta-live-tables/sql-ref.html#change-data-capture-with-sql-in-delta-live-tables), the `COLUMNS` clause in a `AAPLY CHANGES INTO` statement is optional. This is not the case in the sqlfluff parser of `sparksql` at the moment. This PR fixes this by marking `COLUMNS` as optional in the parser code.
> ### [Change data capture with SQL in Delta Live Tables ](https://docs.databricks.com/en/delta-live-tables/sql-ref.html#change-data-capture-with-sql-in-delta-live-tables)
>
> Use the APPLY CHANGES INTO statement to use Delta Live Tables CDC functionality, as described in the following:
>
> ```sql
> CREATE OR REFRESH STREAMING TABLE table_name;
> 
> APPLY CHANGES INTO LIVE.table_name
> …
```
> [Spark/Databricks] Fix: make COLUMNS in APPLY CHANGES INTO optional

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/create_table.sql
- test/fixtures/dialects/duckdb/create_table.yml
fixes #5510
- Adds `OR REPLACE` syntax to `CREATE TABLE`
No
- Other.
> DuckDB: Add CREATE OR REPLACE TABLE syntax

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/select_lateral_view.sql
- test/fixtures/dialects/hive/select_lateral_view.yml
fixes #3160 , where UDTF returning multiple column aliases used in SELECT cause is unparsable, even though Hive supports this feature. See https://cwiki.apache.org/confluence/display/hive/languagemanual+udf#LanguageManualUDF-Built-inTable-GeneratingFunctions(UDTF)
No
- Other.
> Hive: allow UDTF to return multiple column aliases in SELECT

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/pivot.sql
- test/fixtures/dialects/duckdb/pivot.yml
- test/fixtures/dialects/duckdb/unpivot.sql
- test/fixtures/dialects/duckdb/unpivot.yml
DuckDB: Adds `PIVOT` and `UNPIVOT` syntax.
fixes #5051
This implements the final missing syntax elements listed.
None.
- Other.
> DuckDB: Added support for `PIVOT` and `UNPIVOT`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/alter_extension.sql
- test/fixtures/dialects/postgres/alter_extension.yml
> Postgres ALTER EXTENSION support: dialect & tests

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/alter_table.sql
- test/fixtures/dialects/mysql/alter_table.yml
Fixed parsing error in ALTER COLUMN ADD/MODIFY when using FIRST keyword.
- Other.
> MySQL: fix FIRST keyword in ALTER ADD/MODIFY

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/anti_semi_join.sql
- test/fixtures/dialects/duckdb/anti_semi_join.yml
- test/fixtures/dialects/duckdb/asof_join.sql
- test/fixtures/dialects/duckdb/asof_join.yml
- test/fixtures/dialects/duckdb/positional_join.sql
- test/fixtures/dialects/duckdb/positional_join.yml
fixes #5536 
- Add the conditional joins `ANTI`, `SEMI`, and `ASOF`
- Add the unconditional join `POSITIONAL`
None
- Other.
> DuckDB: Add ANTI, SEMI, ASOF, and POSITIONAL joins

- docs/source/partials/starter_config.cfg
Update docs starter config to use `extended_capitalisation_policy` for `capitalisation.identifiers`, since `capitalisation_policy` seems to not work there.
https://docs.sqlfluff.com/en/stable/rules.html#rule-capitalisation.identifiers
> [Docs] Use extended policy for identifier capitalisation in starter config

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/rules/convention/CV01.py
- test/fixtures/rules/std_rule_cases/CV01.yml
fixes #5529 
This adds an ANSI (`<>`) style and consistent configuration option to CV01.
This changes the default setting from the C (`!=`) style to consistent.
- Other.
> CV01: Add options for ANSI and consistent style.

- docs/source/partials/starter_config.cfg
Following on from #5539 (which relaxes the default configuration), this updates the _recommended_ starter config to reflect the previous default behaviour.
> Stricter recommended config for not_equals convention

- src/sqlfluff/core/templaters/jinja.py
- test/core/templaters/jinja_test.py
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_cross_ref.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_cross_ref.yml
Dbt introduced the possibilty to reference models from other projects, by using two arguments in the ref() function: https://docs.getdbt.com/docs/collaborate/govern/project-dependencies 
This breaks the current jinja templater as it expects exactly one argument.
This change works also for cross project refs by extracting the model_ref as the last argument in the ref() function.
Fixes #5472
No side effects were observed. The project reference, which is the additional argument in the cross project ref case is not used. …
> Allows using dbt cross project ref in jinja templater

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
- .github/workflows/create-release-pull-request.yaml
- .github/workflows/publish-dbt-templater-release-to-pypi.yaml
- .github/workflows/publish-sqlfluff-release-to-pypi.yaml
We're getting deprecation warnings for a bunch of github actions. This updates most of them to latest versions. Also pins the coveralls one to an actual release rather than just `@master`.
> Update github actions to latest versions

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/alter_policy.sql
- test/fixtures/dialects/postgres/alter_policy.yml
Fixes #5576
Allows postgres `alter policy` statements with multiple clauses, as described in the postgres docs.
- Other.
> Add support & test for postgres alter policy with multiple clauses

- pyproject.toml
- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/linter/linted_dir.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/linter/linting_result.py
- test/cli/commands_test.py
- test/fixtures/cli/passing_timing.sql
Resolves #5566 .
It adds a setting which doesn't keep the full parsed and linted file during linting operations. Only the metadata would then be kept - in theory lowering the memory overhead during long linting operations.
@noel - this is the feature I was talking about. UPDATE: Tested by noel on their big project and seems to reduce OOM killing events.
> Memory overhead optimisations during linting

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/select_cluster_by.sql
- test/fixtures/dialects/sparksql/select_cluster_by.yml
- test/fixtures/dialects/sparksql/select_distribute_by.sql
- test/fixtures/dialects/sparksql/select_distribute_by.yml
- test/fixtures/dialects/sparksql/select_from_lateral_view.sql
- test/fixtures/dialects/sparksql/select_from_lateral_view.yml
- test/fixtures/dialects/sparksql/select_lateral_view_supported_tvf.yml
- test/fixtures/dialects/sparksql/select_qualify.sql
- test/fixtures/dialects/sparksql/select_qualify.yml
- test/fixtures/dialects/sparksql/select_sort_by.sql
- test/fixtures/dialects/sparksql/select_sort_by.yml
- test/fixtures/dialects/sparksql/window_functions.yml
fixes #5439 
- `LATERAL VIEW` handled as a JOIN-like clause
- Fix `SELECT ... CLUSTER BY` without `FROM`
- Fix `SELECT ... DISTRIBUTE BY` without `FROM`
- Fix `SELECT ... SORT BY` without `FROM`
- Fix `SELECT ... QUALIFY` without `FROM`
None
- Other.
> Sparksql: Fix `LATERAL VIEW` following `JOIN`; `CLUSTER|SORT|DISTRIBUTE BY` or `QUALIFY` without `FROM`

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_db2.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/db2/select_ordered_nested_sets.sql
- test/fixtures/dialects/db2/select_ordered_nested_sets.yml
- test/fixtures/dialects/postgres/select_ordered_nested_sets.sql
- test/fixtures/dialects/postgres/select_ordered_nested_sets.yml
fixes #5605 
- Fixed nested set expressions
- Generalized allowing nested set expressions to contain grammar such as `ORDER BY`
- Removed BigQuery's nested set implementation for ANSI's
None
- Other.
> Multiple Dialects: Fix handling of nested sets expressions

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/temporary_table.sql
- test/fixtures/dialects/oracle/temporary_table.yml
Oracle allows length specifiers for types `CHAR` and `VARCHAR2`
- https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/Data-Types.html
Allow parsing of `VARCHAR2(100 BYTE)`, `VARCHAR2(100 CHAR)`, etc.
Fix Oracle dialect to support parsing this, e.g. in create table statement.
- Other.
> Oracle: parse length qualifier in types

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_exasol.py
- src/sqlfluff/dialects/dialect_sqlite.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/exasol/create_function_statement.yml
- test/fixtures/dialects/sqlite/create_index.yml
- test/fixtures/dialects/sqlite/is_clause.sql
- test/fixtures/dialects/sqlite/is_clause.yml
- test/fixtures/dialects/tsql/add_index.yml
- test/fixtures/dialects/tsql/create_procedure.yml
- test/fixtures/dialects/tsql/create_view_with_cte.yml
- test/fixtures/dialects/tsql/create_view_with_set_statements.yml
- test/fixtures/dialects/tsql/cte_s.yml
- test/fixtures/dialects/tsql/cursor.yml
- test/fixtures/dialects/tsql/declare_with_following_statements.yml
- test/fixtures/dialects/tsql/delete.yml
- test/fixtures/dialects/tsql/function_no_return.yml
- test/fixtures/dialects/tsql/functions_a.yml
- test/fixtures/dialects/tsql/hints.yml
- test/fixtures/dialects/tsql/merge.yml
fixes #5619 
- Makes the `DISTINCT FROM` optional in SQLite
- Defaulted `IsClauseGrammar` in all dialects and set `NanLiteralSegment` to `Nothing` for current dialects removing it
This could impact SQLite, TSQL, or Exasol rules where CP01 and CP04 are set different for `IS [NOT] NULL`. This is the default behavior for all other dialects as noted in #5099.
Input:
```sql
SELECT true from tab where col is not null;
```
Fixed:
```sql
SELECT true FROM tab WHERE col IS NOT null; 
```
- Full autofix …
> SQLite: Make `DISTINCT FROM` optional; SQLite/TSQL/Exasol: Nothing'd `NanLiteralSegment`

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_table_column.sql
- test/fixtures/dialects/snowflake/alter_table_column.yml
Previously this resulted in an unparseable section.
snowflake documentation that shows this is valid: https://docs.snowflake.com/en/sql-reference/sql/alter-table#table-column-actions-tablecolumnaction
Added a TODO, technically using IF NOT EXISTS with DEFAULT, AUTOINCREMENT, IDENTITY, UNIQUE, PRIMARY KEY, FOREIGN KEY is not valid. However this still closes the gap with what is parseable by the dialect.
- Other. …
> [snowflake dialect] support ALTER TABLE ... ADD COLUMN IF NOT EXISTS

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/mysql/create_role.sql
- test/fixtures/dialects/mysql/create_role.yml
Makes progress on #5388
The feature was requested for MySQL, so the test has been added there. But I see no harm in adding this to ANSI.
Added to ANSI, though it can't be a destructive change
- Other.
> ANSI/MYSQL: Support Create Role If Not Exists

- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_teradata.py
Replace the Sequence version of IfExists, IfNotExists, and OrReplace, with their simpler Refs
Fixes #5476 
No
- Other.
> Tech Debt: Replace some sequences with their Ref equivalents

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/select.sql
- test/fixtures/dialects/tsql/select.yml
This adds a word terminator to unquoted_relative_sql_file_path, allowing `sql` to be the start of a longer string.
Fixes #5481 
No
- Other.
> T-SQL Fix relative sql filepath lexer

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_table.sql
- test/fixtures/dialects/postgres/create_table.yml
Fixes #5622 
Also. deletes the redundant and unused ReferentialActionSegment
No
- Other.
> Postgres: Update ReferentialActionGrammar to support sets of columns

- test/cli/commands_test.py
- test/core/rules/rules_test.py
I think I found an issue.
We have a test case `test__cli__fix_loop_limit_behavior` which designed to check error behaviour around the loop limit on fixes. We have one test case designed to see what happens when the limit is reached - and look for an exit code of 1 if it does.
What is _actually_ happening here however is that we're getting an exception because `BaseRule._eval()` raises a `NotImplementedError` when run rather than actually because we're hitting the loop limit. That means this test case is misleading.
If I resolve that first issue - the test case then doesn't work anymore because the error code is different. @barrywhart - you're the last person in that chunk of code, what's your view on what we do here?
> Resolve broken loop limit test

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/cast_datatype_accessor.sql
- test/fixtures/dialects/snowflake/cast_datatype_accessor.yml
Fixes https://github.com/sqlfluff/sqlfluff/issues/5647. Previously, traversing semi-structured data after casting to `variant` was unparsable.
Added corresponding tests.
- Other.
> Resolve #5647: Snowflake unparsable variant access after cast

- pyproject.toml
As brought up on slack, it appears these ruff config changes are causing issues with the pre-commit hook.
> Revert Ruff Changes

- .pre-commit-config.yaml
- pyproject.toml
This brings the pre-commit hooks versions up to date to align with the versions used by GitHub Actions linting steps.
There should be no side effects with this change however I'll note the following:
This removes the eventually-to-be-deprecated `flake8-docstrings` (with `pydocstyle` being deprecated and `ruff` being the replacement) from the pre-commit. The updated version of `ruff` now correctly catches the docstrings style with the current configuration. `flake8-docstrings` and `pydocstyle` should probably eventually be removed from the `requirements_dev.txt`
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note …
> [CI]: Update pre-commit hook versions

- src/sqlfluff/rules/aliasing/AL05.py
- test/fixtures/rules/std_rule_cases/AL05.yml
Prevent removing aliases in postgres values clause as they are required.
fixes #5600
None
- Other.
> Postgres: AL05, ignore aliases in values clause

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/regexp_replace_with_lambda.sql
- test/fixtures/dialects/trino/regexp_replace_with_lambda.yml
This PR aims to address a particular syntax that invloves a lambda expression
inside of the REGEXP_REPLACE function.
```sql
SELECT REGEXP_REPLACE('new york', '(\w)(\w*)', x -> UPPER(x[1]) || LOWER(x[2]))
```
Fixes #5582
I found the changes required for this from the Athena dialect implementation. Athena
and Trino share some code history, and both make use of lambda expressions for array
functions (which is not the target of this PR). I don't believe I've done enough work on
this to enable all the Trino array functions to be parseable in the Trino dialect though. 
Hopefully this is a step towards that support in the future _and_ it parses the
`REGEXP_REPLACE` with lambda parameter syntax as-is.
- Included test cases to demonstrate any code changes, which may be one or more of the …
> Trino: Parse regexp_replace with lambda func

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/changes_clause.sql
- test/fixtures/dialects/snowflake/changes_clause.yml
Does what it says on the tin. Looks like we missed one keyword during the initial implementation https://github.com/sqlfluff/sqlfluff/pull/2764.
This resolves an issue raised on slack.
> Allow use of STREAM in snowflake CHANGES clause

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/select_distinct_on.sql
- test/fixtures/dialects/clickhouse/select_distinct_on.yml
Adds parsing for the "distinct on" syntax [available in Clickhouse](https://clickhouse.com/docs/en/sql-reference/statements/select/distinct). This is similar to Postgres.
No
- Other.
> Clickhouse: add parsing for "distinct on" syntax

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/array.sql
- test/fixtures/dialects/trino/array.yml
Adds an `ArrayTypeSegment` to match on `ARRAY` so array tokens are parsed as a `typed_array_literal` instead of being naked.
Before this, `ARRAY` was not getting parsed as an `array_type` causing an 'array' of issues with linting and parsing. Most notably:
```sql
SELECT ARRAY[ARRAY[1,2], ARRAY[3,4]];
```
would return unparsable errors when this in fact valid sql for trino.
Fixes #5721
Makes progress on #5705
Fixes #5617
Not that I'm aware of. …
> Add array type support to Trino dialect

- src/sqlfluff/dialects/dialect_clickhouse.py
- src/sqlfluff/dialects/dialect_clickhouse_keywords.py
- test/fixtures/dialects/clickhouse/select_except.sql
- test/fixtures/dialects/clickhouse/select_except.yml
Adds support for `SELECT * EXCEPT (column_1, column_2)` syntax in Clickhouse. [Reference here](https://clickhouse.com/docs/en/sql-reference/statements/select#except). Similar syntax and segments exist for BigQuery and Snowflake. 
No
- Other.
> Clickhouse: add parsing for select except clause

- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
This suppresses the traceback output from user errors being printed as output from the CLI.
This fixes the issue in sqlfluff/vscode-sqlfluff#122 where the useful error message is hidden.
None
- Other.
> CLI: Suppress tracebacks on render/fix/format

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_view_options_as.sql
- test/fixtures/dialects/bigquery/create_view_options_as.yml
fixes: https://github.com/sqlfluff/sqlfluff/issues/5737
The current BigQuery dialect does not correctly consider CREATE VIEW statements containing `view_column_name_list` so we will attempt to fix this.
As far as I know, there should be no impact beyond being able to parse SQL that cannot currently be parsed.
- Other. …
> Fix implementation for view_column_name_list in BigQuery's CREATE VIEW

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/line_comment.sql
- test/fixtures/dialects/mysql/line_comment.yml
Fix #5724 mysql: Allow Line comments without space after --
> Fix #5724 mysql: Allow Line comments without space after --

- src/sqlfluff/core/rules/config_info.py
- src/sqlfluff/rules/capitalisation/CP01.py
- test/fixtures/rules/std_rule_cases/CP02.yml
- test/fixtures/rules/std_rule_cases/CP03.yml
fixes #5470
Hi sqlfluff! in this pr, I'm adding desired capitalisation policy of `snake` for snake_case enforcement and correction
None indicated by running tests.
Tested regex on multiple test cases, but would love a second opinion on it (the lookbehinds cause worry, but should be structured to only look 1 character behind)
Note: tests for this change have been added in `CP02.yml` and `CP03.yml` to follow the current pattern of testing `pascal` capitalisation policy
- Full autofix test cases …
> adding snake_case to CP01 extended_capitalisation_policy

- .pre-commit-hooks.yaml
In v3, SQLFluff does not require the `--force` flag for `sqlfluff fix` anymore and emits a warning.
n/a
- Other.
> Remove `--force` flag from pre-commit hook definition

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/pattern_matching.sql
- test/fixtures/dialects/sqlite/pattern_matching.yml
This adds `GLOB`, `MATCH`, and improves `REGEXP` in SQLite.
- Fixed handling of `NOT REGEXP`
- Added `PatternMatchingGrammar` in ANSI for future support in other dialects such as DuckDB.
fixes #5717 
None
- Other.
> SQLite: Add `GLOB`, `MATCH`. Improved `REGEXP`

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/databricks/select_from_lateral_view.sql
- test/fixtures/dialects/databricks/select_from_lateral_view.yml
Fixes alias exclusions that may follow a join-like object in Databricks.
fixes #5746 
None
- Other.
> Databricks: Fix Aliases for Join-like objects

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/templater_test.py
Fixed raising an error when using the dbt templater with stdin.
- A SQLFluffUserError is used to pretty print the error
fixes #5750 
None
- Other.
> dbt templater: Raise UserError when using stdin

- src/sqlfluff/rules/structure/ST04.py
- test/fixtures/rules/std_rule_cases/ST04.yml
Fix to retain comments when flattening nested case statements.
- fixes #4848 
- fixes #4966 
None
- Other.
> ST04: Retain comments when flattening `CASE`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_function.sql
- test/fixtures/dialects/postgres/create_function.yml
> Postgres: Allow return control structures in atomic functions

- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_postgres_keywords.py
- test/fixtures/dialects/postgres/pgvector.sql
- test/fixtures/dialects/postgres/pgvector.yml
> Postgres: Support pgvector vector type

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_table_constraints.sql
- test/fixtures/dialects/tsql/create_table_constraints.yml
Adds support for bare functions in column default constraints for TSQL.
Fixes #4631 
> TSQL: Fix bare functions in default constraints

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/triggers.sql
- test/fixtures/dialects/tsql/triggers.yml
Allow the optional `OR ALTER` on `CREATE TRIGGER` statements in T-SQL dialect.  This is already possible on `VIEW`, `FUNCTION` and `PROCEDURE`.
Not as far as I know.
> TSQL: allow 'OR ALTER' on 'CREATE TRIGGER'

- .github/workflows/add-to-release-notes.yml
- .github/workflows/create-release-pull-request.yaml
This is a pretty small PR, with some incremental changes to the release PR action. It should now _tag_ the GitHub release on creating the release PR, add a placeholder title and leaves a note for when the title should get updated.
I'll come back and add more stuff later, but wanted to get this bit merged and tested before _creating_ the next release PR so I can test the update stuff later.
> Upgrades to release actions.

- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/enums.py
Ok, so this might be a little controversial.
I understand why #5458 was merged - the previous situation didn't work well with dark mode terminals (see #1659 and #1170). _However_ I'm finding that the solution of changing the background is _also_ quite hard to read on some other themes (in particular on powershell), so I've played with a few options, and I think this might be an improvement on both.
This changes the `lightgrey` colour to just `light` and maps it to the ANSI _yellow_ code. It does change the overall feel quite a bit, but I think it's a good compromise. Here's some shots of what it looks like on a few different colour schemes:
Ubuntu
Monokai
Solarized
Unfortunately I don't have a mac and so can't confirm exactly what it looks like on MacOS dark solarized as per the original …
> Improve light colour highlight

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table.sql
- test/fixtures/dialects/tsql/alter_table.yml
- test/fixtures/dialects/tsql/create_table.sql
- test/fixtures/dialects/tsql/create_table.yml
fixes #4971 
Proper support for [TSQL computed columns:](https://learn.microsoft.com/en-us/sql/relational-databases/tables/specify-computed-columns-in-a-table?view=sql-server-ver16)
- `CREATE TABLE`
- `ALTER TABLE`
no
- Other.
> TSQL: support computed columns

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_schema.sql
- test/fixtures/dialects/bigquery/create_schema.yml
- test/fixtures/dialects/bigquery/create_table_default_collate.sql
- test/fixtures/dialects/bigquery/create_table_default_collate.yml
related: #5789
The current BigQuery dialect does not correctly parse CREATE SCHEMA / CREATE TABLE statements containing `DEFAULT COLLATE` so we will attempt to fix this.
As far as I know, nothing.
- Other.
> BigQuery: Support DEFAULT COLLATE segment

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_table_like_copy_clone.sql
- test/fixtures/dialects/bigquery/create_table_like_copy_clone.yml
related: #5789
The current BigQuery dialect does not correctly parse CREATE TABLE CLONE statements containing `FOR SYSTEM_TIME AS OF` so we will attempt to fix this.
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_table_clone_statement
As far as I know, nothing.
- Other.
- Created GitHub issues for any relevant followup/future enhancements …
> BigQuery: Support FOR SYSTEM_TIME AS OF in CREATE TABLE CLONE statement

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/create_master_key.sql
- test/fixtures/dialects/tsql/create_master_key.yml
fixes #5795
- https://learn.microsoft.com/en-us/sql/t-sql/statements/create-master-key-transact-sql
- https://learn.microsoft.com/en-us/sql/t-sql/statements/alter-master-key-transact-sql
- https://learn.microsoft.com/en-us/sql/t-sql/statements/drop-master-key-transact-sql
no
- Other.
> TSQL: parse `CREATE/ALTER/DROP MASTER KEY`

- src/sqlfluff/cli/commands.py
- test/cli/commands_test.py
- test/fixtures/cli/stdin_filename/.sqlfluff
This introduces the `--stdin-filename` option to the cli. This allows for "dirty" content of a file from an editor such as vscode to be read in from stdin and apply the same configuration as the base file.
- fixes #5800 
None.
- Other.
> CLI: Add `--stdin-filename` option

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_function_no_args.sql
- test/fixtures/dialects/bigquery/create_function_with_args.sql
- test/fixtures/dialects/bigquery/create_function_with_args.yml
- test/fixtures/dialects/bigquery/drop_function.sql
- test/fixtures/dialects/bigquery/drop_function.yml
related: https://github.com/sqlfluff/sqlfluff/issues/5789
The current BigQuery dialect does not correctly parse `CREATE FUNCTION` statements with `OPTIONS` segment, so we try to fix this.
And refactor and add some test cases.
None
- Other.
> BigQuery: Support OPTIONS in CREATE FUNCTION statement

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/templater_test.py
- src/sqlfluff/core/linter/linter.py
- src/sqlfluff/core/templaters/base.py
- src/sqlfluff/core/templaters/jinja.py
- src/sqlfluff/core/templaters/placeholder.py
- src/sqlfluff/core/templaters/python.py
- test/core/templaters/jinja_test.py
Related to #5794. We've been fairly inconsistent in whether we raise issues or return `None` from the templater `.process()` methods. This PR tightens that up a bit.
Previously the methods could optionally return `None`, this PR prevents that - and instead for fatal templating errors requires the process method to explicitly raise a `SQLTemplaterError` which is then caught in the linter.
While it's not a massive change - it does modify the interface for the templater slightly. The upside of all of this is that it reduces the number of different scenarios that we need to handle outside the templater so simplify processing.
> Tighten up the return from .process()

- src/sqlfluff/core/parser/lexer.py
- test/fixtures/templater/jinja_l_metas/003.yml
This fixes half of #5803, but not all of it (and it only addresses the easy bit 🤷).
Good opportunity to simplify the code a little too at the same time.
> Fix placeholder labelling

- test/core/linter/linter_test.py
This is based on #5794 and #5810, and fleshes out what should happen in some of the failure cases.
This is entirely just additional coverage and clarity on exactly what should happen in each case. No logic changes.
> Test cases for linter fails.

- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_bigquery_keywords.py
- test/fixtures/dialects/bigquery/create_row_access_policy.sql
- test/fixtures/dialects/bigquery/create_row_access_policy.yml
related: #5789
The current BigQuery dialect does not correctly parse `CREATE ROW ACCESS POLICY` statements, so we will attempt to fix this.
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#create_row_access_policy_statement
None
- Other.
> BigQuery: Support CREATE ROW ACCESS POLICY statement

- src/sqlfluff/utils/reflow/respace.py
- test/fixtures/rules/std_rule_cases/LT01-alignment.yml
Extension of #5823. Fixes #5672 .
This allows to format
```sql
create table tab1 (
a    varchar(25)  not null,
b int not null unique references tab2(b),
c varchar(5) not null primary key references tab2(c)
)
```
as
```sql
create table tab1 (
a varchar(25) not null,
b int         not null unique      references tab2 (b),
c varchar(5)  not null primary key references tab2 (c)
)
```
rather than
```sql
create table tab1 (
a varchar(25) not null,
b int         not null unique references tab2 (b),
c varchar(5)  not null primary key references tab2 (c)
)
```
which creates some more clarity.
n/a …
> Allow to align all siblings when respacing

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/postgres_postgis_operators.sql
- test/fixtures/dialects/postgres/postgres_postgis_operators.yml
Fixes #4260
Only by adding regex lexer for postgis operators as suggested in the discussions in the initial PR: https://github.com/sqlfluff/sqlfluff/pull/4824
- Other.
> Postgres: Add Support for PostGIS operators

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/execute_immediate.sql
- test/fixtures/dialects/snowflake/execute_immediate.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/5694
Snowflake technically treats `EXECUTE IMMEDIATE` and `EXECUTE IMMEDIATE FROM` as two commands, but I think they are close enough to parse together. If you want, I could separate them into two on our end though.
- Other.
> Snowflake execute immediate from

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/prewhere.sql
- test/fixtures/dialects/clickhouse/prewhere.yml
In Clickhouse, there is such a thing as PREWHERE when requesting SELECT. This PR adds PREWHERE support
https://clickhouse.com/docs/en/sql-reference/statements/select/prewhere
No
- Other.
> Clichouse prewhere

- src/sqlfluff/rules/structure/ST02.py
- test/fixtures/rules/std_rule_cases/ST02.yml
Fixes #5844 
The comparison was previously ignoring array accessors, and just comparing the column reference
No
- Other.
> Bugfix: ST02 - Compare entire condition expression

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/create_temporary_table.sql
- test/fixtures/dialects/clickhouse/create_temporary_table.yml
I have made changes to the Clickhouse dialect. The changes are related to the creation of a Temporary TABLE, they have become more rigid, and also added the ability to AS SELECT for a TEMPORARY TABLE
No
- [ x] Please confirm you have completed any of the necessary steps below.
- Other.
> [fix_clickhouse] Temporary Table Create AS SELECT

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/export_statement.sql
- test/fixtures/dialects/bigquery/export_statement.yml
- test/fixtures/dialects/bigquery/handle_exception.yml
fixes #5409
The parsing logic for `EXPORT DATA` was implemented, but lacked consideration of some option items and the case where an expression was specified for the value, so we try to fix it.
https://cloud.google.com/bigquery/docs/reference/standard-sql/other-statements#export_data_statement
None
- Other. …
> BigQuery: Fix EXPORT DATA statement

- pyproject.toml
- src/sqlfluff/core/linter/linted_dir.py
- src/sqlfluff/core/linter/linting_result.py
- src/sqlfluff/utils/functional/segments.py
`Literal`, `SupportsIndex` and `TypedDict` were added in `typing` in Python 3.8.
> Remove typing_extensions requirement

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/select_operators.sql
- test/fixtures/dialects/mysql/select_operators.yml
fixes #5868
The above problem was caused by the lack of implementation of MySQL-specific BinaryOperator, which is not defined in ANSI.
According to the documentation, `DIV` and `MOD` were needed, so I try to add them.
https://dev.mysql.com/doc/refman/8.0/ja/arithmetic-functions.html
None
- Other.
> MySQL: Support DIV and MOD operators

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/alter_table_add_key.sql
- test/fixtures/dialects/bigquery/alter_table_add_key.yml
makes progress on #5789
The current BigQuery dialect does not correctly parse `ALTER TABLE ADD KEY` statements, so we try to fix them.
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_add_foreign_key_statement
https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_add_primary_key_statement
None
- Other.
- Added appropriate documentation for …
> BigQuery: Support ALTER TABLE ADD KEY statements

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/alter_table_drop_constraint.sql
- test/fixtures/dialects/bigquery/alter_table_drop_constraint.yml
- test/fixtures/dialects/bigquery/alter_table_drop_key.sql
- test/fixtures/dialects/bigquery/alter_table_drop_key.yml
- test/fixtures/dialects/bigquery/alter_table_set_default_collate.sql
- test/fixtures/dialects/bigquery/alter_table_set_default_collate.yml
- test/fixtures/dialects/bigquery/alter_view_alter_column.sql
- test/fixtures/dialects/bigquery/alter_view_alter_column.yml
makes progress on #5789
The current BigQuery dialect does not correctly parse some `ALTER TABLE` and `ALTER VIEW` statements, so we try to fix them.
- ALTER TABLE DROP CONSTRAINT statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_constraint_statement
- ALTER TABLE DROP PRIMARY KEY statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_drop_primary_key_statement
- ALTER TABLE SET DEFAULT COLLATE statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_table_collate_statement
- ALTER COLUMN SET OPTIONS statement with ALTER VIEW
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#alter_colu …
> BigQuery: Support unimplemented alter table and view statements

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_trigger.yml
- test/fixtures/dialects/sqlite/create_view.sql
- test/fixtures/dialects/sqlite/create_view.yml
- test/fixtures/dialects/sqlite/update.sql
- test/fixtures/dialects/sqlite/update.yml
* Support SQLite specific create view (https://www.sqlite.org/lang_createview.html)
* Add OR clause to UPDATE as per https://www.sqlite.org/lang_update.html
* Support column-name-list in update https://www.sqlite.org/lang_update.html
- Other.
> SQLite: Specialize create view with support for temporary views.

- docs/source/configuration.rst
- test/fixtures/templater/jinja_q_multiple_path_macros/even_more_macros/subdir/subdir_foo.sql
- test/fixtures/templater/jinja_q_multiple_path_macros/jinja.sql
- test/fixtures/templater/jinja_q_multiple_path_macros/jinja.yml
The documentation erroneously states that SQLFluff will not look in subfolders when loading macros using the load_macros_from_path config. This is not actually the case: the JinjaTemplater._extract_macros_from_path function will recursively search subdirectories, and load those macros into the Jinja global namespace as well:
https://github.com/sqlfluff/sqlfluff/blob/06b22f56a89043683915886a63d19aa34a4f63ec/src/sqlfluff/core/templaters/jinja.py#L169-L177
This commit does the following:
1.  Amends one of the existing test cases to demonstrate that macros can be loaded from subdirectories.  No obvious existing test case seemed to meaningfully cover this scenario.
2.  Updates the documentation to state that subdirectories will be searched as well.
There is no actual change in behavior of the …
> Clarify docs around subdir handling when loading macros

- docs/source/configuration.rst
- src/sqlfluff/core/config.py
- src/sqlfluff/core/templaters/jinja.py
- test/core/templaters/jinja_test.py
- test/fixtures/templater/jinja_t_loader_search_path/.sqlfluff
- test/fixtures/templater/jinja_t_loader_search_path/jinja.sql
- test/fixtures/templater/jinja_t_loader_search_path/jinja.yml
- test/fixtures/templater/jinja_t_loader_search_path/macro_load/macro_load.sql
- test/fixtures/templater/jinja_t_loader_search_path/macro_load/subdir/macro_load_subdir.sql
- test/fixtures/templater/jinja_t_loader_search_path/search_a/search_a.sql
- test/fixtures/templater/jinja_t_loader_search_path/search_a/subdir/search_a_subdir.sql
- test/fixtures/templater/jinja_t_loader_search_path/search_b/search_b.sql
Currently, in order to include a folder in the Jinja loader search path, one must specify it using the load_macros_from_path setting.  However, this setting carries a side effect, which may be unwanted in some scenarios: it will also load every single file in that directory (which is slow), and loads those macros into the global namespace (which may not be an accurate representation of the end-user application behavior). There is currently no option to avoid this additional behavior.
This commit adds a new loader_search_path setting, which is a simple way of specifying the Jinja loader's search path.  The behavior of the existing load_macros_from_path setting remains unchanged.  If both options are set, all directories are merged and included in the Jinja loader search path.
Further …
> Add loader_search_path setting to Jinja templater

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/create_function.yml
- test/fixtures/dialects/tsql/select_assign_parameter.sql
- test/fixtures/dialects/tsql/select_assign_parameter.yml
Fixes #5678 
`AltAliasExpressionSegment` can be matched by `ParameterNameSegment` (i.e. a SELECT projection that looks like `@myparam = mycolumn`). Test AT09 tries to obtain `alias_identifier` from this segment, but it only looks for `naked_identifier` or `quoted_identifier` types and `ParameterNameSegment` is of type `parameter`. There are no matches and the resulting `alias_identifier` is `None` and fails the the assertion.
Statement was wrongly classified and linted as an alias; this change fixes that without any other side effect. All tests pass.
- `.yml` rule test cases in `test/fixtures/rules/std_rule_cases`. **N/A**
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note …
> T-SQL: Parameter assignment in SELECT vs alias

- src/sqlfluff/dialects/dialect_exasol.py
- test/fixtures/dialects/exasol/select_statement.sql
- test/fixtures/dialects/exasol/select_statement.yml
Add support for REGEXP_LIKE 
https://docs.exasol.com/db/latest/sql_references/predicates/not_regexp_like.htm
- Other.
> Exasol: add REGEXP_LIKE

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/named_argument.sql
- test/fixtures/dialects/databricks/named_argument.yml
Fixes #5944 by adding support for Databricks named parameters.
- Other.
> 5944: Add support for databricks named parameters

- src/sqlfluff/utils/reflow/reindent.py
- test/utils/reflow/reindent_test.py
Some custom templater plugins might emit special zero-length marker template slices with a special slice type, as previously described in #4708.  These are transformed into a meta TemplateSegment with an empty source string, which mostly works great.  However, the LT02 indention rule will attempt to indent these meta nodes, which is impossible because there is no `source_str` that the indention would affect, and thus it is impossible to resolve this lint violation.
For example, suppose the parse tree looks like this:
```
[META] placeholder: [Type: 'block_start', Raw: "{% up 'Do nothing' %}", Block: 'f142fe']
[META] indent:      [Block: 'f142fe']
[META] placeholder: [Type: 'migration_up', Raw: '']
newline:            '\n'
whitespace:         '    '
```
The indention rule will perceive a …
> Don't indent invisible template slices

- docs/source/configuration.rst
- src/sqlfluff/core/templaters/placeholder.py
- test/core/templaters/placeholder_test.py
Closes #5140, though that issue has a bit of maybe a misunderstanding of the problem
psql sql interpolation supports colon followed by variable name, unquoted, single-quoted, or double-quoted, such as
```sql
SELECT :"column" FROM :table WHERE user = :'name'
```
When invoked with `psql -c "SELECT ..." -v column=columnWithUppercase -v table=my_table -v user=my_name` renders to
```sql
SELECT "columnWithUppercase" FROM my_table WHERE user = 'my_name'
```
This implements a new `param_style` for `placeholder` templater to allow for this. If a name more specific to its use case (rather than a description of the style) would be useful, like `psql_colon`, let me know
It does add a new capture group to the regex, and looks for this capture group in the generic placeholder code. Shouldn't cause …
> Support quoted psql parameters with `placeholder` templater

- src/sqlfluff/core/rules/fix.py
- test/fixtures/rules/std_rule_cases/AL07.yml
Validates the condition of the assertions for "replace" with `is_just_source_edit` in `LintFix.to_dict`
- Fixes #5954 
None
- Other.
> AL07: Fix self-referencing table aliases

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/drop_various_resources.sql
- test/fixtures/dialects/bigquery/drop_various_resources.yml
makes progress on #5789
The current BigQuery dialect does not correctly parse some DROP TABLE statements, so we try to fix them.
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_row_access_policy_statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_capacity_statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_reservation_statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_assignment_statement
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_search_index
- https://cloud.google.com/bigquery/docs/reference/standard-sql/data-definition-language#drop_vect …
> BigQuery: Support various DROP statements

- src/sqlfluff/utils/reflow/rebreak.py
- test/fixtures/rules/std_rule_cases/LT04.yml
- test/rules/std_LT04_ST06_test.py
This fixes how rebreak recombines moved elements for the "Leading Tricky Case", namely `dedent` segments.
- Fixes #4882
- Fixes #5913
This also fixes when a rebreak doesn't have an anchor point and attempts to find the next element with segments.
- Fixes #5973
None
- Other.
> Rebreak: Fix meta dedent segment order

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/call_statement.yml
- test/fixtures/dialects/mysql/create_trigger.yml
- test/fixtures/dialects/mysql/if_session_variable.yml
- test/fixtures/dialects/mysql/load_data.yml
- test/fixtures/dialects/mysql/repeat_label.yml
- test/fixtures/dialects/mysql/repeat_multiple_statements.yml
- test/fixtures/dialects/mysql/repeat_no_label.yml
- test/fixtures/rules/std_rule_cases/RF02.yml
fixes: https://github.com/sqlfluff/sqlfluff/issues/5479
Change what was parsed as:
```yaml
- column_reference:
variable: '@a'
```
in many places in the MySQL dialect to be parsed as:
```yaml
- variable: '@a'
```
As a result, we can resolve the false match in the lint rule that requires a variable to be qualified for a non-column variable, as shown in the above issue.
This change may affect existing MySQL grammars. Since variable is not a column, this change should result in more accurate parsing results than the current implementation. However, if existing syntaxes handle variables and columns indistinguishably, the parsing results may be incorrect because it is no longer be wrapped in a `column_reference`.
At the very least, the effect of this change is limited to the MySQL dialect. The …
> MySQL: Fix variable handlings inside expressions

- src/sqlfluff/core/templaters/jinja.py
- src/sqlfluff/core/templaters/slicers/tracer.py
- test/core/templaters/jinja_test.py
Currently, the JinjaAnalyzer implementation will directly construct an instance of JinjaTracer, making it difficult for users providing a derived JinjaAnalyzer to also have it return a derived JinjaTracer.
By moving the construction of JinjaTracer to a separate function, it is easy for plugin authors to override this function and provide their own tracer.
This approach is very similar to the one taken for allowing custom JinjaAnalyzer implementations in pull request #5543.
No.  This is a small refactor that makes it easier to write derived classes.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files …
> Add support for custom JinjaTracer implementations

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_procedure.sql
- test/fixtures/dialects/snowflake/create_procedure.yml
The parser was not able to correctly parse a fully working CREATE PROCEDURE statement in Snowflake where a script was not part of the statement. Example: 
```
CREATE OR REPLACE PROCEDURE MY_PROCEDURE(hello_world VARCHAR(10000))
COPY GRANTS
RETURNS TABLE ()
LANGUAGE PYTHON
RUNTIME_VERSION = '3.11'
PACKAGES = ('snowflake-snowpark-python')
HANDLER = 'my.path.func_formula_parser_test_script_runner_proc'
IMPORTS = ('@MIRROR.PYTHON_SCRIPTS/script.py')
EXECUTE AS OWNER
;
```
No
- Included test case in test/fixtures/dialects/snowflake/create_procedure.sql
> Snowflake: fix scriptless stored procedure parsing

- .gitignore
- docs/source/configuration.rst
- src/sqlfluff/core/config.py
- test/core/config_test.py
When searching for configuration files, this PR adds a step that looks for configuration files between the users home directory and the current working directory. This makes it possible to execute sqlfluff in subdirectories of a project where the sqlfluff config is in the root of the project, making it simpler to configure linting in editors.
Fixes #5957 (at least its a possible solution)
- Would it be better to but this feature behind a feature or cli flag (i.e. make it not default)?
- In this PR, if there are several directories between home and cwd that contains a config, it will only take the config closest to cwd, and ignore all other configs. Wondering if it should just include all of them?
- Included test cases to demonstrate any code changes in `test/core/config_test.py`.
- Added …
> Parent dir config search

- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/utils/analysis/select.py
- test/fixtures/rules/std_rule_cases/RF03.yml
Allows multiple types for `BaseSegment.recursive_crawl`'s `no_recursive_seg_type`
Don't analyze merge statements that may be present in subselects for object references
- Fixes #5980 
None
- Other.
> Select Analysis: Don't recursively crawl merge subselects

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/connect_by.sql
- test/fixtures/dialects/snowflake/connect_by.yml
Fixes parsing of CONNECT BY PRIOR in SELECT statements where START WITH is not used.
No
- Other.
> Snowflake: fix connect by prior selects

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_table_column.sql
- test/fixtures/dialects/snowflake/alter_table_column.yml
Adds parsing fixes to `ALTER TABLE ... DROP COLUMN IF EXISTS` special cases: 
- `DROP IF EXISTS column1, IF EXISTS column2`
- `DROP COLUMN IF EXISTS column1, IF EXISTS column2` 
No
- Other.
> Snowflake: fixes drop column if exists parsing rules

- constraints/dbt150-winpy.txt
- plugins/sqlfluff-templater-dbt/setup.cfg
Based on slack conversation, I think we have some old and unnecessary dependencies in the `setup.cfg` file for the dbt templater.
Those constraints were previously altered:
- `markupsafe` pinned in #2685 to fix #2684, which is linked to dbt-core 1.0 and python 3.8. dbt-core 1.0 doesn't compile anymore (see #4442).
- `markupsafe` unpinned in #3967 (but dependency not removed).
- `ruamel.yaml`, `pydantic` and `rich` were added as dependencies as part of #3976, but then the code that was added was removed in #4273 (but didn't remove the dependencies).
I think it's safe to nuke them now.
> Remove old deps for dbt templater

- .pre-commit-config.yaml
- requirements_dev.txt
The package `types-pkg-resources` has been yanked with a note to replace with `types-setuptools`
None
- Other.
> Replace types-pkg-resources with types-setuptools

- src/sqlfluff/rules/convention/CV11.py
Removes the print statement found in CV11.
- fixes #4850
None
- Other.
> CV11: Remove rogue print statement

- src/sqlfluff/rules/references/RF03.py
- src/sqlfluff/utils/analysis/query.py
- test/fixtures/rules/std_rule_cases/RF03.yml
This fixes a number of edge cases with subqueries with RF03.
- fixes #3987
- fixes #5599 
- fixes #5983
- fixes #6014
None
- Other.
> RF03: Fixed some subquery reference scenarios

- src/sqlfluff/core/config.py
- test/core/config_test.py
Fixes #5697
- The code parsing comma-separated input in the `FluffConfig` class constructor taken out into a separate internal method. This method is called from the `FluffConfig` class constructor to preserve the original use. In addition, it is now also called when inline directive processing on a file is done to ensure the comma-separated lists are exploded into internal variables.
- While this fixes the encountered issue, it does so within the existing facilities for the inline configuration directive parsing. These are however implemented differently from the rest of the configuration loading - the former as a set of method on `FluffConfig`, the latter via a dedicated `ConfigLoader` functions. It is possible that the correct way to fix the problem is to re-implement the inline …
> Fix ignored inline rule overrides (#5697)

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/filter_aggregate.sql
- test/fixtures/dialects/trino/filter_aggregate.yml
- test/fixtures/dialects/trino/within_group.sql
- test/fixtures/dialects/trino/within_group.yml
Fixes #6055
1. I added a test case to confirm the `WITHIN GROUP (...) FILTER (...)` query can be parsed.
1. I also added a test case to confirm that the base FILTER works __without__ the WITHIN GROUP clause.
I found that parsed before this change and continued to parse after.
- Other.
> TRINO: support FILTER after WITHIN GROUP agg expression

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/cte.yml
- test/fixtures/dialects/clickhouse/limit_by.sql
- test/fixtures/dialects/clickhouse/limit_by.yml
- test/fixtures/dialects/clickhouse/limit_delimited.sql
- test/fixtures/dialects/clickhouse/limit_delimited.yml
fixes #5494 adding support for limit by and limit 1,2 as well as LIMIT (1), (2) formats that are valid in Clickhouse
Nope
> fix(clickhouse): add support for limit by and bracketed format

- .pre-commit-hooks.yaml
This disables the pre-commit hooks from using the progress bar. Pre-commit doesn't print information to the terminal until after the hook completes. Disabling this in the hook improves performance.
None
- Other.
> pre-commit: Disable progress bar

- src/sqlfluff/utils/reflow/rebreak.py
- test/rules/std_LT02_LT04_test.py
This corrects the issue with LT04 removing `dedent` segments from the fix.
- fixes #5466
None
- Other.
> LT04: Fix indentation conflict with LT02

- docs/generate-rule-docs.py
- docs/source/_partials/.gitignore
- docs/source/conf.py
Unfortunately, #6052 will break the VSCode docs link, by moving the rules again. However I now have a better solution so that we never need to break them again!
**RULE PERMALINKS**.
This PR adds permanent links to the rules which can then internally redirect. e.g. the VSCode plugin would be able to point at `/perma/rule/RF01.html` and be internally redirected by the docs to the appropriate location - in this case `/reference/rules.html#sqlfluff.rules.sphinx.Rule_RF01`.
I'll make a PR for the VSCode plugin shortly.
> Add perma-links for rules

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/create_materialized_view.sql
- test/fixtures/dialects/clickhouse/create_materialized_view.yml
- test/fixtures/dialects/clickhouse/create_table.yml
- test/fixtures/dialects/clickhouse/create_temporary_table.yml
Fixes #5749 - the support for create materialized view is ok but needed to be more lenient in regarde to the following syntaxes : 
```
ENGINE = MergeTree()
-- equivalent to
ENGINE MergeTree
```
and 
```
ORDER BY (col1, col2)
-- or if you don't care what to pick using a MergeTree engine 
ORDER BY tuple() -- the parenthesis being mandatory
```
Nope
> fix(clickhouse): add support for tuple() and ENGINE MergeTree

- src/sqlfluff/dialects/dialect_databricks.py
- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/databricks/select_group_by.sql
- test/fixtures/dialects/databricks/select_group_by.yml
Add support for GROUP BY ALL to the Databricks dialect. This syntax is not yet supported by the SparkSQL dialect, so I've added a new GroupByClauseSegment to the Databricks grammar. I have also replicated the tests from SparkSQL, adding a test for GROUP BY ALL at the end.
None for now. When SparkSQL supports GROUP BY ALL, we can simply move this change to the SparkSQL dialect.
I have also cleaned up the GroupByClauseSegment for SparkSQL, but this should have no impact to parsing, as demonstrated by the unchanged fixture YML files.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto …
> Databricks: Add support for GROUP BY ALL

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/row_datatype.sql
- test/fixtures/dialects/trino/row_datatype.yml
fixes https://github.com/sqlfluff/sqlfluff/issues/6084
Inspired by Bigqueries STRUCT definition. Using `ansi.StructTypeSegment` as base as Trino's ROW is essentially a STRUCT.
- Other.
> fix(dialect-trino): Trino ROW datatype definition in queries

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/raw_literal.sql
- test/fixtures/dialects/sparksql/raw_literal.yml
Add support for raw string literals to SparkSQL and Databricks.
See: https://spark.apache.org/docs/latest/sql-ref-literals.html#string-literal
None.
- Other.
> SparkSQL + Databricks: Add support for raw string literals

- plugins/sqlfluff-templater-dbt/test/conftest.py
Tests for the dbt templater keep failing on timeout. This increases that timeout to help prevent some of these failures.
None
- Other.
> dbt Templater: Increase `dbt deps` test fixture timeout

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/table_object_references.sql
- test/fixtures/dialects/tsql/table_object_references.yml
This allows for leading dots in tsql's table references. This also adds grammar for a special leading dot for LT01 spacing.
- fixes #5571
None
- Other.
> tsql: Allow leading dots in table references

- src/sqlfluff/rules/aliasing/AL04.py
- src/sqlfluff/rules/references/RF02.py
- test/fixtures/rules/std_rule_cases/RF02.yml
This handles finding column references within subqueries.
- fixes #6067
None
- Other.
> RF02: Handle subquery column qualification

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/frame_clause.sql
- test/fixtures/dialects/snowflake/frame_clause.yml
Adds support for the `INTERVAL` keyword within a `frame_clause`
- fixes #6092
None
- Other.
> Snowflake: Added `INTERVAL`s to Frame Clause

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/conflict_clause.sql
- test/fixtures/dialects/sqlite/conflict_clause.yml
> SQLite: Add conflict_clause to unique table constraint

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/clickhouse/tuple_datatype.yml
- test/fixtures/dialects/sparksql/select_like_clause.yml
This fixes an issue where some bracketed, delimited expressions were resolving to delimited column references instead of the literal values that they should have been.
- Fixes #6040
None
- Other.
> Change evaluation order of literals before column refs in bracketed, delimited expressions

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/try_catch.sql
- test/fixtures/dialects/tsql/try_catch.yml
This allows for the catch block to be empty.
- fixes #6114 
None
- Other.
> TSQL: Allow for empty catch block in try-catch

- src/sqlfluff/cli/commands.py
- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/core/linter/linter.py
- test/cli/commands_test.py
- test/core/rules/noqa_test.py
- test/fixtures/cli/disable_noqa_test.sql
Adds an option to allow only a subset of rules when a line is marked with `--noqa: rule_id`
- fixes #6097 
None
- Other.
> Add option for allowing only a subset of rules for noqa

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select_higher_order_function.sql
- test/fixtures/dialects/snowflake/select_higher_order_function.yml
fixes #5977 and #6122
This change introduces support for Higher-Order Functions - see https://docs.snowflake.com/en/user-guide/querying-semistructured#filter-and-transform-data-with-snowflake-higher-order-functions
Based on a bit of testing, I've found that Snowflake will parse a lambda expression (`x -> x:value`) anywhere it appears as long as it's within a function. Meaning - it _won't_ parse a lambda expression outside of a function, but also it _will_ parse a lambda expression even when it's in an unrelated function (or in an incorrect position). I've chosen to replicate that logic as a result, assuming that will better match any changes in Snowflake going forwards as well.
None identified
- Included test cases to demonstrate any code changes, which may be one or more of the …
> Add support for Snowflake Higher-Order Functions

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/.gitignore
- plugins/sqlfluff-templater-dbt/test/templater_test.py
This is part of #6138, but the uncontroversial part. This effectively contains only quality of life improvements around dbt exceptions.
This is loosely related to #6037, but doesn't resolve it on it's own.
> More robust exception handling for dbt.

- src/sqlfluff/rules/structure/ST08.py
- test/fixtures/rules/std_rule_cases/ST08.yml
This ignores `DISTINCT`s with brackets which contain subquery expressions for ST08.
- fixes #6142
None, performance hit _should_ be minimal.
- Other.
> ST08: Ignore `DISTINCT`s with subqueries

- .github/workflows/ci-tests.yml
- constraints/dbt110.txt
- constraints/dbt120.txt
- constraints/dbt130.txt
- constraints/dbt140.txt
- plugins/sqlfluff-templater-dbt/pyproject.toml
- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- tox.ini
DBT 1.1 & 1.2 have been EOL for over 2 years, 1.3 has been EOL for almost 2 years. We are having to make exceptions for them - such as setuptools not supporting them any more. Thus, it's time to sunset them. This PR should trigger a minor release.
I've cleaned up some old paths in the templater. I've also pinned 1.4 to 1.4.1+ to allow another code path cleanup. Realistically, we could sunset 1.4, as it's also very old, so i'm not worried about pinning the patch.
No …
> Deprecate support for dbt 1.1-1.3

- src/sqlfluff/rules/references/RF06.py
This is a very small method to simplify a section of RF06. There's a section here which effectively re-implements `functools.cached_property`. This PR updates that to just use `functools.cached_property`, and remove the complexity.
> Cached property in RF06 rather than DIY

- src/sqlfluff/rules/capitalisation/CP02.py
- test/fixtures/rules/std_rule_cases/CP02.yml
As part of resolving the conflict around RF06 and AL09, there's some influence from CP02. The docs for this rule were fairly poor, but the functionality is good I think.
This PR significantly updates the docs and adds/improves a few of the test cases.
> Update Docs and tests for CP02

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/list_comprehension.sql
- test/fixtures/dialects/duckdb/list_comprehension.yml
This adds list comprehensions to the duckdb dialect.
- fixes #6157
None
- Other.
> Duckdb: Add support for list comprehensions

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/merge.sql
- test/fixtures/dialects/tsql/merge.yml
This correct the issue when a merge statement does not include an alias on the target table.
- fixes #5989
None
- Other.
> TSQL: Fix `MERGE` without a target alias

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/insert_overwrite_directory.sql
- test/fixtures/dialects/sparksql/insert_overwrite_directory.yml
Add support for an `INSERT OVERWRITE DIRECTORY` statement after a CTE.
- fixes #5901
None
- Other.
> sparksql: Allow `INSERT OVERWRITE` after a CTE

- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sparksql_keywords.py
- test/fixtures/dialects/sparksql/create_table_complex_datatypes.sql
- test/fixtures/dialects/sparksql/create_table_complex_datatypes.yml
Adds support for the `VARIANT` data type in SparkSQL (feature being added in 4.0.0) and Databricks.
- fixes #6120 
None
- Other.
> SparkSQL/Databricks: Support for `VARIANT` type

- docs/source/_ext/sqlfluff_domain.py
- src/sqlfluff/rules/aliasing/AL06.py
- src/sqlfluff/rules/aliasing/AL07.py
The docs for AL06 and AL07 have (in theory) links to other rule docs in them. Those links are currently broken, but not surprisingly because the details on how to cross reference rules is poorly documented.
This PR fixes the links and improves the documentation.
> Better documentation on how to cross reference rules and fix a few.

- docs/source/reference/dialects.rst
- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_athena.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_mariadb.py
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sqlite.py
- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/postgres/unicode_double_quote.yml
After #6153, it's more obvious that some of the dialects have more extensive documentation than others. This starts to flesh out that documentation. I originally wanted to be more complete here, but some dialects were much easier to test and find than others.
I've added details for as many dialects as I'm either familiar with or have direct access to for testing. I've also added links where I can, especially where dialects do interesting things.
I've also started a bit of a convention (which I hope other dialects will follow) on what kinds of things to document.
(I also fixed a bug in the Postgres dialect which I found on the way through)
> More dialect documentation

- src/sqlfluff/rules/aliasing/AL09.py
Bug reports like #5782 suggest that we're making assumptions in AL09 which aren't always true. Without better logging information we can't _fix_ them, but we can definitely make the user experience better by not raising an exception, and also by producing better logging and debug information.
This sorts that. No coverage because I don't actually know what will trigger this yet - just that it is definitely being triggered.
> Handle errors better in AL09

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/walrus_operator_function.sql
- test/fixtures/dialects/duckdb/walrus_operator_function.yml
This adds support for functions that use a `walrus operator` in DuckDB.
- fixes #6189
None
- Other.
> DuckDB: Support functions with walrus operators

- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/duckdb/create_table.sql
- test/fixtures/dialects/duckdb/create_table.yml
- test/fixtures/dialects/duckdb/structs.sql
- test/fixtures/dialects/duckdb/structs.yml
Adds support for `STRUCT` datatype in DuckDB
- fixes #6195
None
- Other.
> DuckDB: Support `STRUCT` datatype

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/create_type.sql
- test/fixtures/dialects/duckdb/create_type.yml
This adds support for `CREATE TYPE` in DuckDB. Namely `STRUCT` and `UNION` types.
- fixes #6200
None
- Other.
> DuckDB: Support `CREATE TYPE` statement

- src/sqlfluff/core/config/__init__.py
- src/sqlfluff/core/config/file.py
- src/sqlfluff/core/config/fluffconfig.py
- src/sqlfluff/core/config/ini.py
- src/sqlfluff/core/config/removed.py
- src/sqlfluff/core/config/toml.py
- src/sqlfluff/core/config/types.py
- src/sqlfluff/core/helpers/dict.py
- tox.ini
This brings the `core.helpers` and `core.config` modules up to string mypy typing. Also helpfully it does a little bit of type narrowing so that any lists in config mappings can only contain strings. Practically this doesn't change downstream functionality (as they should only be lists anyway), but it makes type handling downstream simpler.
> Strict typing in `config` and `helpers`.

- src/sqlfluff/core/linter/patch.py
- test/fixtures/linter/autofix/ansi/028_leading_comma_with_jinja/after.sql
- test/fixtures/linter/autofix/ansi/028_leading_comma_with_jinja/before.sql
- test/fixtures/linter/autofix/ansi/028_leading_comma_with_jinja/test-config.yml
- test/fixtures/linter/autofix/ansi/029_indentation_join_reorder_LT02_ST09/.sqlfluff
- test/fixtures/linter/autofix/ansi/029_indentation_join_reorder_LT02_ST09/after.sql
- test/fixtures/linter/autofix/ansi/029_indentation_join_reorder_LT02_ST09/before.sql
- test/fixtures/linter/autofix/ansi/029_indentation_join_reorder_LT02_ST09/test-config.yml
This fixes how the patcher applies the patches in order. Originally this anchor was on the first raw sub-segment in a segment, this now captures the first point where an insertion buffer has data appended to it and uses that position to build out where the next patch is applied. Once that point has been inserted into the fixed string, we reset the `first_segment_pos` anchor.
- fixes #6048 
- fixes #5641
There should be no side effects with this change, but obviously testing was limited to the examples that were failing and current test continue to be applied appropriately. All in all this should be more correct than before.
- …
> Fix patch will anchor on first buffer insertion point

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/string_normalization.sql
- test/fixtures/dialects/postgres/string_normalization.yml
Fixes #6210
For postgres, allows use of normalization operators in expressions.
Syntax: 
```
text IS [NOT] [form] NORMALIZED
```
where `form` is:
```
{ NFC | NFD | NFKC | NFKD }
```
Defines a new `NormalizedGrammar` in `dialect_ansi` which is not set for any dialects other than postgres.
- Other.
> Add postgres normalization operator support

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/at_before_time_travel.sql
- test/fixtures/dialects/snowflake/at_before_time_travel.yml
- fixes #5570
- fixex #6070 
- Other.
> Fix time travel clauses in Snowflake dialect

- src/sqlfluff/core/linter/linting_result.py
The "templating", "lexing", "parsing" and "linting" columns appear twice in the timing records output, because their ordering both is configured explicitly, and because they still are included in the `rule_codes` set.
This fixes that by removing them from `rule_codes` so they only appear once in the resulting CSV file.
None
- Other. …
> Remove duplicate timing columns from the timing records

- src/sqlfluff/dialects/dialect_teradata.py
- test/fixtures/dialects/teradata/create_table.sql
- test/fixtures/dialects/teradata/create_table.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/6232
No
- Other.
> Teradata order of VOLATILE and MULTISET

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_table_column.sql
- test/fixtures/dialects/snowflake/alter_table_column.yml
- test/fixtures/dialects/snowflake/create_table.sql
- test/fixtures/dialects/snowflake/create_table.yml
This change adds the ability to define [virtual/calculated columns](https://snowflakewiki.medium.com/virtual-column-in-snowflake-the-complete-guide-50c1a224ffd0) using `CREATE TABLE` and `ALTER TABLE ... ADD COLUMN` statements.
This is an extension of the dialect. The existing unit tests show that none of the existing functionalities in the Snowflake dialect are impacted adversely.
- Other. …
> Snowflake: Support defining virtual columns

- src/sqlfluff/dialects/dialect_exasol.py
- test/fixtures/dialects/exasol/select_statement.sql
- test/fixtures/dialects/exasol/select_statement.yml
The value range table clause also allows function calls which return integer values, as there are many possibilities to create integer values with different functions I added functions and bare functions besides numeric literals.
[Exasol Doc link](https://docs.exasol.com/db/latest/sql/select.htm)
> The arguments min_value and max_value in the VALUES BETWEEN clause must be constant expressions that evaluate to integers. The argument step_value must be a constant expression that evaluates to a positive integer.
No …
> Exasol - allow function calls in values clause

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/pivot.sql
- test/fixtures/dialects/snowflake/pivot.yml
The previous implementation did not allow subqueries, ANY [ORDER BY ...], and 'DEFAULT ON NULL'. I've completed it following the [Snowflake docs.](https://docs.snowflake.com/en/sql-reference/constructs/pivot)
- fixes #5876 
There should be no side effects with this change.
- Other.
> Complete the support for PIVOT in Snowflake dialect

- src/sqlfluff/rules/references/RF02.py
- test/fixtures/rules/std_rule_cases/RF02.yml
This removes including the parent table alias of a subquery. These cases would be referencing the subquery itself.
- fixes #6231
none
- Other.
> RF02: Ignore alias references that are self-inner

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/set.sql
- test/fixtures/dialects/postgres/set.yml
This allows for double quoted identifiers to be used in a `SET` statement in postgres.
- fixes #6234
None
- Other.
> Postgres: Support `SET` with double quoted identifiers

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/create_type.sql
- test/fixtures/dialects/duckdb/create_type.yml
Originally, I pointed to the wrong segment type for data types in `CREATE TYPE`. This corrects this to use `DatatypeSegments`.
- fixes #6225 
none
- Other.
> DuckDB: Fixed `DatatypeSegment` references

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/linter/__init__.py
- src/sqlfluff/core/linter/formatter.py
- src/sqlfluff/core/linter/linted_dir.py
- src/sqlfluff/core/linter/linted_file.py
- src/sqlfluff/core/linter/linting_result.py
- src/sqlfluff/core/linter/patch.py
- src/sqlfluff/core/linter/runner.py
- src/sqlfluff/core/rules/noqa.py
- test/core/config/fluffconfig_test.py
- test/core/linter/linter_test.py
- tox.ini
This brings the `sqlfluff.core.linter` module up to strict mypy typing (and enforces that in CI).
A lot of this is just type annotations, however there are a few more interesting bits:
- The `linter` module now defines a `FormatterInterface` for the `cli.OutputStreamFormatter` to inherit from. This means that all of the `Linter` methods which allow a `formatter` argument have an interface to use for typing without importing the `cli` module.
- The `check_tuples` method on `LintedFile`, `LintedDir` and `LintingResult` no longer supports a `by_path` argument. Instead there's now a seperate method called `check_tuples_by_path` to replace that functionality. That makes the typing much cleaner (and removes a bunch of overloads).
- For the `runner` module, there's more use of `abstractmethod` …
> Strict typing for `sqlfluff.core.linter`

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/rules/std_rule_cases/RF06.yml
Per the new changes auto-enforcing RF06, I've run into issues of `fix` making invalid sql, centered around that postgres naked identifiers cannot begin with digits.
If you run `sqlfluff lint file.sql --dialect postgres` with no other config using sqlfluff 3.2.0 on
```sql
SELECT
regular,
"1a"
FROM
my_schema.mytable
```
`"1a"` is flagged as a violation. However, the correction is invalid sql - identifiers beginning with a digit must be quoted. Running sql violating this returns `ERROR: trailing junk after numeric literal at or near "1a"`
I didn't create a linked issue for this problem, let me know if that's preferred to a standalone PR
A little concerned of other unintended consequences, I'm not hugely familiar with this codebase, but this seems relatively specific. We'll see what tests …
> fix RF06 issue in postgres naked identifier regex

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mariadb/column_alias.sql
- test/fixtures/dialects/mariadb/column_alias.yml
- test/fixtures/dialects/mysql/column_alias.sql
- test/fixtures/dialects/mysql/column_alias.yml
- test/fixtures/rules/std_rule_cases/AL09.yml
This corrects the exception raised by AL09 when using double quoted aliases in MySQL or MariaDB.
- fixes #6218
None
- Other.
> MySQL: AL09 handle double quoted identifiers

- docs/source/production/diff_quality.rst
The readthedocs.io page for diff quality seems to have become unlinked from the project, the link we have in the docs also doesn't work anyway. The project is still maintained and the docs were just a rendered copy of the README anyway, so this updates the link in the docs to just point at the github page.
I've let the folks at diff cover know: https://github.com/Bachmann1234/diff_cover/issues/420
> Update link to diff-cover docs

- plugins/sqlfluff-templater-dbt/pyproject.toml
Two tiny nits I found. Added py3.12 support to the tags for the dbt templater, and removed the reference to the dbt_osmosis package in the `[tool.setuptools.packages.find]` section.
> dbt templater `pyproject.toml` nits

- .github/workflows/ci-test-dbt.yml
- .github/workflows/ci-test-python.yml
- .github/workflows/ci-tests.yml
- README.md
@greg-finley has identified that the coveralls jobs are failing, and that the repo doesn't seem to be updated anymore. All of our coverage jobs have already been migrated to github actions anyway, so this finishes the job and removes coveralls entirely.
> Remove dependency on coveralls.

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/datetrunc.sql
- test/fixtures/dialects/tsql/datetrunc.yml
> TSQL: Add DATETRUC to date_part_function_name list

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/handle_exception.yml
- test/fixtures/dialects/bigquery/set_variable_single.sql
- test/fixtures/dialects/bigquery/set_variable_single.yml
This adds support for system variables in a `SET` statement. Also allows for system variables with dots.
- fixes #5404
None
- Other.
> BigQuery: Add support for `SET` with system variables

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_procedure.sql
- test/fixtures/dialects/bigquery/create_procedure.yml
- test/fixtures/dialects/bigquery/execute_immediate.yml
This adds support for concatenation in an `EXECUTE IMMEDIATE` statement.
- fixes #5405 
None
- Other.
> BigQuery: Add support for concatenating in `EXECUTE IMMEDIATE`

- plugins/sqlfluff-templater-dbt/test/conftest.py
- src/sqlfluff/core/config/fluffconfig.py
- src/sqlfluff/rules/jinja/JJ01.py
- test/core/config/fluffconfig_test.py
I noticed a _really wierd bug_ with JJ01. It basically doesn't work in parallel mode at the moment.
On debugging, the cause seems to be that when it checks for the presence of a jinja templater (or subclass), and it's using `context.config.get("templater_obj")` which intentionally isn't rehydrated when the `FluffConfig` object is pickled/unpickled. Instantiating a new templater object seems overkill, but we do still need a way of checking the class.
This PR allows a new method `get_templater_class()` which rules can use to find out if they're in a jinja-like environment. That one does work in parallel mode.
In doing that, I've changed the type signature of the original `get_templater()` method to use the config value rather than the argument. I think it's cleaner and safer.
> Bugfix for JJ01 in parallel mode

- src/sqlfluff/rules/layout/LT07.py
- test/fixtures/rules/std_rule_cases/LT07.yml
I noticed that LT07 is throwing false positives if a CTE ends with a whitespace-consuming jinja tag. this adds logic to handle that situation and react accordingly.
> Bugfix for LT07 with consumed newlines.

- docs/source/configuration/ignoring_configuration.rst
- docs/source/configuration/rule_configuration.rst
- docs/source/reference/rules.rst
Currently there are two, almost identical sections on how to ignore specific rules:
- https://docs.sqlfluff.com/en/stable/reference/rules.html#inline-ignoring-errors
- https://docs.sqlfluff.com/en/stable/configuration/ignoring_configuration.html#ignoring-errors-files
This is unhelpful and confusing, especially given the information in each is slightly different.
This PR sets the one in `configuration` as the main one, and then just links to that from the rules references section.
> Dededuplicate rule ignore docs

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/nested_joins.sql
- test/fixtures/dialects/tsql/nested_joins.yml
- test/fixtures/rules/std_rule_cases/RF01.yml
This adds supported for bracketed nested joins in tsql.
Also fixes how aliases of bracketed `table_expression` detect aliases
- fixes #6137
None
- Other.
> TSQL: handle nested joins, RF01 better aliasing

- src/sqlfluff/dialects/dialect_duckdb.py
- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/table_functions.yml
- test/fixtures/rules/std_rule_cases/RF03.yml
This adds support for walrus named arguments in a postgres function. As duckdb now matches postgres' named arguments, this has been dropped.
- fixes #6290
None
- Other.
> Postgres: Support walrus operator named arguments

- docs/source/index.rst
- docs/source/reference/releasenotes.rst
I noticed there's a note about 1.0.x and 2.0.x on the index of the docs, but nothing on 3.0.x (the current major version). This adds a brief note for completeness.
> Add note on 3.0.x to main docs page.

- src/sqlfluff/core/config/fluffconfig.py
- test/rules/std_JJ01_test.py
This resolves an exception that I'm getting with the new JJ01 code. The current tests don't adequately cover the parallel use case. I've added a test case to simulate that by crawling with a config object which has done a pickling round trip.
> Hotfix for JJ01

- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/dialects/clickhouse/order_by_expression.sql
- test/fixtures/dialects/clickhouse/order_by_expression.yml
As raised on slack. This enabled expressions in the `ORDER BY` clause for clickhouse.
> Allow expressions in ORDER BY for clickhouse

- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/indent_loop_4.sql
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/dbt_project/models/my_new_project/indent_loop_8.sql
- plugins/sqlfluff-templater-dbt/test/rules_test.py
- src/sqlfluff/utils/reflow/elements.py
- src/sqlfluff/utils/reflow/reindent.py
- test/fixtures/rules/std_rule_cases/LT02-indent.yml
I originally found this bug while working with the `dbt` templater and a query which reduces to this:
```jinja
select
{% for i in range(1, 3) %}
1
{% if not loop.last %},{% endif %}
{% endfor %}
from foo
```
The `{% if not loop.last %},{% endif %}` would get shuffled between 4 and 8 indents on successive linting runs. The issue was that it was actually getting linted twice, twice when it was rendered in the middle of the loop and once at the end. The latter case was distorted around the indent tokens because it didn't contain any rendered code and was being treated as whitespace.
I found a few other bugs with the indentation logic here too, but this PR was getting too big with all of them (and I haven't managed to solve all of them yet). So I'm putting this one up in it's current state.
> Resolve an oscillation bug with LT02

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_schema.sql
- test/fixtures/dialects/snowflake/create_schema.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/6315
I ensured that `CREATE SCHEMA MYSCHEMA COMMENT = "Space for landing my data"` actually works in Snowflake.
No.
- Other.
> Snowflake allow double-quoted comments

- src/sqlfluff/rules/convention/CV11.py
- test/fixtures/rules/std_rule_cases/CV11.yml
I found this bug earlier today. Consider the following query (although it would be better to imagine that the macro is defined somewhere else in the codebase entirely):
```sql
{% macro cast_macro(col) %}
CAST(col as int)
{% endmacro %}
select
a,
{{ cast_macro('b') }},
c::date as d
from tbl
```
The casting style is definitely inconsistent (there's an explicit `CAST()` and there's also an implicit `::date` operation). However for the user writing the final query they may now know (or have control over) the macro they're calling (over `cast_macro`). As such I don't think it should be an error if `::date` is inconsistent with the casting inside the `cast_macro`. This PR excludes any templated sections from being considered for `CV11`.
> Exclude templated casts from CV11

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/grant_revoke.sql
- test/fixtures/dialects/snowflake/grant_revoke.yml
Added support for `grant monitor on user ...` in Snowflake dialect.
Fixes #6308.
Not to my knowledge.
- Other.
> Add support for `grant monitor on user ...` in Snowflake dialect

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/json_operators.sql
- test/fixtures/dialects/postgres/json_operators.yml
This fixes the ordering of lexing some of the JSON operators in the postgres dialect. This was preventing some operators from being lexed properly.
- fixes #6321
None
- Other.
> Postgres: Fix lexing some JSON operators

- src/sqlfluff/dialects/dialect_trino.py
- src/sqlfluff/rules/references/RF03.py
- src/sqlfluff/utils/analysis/select.py
- test/fixtures/dialects/trino/array.yml
- test/fixtures/dialects/trino/regexp_replace_with_lambda.yml
- test/fixtures/rules/std_rule_cases/RF01.yml
- test/fixtures/rules/std_rule_cases/RF03.yml
This fixes how some rules interact with lambda function and their parameters. Namely touches Trino, but also supports any of the dialects that use lambda functions/expressions
- fixes #6141
None
- Other.
> Trino: Fix rule interactions with lambda functions

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/bigquery/select_struct.sql
- test/fixtures/dialects/bigquery/select_struct.yml
This allows for expressions to be in bracketed expressions. Namely used by BigQuery and the tuple syntax.
- fixes #6015
None, as far as I can tell
- Other.
> BigQuery: Support Tuple syntax in other locations

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_athena.py
- src/sqlfluff/dialects/dialect_postgres.py
- src/sqlfluff/dialects/dialect_redshift.py
- src/sqlfluff/dialects/dialect_trino.py
- src/sqlfluff/dialects/dialect_vertica.py
- test/fixtures/dialects/athena/select_cast_withtimezone.sql
- test/fixtures/dialects/athena/select_cast_withtimezone.yml
- test/fixtures/dialects/trino/timestamp_resolutions.yml
Closes https://github.com/sqlfluff/sqlfluff/issues/6330 but also reduces the same implementation in many dialects of the same thing
It could have been solved more simply per the first commit, but I think this reduction in duplication is good. And dialects can override `TimeWithTZGrammar` if desired.
- Other. …
> Refactor timestamp grammar

- src/sqlfluff/rules/structure/ST06.py
- test/fixtures/rules/std_rule_cases/ST06.yml
Add failing test cases, no fix yet.
Fixes #5956
- Other.
> ST06 - Fix union of CTE/Subquery

- src/sqlfluff/core/linter/runner.py
As discussed on slack. Python 3.13 deprecates the "fork" threading option. This explicitly sets the option to "spawn" for all platforms.
https://docs.python.org/3/library/multiprocessing.html#contexts-and-start-methods
> Handle deprecation warning of "fork"

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_foreign_wrapper.sql
- test/fixtures/dialects/postgres/create_foreign_wrapper.yml
This adds the `CREATE FOREIGN DATA WRAPPER` statement for the `postgres_fdw` extension.
- fixes #6027
None
- Other.
> Postgres: Add `CREATE FOREIGN DATA WRAPPER` statement

- plugins/sqlfluff-templater-dbt/sqlfluff_templater_dbt/templater.py
- plugins/sqlfluff-templater-dbt/test/fixtures/dbt/error_models/compile_missing_table.sql
- plugins/sqlfluff-templater-dbt/test/templater_test.py
There's a section in the dbt template which was marked as `# pragma: no cover`, but I managed to cover it recently! This adds a test case which triggers it - and also removes the old warning asking people to report it, because I don't think they need to anymore.
> Revise dbt warnings when a file fails to compile

- src/sqlfluff/rules/references/RF05.py
- test/fixtures/rules/std_rule_cases/RF05.yml
This code snippet bypasses the `RF05` rule for PostgreSQL dialects when an `extension_reference` type is detected in the parent stack. If the current SQL dialect is PostgreSQL and the parent stack contains an `extension_reference`, the function will return `None`, effectively ignoring the `RF05` rule in this specific context. 
- fix #4935 
No
```
test_pass_create_extension_reference_quoted:
pass_str: CREATE EXTENSION IF NOT EXISTS "quoted-extension";
configs:
core:
dialect: postgres
test_pass_drop_extension_reference_quoted:
pass_str: DROP EXTENSION IF EXISTS "quoted-extension";
configs:
core:
dialect: postgres
```
- …
> Postgres : Allow Extensions with Special Characters in Name

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table.sql
- test/fixtures/dialects/tsql/alter_table.yml
This allows for both `ON DELETE` and `ON UPDATE` to exist on a single `reference_constraint_grammar` for tsql.
- fixes #6339
None
- Other.
> tsql: allow both on delete and on update in a `reference_constraint`

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/triggers.sql
- test/fixtures/dialects/tsql/triggers.yml
This allows for the `UPDATE` keyword to a be function in the tsql dialect.
- fixes #5960
None.
- Other.
> TSQL: allow `UPDATE` to be a function name

- src/sqlfluff/core/config/fluffconfig.py
- src/sqlfluff/core/linter/linter.py
- test/core/config/fluffconfig_test.py
Uses a deepcopy of the FluffConfig when parsing files. This prevents the config from being mutated by file-level config overrides.
fixes #6343 
Configs will no longer be mutated when parsing files, so file-level config overrides will now only apply to the file in which they are applied.
- Other.
> Utilize a deepcopy of the config object when parsing files

- src/sqlfluff/core/templaters/jinja.py
- test/core/templaters/jinja_test.py
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_this.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_this_callable.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_this_callable.yml
Make the dbt `RelationEmulator` safely callable.
Fixes #6357.
No.
> Make dbt `RelationEmulator` safely callable

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/create_table.sql
- test/fixtures/dialects/databricks/create_table.yml
fixes #6361
Databricks support adding default values to columns when creating tables, e.g.
```
CREATE TABLE test (
value STRING DEFAULT "test"
);
``` 
The default values can either be a literal or a function, such as `current_timestamp()`.
There are some false negatives with this change, such as 
```
CREATE TABLE test (
value STRING DEFAULT "test" DEFAULT "fail"
);
``` 
which passes the checks but is invalid SQL. Though this kind of false positives already exist on main with e.g. 
```
CREATE TABLE test (
value STRING NOT NULL NOT NULL
);
``` 
which also passes a sqlfluff check but fails to execute in databricks sql.
- …
> enable default values when creating databricks tables

- src/sqlfluff/rules/aliasing/AL05.py
- test/fixtures/rules/std_rule_cases/AL05.yml
Resolves #4623 . Some of these examples were already resolved, so I've added test cases, but calling array functions and then referring to what looks like a table reference, but it's actually a column reference wasn't. This adds an edge case to AL05 for that syntax.
> Prevent false positives with AL05 and array functions

- src/sqlfluff/rules/structure/ST02.py
- test/rules/std_LT01_ST02_test.py
This fixes #6359, which it looks like was caused by #5809. The fix created by ST02 didn't have the expected structure from the rest of the dialect and so was being created with the wrong typing.
> Resolve collision between ST02 and LT01

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/add_file.sql
- test/fixtures/dialects/sparksql/add_file.yml
- test/fixtures/dialects/sparksql/add_jar.yml
- test/fixtures/dialects/sparksql/division_operator.sql
- test/fixtures/dialects/sparksql/division_operator.yml
- test/fixtures/dialects/sparksql/list_file.sql
- test/fixtures/dialects/sparksql/list_file.yml
- test/fixtures/rules/std_rule_cases/LT01-operators.yml
This prevents some segments that use division without spaces from being lexed as a `file_literal`.
- fixes #6363 
This changes the `file_literal` to have some sub-parts namely `path_segment` and `slash` (taken from the `clickhouse` dialect). This shouldn't have any impact but changes the parsing tree. 
Also `slash` now allows for `any` layout for before and after spacing as we shouldn't manipulate the filepath.
- Other.
- Added …
> SparkSQL: Improved lexing and parsing of file literals

- src/sqlfluff/rules/ambiguous/AM02.py
Based on conversation in https://github.com/sqlfluff/sqlfluff/pull/6337#issuecomment-2417433407 and in https://github.com/sqlfluff/sqlfluff/issues/5964#issuecomment-2192409972, this PR expands coverage of the [ambiguous union rule](https://docs.sqlfluff.com/en/stable/reference/rules.html#rule-ambiguous.union) (AM02) to Snowflake and Trino.
- Other. …
> Enable AM02 for snowflake and trino by default.

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/alter_database.sql
- test/fixtures/dialects/postgres/alter_database.yml
This adds support for identifiers in a `ALTER DATABASE ... SET` statement.
- fixes #6374
None
- Other.
> Postgres: Support identifiers in `ALTER DATABASE SET`

- docs/source/production/diff_quality.rst
- docs/source/production/pre_commit.rst
This helps tie off #2848 .
This PR contains a few formatting improvements for the docs relating to `diff-quality` and `pre-commit`. It mostly clarifies best practice when using `diff-quality` to avoid issues with file discovery.
> Details on debugging and setup for diff-quality

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/connect_by.sql
- test/fixtures/dialects/snowflake/connect_by.yml
This allows for expressions in a `CONNECT BY` clause which may use the `PRIOR` keyword before a column name, but may be inside another expression in snowflake.
- fixes #5863
This opens up parsing to be like a `join_on_condition` like the snowflake docs indicate. While potentially allowing for some non-runnable sql, it more correctly handles the parsing.
- Other.
- Created GitHub …
> Snowflake: Allow for additional `CONNECT BY` expressions that may use `PRIOR`

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select_higher_order_function.sql
- test/fixtures/dialects/snowflake/select_higher_order_function.yml
This makes the datatype in a bracketed lambda function optional for the snowflake dialect.
- fixes #6386 
None
- Other.
> Snowflake: Support bracketed lambda functions without datatypes

- src/sqlfluff/core/default_config.cfg
- test/fixtures/rules/std_rule_cases/LT01-brackets.yml
Removes the whitespace between `match_condition` and the `bracket` in LT01.
- fixes #5885
None
- Other.
> LT01: Add default config for `match_condition` to touch

- README.md
Hello team,
I'm the maintainer of [Anteon](https://github.com/getanteon/anteon). We have created Gurubase.io with the mission of building a centralized, open-source tool-focused knowledge base. Essentially, each "guru" is equipped with custom knowledge to answer user questions based on collected data related to that tool.
I wanted to update you that I've manually added the [SQLFluff Guru](https://gurubase.io/g/sqlfluff) to Gurubase. SQLFluff Guru uses the data from this repo and data from the [docs](https://docs.sqlfluff.com/en/stable/) to answer questions by leveraging the LLM.
In this PR, I showcased the "SQLFluff Guru" badge, which highlights that SQLFluff now has an AI assistant available to help users with their questions. Please let me know your thoughts on this contribution. …
> Introducing SQLFluff Guru on Gurubase.io

- src/sqlfluff/core/helpers/string.py
- test/core/config/fluffconfig_test.py
Support JSON values, sometimes used in Jinja context.
Fixes #6370
Hopefully not.
- Other.
> Improve heuristics for inline config

- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/ignore_nulls.sql
- test/fixtures/dialects/tsql/ignore_nulls.yml
Adding the unreserved keyword NULLS to the TSQL dialect. Fixes #5212
> TSQL: add missing unreserved keyword NULLS (#5212)

- docs/source/guides/contributing/rules.rst
- plugins/sqlfluff-plugin-example/test/rules/rule_test_cases_test.py
- src/sqlfluff/utils/testing/rules.py
- test/conftest.py
- test/rules/yaml_test_cases_test.py
- test/testing_test.py
I'd like to do a bit of an overhaul of the yaml rule test cases to eventually support a wider range of features. In particular specifying multiple rules in one test.
Rather than do that in one big PR, I intend to do it bit by bit in more manageable pieces. This PR is the first one of those.
This PR:
* Is _mostly_ documentation and docstrings. A lot of the methods and classes in this part of the codebase aren't particularly well documented, and I've added most of this just to help _myself_ as I go further with the refactor because I didn't know what each method did.
* It moves the main entry point for rules testing to a method on the `RuleTestCase` called `.evaluate()`. It's currently just a thin shim onto `rules__test_helper()` but that will change in the next step.
* It removes the …
> Documentation and small overhaul of parametrized rule test cases

- docs/source/conf.py
- docs/source/guides/contributing/architecture.rst
- docs/source/guides/contributing/dialect.rst
- docs/source/guides/index.rst
- docs/source/guides/setup/developing_custom_rules.rst
- docs/source/guides/troubleshooting/how_to.rst
- plugins/sqlfluff-plugin-example/README.md
This adds two more guides in the guides section:
- One on how to troubleshoot SQLFluff (this one probably needs extending at some point, but I think it's probably a good starting set of steps).
- One on how to develop custom rules (where I've also fleshed out the `README.md` file for the example plugin).
I think the latter should resolve #5655 and resolve #2352.
> Guides for custom rules and for troubleshooting

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_virtual_table_check.sql
- test/fixtures/dialects/sqlite/create_virtual_table_check.yml
Support for parsing `CREATE VIRTUAL TABLE` statements in SQLite.
Fixes #6403 
None
- Other.
> SQLite : Add `CREATE VIRTUAL TABLE`  Statement

- src/sqlfluff/rules/references/RF01.py
- test/fixtures/rules/std_rule_cases/RF01.yml
- if only one table unaliased is referenced in query and dialect supports dot-struct-access, skip check
- add ability to inject _implicit_ references, implement them for sqlite triggers
- fixes #6033 and #6402
No.
- Other.
> RF01: refine support for dialects with dot access syntax

- src/sqlfluff/core/rules/base.py
- test/fixtures/rules/std_rule_cases/CP04.yml
Very minor bugfix. The current rule docs for CP04 don't show any configuration values. That's not because they're not there, but it's because they're totally inherited. That also means it's ambiguous as to which capitalisation policy that rule uses (as I found out on a project recently 🤦 ).
This fixes the docs, and add more test cases for CP04 to show it uses the root capitalisation policy.
No actual functionality changes here.
> Fix docs for CP04 config and add test cases

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/set_statements.sql
- test/fixtures/dialects/tsql/set_statements.yml
Extends `ExpressionSegment` in TSQL to include the `NEXT VALUE FOR` as an expression, as it returns a scalar value.
No known side-effects
- Other.
> TSQL: allow `NEXT VALUE FOR` use as expression

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/insert_overwrite_directory.yml
- test/fixtures/dialects/sparksql/select_hints.yml
- test/fixtures/dialects/sparksql/select_sort_by.yml
- test/fixtures/rules/std_rule_cases/LT01-functions.yml
> Sparksql: Fix hint function for proper spacing

- src/sqlfluff/dialects/dialect_trino.py
Fixes #5875
Temporary and Transient are both unsupported in Trino. I've tested this locally, and it now compiles.
No
- Other.
> Trino: Remove TemporaryTransientGrammar

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/copy_into_table.sql
- test/fixtures/dialects/snowflake/copy_into_table.yml
> Snowflake: Allow literals in match_by_column_name

- src/sqlfluff/utils/analysis/select.py
- test/fixtures/rules/std_rule_cases/RF02.yml
This adds Databricks as a dialect with lambda functions.
- fixes #6436
No
- Other.
> RF02: Allows for lambda functions in Databricks

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/create_table_datasource.sql
- test/fixtures/dialects/sparksql/create_table_datasource.yml
> Sparksql: Fix ordering of create table options

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/select.sql
- test/fixtures/dialects/postgres/select.yml
Fixes #6425 
Also adds the fetch clause.
No
- Other.
> Postgres: Fix Select statement ordering

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/create_table_keys.sql
- test/fixtures/dialects/bigquery/create_table_keys.yml
This allows for the column level definition for a key constraint e.g. `PRIMARY KEY NOT ENFORCED` or `REFERENCES table_name(column_name) NOT ENFORCED`
- fixes #6462
None
- Other.
> Bigquery: Support column level key definitions

- docs/source/configuration/rule_configuration.rst
- src/sqlfluff/core/errors.py
- test/cli/commands_test.py
- test/fixtures/cli/warning_name_a.sql
According to the official documentation, rules can be downgraded to warnings by specifying their rule codes. However, there is IHMO an inconsistency in how rules are handled for exclusions versus warnings. Currently:
- Rules can be excluded using either rule code or rule name.
- Rules can only be downgraded to warnings using rule code.
This PR addresses this inconsistency by extending the configuration to allow warnings to be specified via both rule code and rule name. This aligns the handling of warnings with the existing behavior for `exclude_rules`.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML …
> Rule names in warnings logic

- src/sqlfluff/dialects/dialect_databricks.py
- src/sqlfluff/dialects/dialect_sparksql.py
- src/sqlfluff/dialects/dialect_sparksql_keywords.py
- test/fixtures/dialects/databricks/set_variable.sql
- test/fixtures/dialects/databricks/set_variable.yml
- test/fixtures/dialects/sparksql/set_variable.sql
- test/fixtures/dialects/sparksql/set_variable.yml
* Added grammar for `Set variable` statements in SparkSQL (Preview of Spark 4.0.0.) and Databricks (already implemented)
* Added tests
* fixes #6463 
- Other.
> fixes #6463: Set Variable Parsing for SparkSQL and Databricks

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/dialects/dialect_mysql.py
- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/mariadb/json.yml
- test/fixtures/dialects/mysql/json.yml
- test/fixtures/dialects/sqlite/json_operators.yml
- test/fixtures/rules/std_rule_cases/LT01-operators.yml
> Standardise json operator spacing between dialects

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/alter_view.sql
- test/fixtures/dialects/hive/alter_view.yml
Add 'ALTER VIEW' query for the two supported operations: 
1. updating schema via 'AS SELECT...',
2. setting table properties
Fixes #6476 
None
- Other.
> Hive: Add 'ALTER VIEW' query grammar

- src/sqlfluff/rules/convention/__init__.py
- teensy docs whitespace change
- "literalin the file" -> "literal in the file" 
Missing whitespace was below: 
Note: I haven't built / tested this locally but it looks pretty shallow.. 
- Other.
> [docs] Update missing convention whitespace for CV10

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/describe_volume.yml
fix: databricks describe volume recognition
Added `at=0` so that the Databricks parser doesn't mistakenly recognize `Describe Volume` as a `Describe Table` query.`
None that I am aware of.
- Other.
> fix: databricks describe volume recognition

- src/sqlfluff/rules/references/RF01.py
- test/fixtures/rules/std_rule_cases/RF01.yml
fixes #6551 
DuckDB, as described [on their page about the DuckDB struct type
](https://duckdb.org/docs/sql/data_types/struct#retrieving-from-structs), allows for "dot"-based access to struct fields. 
For example, the following query returns 'there' when executed by DuckDB:
```sql
SELECT ex.x.hi
FROM (SELECT { 'hi': 'there' } AS x) AS ex
```
Effectively disables non-trivial RF01 checks for all DuckDB queries. As far as I can tell, this is in-line with our current strategy for other languages that allow "dot"-based access, since otherwise we generate far too many false-positives to be useful. …
> Add DuckDB to RF01 filter for dialects with dot-access

- src/sqlfluff/rules/aliasing/AL04.py
- test/fixtures/rules/std_rule_cases/AL04.yml
This now causes AL04 to check any reference or aliases that are within a subquery to not be a duplicated name with any elements in the parent query.
- makes progress on #6326
None
- Other.
> AL04: Check for duplicates in subquery aliases and table references

- src/sqlfluff/rules/structure/ST09.py
- test/fixtures/rules/std_rule_cases/ST09.yml
This adds support for the `<=>` operator in the ST09 rule. More generally it prevents some comparison operators from flipping that are not strictly the greater than or less than signs.
- fixes #6560
None
- Other.
> ST09: Handle `lt_eq_gt` operator

- src/sqlfluff/rules/structure/ST03.py
- src/sqlfluff/utils/analysis/query.py
- test/fixtures/rules/std_rule_cases/ST03.yml
This allows for quotes to be in either the CTE name or the table_expression that references it (mix and match).
- fixes #6556
This touches the `Query` class and removes quotes from the `ctes` dictionary keys. This may reveal other opportunities to apply the quote change to other rules, but a cursory glance determined minimal impact.
- Other. …
> ST03: Handle quotes in CTE names

- src/sqlfluff/rules/structure/ST11.py
- test/fixtures/rules/std_rule_cases/ST11.yml
This fixes a number of issues with ST11:
- wildcard usage
- table functions such as `UNNEST` or `LATERAL FLATTEN`
- implicit cross joins (legacy comma joins)
Issues:
- fixes #6496 
- fixes #6511 
- fixes #6558
None
- Other.
> ST11: Table and wildcard reference fixes

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/substitution_variable.sql
- test/fixtures/dialects/oracle/substitution_variable.yml
> Add support for Oracle SQL*Plus substitution variable `&`.

- src/sqlfluff/core/templaters/builtins/dbt.py
- test/core/templaters/jinja_test.py
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_zip.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_zip.yml
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_zip_strict.sql
- test/fixtures/templater/jinja_c_dbt/dbt_builtins_zip_strict.yml
- Add `zip` and `zip_strict` dbt built-in jinja2 functions.  (from the official doc: https://docs.getdbt.com/reference/dbt-jinja-functions/zip)
- These missing functions will break the linting even even when we configure `apply_dbt_builtins=true`
```bash
sqlfluff lint --templater=jinja --dialect bigquery --ignore="templating, parsing" -<<EOF
{% set cols = ['c1', 'c2', 'c3'] %}
{% set tables = ['alice', 'bob', 'tim'] %}
{% for (c, t) in zip(cols, tables) %}
select
{{ c }} as col
from
{{ t }}
{% if not loop.last %}
union all
{% endif %}
{% endfor %}
EOF
```
This will throw a `ValueError` because zip is not a built-in jinja2 function. …
> Add zip and zip_strict dbt jinja2 functions

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/alter_foreign_table.sql
- test/fixtures/dialects/postgres/alter_foreign_table.yml
> Add support for Postgres `ALTER FOREIGN TABLE` statement.

- src/sqlfluff/rules/references/RF02.py
- test/fixtures/rules/std_rule_cases/RF02.yml
This handles a few edges cases with RF02 namely if a subquery is in the `FROM` or `JOIN` clause where external references are not allowed. Added additional test cases for some other subquery related failures.
- fixes #6598
- makes progress on #6326
None
- Other.
> RF02: Handle additional edge cases with subqueries

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_trigger.yml
- test/fixtures/dialects/sqlite/update.yml
This adds the `set_clause_list` parsing grammar to sqlite's UPDATE statement.
- fixes #6602
None
- Other.
> Sqlite: Added `set_clause_list` to `UPDATE` statement

- src/sqlfluff/dialects/dialect_hive.py
- test/fixtures/dialects/hive/double_equals.sql
- test/fixtures/dialects/hive/double_equals.yml
Allows the use of a `==` in the hive sql dialect as a synonym of `=` per [https://cwiki.apache.org/confluence/display/Hive/Hive+Operators]()
fixes #6622 
None that I'm aware of
- Other.
> Allow double equals in hive dialect

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_procedure.sql
- test/fixtures/dialects/postgres/create_procedure.yml
> Add support for `WithCompoundStatementSegment` in procedures in Postgres

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/alter_event.sql
- test/fixtures/dialects/mysql/alter_event.yml
- test/fixtures/dialects/mysql/create_event.sql
- test/fixtures/dialects/mysql/create_event.yml
- test/fixtures/dialects/mysql/drop_event.sql
- test/fixtures/dialects/mysql/drop_event.yml
> Add support for `EVENT` statements in MySQL.

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_clickhouse.py
- test/fixtures/cli/passing_timing.sql
- test/fixtures/dialects/clickhouse/in_implicit_array_tuple.sql
- test/fixtures/dialects/clickhouse/in_implicit_array_tuple.yml
- test/fixtures/dialects/clickhouse/in_operator.yml
- test/fixtures/dialects/clickhouse/in_table_cte.sql
- test/fixtures/dialects/clickhouse/in_table_cte.yml
- Added support for queries like `WHERE id IN (1,2)`, `WHERE id IN [1,2]`, `WHERE id IN table_name`, and `WHERE id IN cte`, where `table_name` and `cte` contain only a single column.  
- Exported `TupleSegment` to the ANSI dialect to enable passing it to the ClickHouse dialect, as tuples are supported in ANSI.
- ANSI supports `IN tuple`, but its implementation differs from ClickHouse.  
- This leads to inconsistent parsing of expressions like `IN (1,2)`:  
- **ANSI Parsing:**
```
bracketed:
- start_bracket: (
- numeric_literal: '1'
- comma: ','
- numeric_literal: '2'
- end_bracket: )
```
- **ClickHouse Parsing:**
```
tuple:
bracketed:
- start_bracket: (
- numeric_literal: '1'
- comma: ','
- numeric_literal: '2'
- end_bracket: )
```
- Explicitly adding `tuple` to …
> IN TABLE/CTE and implicit Array, Tuple support for ClickHouse

- src/sqlfluff/rules/aliasing/AL03.py
- test/fixtures/rules/std_rule_cases/AL03.yml
This now correctly lints missing aliases for AL03 when the `select_clause_element` is a subquery.
- fixes #6650
None
- Other.
> AL03: Lint for missing aliases on subqueries

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/alter_table.sql
- test/fixtures/dialects/oracle/alter_table.yml
> Fix check constraints in `ALTER TABLE` statements in Oracle.

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/delete.sql
- test/fixtures/dialects/postgres/delete.yml
> Adds support for `JoinClauseSegment` in `DeleteStatementSegment` in Postgres

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/json_operators.sql
- test/fixtures/dialects/postgres/json_operators.yml
> Add support for `key: value` syntax in functions in Postgres.

- src/sqlfluff/diff_quality_plugin.py
- src/sqlfluff/utils/testing/cli.py
- test/cli/commands_test.py
https://github.com/pallets/click/pull/2523 introduced changes to `click.testing` that broke some unit tests in SQLFluff: `mix_stderr=False` is now effectively the default and can no longer be specified explicitly.
In addition, https://github.com/pallets/click/pull/1489 caused the diff-quality plugin to incorrectly believe that SQLFluff is not installed.
Although this Click version hasn't been fully released yet, this adjusts SQLFluff to work with both old and new versions.
Fixes: #6676
- Full …
> Fix tests with Click 8.2

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/create_table_complex_datatypes.sql
- test/fixtures/dialects/sparksql/create_table_complex_datatypes.yml
Fixes #6699. The colon is optional in Spark SQL. See https://docs.databricks.com/aws/en/sql/language-manual/data-types/struct-type.
In addition to the Databricks documentation, I've also confirmed in vanilla Spark SQL that these create table statements are valid.
I wasn't able to confirm whether this is true for Hive, so I've copied over the Hive implementation and changed the colon to optional.
N/A
- Other. …
> SparkSQL: Make colon optional in `STRUCT` datatype

- src/sqlfluff/dialects/dialect_snowflake.py
Just removing the comment:
As it was done in #6654 
It was a bit confusing. 
no 
- Other.
> Cleaning: Remove Todo set tag from Snowflake ALTER TABLE statement

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_user.sql
- test/fixtures/dialects/snowflake/create_user.yml
fixes #6712 
Allow parsing of statements like:
```sql
CREATE USER user1
RSA_PUBLIC_KEY = '<PUBLIC RSA KEY IN BASE64>';
```
For the snowflake dialect: <https://docs.snowflake.com/en/sql-reference/sql/create-user>
Please review, I'll be happy to contribute to snowflake dialect.
> Fill in gap in parsing `create user rsa_public_key=...` / snowflake

- tox.ini
> Fix tox config so that it supports spaces in the path name (#6726)

- .github/workflows/ci-tests.yml
- CONTRIBUTING.md
- docs/source/guides/contributing/dialect.rst
- docs/source/guides/contributing/git.rst
- plugins/sqlfluff-plugin-example/pyproject.toml
- plugins/sqlfluff-templater-dbt/pyproject.toml
- pyproject.toml
- src/sqlfluff/__init__.py
- src/sqlfluff/core/config/loader.py
- tox.ini
Python 3.8 hit EOL in October 2024. 5 months on is probably a good time to drop support for it. It allows us to drop a dependency, there's probably some other code clean up we can do without it. This'll trigger a minor release.
About 2% of our downloads are still on Python 3.8. But this still seems like a reasonable time to stop developing new features for it.
- Other.
- Created …
> Drop support for Python 3.8

- src/sqlfluff/dialects/dialect_duckdb.py
- test/fixtures/dialects/duckdb/insert.sql
- test/fixtures/dialects/duckdb/insert.yml
Fixes #6649 
Adding the InsertStatementSegment for Duckdb specific syntax following documentation:
https://duckdb.org/docs/stable/sql/statements/insert.html
- Other.
> Duckdb: Adding InsertStatementSegment for Duckdb specifics

- src/sqlfluff/core/parser/segments/base.py
- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/rules/std_rule_cases/RF02.yml
~~Previously, the `get_alias` function was getting the first alias found in a depth-first manner, which was not always the correct alias to include when a subquery may have had an internal `alias_expression`. This adds a breadth-first crawler and uses that to grab the topmost, first alias.~~
Prevent `get_alias` from recursively crawling through subqueries.
- fixes #6389
None
- Other. …
> Fix: column aliases should find the topmost alias

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/rules/structure/ST11.py
- test/fixtures/rules/std_rule_cases/RF01.yml
- test/fixtures/rules/std_rule_cases/ST11.yml
Fixes #5356
Not that I can see.
- Other.
> Fix rule failures for MySQL/MariaDB with backticked identifiers

- src/sqlfluff/core/config/toml.py
- test/cli/commands_test.py
- util.py
As part of the TOML spec, they should always be utf-8 encoded.
- fixes #6208
None
- Other.
> Always use utf-8 encoding for toml files

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_task.sql
- test/fixtures/dialects/snowflake/create_task.yml
Changes limited to `create task` in the snowflake dialect
* Enables the use of reference variables in the `warehouse` and `schedule` parameters.
* And adds LOG_LEVEL
- Other.
> feat(snowflake): allow reference variables in create task 

- src/sqlfluff/core/default_config.cfg
- src/sqlfluff/rules/layout/LT15.py
- src/sqlfluff/rules/layout/__init__.py
- test/fixtures/rules/std_rule_cases/LT15.yml
This PR adds a long-requested rule. It allows the control of how many blank lines there can be in a row. It is configurable to different values inside and outside of a statement.
This changes the default rule set - and so should trigger a minor release.
Fixes #2634 
No
- Other.
> New Rule: LT15

- src/sqlfluff/rules/structure/ST11.py
- test/fixtures/rules/std_rule_cases/ST11.yml
Builds on #6702 to also check quoted table names.
- fixes #6741
None
- Other.
> ST11: Fix quoted table name comparisons

- src/sqlfluff/dialects/dialect_snowflake.py
- src/sqlfluff/utils/analysis/select.py
- test/fixtures/dialects/snowflake/select_higher_order_function.yml
- test/fixtures/rules/std_rule_cases/RF02.yml
- test/fixtures/rules/std_rule_cases/RF03.yml
fixes #6683
Allows RF02 to ignore anonymous parameters for Snowflake lambda expressions used in functions `transform`, `filter`, `reduce`.
Dialect parsing implementation for lambdas in Snowflake was different than for trino and duckdb.
Made changes to snowflake tokens to match trino and duckdb implementation, this allows for minimal change in rule checking.
With the modified tokens, simply adding snowflake to the list of dialects that support lambda expressions in `analysis/select.py` fixes RF02 to no longer trigger incorrectly.
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files can be auto generated …
> RF02: do not trigger on snowflake lambda anonymous parameters

- src/sqlfluff/dialects/dialect_sparksql.py
- test/fixtures/dialects/sparksql/structure_accessor.sql
- test/fixtures/dialects/sparksql/structure_accessor.yml
Support the dot operator for SparkSQL and Databricks.
- fixes #5593
None
- Other.
> SparkSQL/Databricks: Support dot sign operator

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/create_table.sql
- test/fixtures/dialects/postgres/create_table.yml
Postgres reserved keywords were being set with ansi reserved keywords and updated with dialect reserved keywords. So `INTERVAL`, for example, were considered reserved despite it's `non-reserved-(cannot-be-function-or-type)`.
Closes #4893
- Other.
> Fix reserved keywords in Postgres.

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_external_volume.yml
- test/fixtures/dialects/snowflake/alter_role.yml
- test/fixtures/dialects/snowflake/alter_storage_integration.yml
- test/fixtures/dialects/snowflake/alter_tag.yml
- test/fixtures/dialects/snowflake/create_authentication_policy.yml
- test/fixtures/dialects/snowflake/create_database_role.yml
- test/fixtures/dialects/snowflake/create_external_volume.yml
- test/fixtures/dialects/snowflake/create_masking_policy.yml
- test/fixtures/dialects/snowflake/create_network_policy.yml
- test/fixtures/dialects/snowflake/create_password_policy.yml
- test/fixtures/dialects/snowflake/create_role.yml
- test/fixtures/dialects/snowflake/create_row_access_policy.yml
- test/fixtures/dialects/snowflake/create_tag.yml
Use the CommentEqualsClauseSegment everywhere where it should be used 
- Other.
> Housekeeping: snowflake use CommentEqualsClauseSegment everywhere

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/alter_pipe.sql
- test/fixtures/dialects/snowflake/alter_pipe.yml
> add ERROR_INTEGRATION to AlterPipeSegment

- .github/workflows/publish-sqlfluff-docker-image-to-dockerhub.yaml
This is a best effort on deploying the release docker images to ghcr.io in addition to docker hub.
The instructions have been replicated from [here](https://docs.github.com/en/actions/use-cases-and-examples/publishing-packages/publishing-docker-images#publishing-images-to-docker-hub-and-github-packages) but still include the cached testing step.
- resolves #6677
This change can't be tested without an actual release (maybe 3.4.0 can be that?) so it may need a revisit if something has been incorrectly configured. …
> CI: mirror image deployment to ghcr.io

- src/sqlfluff/dialects/dialect_bigquery.py
- test/fixtures/dialects/bigquery/select_except.sql
- test/fixtures/dialects/bigquery/select_except.yml
- test/fixtures/dialects/bigquery/select_except_replace.yml
- test/fixtures/dialects/bigquery/select_replace.yml
- test/fixtures/rules/std_rule_cases/AL02.yml
This makes BigQuery's select replace syntax require the `AS` keyword and not remove it from AL02 when set to implicit.
- fixes #6775
None
- Other.
> BigQuery: Make select replace `AS` not optional

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/unnest_with_ordinality.sql
- test/fixtures/dialects/trino/unnest_with_ordinality.yml
Fixes #5384
Trino Dialect - Parse UNNEST (...) WITH ORDINALITY
I added tests for parsing in Trino dialects directory to confirm the parsing error is resolved.
- Other.
> Trino Dialect - Parse UNNEST (...) WITH ORDINALITY

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/openrowset.sql
- test/fixtures/dialects/tsql/openrowset.yml
Add support for the WITH clause for an OPENROWSET in T-SQL as used in Azure Synapse Analytics. The syntax documentation can be found [here](https://learn.microsoft.com/en-us/azure/synapse-analytics/sql/develop-openrowset#syntax) 
No
- Other.
> Add support for the WITH clause for an OPENROWSET in T-SQL

- src/sqlfluff/dialects/dialect_clickhouse.py
- src/sqlfluff/dialects/dialect_clickhouse_keywords.py
- test/fixtures/dialects/clickhouse/alter_table.sql
- test/fixtures/dialects/clickhouse/alter_table.yml
- test/fixtures/dialects/clickhouse/complex_table_definition.sql
- test/fixtures/dialects/clickhouse/complex_table_definition.yml
- test/fixtures/dialects/clickhouse/create_materialized_view.sql
- test/fixtures/dialects/clickhouse/create_materialized_view.yml
- test/fixtures/dialects/clickhouse/create_table.yml
- test/fixtures/dialects/clickhouse/tuple_datatype.yml
Adds support 
* for more complex data types in clickhouse (Enum, Tuple, Nested, Array, JSON) 
* ALIAS columns referencing dictionaries and using other functions.
* ALTER TABLE MODIFY QUERY statemetns
- Other.
> Clickhouse: support more complex types and functions in table definition

- src/sqlfluff/rules/convention/CV12.py
- test/fixtures/dialects/tsql/outer_apply.sql
- test/fixtures/dialects/tsql/outer_apply.yml
- test/fixtures/dialects/tsql/select_cross_apply.sql
- test/fixtures/dialects/tsql/select_cross_apply.yml
- test/fixtures/rules/std_rule_cases/CV12.yml
In TSQL there is the CROSS APPLY and OUTER APPLY joins that don't have an ON clause. CV12 was throwing error for OUTER APPLY joins.
Fixes [#6825](https://github.com/sqlfluff/sqlfluff/issues/6825)
- Other.
> CV12 rule to exclude APPLY clause from the rule

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/select_exclude.sql
- test/fixtures/dialects/redshift/select_exclude.yml
Add support for the [`SELECT * EXCLUDE` syntax](https://docs.aws.amazon.com/redshift/latest/dg/r_EXCLUDE_list.html) introduced in [Amazon Redshift patch 188](https://docs.aws.amazon.com/redshift/latest/mgmt/cluster-versions.html#cluster-version-188):
```sql
-- EXCLUDE column-name, ... | ( column-name, ... )
-- For example:
SELECT * EXCLUDE col1 FROM table1;
SELECT * EXCLUDE col1, col2 FROM table1;
SELECT * EXCLUDE (col1) FROM table1;
SELECT * EXCLUDE (col1, col2) FROM table1;
```
See https://docs.aws.amazon.com/redshift/latest/dg/r_EXCLUDE_list.html
- `.sql`/`.yml` parser test cases in `test/fixtures/dialects` (note YML files …
> Redshift: Add support for `select exclude` syntax

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/json_functions.sql
- test/fixtures/dialects/tsql/json_functions.yml
fixes #6843
Adds support to tsql for JSON_ARRAY and JSON_OBJECT functions following syntax from documentation:
https://learn.microsoft.com/en-us/sql/t-sql/functions/json-array-transact-sql
https://learn.microsoft.com/en-us/sql/t-sql/functions/json-object-transact-sql
No
- Other.
> TSQL: Add support for JSON_ARRAY and JSON_OBJECT

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/collections.yml
- test/fixtures/dialects/oracle/create_procedure.yml
- test/fixtures/dialects/oracle/forall.yml
- test/fixtures/dialects/oracle/if.yml
- test/fixtures/dialects/oracle/select.sql
- test/fixtures/dialects/oracle/select.yml
> Fixes Oracle parsing tree with `/` operator.

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/dialects/sqlite/create_table_unsigned.sql
- test/fixtures/dialects/sqlite/create_table_unsigned.yml
Like MySQL, allow the unsigned keyword to trail the data type identifier. Fixes #6844
I don't anticipate side effects.
- Other.
> SQLite: allow trailing unsigned

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/drop_iceberg_table.sql
- test/fixtures/dialects/snowflake/drop_iceberg_table.yml
Added a new segment `DropIcebergTableStatementSegment` in the Snowflake dialect to support parsing of `DROP ICEBERG TABLE [IF EXISTS] <table_name>` syntax.
Changes made:
- Defined `DropIcebergTableStatementSegment` with appropriate `match_grammar` using `Sequence`, `Ref`, and `IfExistsGrammar`.
- Registered the new segment via `snowflake_dialect.add(...)`.
This change resolves issues with SQLFluff failing to parse valid Snowflake statements involving Iceberg tables, such as:
DROP ICEBERG TABLE IF EXISTS SAMPLE_DEV.SAMPLE.CASH;
Helps avoid parse errors like:
PRS | Found unparsable section: 'DROP ICEBERG TABLE IF EXISTS ...'
- …
> feat(snowflake): add support for 'DROP ICEBERG TABLE' statement

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/athena/select_cast_withtimezone.yml
- test/fixtures/dialects/mariadb/create_table_datetime.yml
- test/fixtures/dialects/mysql/create_table_datetime.yml
- test/fixtures/dialects/postgres/datatypes.yml
- test/fixtures/dialects/trino/timestamp_resolutions.yml
- test/fixtures/rules/std_rule_cases/LT01-brackets.yml
This corrects where some datatypes that had bracketed parts to be disjointed when LT01 was ran.
- fixes #6846
None
- Other.
> LT01: Brackets should touch datatypes

- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_bigquery_keywords.py
- test/fixtures/dialects/bigquery/pipe_statement.sql
- test/fixtures/dialects/bigquery/pipe_statement.yml
Full support of Pipe syntax as per https://cloud.google.com/bigquery/docs/reference/standard-sql/pipe-syntax
Fixes #6630
No
- Other.
> Bigquery: Support Pipe statements

- src/sqlfluff/utils/testing/cli.py
With the release of click 8.2.0, mix_stderr has been removed. However to continue supporting older version (namely for python 3.9) we need to ignore the missing argument where the signature is already checked in the prior line.
None
- Other.
> CI: Ignore mypy call-arg for CliRunner mix_stderr

- src/sqlfluff/dialects/dialect_mysql.py
- test/fixtures/dialects/mysql/collate.sql
- test/fixtures/dialects/mysql/collate.yml
Supports `COLLATE` expressions in MySQL.
- fixes a separate issue noted in #5754
None
- Other.
> MySQL: Add collate expressions

- test/core/parser/lexer_test.py
While running the lexer test in rust mode, these `RawFileSlice` tags came across with type errors. This fixes the order of the `block_idx` and `tag`.
None
- Other.
> Fix RawFileSlice idx and tags in lexer_test

- pyproject.toml
While #6676 has a fix for Click 8.2.0, since Click can have breaking changes in minor releases, it is probably a good idea to explicitly pin the Click version in `pyproject.toml` to prevent issues like #6888 from affecting older releases in the future. Then the upper bound can be increased along with any changes needed.
https://github.com/pallets/click/issues/2909#issuecomment-2874389113
Part of #6888
(while this won't retroactively fix issues with older releases, it should help avoid similar problems in the future)
When updating for newer Click versions, the upper bound will need to be updated along with any changes needed to code / tests.
IMO, the project might want to consider at least some basic version constraints in other dependent packages as well.
- Included test cases to …
> Pin to Click < 8.3.0

- src/sqlfluff/rules/structure/ST05.py
- test/fixtures/rules/std_rule_cases/ST05.yml
This corrects where it was assumed that a `table_expression` would always have a `bracketed` section. Now, we skip over non-bracketed table expressions such as functions.
- fixes #6777
None
- Other.
> ST05: Ignore table_expressions that aren't bracketed

- src/sqlfluff/dialects/dialect_redshift.py
Update the "Redshift Names & Identifiers Docs" link to point to the correct AWS Redshift documentation.
Currently the link incorrectly points to the Apache Spark SQL reference.
No.
- Other.
> Redshift: Fix documentation link

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/select_from_read_file.sql
- test/fixtures/dialects/databricks/select_from_read_file.yml
Add `STREAM` as a pre table keyword for the databricks dialect as this is causing parsing issues due to the parser mistaking the keyword and function as a table name and alias:
Taking this example query: `SELECT * FROM STREAM read_files('gs://my-bucket/avroData', includeExistingFiles => false);`
The parser was producing the following:
```
[L:  1, P: 10]      |            from_clause:
// Removed
[L:  1, P: 15]      |                                naked_identifier:             'STREAM'
[L:  1, P: 21]      |                        whitespace:                           ' '
[L:  1, P: 22]      |                        alias_expression:
[L:  1, P: 22]      |                            naked_identifier:                 'read_files'
```
After this change the output is:
```
[L:  1, P: 10]      | …
```
> Databricks: Prevent parsing error when reading from a streaming file

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/select.sql
- test/fixtures/dialects/tsql/select.yml
> TSQL: fix `USER` (bare function) unparsable

- src/sqlfluff/dialects/dialect_redshift.py
- test/fixtures/dialects/redshift/alter_table.sql
- test/fixtures/dialects/redshift/alter_table.yml
* Add SET LOCATION action to AlterTableActionSegment in Redshift dialect
* Add test case for ALTER TABLE ... SET LOCATION 's3://bucket/folder/'
* Supports external table location changes in Redshift
* Updated corresponding YAML test fixture
This enables parsing of ALTER TABLE table_name SET LOCATION 'location_string' syntax which is used for modifying external table locations in Amazon Redshift.
AWS documentation:
https://docs.aws.amazon.com/redshift/latest/dg/r_ALTER_TABLE.html
Summary in commit message.
No
- [✅] Please confirm you have completed any of the necessary steps below. …
> feat(redshift): add support for ALTER TABLE SET LOCATION syntax

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/returning_into.sql
- test/fixtures/dialects/oracle/returning_into.yml
> Adds support for `RETURNING INTO` clause in `INSERT`, `UPDATE`, `DELETE` and `MERGE` statements in Oracle.

- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/dialects/dialect_tsql_keywords.py
- test/fixtures/dialects/tsql/create_table_graph.sql
- test/fixtures/dialects/tsql/create_table_graph.yml
This PR is adding support for graph tables in TSQL. These use special syntax at table creation and a specific constraint for such tables.
* Add required keywords
* Add graph table syntax variation with AS NODE and AS EDGE reusing as much as possible
* Add related constraints
PS: My first contribution to this repo, happy to take advice on further improvements in this PR.
No
- Other.
- …
> TSQL: Add support for CREATE TABLE GRAPH statements

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/select.sql
- test/fixtures/dialects/tsql/select.yml
This PR extends unquoted (naked) identifiers in T-SQL to include Unicode letters as well.
Fixes #6710 
N/A
- Other.
> TSQL: add support for extended Unicode characters in identifiers

- src/sqlfluff/dialects/dialect_tsql.py
- test/fixtures/dialects/tsql/alter_table.sql
- test/fixtures/dialects/tsql/alter_table.yml
Allows for a DROP CONSTRAINT IF EXISTS sequence to te parsed correctly in tsql. 
fixes #6956
Does not seem likely
- Other.
> Tsql add alter constraint if exists

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/ansi/merge_into.sql
- test/fixtures/dialects/ansi/merge_into.yml
Fixes https://github.com/sqlfluff/sqlfluff/issues/6897. Adds `MERGE` to the supported list of statements that can come after a CTE. Added a test to verify the change.
Reference: https://www.datacamp.com/tutorial/cte-sql
I discovered this issue when trying to parse production Spark SQL code that is currently running.
N/A
- Other. …
> ANSI: Support CTEs in Merge

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/json_object.sql
- test/fixtures/dialects/oracle/json_object.yml
Closes #6966 
Test examples from [Oracle docs](https://docs.oracle.com/en/database/oracle/oracle-database/23/sqlrf/JSON_OBJECT.html)
- Other.
> Adds support for `json_object` syntax in Oracle.

- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/create_table.sql
- test/fixtures/dialects/snowflake/create_table.yml
This fixes `CREATE TABLE` statements that have `COLLATE` and aliases specified.
- fixes #6917 
None
- Other.
> Snowflake: fix collate grammar with aliases

- src/sqlfluff/cli/commands.py
- src/sqlfluff/cli/formatters.py
- src/sqlfluff/core/default_config.cfg
- test/cli/commands_test.py
This adds support for the no-color.org `NO_COLOR` environment variable to disable color output.
None
- Other.
> CLI: Add support for the `NO_COLOR` environment variable

- src/sqlfluff/rules/convention/CV12.py
- src/sqlfluff/utils/testing/rules.py
- test/fixtures/rules/std_rule_cases/AL05_CV12.yml
This stops AL05 from deleting references that may have been moved around from the `where_clause` into the `join_on_condition`.
- fixes #6946
None
- Other.
> CV12 and AL05: Prevent AL05 from deleting rewritten CV12 references

- src/sqlfluff/dialects/dialect_trino.py
- test/fixtures/dialects/trino/alter_table.yml
- test/fixtures/dialects/trino/array.yml
- test/fixtures/dialects/trino/create_table.sql
- test/fixtures/dialects/trino/create_table.yml
- test/fixtures/dialects/trino/integer_types.yml
- test/fixtures/dialects/trino/row_datatype.yml
- test/fixtures/dialects/trino/timestamp_resolutions.yml
Add support for DataType like `MAP(VARCHAR, INTEGER)`.
- Other.
> Trino: support map data type

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_snowflake.py
- test/fixtures/dialects/snowflake/select.sql
- test/fixtures/dialects/snowflake/select.yml
Fixes early termination of a number of clauses where a non-reserved keyword `LIMIT` may exist as a column name.
- fixes #5420
- fixes #6991
None
- Other.
> Snowflake: fix parsing `LIMIT` when not a limit clause

- src/sqlfluff/dialects/dialect_postgres.py
- test/fixtures/dialects/postgres/alter_foreign_table.sql
- test/fixtures/dialects/postgres/alter_foreign_table.yml
Adds support for RENAME in ALTER FOREIGN TABLE in Postgres, which couldn't be parsed at all before.
https://www.postgresql.org/docs/current/sql-alterforeigntable.html
I can't think of any.  This failed as unparseable before.
> Add support for RENAME in ALTER FOREIGN TABLE in Postgres

- src/sqlfluff/rules/structure/ST09.py
- test/fixtures/rules/std_rule_cases/ST09.yml
This allows for quoted and non-quoted (naked) identifiers between tables or their aliases in the from/join clauses and the `join_on_condition`. Namely you can have `FROM foo JOIN bar on "bar".id = "foo".id` auto fixed.
- fixes #7016 
None
- Other.
> ST09: Handle mixed quoted table aliases

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/alter_table.sql
- test/fixtures/dialects/oracle/alter_table.yml
Add `ALTER TABLE ... RENAME CONSTRAINT` syntax for oracle
It makes progress on #7044.
No.
- Other.
> Oracle: Support `ALTER TABLE ... RENAME CONSTRAINT`

- src/sqlfluff/dialects/dialect_sqlite.py
- test/fixtures/linter/autofix/sqlite/001_trigger_indentation/after.sql
- test/fixtures/linter/autofix/sqlite/001_trigger_indentation/before.sql
- test/fixtures/linter/autofix/sqlite/001_trigger_indentation/test-config.yml
- test/fixtures/linter/autofix/sqlite/002_trigger_complex_indentation/after.sql
- test/fixtures/linter/autofix/sqlite/002_trigger_complex_indentation/before.sql
- test/fixtures/linter/autofix/sqlite/002_trigger_complex_indentation/test-config.yml
- test/fixtures/linter/autofix/sqlite/003_sqlite_specific_indentation/after.sql
- test/fixtures/linter/autofix/sqlite/003_sqlite_specific_indentation/before.sql
- test/fixtures/linter/autofix/sqlite/003_sqlite_specific_indentation/test-config.yml
- test/fixtures/linter/autofix/sqlite/004_pragma_indentation/after.sql
- test/fixtures/linter/autofix/sqlite/004_pragma_indentation/before.sql
- test/fixtures/linter/autofix/sqlite/004_pragma_indentation/test-config.yml
- test/fixtures/linter/autofix/sqlite/005_virtual_table_indentation/after.sql
- test/fixtures/linter/autofix/sqlite/005_virtual_table_indentation/before.sql
- test/fixtures/linter/autofix/sqlite/005_virtual_table_indentation/test-config.yml
This PR addresses indentation issues in SQLite triggers by adding proper formatting for `WHEN` clauses and `BEGIN/END` blocks, along with comprehensive test coverage for SQLite-specific indentation scenarios.
Partially fixes #7062.
Partially fixes #7063.
No.
- Other.
> SQLite: Fix WHEN and BEGIN/END indentation

- src/sqlfluff/dialects/dialect_ansi.py
- test/fixtures/dialects/greenplum/frame_clause.sql
- test/fixtures/dialects/greenplum/frame_clause.yml
- test/fixtures/dialects/postgres/select_frame_clause.yml
This allows for all types of the interval expressions and column references to be used in a `frame_clause`.
- fixes #6680
None
- Other.
> ANSI: Update `frame_clause` to support all `interval_expressions`

- src/sqlfluff/rules/layout/LT15.py
- test/fixtures/rules/std_rule_cases/LT15.yml
This handles cases where both the jinja and dbt templater may introduce blank lines via macros or other sorcery. We want to prevent formatting based on the templated newlines, so we choose to ignore any newlines found in templated areas.
- fixes #6817
None
- Other.
> LT15: Handle newlines that exists in templated areas

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/rules/std_rule_cases/LT02-indent-oracle.yml
Properly indent Oracle PL/SQL declaration blocks that follow IS/AS keywords in procedures, functions, packages, and type bodies.
Fixes #7064.
No
- Other.
> Oracle: Indent multiline PL/SQL after IS/AS keywords

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/oracle_operators.sql
- test/fixtures/dialects/oracle/oracle_operators.yml
Enable Oracle ** (power) and MOD operators in all expression contexts.
Fixes #7060.
No.
- Other.
> Oracle: Add support for ** (power) and MOD operators in expressions

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/bulk_collect_into.sql
- test/fixtures/dialects/oracle/bulk_collect_into.yml
Allow the parser to recognize `BULK COLLECT INTO` as a valid clause after the SELECT list.
Fixes #7073.
No.
- Other.
> Oracle: Fix BULK COLLECT INTO parsing in SELECT statements

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/case_expressions.sql
- test/fixtures/dialects/oracle/case_expressions.yml
Fixes #7099 
Currently, valid CASE statements with a bracket in a WHEN clause will fail, such as
```sql
SELECT 
CASE
WHEN abc = 1 THEN NULL
WHEN (
defg = 2
AND hijk = 3
) THEN NULL
END AS result
FROM abc;
```
This PR fixes that.
No, side effect free.
> Support brackets in CASE statement condition

- src/sqlfluff/dialects/dialect_databricks.py
- test/fixtures/dialects/databricks/comment_on.sql
- test/fixtures/dialects/databricks/comment_on.yml
Extends #6196 to also include COMMENT ON for COLUMNS.
None
- Other.
> extend databricks COMMENT ON to include columns

- src/sqlfluff/dialects/dialect_oracle.py
- test/fixtures/dialects/oracle/column_value.sql
- test/fixtures/dialects/oracle/column_value.yml
This modifies `COLUMN_VALUE` to be used as a bare function. This allows it to be used without a reference in a select clause as well as generally used as needed, but the word is still reserved.
- fixes #7110
None
- Other.
> oracle: Support `COLUMN_VALUE` as a bare function

- src/sqlfluff/dialects/dialect_ansi.py
- src/sqlfluff/dialects/dialect_bigquery.py
- src/sqlfluff/dialects/dialect_tsql.py
- src/sqlfluff/rules/structure/ST12.py
- src/sqlfluff/rules/structure/__init__.py
- test/fixtures/dialects/ansi/multiple_semicolons.sql
- test/fixtures/dialects/ansi/multiple_semicolons.yml
- test/fixtures/dialects/tsql/multiple_semicolons.sql
- test/fixtures/dialects/tsql/multiple_semicolons.yml
- test/rules/std_ST12_test.py
Fixes #7093.
This PR:
- Allows consecutive semicolons in T-SQL by accepting empty statements (avoids unparsable segments).
- Adds new T-SQL rule TQ02 to warn (fixable) on two or more consecutive delimiters.
- Updates affected T-SQL parse fixtures and adds a new multi-semicolon fixture.
- Consolidates and extends rule tests; all suites (py312, linting, mypy, fixture generation) pass.
- T-SQL parse trees for batches containing extra semicolons now include empty statement placeholders instead of unparsable segments (handled via updated fixtures).
- Impact multiple dialects.
- Automatic fixes introduced.
- Add user-facing documentation for rule ST12 (if approved to include in docs set).
> TSQL: Allow consecutive semicolons & add rule ST12 (warn and fix)
